### ISSUE TITLE
Build CLI then deploy

### ISSUE THREAD

**Issue by romainquellec** [serverless-nextjs/serverless-next.js#10]
> When running serverless deploy all your next pages will be automatically compiled, packaged and deployed.

I'm trying to use your plugin with my current project : https://github.com/CuistotduCoin/front
I'm using Typescript, and I need to build before deploying. Can you divide your current deploy phase into two phases : build (like next build but custom) then deploy ?

Alternative : (three steps)
- Use custom build from next (With requirements for 2nd step (dir, ect))
- Rewrite Handlers
- Deploy

Thanks for the work.

EDIT : I just saw sls package. I didnt knew that.

**Comment by danielcondemarin** [comment]
Would something like this work?:

```shell
serverless package // the plugin builds the next pages at this point
./my-custom-build.sh // some custom build script
serverless deploy --package .serverless/ // deploys using whatever was packaged above
```

https://serverless.com/framework/docs/providers/aws/cli-reference/deploy#deployment-from-a-pre-packaged-directory

This approach wouldn't work right now but is something I could fix relatively easy.

**Comment by romainquellec** [comment]
What I'm doing right now (will look a bit closer with more time :D) :
- Next build
- Serverless package
- Serverless deploy --package .serverless

At this point, I dont remember if "serverless package" is also building or not.
One pain point is : Right now, I cant see what Serverless package "do" because files are compressed.

Will look tonight and tomorrow. Maybe, that's just me and I'm worried to much about whats done under the hood.

**Comment by danielcondemarin** [comment]
The approach I suggested won't work right now when using the plugin. I have to make some changes for that to work. Should have it working relatively soon.

**Comment by romainquellec** [comment]
👍

**Comment by danielcondemarin** [comment]
Just tested tonight the following:

```shell
serverless package --package sls-build
serverless deploy --package sls-build
```
I thought it wouldn't but actually **does** work fine. You can have any custom build steps before running `serverless deploy --package ...`

**Comment by romainquellec** [comment]
Well, actually, there is a pain point : 
sls package does create a zip. (logical yes :D)

If you want a specific script to modify a handler between package & deploy phase, you have to unzip, make your modification, zip again.

Ideal steps will be :
- Build (create a dir "sls-next-build" with all the handlers)
- Custom phase (Optional)
- Package (zip all this)
- Deploy

**Comment by Vadorequest** [comment]
@romainquellec Did you succeed? I'm considering TS for my Next app and for the node lambda handler as well.

**Comment by romainquellec** [comment]
I'm using next with TypeScript with no worries.
For lambda handler, you can check : https://github.com/danielcondemarin/serverless-next.js/tree/master/examples/app-with-custom-lambda-handler

**Comment by dphang** [comment]
Now we had separated build step completely into Lambda@Edge package, which you enable with `deploy: false` input (see README). We could probably also add a separate command to build only for simplicity.
