### ISSUE TITLE
Not able to configure PROD_AWS_ACCESS_KEY_ID and PROD_AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by abiswas529** [serverless-nextjs/serverless-next.js#1002]
### Describe the bug
Hi Team,
I am using component: "@sls-next/serverless-component@1.18.0". I have two variable in DEV_AWS_ACCESS_KEY_ID , DEV_AWS_SECRET_ACCESS_KEY and PROD_AWS_ACCESS_KEY_ID, PROD_AWS_SECRET_ACCESS_KEY in gitlab CICD settings.

when I am using AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY and then doing npx serverless it is not working.
![image](https://user-images.githubusercontent.com/55099778/115018389-6a164880-9ed5-11eb-8dd5-8ebc830be43b.png)

But if I save the same id and key with the name of AWS_ACCESS_KEY_ID , AWS_SECRET_ACCESS_KEY in gitlab CICD settings. it is working fine.
![image](https://user-images.githubusercontent.com/55099778/115018683-c8dbc200-9ed5-11eb-9334-b60218d60a09.png)

### Actual behavior
Now the issue is I can''t not hard code the AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY to specific value in gitlab CICD settings as I need to use PROD_AWS_ACCESS_KEY_ID, PROD_AWS_SECRET_ACCESS_KEY for PROD deployment as below.
![image](https://user-images.githubusercontent.com/55099778/115019070-4a335480-9ed6-11eb-900b-4000f45acb07.png)

### Expected behavior

The above configuration should work as I am registering AWS_ACCESS_KEY_ID , AWS_SECRET_ACCESS_KEY as environment variable only. Please help me with a solution for this.

### Versions

- OS/Environment:
- @sls-next/serverless-component version:1.18.0
- Next.js version: 10.1.3

**Comment by dphang** [comment]
I don't use Gitlab so the environment might be different, but assuming you probably need to set your `AWS_ACCESS_KEY_ID` in the same line as `npx serverless`.

Something like `AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$PROD_SECRET_ACCESS_KEY npx serverless`.

I use GitHub actions and they also have env variables you can set in each step, which should be exactly for use cases like this: https://docs.github.com/en/actions/reference/environment-variables. Not sure what the equivalent is in Gitlab.

**Comment by dphang** [comment]
Closing old issue, hopefully this has been solved, if not feel free to comment/open a new issue.
