### ISSUE TITLE
CDK public folder assets

### ISSUE THREAD

**Issue by davegariepy** [serverless-nextjs/serverless-next.js#1004]
### Describe the bug
Using CDK for deployment, images from the `public` folder break when using the `next/image` component

### Actual behavior
A 503 error is returned for the image network request. The lambda@edge logs show a `LambdaExecution` error where the image is being requested from s3. The image is being bundled and uploaded to s3, the `vercel.svg` using the normal html `img` tag works. The uploaded image can be accessed by using the s3 object URL.

### Expected behavior
lambda@edge will access images in the s3 `public` folder
 
### Steps to reproduce
load an image from the `public` folder with the `next/image` component

### Screenshots/Code/Logs

main.js
```
const cdk = require("@aws-cdk/core");
const NextStack = require("../lib/next-stack.js");

const app = new cdk.App();
new NextStack(app, `NextStack`);
```

build.js
```
const path = require("path");
const { Builder } = require("@sls-next/lambda-at-edge");
const nextConfigDir = path.join(__dirname, "../../app");
const outputDir = path.join(nextConfigDir, "build");

const builder = new Builder(nextConfigDir, outputDir, {
  cwd: nextConfigDir,
  args: ["build"]
});

builder
  .build(true)
  .then(() => console.log("built next app"))
  .catch((e) => console.log(e));
```

next-stack.js
```
const { NextJSLambdaEdge } = require("@sls-next/cdk-construct");
const cdk = require("@aws-cdk/core");
const iam = require("@aws-cdk/aws-iam");

class NextStack extends cdk.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);

    const nextDistro = new NextJSLambdaEdge(this, "NextDistro", {
      serverlessBuildOutDir: `${__dirname}/../../app/build`,
      withLogging: true
    });

    // nextDistro.bucket.grantRead(nextDistro.edgeLambdaRole);

    nextDistro.edgeLambdaRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        resources: [
          nextDistro.bucket.bucketArn,
          `${nextDistro.bucket.bucketArn}/*`
        ],
        actions: ["s3:GetObject*", "s3:GetBucket*", "s3:List*", "s3:HeadBucket"]
      })
    );

    new cdk.CfnOutput(this, "NextDistroURL", {
      value: `https://${nextDistro.distribution.distributionDomainName}`
    });
  }
}

module.exports = NextStack;
```

### Versions
- OS/Environment: Mac Mojave
- "@sls-next/cdk-construct": "^1.19.0-alpha.38"
- "@sls-next/lambda-at-edge": "^1.8.0-alpha.33"
- Next.js version: 10.1.3
- CDK 1.75

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by davegariepy** [comment]
I did a little more investigating and came across the popular objects tab in CloudFront. I noticed that for the 5xx errors the path does not contain the image filename. It is shown as `/_next/image` where I would expect something like `/_next/image/photo.png`.

![Screen Shot 2021-04-18 at 3 44 19 PM](https://user-images.githubusercontent.com/3921481/115158680-5eee2480-a05d-11eb-9dea-a33fb2988500.png)

**Comment by davegariepy** [comment]
ok, so I noticed a mismatch in the image URL when comparing the browser network request and logs:

the network request: 
`https://redacted.cloudfront.net/_next/image?url=%2Fphoto.png&w=256&q=75`

in the lambda@edge logs in s3 I see this is logged with the lambda execution error:
`url=%252Fphoto.png&w=256&q=75`

the discrepancy is `%252Fphoto.png` vs `%2Fphoto.png`, so maybe the extra 52 is causing a miss?

relevant logging output:
```
#Version: 1.0
#Fields: date time x-edge-location sc-bytes c-ip cs-method cs(Host) cs-uri-stem sc-status cs(Referer) cs(User-Agent) cs-uri-query cs(Cookie) x-edge-result-type x-edge-request-id x-host-header cs-protocol cs-bytes time-taken x-forwarded-for ssl-protocol ssl-cipher x-edge-response-result-type cs-protocol-version fle-status fle-encrypted-fields c-port time-to-first-byte x-edge-detailed-result-type sc-content-type sc-content-len sc-range-start sc-range-end

relevant log:
2021-04-22	01:39:51	BOS50-C3	1272	redactedIP	GET	redacted.cloudfront.net	/_next/image	503	https://redacted.cloudfront.net/	Mozilla/...redacted	url=%252Fphoto.png&w=256&q=75	-	LambdaExecutionError	n8wY_i8kPGbBgwe4-buHPXggnel3sRmOoRsGb6oikc_AiNJtjfcUXQ==	redacted.cloudfront.net	https	55	3.850	-	TLSv1.3	TLS_AES_128_GCM_SHA256	LambdaExecutionError	HTTP/2.0	-	-	60359	3.850	LambdaExecutionError	text/html	1019	-	-
```

**Comment by cweekly** [comment]
At a glance it looks like your test image has a leading space char: `%2Fphoto.png`. The `%2F` gets re-encoded as `%252F`.

**Comment by dphang** [comment]
Does it work in the normal component deployment (not CDK)? If not as well, then I might need to look into the image handler to see if it's handling the encoded paths correctly (I ported almost as-is from Next.js, they might have some bugs though)

**Comment by davegariepy** [comment]
@cweekly thanks.  It was like `/photo.png`, but no extra space. 

Maybe there is something going on in the code for how the slash is treated?

I tried both ways, slash and no slash. I also deleted the entire deployment, upgraded the packages and redeployed. When I run a local build and nom start the image from the public folder still works.

also tried making it so that my local build and deployment build had different names, since initially I had them both as "build" but that didn't seem to change anything either.

**Comment by davegariepy** [comment]
when the build runs the url for the static image gets coded into the file like this:  

```
srcset="
 /_next/image?url=%2Fphoto.png&amp;w=256&amp;q=75 1x,
 /_next/image?url=%2Fphoto.png&amp;w=640&amp;q=75 2x
 "
```
so the _slash_  from `/photo.png` is already encoded here as `%2F` _during build_

I haven't tested this, but my best guess is in the `compatLayer`: `queryString.stringify(event.multiValueQueryStringParameters` encodes `%2F` again giving us `%252F`

maybe this need to be escaped if it is determined that it is an image request with parameters?

**Comment by davegariepy** [comment]
this seems to be working now after upgrading to `3.1.0-alpha.5`

**Comment by dphang** [comment]
I see, I am not sure what had solved it? The only thing I can think of was that I had fixed some pathing issues but that was only for Windows (/ vs \ paths). Anyway I think we can close, if there are further issues feel free to reopen?
