### ISSUE TITLE
Migrating from serverless-nextjs-plugin but still using API Gateway

### ISSUE THREAD

**Issue by Arditc** [serverless-nextjs/serverless-next.js#1006]
Hey,

I was wondering if there is any support from migrated from:
`serverless-nextjs-plugin` to `serverless-next.js` but still being able to use API Gateway + lambdas. This is because we already  use a CDN which isn't cloudfront. 

I wasn't able to find anything in your documentation to say that this still supports API gateway + lambda lambda integration. Has this been deprecated?

Many thanks for your help 🙌

**Comment by davegariepy** [comment]
hey @Arditc, it was mentioned in #970 and #777 that there are plans to become more platform agnostic.  At the moment everything is tied to CloudFront and lambda@edge.

**Comment by Arditc** [comment]
Amazing thanks @davegariepy !
