### ISSUE TITLE
Runtime env not being set

### ISSUE THREAD

**Issue by mattvb91** [serverless-nextjs/serverless-next.js#1010]
`@sls-next/serverless-component@1.19.0-alpha.45`

I currently have a setup that has this nextJS setup for the frontend. But I am using a proxy on the `/api` route that proxies through to another external lambda JSON api (Which is up and running, and accessible)

https://github.com/chimurai/http-proxy-middleware

The issue I currently have is that on pages where I am making use of the proxied external api through `getServerSideProps` I am getting a `The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions.` error. 

Has anyone had a similar issue and suggestions for the correct / needed permissions? It seems like a fetch to another lambda (Accessible from my browser) is what causes the issue. Pages that dont make use of any api calls are working fine.

**Comment by dphang** [comment]
Please provide some CloudWatch logs (in the future please follow the template if possible as it has a guide). "The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions" is generic but normally means an exception was thrown in the Lambda. The logs would help pinpoint which code failed.

**Comment by mattvb91** [comment]
Hi @dphang thanks for the response, thats actually part of the issue that makes it difficult to understand, The logs permissions are set as suggested in the readme for the role however on the console I just receive an error that this loggroup does not exist.

**Comment by mattvb91** [comment]
So it turns out my env variables aren't coming through on the lambda itself. I have the nextjs.conf setup like in the readme. 

```
myNextApplication:
  component: "@sls-next/serverless-component@1.19.0-alpha.45"
  inputs:
    build:
      env:
        API_TARGET: "https://validapi-point.execute-api.us-east-1.amazonaws.com"
```
but on the lambda it never shows up?

![image](https://user-images.githubusercontent.com/11991564/116526417-ddf32080-a8d9-11eb-8579-6de22b5d64ba.png)

Am i confusing "Build" env with what i was assuming was the runtime env vars?

**Comment by jvarho** [comment]
@mattvb91 If you use .env files for your environment variables, Next.js build will fill them in at build time: https://nextjs.org/docs/basic-features/environment-variables

If it's a plugin you use that requires the env vars, that might or might not work. The reference has to be detectable statically. If it does not work, there's nothing serverless-next.js can do about it.

**Comment by mattvb91** [comment]
@jvarho thanks! never occured to me i can of course build it into my deployment step!! thanks again
