### ISSUE TITLE
@sls-next/cdk-construct - allow additional edgeLambdas to be set without overriding the default ones.

### ISSUE THREAD

**Issue by afenton90** [serverless-nextjs/serverless-next.js#1014]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to add Lambda@Edge functions to the default behaviour for the Cloudfront Distribution generated as part of `@sls-next/cdk-construct` without overriding the default Lambda@Edge functions. 

**Describe the solution you'd like**
Rather than spreading over all props here https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/serverless-components/nextjs-cdk-construct/src/index.ts#L250 I'd like the supplied `edgeLambdas` to be concatenated. I don't see a use case for always overriding the default lambdas after all isn't that why this `Construct` exists?

**Describe alternatives you've considered**
Using the `Construct` and adding the behaviour with `addBehaviour` however this is not allowed for default behaviours.

**Comment by afenton90** [comment]
To be clear if people think this is a good idea I don't mind contributing this.

**Comment by kirkness** [comment]
Hi @afenton90, I agree this would be a worthwhile feature! Contributions most welcome, do let me know if you'd like any pointers.
