### ISSUE TITLE
What is the recommended target for deployment?

### ISSUE THREAD

**Issue by otekdo** [serverless-nextjs/serverless-next.js#1017]
Hi im just gonna make a basic question!

![image](https://user-images.githubusercontent.com/65221868/115886189-accca900-a41e-11eb-8236-4c00b5f333c2.png)

When deploying a nextjs app with this framework...

**What is the recommended target?**

I am not sure which one i must choose

**Comment by dphang** [comment]
You can configure the target using the `serverless.yml` file instead with `useServerlessTraceTarget`. Serverless target just means each page bundles all dependencies. However if you have lots of pages the Lambda size can go up a lot.

Serverless trace means that there is only one set of dependencies, so your Lambda size will be smaller. However, each page JS will have to load your dependencies one file at a time, and file I/O can actually slow down your JS load time especially during cold start.

I would suggest you use the Serverless target first until you hit the size limits (and you can also minify your pages as well).

**Comment by otekdo** [comment]
Ok, thanks!
