### ISSUE TITLE
useServerlessTraceTarget leads to copy error in building the default-lambda

### ISSUE THREAD

**Issue by jjanssen** [serverless-nextjs/serverless-next.js#1020]
### Describe the bug
We recently were in a need to use the useServerlessTraceTarget feature as we were running into the EntityTooLarge exception.
When enabling useServerlessTraceTarget the code for the default-lambda can no longer be build due to a copy error.

```
error:
  [Error: EEXIST: file already exists, mkdir '/my-path/client/.serverless_nextjs/default-lambda/pages'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/my-path/client/.serverless_nextjs/default-lambda/pages'
}
```

### Actual behavior
Although not happening in a bare example it can be the case that the initial copyLambdaHandlerDependencies has an overlap with the copy that includes the filter.

https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/build.ts#L277
https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/build.ts#L315

Turn of either one of those and build can complete, but offcourse this will lead to some files missing.
My best guess is that there are overlapping files and folders in both function for copying `.next/serverless/pages` into their default-lambda/pages location. Although I haven't been able to pinpoint what files exactly.

### Steps to reproduce
At the moment I'm trying to consolidate the behaviour which is causing outside of our project. But luck isn't on my side just yet. When I'm actually able to reproduce this behavior, I'll post a link to a Github project. I'm hoping maybe others in the community could shed an additional light on this.

### Screenshots/Code/Logs
```
error:
  [Error: EEXIST: file already exists, mkdir '/my-path/client/.serverless_nextjs/default-lambda/pages'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/my-path/client/.serverless_nextjs/default-lambda/pages'
}
```

Coming from: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/build.ts#L315

### Versions
- OS/Environment: OSX 10.14.6
- @sls-next/serverless-component version: 1.19.0-alpha.48
- Next.js version: 10.1.3

### Checklist
- [X] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [X] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jjanssen** [comment]
I actually found the combination, reproduction can be found at:
https://github.com/jjanssen/serverless-next-bare-example/tree/use-serverless-target

What is interesting, it occurs with the presence of:
- next-translate wrapped around the `next.config.js`
- next-auth being present in `/api/auth/`

If I were to leave out `nextTranslate` as a wrapper in `next.config.js`, the build does not encounter any errors.
If I were to leave out the `/api/auth/` folder, the build does not encounter any errors.

next-translate seems to be fiddling around with actual routes-manifest probably causing `/api/auth/` to get flagged as default-lambda instead of api-lambda target.

**Comment by jjanssen** [comment]
I've been giving this issue a couple of thoughts the last few days.

When the build hits the `useServerlessTraceTarget` conditional in `buildDefaultLambda` the `nodeFileTrace` takes the `pages/api` folder into consideration. In the scenario of having `next-translate` and `next-auth` installed it still doesn't add up on why this would be flagged accordingly for `nodeFileTrace`.

Now I would happy to make a PR to resolve this. At the moment two options are crossing my mind:
1. nodeFileTrace should have an ignore on returning paths with `pages/api/**/*`
2. We could add a setting to the configuration to let end-users customize this if applicable. For eg: `buildOptions.ignore` (`string | string []`) as per [nft settings](https://github.com/vercel/nft#ignore).
3. Make the [second copy](https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/build.ts#L315) execute regardless even if there is already an existent target subfolder.

Regarding the 1st option I only have concerns on whether this is a valid assumption or not? Or am I overlooking a specific scenario? Fiddling around with ignore does not lead to unexpected results in our application, but I'm not sure on the impact in general.

Happy to hear anyone's thoughts about this.

**Comment by dphang** [comment]
Sorry I missed looking at this. I think with latest versions serverless-trace is going away (https://github.com/vercel/next.js/discussions/16276#discussioncomment-709863) because of the new chunking/code-splitting in later versions, it seems in 10.2.3 at least it doesn't do anything (sorry haven't been following too closely). So I think we can close this as "won't fix".

**Comment by dphang** [comment]
I will close this since with newer Next.js versions, serverless trace got deprecated and it might not be worth investing time into. Sorry it could not be directly addressed, I want to address it, but unfortunately don't have enough resources. Please do let us know if there are any concerns.
