### ISSUE TITLE
Running serverless results in ENOENT: no such file or directory, .....serverless/components/registry/npm/@sls-next

### ISSUE THREAD

**Issue by jake-chambers** [serverless-nextjs/serverless-next.js#1023]
### Describe the bug
Following the README and running serverless errors out

### Actual behavior
```
jacobchambers@Jakes-MacBook-Pro web-story-viewer % serverless

  error:
  Error: Component "@sls-next/serverless-component@1.9.10" was not found on NPM nor could it be resolved locally.
    at /Users/jacobchambers/Desktop/Liferoll/web-story-viewer/node_modules/@serverless/core/src/utils/download.js:97:15
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Promise.all (index 0)
    at async Object.download (/Users/jacobchambers/Desktop/Liferoll/web-story-viewer/node_modules/@serverless/core/src/utils/download.js:131:3)
    at async downloadComponents (/Users/jacobchambers/Desktop/Liferoll/web-story-viewer/node_modules/@serverless/template/utils.js:194:27)
    at async Template.default (/Users/jacobchambers/Desktop/Liferoll/web-story-viewer/node_modules/@serverless/template/serverless.js:51:37)
    at async Object.runComponents (/Users/jacobchambers/Desktop/Liferoll/web-story-viewer/node_modules/@serverless/cli/src/index.js:220:17)

  0s › Template › Error: Component "@sls-next/serverless-component@1.9.10" was not found on NPM nor could it be resolved locally.
```
- OS/Environment: MacOS
- @sls-next/serverless-component version: 1.9.10
- Next.js version: 10.1.3

### Additional context
My serverless.yml file

```
# serverless.yml

myNextApplication:
  component: "@sls-next/serverless-component" # it is recommended you pin the latest stable version of serverless-next.js

```

- I did not include @sls-next/serverless-component in my package.json
- It works fine if I refer to the local installation like:

```
# serverless.yml

myNextApplication:
  component: "./node_modules/@sls-next/serverless-component"

```

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by davegariepy** [comment]
shouldn't it be 1.19?

**Comment by jake-chambers** [comment]
thats why im unsure what its complaining about, i didnt specify a version in the `serverless.yml`

**Comment by dphang** [comment]
Not sure the issue - if you don't specify version it uses the npm `latest` tag here under versions: https://www.npmjs.com/package/@sls-next/serverless-component. Perhaps there was some mistagging before but I think it's correct now. It is recommended to pin the version to avoid issues like this (once a version is published, it will be immutable)

Anyway, I'm closing for now, feel free to reopen in case of other issues.
