### ISSUE TITLE
Incompatible with serverless-aws-alias

### ISSUE THREAD

**Issue by mekwall** [serverless-nextjs/serverless-next.js#103]
Instead of using serverless stages we instead use the https://github.com/serverless-heaven/serverless-aws-alias plugin. Sadly, the S3 part of serverless-nextjs-plugin doesn't work well together with this plugin.

We have three stages and thus need three different buckets, but serverless-nextjs-plugin only allow one bucket. Deploying with alias `dev` works just fine, but when we try to deploy to `staging` with another bucket serverless-aws-alias will first give the following error because `NextStaticAssetsS3Bucket` resource is listed twice (which isn't allowed, it has to have a unique name per alias):

```
Serverless: Preparing alias ...
Unhandled rejection Error: Resource NextStaticAssetsS3Bucket is already deployed in another alias with a different configuration. Either you change your resource to match the other definition, or you change the logical resource id to deploy your resource separately.
```

The deployment will eventually fail with the following error:

```
The assets bucket "staging-next-assets.playpilot.com" does not exist. Create it manually or delete the stack and recreate it.
```

Manually creating this bucket does't help either. You'll just get the same error.

A quick fix is to disable serverless-nextjs-plugin handling of S3 altogether and we do it manually ourselves in our config, but I haven't found a way to do that for now. Later on it would be great if these incompatibilities could be fixed so these two plugins can play well together. I'd gladly help out with that.

**Comment by danielcondemarin** [comment]
@mekwall How do you solve this problem for other cf `resources` in your stack?

**Comment by mekwall** [comment]
@danielcondemarin I just add the alias as part of their resource names so that they are unique.

**Comment by mekwall** [comment]
With the referenced PR I can now work around this issue by disabling creation of s3 asset bucket and set it up manually in my serverless config like this:

```
const capitalizedAlias = alias[0].toUpperCase() + alias.substr(1);
const bucketResourceName = `NextStaticAssetsS3Bucket${capitalizedAlias}`;

const resources = {
  Resources: {
    [bucketResourceName]: {
      Type: 'AWS::S3::Bucket',
      Properties: {
        AccessControl: 'PublicRead',
        CorsConfiguration: {
          CorsRules: [
            {
              AllowedHeaders: ['*'],
              AllowedMethods: ['GET'],
              AllowedOrigins: ['*'],
              ExposedHeaders: ['Date'],
              Id: 'NextStaticAssetsS3BucketId1',
              MaxAge: '3600',
            },
          ],
        },
        BucketName: assetBuckets[alias],
        WebsiteConfiguration: {
          IndexDocument: 'index.html',
          ErrorDocument: 'error.html',
        },
      },
      DeletionPolicy: 'Retain',
    },
  },
  Outputs: {
    [`NextStaticAssetsS3BucketWebsiteURL${capitalizedAlias}`]: {
      Value: { 'Fn::GetAtt': [bucketResourceName, 'WebsiteURL'] },
      Description: 'URL for the S3 website hosting the static assets',
    },
    [`NextStaticAssetsS3BucketSecureURL${capitalizedAlias}`]: {
      Value: {
        'Fn::Join': [
          '',
          ['https://', { 'Fn::GetAtt': [bucketResourceName, 'DomainName'] }],
        ],
      },
      Description: 'S3 Bucket which holds the static assets',
    },
  },
};
```

However, it would be cool if the plugin would support it out of the box 😸

**Comment by mekwall** [comment]
Celebrated too early... This has to be done with all resources generated by the plugin so it's not enough to do it for only the asset bucket.
