### ISSUE TITLE
Compilation issue when trying to use RecordTarget with the nextLambdaEdge.distribution on the CDK Construct

### ISSUE THREAD

**Issue by ignaciolarranaga** [serverless-nextjs/serverless-next.js#1032]
### Describe the bug
The CDK version does not compile when using sourceTargets, for example:
```
      // Linking the domain
      new ARecord(this, `Sample}`, {
        recordName: env,
        zone: mainHostedZone,
        // spellchecker: disable-next-line
        target: RecordTarget.fromAlias(new CloudFrontTarget(nextLambdaEdge.distribution))
      });
```

### Actual behavior
```
Argument of type 'Distribution' is not assignable to parameter of type 'IDistribution'.
  The types of 'stack.tags' are incompatible between these types.
    Type 'import("/Users/ignacio/Workspaces/EPolls/epolls/epolls-backend/node_modules/@aws-cdk/aws-cloudfront/node_modules/@aws-cdk/core/lib/tag-manager").TagManager' is not assignable to type 'import("/Users/ignacio/Workspaces/EPolls/epolls/epolls-backend/node_modules/@aws-cdk/core/lib/tag-manager").TagManager'.
      Types have separate declarations of a private property 'tags'.ts(2345)
```

### Expected behavior
To be able to create the target.

### Steps to reproduce
Just create a sample distribution and try to create an AReccord.

### Screenshots/Code/Logs
N/A

### Versions
Lastest ones currently.
```
    "@aws-cdk/aws-route53": "^1.101.0",
    "@aws-cdk/aws-route53-targets": "^1.101.0",
    "@aws-cdk/core": "^1.101.0",
    "@sls-next/cdk-construct": "^1.19.0-alpha.48",
    "next": "^10.1.3",
```

### Additional context
N/A

### Checklist
- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by kirkness** [comment]
Hey @ignaciolarranaga, it kinda looks like you have multiple versions of `@aws-cdk/core` installed somehow? Are you able to check the output of `yarn why @aws-cdk/core` or `npm list @aws-cdk/core` to verify what you have installed and why.

Failing that and out of interest does casting `nextLambdaEdge.distribution as IDistribution` resolve the issue?
