### ISSUE TITLE
Add custom next binary location

### ISSUE THREAD

**Issue by j718** [serverless-nextjs/serverless-next.js#1039]
**Is your feature request related to a problem? Please describe.**
I can't use yarn berry because it seems that the project tries to find the next binary at ./node_modules/.bin/next

**Describe the solution you'd like**
An ability to provide a custom next binary location.

**Describe alternatives you've considered**
A built in usage on pnp. This would be harder to implement

**Comment by dphang** [comment]
I think you can use the `build` input to specify custom command to execute for next build.

**Comment by dphang** [comment]
Closing, in case of any new issues, please reopen another issue
