### ISSUE TITLE
Starting SSR Build... Error

### ISSUE THREAD

**Issue by Industrial** [serverless-nextjs/serverless-next.js#1067]
### Describe the bug
All of a sudden, builds started failing. I am getting this error:

```
2021-05-11T10:50:05.046Z [INFO]: Starting SSR Build...
2021-05-11T10:50:19.920Z [INFO]: Error
```

There is no more output then this. The actual error is not displayed. Nothing changed in Source Control.

Is there anything I can do to enable debug logging, for example?

### Versions
- OS/Environment: AWS Amplify
- @sls-next/serverless-component version: 1.19.1.alpha4
- Next.js version: 10.2.0

### Checklist
- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Did it happen randomly or did you upgrade Next.js or this component? I've updated the tests to the newest Next.js version as well just now but haven't seen it there or on my own projects.

You should be able to run `serverless --debug` to see more logs. I'm not sure I can help much unless I have a repro, does anyone have a repo with this issue?

**Comment by Musashi-Sakamoto** [comment]
> ### Describe the bug
> All of a sudden, builds started failing. I am getting this error:
> 
> ```
> 2021-05-11T10:50:05.046Z [INFO]: Starting SSR Build...
> 2021-05-11T10:50:19.920Z [INFO]: Error
> ```
> 
> There is no more output then this. The actual error is not displayed. Nothing changed in Source Control.
> 
> Is there anything I can do to enable debug logging, for example?
> 
> ### Versions
> * OS/Environment: AWS Amplify
> * @sls-next/serverless-component version: 1.19.1.alpha4
> * Next.js version: 10.2.0
> 
> ### Checklist
> * [x]  You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
> * [x]  Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

@Industrial 
I had the same problem.
Looks like you have to configure your app to be detected as SSG.
https://github.com/aws-amplify/amplify-console/issues/412#issuecomment-849992472

**Comment by Industrial** [comment]
Thanks!

**Comment by heysuraj1** [comment]
@Musashi-Sakamoto Thanks for this answer
