### ISSUE TITLE
CI compatible output (spinning loader)

### ISSUE THREAD

**Issue by Industrial** [serverless-nextjs/serverless-next.js#1068]
**Is your feature request related to a problem? Please describe.**
Spinning loaders are not supported in all environments, namely CI environments. They log copious amounts of useless output saying "Deploying..."

**Describe the solution you'd like**
Add an option to disable the spinning loader for CI

**Comment by dphang** [comment]
Unfortunately I think it is because of the serverless component library, until it is upgraded (or maybe we can fork and patch this specifically) then it will have the output like that in CI environments.
