### ISSUE TITLE
Next/Image times out 503

### ISSUE THREAD

**Issue by ryanmalesic** [serverless-nextjs/serverless-next.js#1071]
### Describe the bug
Call to fetch image times out in logs (increasing timeout time doesn't help)

### Actual behavior
503 on request to https://redacted.cloudfront.net/_next/image?url=%2Flogo.png&w=128&q=75
`Task timed out after 3.00 seconds`

### Expected behavior
Image loads on page

### Steps to reproduce
Create Stack
Add image
Deploy

### Screenshots/Code/Logs
All logs above

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.

**Comment by davegariepy** [comment]
hey @ryanmalesic are you using an image stored in the public folder and deploying with CDK? If so I had a similar problem documented in #1004. You can see in some of the logs I posted that the image was not being retrieved when using the next `Image` component. 

The logs from lambda edge are stored in s3, maybe you can post some like I did and we can compare.

Thanks

**Comment by dphang** [comment]
I think the CDK default Lambda timeouts were too low (3 second lambda default). We had already updated it so I think it should be resolved now
