### ISSUE TITLE
Using getStaticProps leads to RequestEntityTooLargeException

### ISSUE THREAD

**Issue by Reiiya** [serverless-nextjs/serverless-next.js#1081]
### Describe the bug
I recently introduced `next-i18next` into my app and it requires that I use `getStaticProps` on every page. Size of my lambda exploded and I hit the dreadful `RequestEntityTooLargeException`.

### Actual behavior
I took a look at what happens in `.serverless_nextjs/default-lambda/pages` and it turns out that if the page has `getStaticProps`, it is included in lambda, therefore size exploded. Is that the expected behavior? I tested and for size of lambda it does not matter if i use getServerSideProps or getStaticProps and that seems to go against the docs.

### Versions
- OS/Environment: ubuntu
- @sls-next/serverless-component version: 1.19.0-alpha.45 , 1.19.1-alpha.7
- Next.js version: 10.2.0

### Additional context
For what its worth, I have a single `getInitialProps` at `_document.ts` due to styling solution, but removing it did not change anything.

### Checklist

- [X] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [X] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jvarho** [comment]
> Is that the expected behavior?

Yes, if you have api routes. Look for preview mode in the README.

**Comment by dphang** [comment]
Yes, please refer to https://github.com/serverless-nextjs/serverless-next.js#the-lambdaedge-code-size-is-too-large for potential solutions. Basically, when API routes are used then we cannot remove all JS files used for prerendering static pages, as preview mode may use any of them.

Right now I think one way is you can use `postBuildCommands` to create a script to remove the JS files you don't want before it deploys (but note that preview mode will be broken), or we could make a config option to explicitly exclude these files even when you have API routes

**Comment by Reiiya** [comment]
I indeed have a single API route. For sanity's sake I did try to delete it but serverless still bundles all pages together. So I assumed there is something else going on I don't understand.

So I was meaning to ask exactly that - if its OK to remove SSG pages at `postBuildCommands`.

**Comment by dphang** [comment]
Yes, you can remove it that way, it allows you to do any arbitrary action right before deployment, it's meant for adding extra binaries (e.g 3rd party libraries) as needed. I am not sure why it did not remove it but maybe with new Next.js version something changed.

If you have time, a repro repository could be helpful so we can fix this case

**Comment by Reiiya** [comment]
Thank you!  Removing them by hand will actually settle the issue for me, I'll need the apis in future. I cannot share the repo in question but I will try to reproduce the error in following days.

I'll use this opportunity - huge thank you for this absolutely amazing project! Don't have the skills to jump in myself, but learned quite a bit just by following it.
