### ISSUE TITLE
Files in static folder not route to S3

### ISSUE THREAD

**Issue by maf1ab0y** [serverless-nextjs/serverless-next.js#109]
Hi,
I tried to deploy app-basic in examples with a modification for index.js file:
```
<div className="homePage">
      <div>Welcome to next.js serverless ⚡</div>
      <img src={"/static/nextjs.png"} alt="Logo"/>
 </div>
```
However nextjs.png file is routed to https://v6vbkbxj52.execute-api.us-east-1.amazonaws.com/static/nextjs.png instead of S3 url (what i expected is: https://nextjs-basic-test.s3.amazonaws.com/static/nextjs.png)

Check this link for detail: https://v6vbkbxj52.execute-api.us-east-1.amazonaws.com/dev/

**Comment by jishaal** [comment]
Any ideas on why this issue may be? Having the same problem

**Comment by dennisrjohn** [comment]
Having the same issue. The static assets are uploaded to S3, but the URL is not rewritten on the page. The rendered page output is:
<img src="/static/Logo.png" alt="Logo">

**Comment by mike-suggitt** [comment]
Same here using latest version of all packages

**Comment by RichiCoder1** [comment]
Next isn't unfortunately actually doing anything special with this urls, you'll have to do something like `${getAssetPrefix()}/static/Logo.png` to make this work in environments like Api Gateway or other envs where Next isn't at the root of the path.

**Comment by dphang** [comment]
Closing out old/stale issues. If same issue occurs with the latest version of this component, please reopen a new issue.
