### ISSUE TITLE
Unable to debug why serverless command takes more than 700 seconds

### ISSUE THREAD

**Issue by Arditc** [serverless-nextjs/serverless-next.js#1094]
**Is your feature request related to a problem? Please describe.**
Ever since I updated to Nextjs 10.2.0 + latest serverless I have seen issues with the serverless command.
Right now it's hard to see why it takes a long time to run the serverless comannd.

Before updating to the latest versions it used to take about 150 seconds to deploy.

It would be useful to have a environment variable to see what step serverless is on. 
Currently when I deploy my serverless nextjs App it takes 700 seconds to complete and it's hard to understand what's taking so long and which step it's on.

**Describe the solution you'd like**
export SLS_DEBUG=* 
should display log off all the steps which are occurring 

**Describe alternatives you've considered**

**Additional context**

**Comment by dphang** [comment]
Does `serverless --debug` not show you any output?

**Comment by Arditc** [comment]
Thank you @dphang! That does the trick 🍾
