### ISSUE TITLE
Error in pathToRegexp for 1.20.0-alpha.3

### ISSUE THREAD

**Issue by probablyup** [serverless-nextjs/serverless-next.js#1100]
### Describe the bug

When bundling with i18n, `target: 'serverless'` and `useServerlessTraceTarget: true` I get an error:

```
Unable to convert path to regex: /en-US/[pageId]. Please check for any special characters.
  TypeError: path_to_regexp_1.pathToRegexp is not a function
```

### Expected behavior
Successful deploy

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by probablyup** [comment]
I happens with `useServerlessTraceTarget` removed as well, so I don't think it's an NFT issue.

**Comment by probablyup** [comment]
I was looking at the core package and it doesn't seem like `path-to-regexp` is listed as a package.json dependency, so that might well be it.

**Comment by probablyup** [comment]
cc @dphang

**Comment by dphang** [comment]
Yes, the code was refactored out into core but looked like path-to-regexp was not moved, it's still in lambda-at-edge package which consumes the core package. It's working in e2e tests but maybe the dependency is not properly resolved on your machine. But will add it back there.
