### ISSUE TITLE
CDK v2 Construct

### ISSUE THREAD

**Issue by walkafwalka** [serverless-nextjs/serverless-next.js#1108]
**Is your feature request related to a problem? Please describe.**
The current (experimental) CDK Construct is built using v1 which is incompatible with CDK v2 (also experimental).

**Describe the solution you'd like**
Upgrade CDK Construct to v2.

**Describe alternatives you've considered**
Support both CDK v1 and v2.

**Comment by kiernan** [comment]
Looks like this is being done in: https://github.com/serverless-nextjs/serverless-next.js/pull/2187
