### ISSUE TITLE
Save the CloudFront appUrl to a file post deploy

### ISSUE THREAD

**Issue by MangoChris** [serverless-nextjs/serverless-next.js#1137]
**Is your feature request related to a problem? Please describe.**
I need to retrieve the CloudFront appUrl as part of my CI/CD build

**Describe the solution you'd like**
I would like to access the CloudFront appUrl post deploy in a similar way to what can be achieved with Export-Env in regular Serverless or aws-config.js in Amplify

**Describe alternatives you've considered**
Writing a script to query AWS via the API in order to fetch the CloudFront URL.

Maybe this already exists and is built into Serverless Components (sorry I'm new to components)?

**Comment by jvarho** [comment]
You can already find the url from the templates under .serverless/ – search for cloudfront.

**Comment by MangoChris** [comment]
Thanks @jvarho!
