### ISSUE TITLE
S3 static file is not found when filename includes non-alphabet/number

### ISSUE THREAD

**Issue by roeniss** [serverless-nextjs/serverless-next.js#1146]
### Describe the bug

If the file name is affected by [percent encoding](https://en.wikipedia.org/wiki/Percent-encoding), like `서버리스.jpg` (It's Korean), then the webpage can't access that file.

/public/iamges/serverless.png --> properly accessible
/public/iamges/서버리스.png --> Error: `$DOMAIN/public/iamges/%EC%84%9C%EB%B2%84%EB%A6%AC%EC%8A%A4.png Not Found`

I think this is serverless-next.js' issue because with `yarn dev` it properly serve my static file.s

### Versions

- OS/Environment: macOS 10.15.4
- @sls-next/serverless-component version: 1.18.0 (and other version also not working)
- Next.js version: 10.0.0

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by roeniss** [comment]
Oh, I pressed enter by mistake. Let me edit issue.... in 5 minutes.

**Comment by dphang** [comment]
Seems like encoding related issues should be fixed in https://github.com/serverless-nextjs/serverless-next.js/issues/822? Though this was released after 1.18. So I think 1.19 and later should have this fixed

**Comment by roeniss** [comment]
@dphang Oh my. Why I had unconsciously thought that 1.18.0 is the newest version? Thank you! 

at 1.19.0, the problem solved.
