### ISSUE TITLE
cdk default memorySize and timeout

### ISSUE THREAD

**Issue by Nemo64** [serverless-nextjs/serverless-next.js#1149]
### Describe the bug
According to https://serverless-nextjs.com/docs/lambdaatedgeconfig, the lambda@edge runs with 512 mb ram by default.
It doesn't by default though making the default configuration slow at best and timeout at worst.

### Actual behavior
The lambda@edge runs with 128mb with 3 second timeout

### Expected behavior
The lambda@edge should run with 512mb memory and 10 second timeout by default.

### Steps to reproduce
use the cdk construct 

### Versions

- OS/Environment: MacOS and/or node:14 docker image
- @sls-next/serverless-component version: 1.19.0
- Next.js version: 10.2.3

### Checklist

- [ ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Yes the docs are only applicable to the legacy deployment (and those need to be updated too actually), not CDK. We can definitely update CDK defaults to be more sensible.
