### ISSUE TITLE
Custom handler location

### ISSUE THREAD

**Issue by aluokkal** [serverless-nextjs/serverless-next.js#1150]
Bug:

Custom handler is forced to be located in same folder with serverless.yml.

Case 1. This works:

Let's assume we have project root => /build and there we have /build/serverless.yml and custom handler as custom.js.

  inputs:
    handler: "custom.handler"

Case 2. This does not work:

Let's assume we have project root => /build and there we have /build/serverless.yml and custom handler 
as /build/custom/custom.js.
...
  inputs:
    handler: "./custom/custom.handler"

app › Deploying 

  error:
  [Error: ENOENT: no such file or directory, stat '/build/.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/build/.js'
}

**Comment by jvarho** [comment]
If you drop the initial period and use `handler: "custom/custom.handler"` it should work.

That does not help if the relative path is outside the directory where serverless.yml is. Then again, next.js is also quite opinionated regarding where everything has to be, so I'm not sure that's a problem.

**Comment by aluokkal** [comment]
Ok, thanks for the clarification, I will close this ticket now.
