### ISSUE TITLE
Custom handler dependencies

### ISSUE THREAD

**Issue by aluokkal** [serverless-nextjs/serverless-next.js#1151]
Feature Request:

I would like to use custom handler and have configured that in serverless.yml.

My custom handler  dependencies are included in the in package.json.

When custom handler is deployed with serverless, those NPM dependencies are missing.

I would like to see that custom handler dependencies are packaged to the default lambda folder.

**Comment by jvarho** [comment]
You can add custom dependencies using build.postBuildCommands in serverless.yml. Or you may want to consider compiling the custom handler using something like webpack to bundle only the dependencies you need.

**Comment by aluokkal** [comment]
Ok, thanks for the clarification, I will close this ticket now.
