### ISSUE TITLE
getServerSideProps not working 

### ISSUE THREAD

**Issue by mikias21** [serverless-nextjs/serverless-next.js#1226]
Hello there,

I was trying to make api request to tmdb on a next js project, using the getServerSideProps function. How ever everytime i try to make request it show time out error. I thought maybe its because of my url string or API KEY, but the same request string works fine on postman. Could you please help me to fix it. 

// My code 
export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTreading.url
    }`
  ).then((res) => res.json());
  return {
    props: {
      results: request.results,
    },
  };

// The error 
FetchError: request to https://api.themoviedb.org/3/discover/movie?api_key=API_KEY&with_genres=28 failed, reason: connect ETIMEDOUT 31.13.91.6:443
    at ClientRequest.<anonymous> (C:\Users\mikia\Desktop\hulu-clone\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

**Comment by dphang** [comment]
Hm, I don't know what their policy is but if it's working locally, I feel that most likely themoviedb.org might think your app is a bot and is blocking connections from AWS datacenter IPs (which is where Lambda@Edge code runs on). Probably you need to check their policies and if there is some whitelisting needed. Or use a proxy to make the connection? (Not legal advice, please do your own research).

**Comment by mikias21** [comment]
@dphang Thanks a lot, I checked some tutorials and I saw that they are all using it locally. I am using Psiphon VPN do you think that's the problem. I am in china and I can't access the service with out VPN but postman works fine.

**Comment by dphang** [comment]
Oh that could be a possibility, that is common across many APIs (to prevent bots). I did actually miss that you are running Next.js locally on Windows? So both of the requests go through the VPN, but just Postman works?

Not sure but maybe the difference is Next.js is setting some headers that make it look like a bot. You'd have to debug the requests in your IDE and/or use Fiddler or other network debugging tools to see how the requests are being made.

**Comment by mikias21** [comment]
Thank you very much, I will try that and hope it works. Thank you for your
kind help

**Comment by dphang** [comment]
Thanks, I will close this then since it's not exactly related to this component/AWS. Feel free to recomment if there are issues with this component itself.
