### ISSUE TITLE
Include custom folder

### ISSUE THREAD

**Issue by azgorov** [serverless-nextjs/serverless-next.js#1255]
Is it possible to include custom folder with some files in deployed api lambda? Right now lambda code contains couple js files + pages folder with api routes. 

Kalin

**Comment by jvarho** [comment]
Yes, see the README for `build.postBuildCommands`. The files under `.serverless_nextjs/api-handler/` get deployed with the lambda.

**Comment by dphang** [comment]
Yes you can use that to execute any script which can do anything e.g add binaries, folders, etc to the Lambdas, .in between build and deploy step.
