### ISSUE TITLE
Static pages/index.js gives 404 with @1.20.0-alpha.28

### ISSUE THREAD

**Issue by talaikis** [serverless-nextjs/serverless-next.js#1256]
### Describe the bug

Static pages/index.js gives 404 with @1.20.0-alpha.28

### Expected behavior

Should work as intended.

### Steps to reproduce

Repo: https://github.com/talaikis/serverless-repro
Url: https://d86v7ththghx1.cloudfront.net/

### Versions

- OS/Environment: Windows 10
- @sls-next/serverless-component version: 1.20.0-alpha.28
- Next.js version: 11.0.0

- [x ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jvarho** [comment]
Unable to reproduce here and the tests _should_ cover this, so most likely a problem in windows compatibility code. The first thing to check would be whether index.html gets copied in `.serverless_next/assets/static-pages/...`?

**Comment by talaikis** [comment]
yep, `3.1.0-alpha.3` fixes it

**Comment by hinsxd** [comment]
> Unable to reproduce here and the tests _should_ cover this, so most likely a problem in windows compatibility code. The first thing to check would be whether index.html gets copied in `.serverless_next/assets/static-pages/...`?
> 
> 
> 
> Also, note that the latest alpha is 3.1.0-alpha.3

Excuse me, I couldnt find anywhere about the difference between v1.20 alphas and v3 alpha. Are they referring the same package?

**Comment by jvarho** [comment]
> > Unable to reproduce here and the tests _should_ cover this, so most likely a problem in windows compatibility code. The first thing to check would be whether index.html gets copied in `.serverless_next/assets/static-pages/...`?
> > Also, note that the latest alpha is 3.1.0-alpha.3
> 
> Excuse me, I couldnt find anywhere about the difference between v1.20 alphas and v3 alpha. Are they referring the same package?

Basically, yes: https://github.com/serverless-nextjs/serverless-next.js/issues/1243

**Comment by hinsxd** [comment]
> > > Unable to reproduce here and the tests _should_ cover this, so most likely a problem in windows compatibility code. The first thing to check would be whether index.html gets copied in `.serverless_next/assets/static-pages/...`?
> 
> > > Also, note that the latest alpha is 3.1.0-alpha.3
> 
> > 
> 
> > Excuse me, I couldnt find anywhere about the difference between v1.20 alphas and v3 alpha. Are they referring the same package?
> 
> 
> 
> Basically, yes: https://github.com/serverless-nextjs/serverless-next.js/issues/1243

Thanks! I came across this issue too and you replied at the same time.

I think thats quite confusing because v1 keeps updating but there is now v3!

**Comment by dphang** [comment]
> > > > Unable to reproduce here and the tests _should_ cover this, so most likely a problem in windows compatibility code. The first thing to check would be whether index.html gets copied in `.serverless_next/assets/static-pages/...`?
> > 
> > 
> > > > Also, note that the latest alpha is 3.1.0-alpha.3
> > 
> > 
> > > 
> > 
> > 
> > > Excuse me, I couldnt find anywhere about the difference between v1.20 alphas and v3 alpha. Are they referring the same package?
> > 
> > 
> > Basically, yes: #1243
> 
> Thanks! I came across this issue too and you replied at the same time.
> 
> I think thats quite confusing because v1 keeps updating but there is now v3!

Yes it is because we want to change the Lerna versioning to a fixed version. Since it's a new versioning scheme and to avoid confusion/conflicts with the independent versions, I bumped it up to a new major version v3 (v2 already had some tags so didn't want to override it)
