### ISSUE TITLE
SSR (getServerSideProps) does not work with locales and/or url query (?key=value)

### ISSUE THREAD

**Issue by hinsxd** [serverless-nextjs/serverless-next.js#1267]
Demo: https://d27fhtnuw9pbq0.cloudfront.net/

Locales:
1. en (default)
2. zh

Url structure:
1. /
2. /?name=
3. /[id]
4. /[id]?name=

### Actual behavior

1. Locales:
 	1.1. Locales works on first load, but subsequent gSSP during clients side routing always return default locale, but `locale` from `useRouter()` works normally
	1.2. Root path with url query (https://d27fhtnuw9pbq0.cloudfront.net/zh?name=test) makes locale fail
2. Dynamic route params always fail in client side routing (try pressing id1, id2 in demo)

### Steps to reproduce

Demo: https://d27fhtnuw9pbq0.cloudfront.net/

### Screenshots/Code/Logs
```tsx
// index.tsx
const Home = ({ name, ssrLocale }) => {
  const { locale } = useRouter();
  const { t } = useTranslation("common");
  return (
    <div>
      <Switcher />
      <h1>{t("title")}</h1>
      <h2>{t("subtitle")}</h2>
      <div>Locale: {locale}</div>
      <div>Locale in gSSP: {ssrLocale}</div>
      <div>Name: {name}</div>
    </div>
  );
};
export const getServerSideProps = async ({ query, locale }) => {
  return {
    props: {
      name: query.name ?? "",
      ssrLocale: locale,
      ...(await serverSideTranslations(locale!, ["common"], {
        i18n,
      })),
    },
  };
};
```

```tsx
// [id].tsx
const ID = ({ id, name, ssrLocale }) => {
  const { locale } = useRouter();
  const { t } = useTranslation("common");
  return (
    <div>
      <Switcher />
      <h1>{t("title")}</h1>
      <h2>{t("subtitle")}</h2>
      <div>Locale: {locale}</div>
      <div>Locale in gSSP: {ssrLocale}</div>
      <div>id: {id}</div>
      <div>name: {name}</div>
    </div>
  );
};
export const getServerSideProps = async ({ query, params, locale }) => {
  return {
    props: {
      id: params!.id,
      ssrLocale: locale,
      name: query.name ?? "",
      ...(await serverSideTranslations(locale!, ["common"], {
        i18n,
      })),
    },
  };
};
```
Path switcher:
```tsx
export default function Switcher() {
  const { pathname, query } = useRouter();
  return (
    <>
      <div>
        <h4>Locales</h4>
        {["en", "zh"].map((lang) => (
          <Link key={lang} href={{ pathname, query }} locale={lang} passHref>
            <a>{lang}</a>
          </Link>
        ))}
      </div>
      <div>
        <h4>Param</h4>
        {["id1", "id2"].map((id) => (
          <Link
            key={id}
            href={{ pathname: `/[id]`, query: { ...query, id } }}
            passHref
          >
            <a>{id}</a>
          </Link>
        ))}
      </div>
      <div>
        <h4>Url query</h4>
        {["name1", "name2"].map((name) => (
          <Link
            key={name}
            href={{ pathname, query: { ...query, name } }}
            passHref
          >
            <a>{name}</a>
          </Link>
        ))}
      </div>
    </>
  );
}
```

### Versions

- OS/Environment: macOS 11.2.3
- @sls-next/serverless-component version: 3.1.0-alpha.5
- Next.js version: v10.2, v11

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jvarho** [comment]
This explains some locale problems I've seen. I didn't make the connection to client side routing for some reason. You could test #1268 to verify the fix.

**Comment by hinsxd** [comment]
Thanks for the prompt fix! How can I apply these changes into my project to test?

**Comment by jvarho** [comment]
> Thanks for the prompt fix! How can I apply these changes into my project to test?

You can find the instructions for building and using a local version here: https://github.com/serverless-nextjs/serverless-next.js/blob/master/CONTRIBUTING.md

**Comment by dphang** [comment]
Yes currently the only way to locally test the changes is if you pull the branch and build them locally, and point your `serverless.yml` to it. Anyway, it's already published in the last alpha version.

**Comment by hinsxd** [comment]
Really really thanks for the quick response. You guys did a tremendous work in pulling the best framework and platform together!
