### ISSUE TITLE
Is there a way to check the files included in the build locally with a command like serverless package in serverless framework?

### ISSUE THREAD

**Issue by s-kikuchi** [serverless-nextjs/serverless-next.js#1275]
This issue is just a question, not a bug report, feature request, and report a security vulnerability.

**Question**
I have experience with serverless framework.
I check what files are inside the source code when using serverless framework because the zip file is uploaded to S3, so I need to know whether the zip file doesn't include credentials (like aws credentials, private npmrc file)
 
I know there are differences between `serverless framework` and `serverless component`.

So I would like to know 
1. whether serverless-nextjs uploads built file(like zip) onto S3.
2. (If the first question is yes) how to check out the built file in local environment. I know `serverlss package` fails, so I couldn't create build file locally.

**Comment by dphang** [comment]
Basically we are different from regular Serverless Framework in that most of the build + AWS deploy code is custom now (we adapted some packages from Serverless Components that were unmaintained).

The output files will be generated and stored in `.serverless_nextjs` (build assets like lambda, s3 etc.) and `.serverless` (the state of CloudFront, Lambda etc after deployment, but right now it is just stored locally, you can store in S3 etc.).

**Comment by s-kikuchi** [comment]
@dphang 
Thank you for your answer, I understood the build files are just on local basically(inside `.serverless_nextjs` and `.serverless`.
