### ISSUE TITLE
index gives 404 @3.1.0-alpha.6

### ISSUE THREAD

**Issue by lalvesoliveira** [serverless-nextjs/serverless-next.js#1277]
### Describe the bug
The index page gives 404

response headers:
```
age: 3
cache-control: public, max-age=0, s-maxage=2678400, must-revalidate
content-encoding: gzip
content-type: text/html
date: Tue, 22 Jun 2021 12:08:02 GMT
etag: W/"c9bf02fb02561a8f39002ccba9ae135b"
last-modified: Tue, 22 Jun 2021 12:04:04 GMT
server: AmazonS3
vary: Accept-Encoding
via: 1.1 81d299a580e85cd7d4af1e1123f3282a.cloudfront.net (CloudFront)
x-amz-cf-id: RauBQ_qL2RxhP0SGEsX4RhAuOC0WiBqA-jE_Qs5TLQly1P0wMJQa0Q==
x-amz-cf-pop: GRU3-C2
x-cache: Error from cloudfront
```

### Actual behavior
After deploy, the index page gives 404

### Expected behavior
Status code must be 20x

### Steps to reproduce
1 - create a new next app
2 - create a simple serverless.yml
3 - deploy to aws

repo: https://github.com/lalvesoliveira/teste-aws
my application: https://da8ewscicjuzd.cloudfront.net/

### Versions

- OS/Environment: Windows 10
- @sls-next/serverless-component version: 3.1.0-alpha.6
- Next.js version: 10.0.2

### Checklist

- [ ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Can you share the code on a GH repo?

**Comment by lalvesoliveira** [comment]
Yes!
https://github.com/lalvesoliveira/teste-aws

**Comment by dphang** [comment]
Thanks, I was able to reproduce the same issue when deploying from Mac as well. Looks like static HTML index page is having, but if you name something else e.g `/another` it works correctly. Need to check the logic for setting 404 status code and fix it.

**Comment by dphang** [comment]
Found the problem.. the origin response handler tries to reverse the s3 page -> original URL. So `index.html` became `/index` but actually it should be `/` as `/index` isn't found as any route, so it sets to 404 page. However

I thought we had sufficient tests for this but somehow the e2e tests stopped testing index page with SSG/HTML page. Will add back tests for it and fix

**Comment by nmclear** [comment]
@dphang I'm having a similar issue when using a basePath. When navigating to the root basePath, the page is returning a 404 (even though content is returned).

I believe the issue is with the replace regex in the function _reconstructOriginalRequestUri_. Since we are checking only for **/index** at the start of the uri, it will skip over the basePath.

(basePath = hotdog)

So if the _originalUri = hotdog/index_ it will return hotdog/index.

If we switch the regex to be:  originalUri = originalUri.replace(/(\/index)?$/, "/");
_originalUri = hotdog/index_ it will return _hotdog_ and not return 404

Do you see any problems with this logic?

`const reconstructOriginalRequestUri = (s3Uri, manifest) => {
    let originalUri = `${basePath}${s3Uri.replace(/(\.html)?$/, manifest.trailingSlash ? "/" : "")}`;
    // For index.html page, it will become "/index", which is not a route so normalize it to "/"
    originalUri = originalUri.replace(/^(\/index)?$/, "/");
    return originalUri;
};`

**Comment by dphang** [comment]
Thanks, yeah I will fix and add a test.

The fix should be

```ts
originalUri = originalUri.replace(/\/index$/, "/");
```

with

```
originalUri = originalUri.replace(/(\/index)?$/, "/");
```

it also since we no longer have ^ it will work for `/basepath/index` but will also end up adding `/` to the end of all paths. See: https://jsfiddle.net/5j80fhyg/

**Comment by nmclear** [comment]
Ah nice catch, thanks @dphang
