### ISSUE TITLE
Lambda tagging

### ISSUE THREAD

**Issue by aluokkal** [serverless-nextjs/serverless-next.js#1282]
Is it possible to add tags to any of the Edge lambdas with serverless configuration?

**Comment by dphang** [comment]
Yes this has been requested before, it needs to be implemented but we can do it in the near future.

**Comment by dphang** [comment]
Should be added in this (Lambda tagging part at least, other resource tagging will be added later): https://github.com/serverless-nextjs/serverless-next.js/pull/1300
