### ISSUE TITLE
Implement Domain based locale detection

### ISSUE THREAD

**Issue by cmaerz** [serverless-nextjs/serverless-next.js#1283]
**Is your feature request related to a problem? Please describe.**
As mentioned in #1127 domain based locales are missing as a supported feature. In my current project I need the functionality. https://nextjs.org/docs/advanced-features/i18n-routing#domain-routing

**Describe the solution you'd like**
As my research shows the real hostname is forwarded till the `_app.js` file, but the domains confgured in `next.config.js` are not matched properly. I'm not really sure why it's not working. 
Does anyone have hints for me? I would try to solve it myself, but I have no idea where to start.

![image](https://user-images.githubusercontent.com/1479186/123094178-e45ece00-d42c-11eb-80c3-18ecb0679310.png)

**Comment by dphang** [comment]
Yes sorry, this one is not implemented yet. If there is interested I can do it.

I think we will have to update the router around here to add the correct locale based on domain: https://github.com/serverless-nextjs/serverless-next.js/blob/21ac575d9b1a4a4d3244bd08629db78edacaf4a7/packages/libs/core/src/route/index.ts#L153 (similar to how we check hostname in the domain redirect).

**Comment by dphang** [comment]
This was added in the latest alpha versions, I think it should be working now?
