### ISSUE TITLE
CloudFront errors when `notFound: true` returned in `getStaticProps`

### ISSUE THREAD

**Issue by olivergrimes** [serverless-nextjs/serverless-next.js#1286]
I have a page that's using dynamic SSR to generate pages on demand.  When a client requests a path/query that does not have a corresponding api entry, I'd like to return a 404.

I have tried using either the `notFound` or `redirect` return options within `getStaticProps`.  Both of these options work as expected locally, however neither work when deployed to AWS.

For example, given the following page:

`pages/items/[name].tsx`

```typescript
import React from 'react';
import { GetStaticProps, GetStaticPaths } from 'next';

interface Props {
  name: string | undefined;
}

export const getStaticProps: GetStaticProps = async (context) => {

  //Paths/conditions provided for example purposes
  const notFound = context.params?.name === 'not-found';
  const redirect = context.params?.name === 'redirect';

  if (notFound) {
    return {
      notFound: true
    };
  }

  if (redirect) {
    return {
      redirect: {
        destination: '/404',
        permanent: false
      }
    };
  }

  const result = {
    props: {
      name: context.params?.name
    }
  };

  return result;
};

export const getStaticPaths: GetStaticPaths = async () => ({
  paths: [],
  fallback: 'blocking'
});

const Item = (props: Props) => {
  const { name } = props;
  return (
    <h1>
      {`Item: ${name}`}
    </h1>
  );
};

export default Item;
```

Locally, both `/item/not-found` and `/item/redirect`, respond with a 404.  However when deployed to AWS the following occurs:

-  `/item/not-found` - CloudFront responds with a 200, but with the content `AccessDenied`.  In addition to this, a zero byte `not-found.html` object is created in S3.
- `item/redirect` - CloudFront responds with a 503

I'd like to be able to handle this "not found" scenario, where the client receives a 404, and no object is generated in S3.

Versions used:
- @sls-next/serverless-component alpha/latest
- NextJs: 10.0.8

**Comment by dphang** [comment]
Yes I think they may need some implementation work as we aren't handling those cases specially. I will try to repro or if you already have a GH repo to share, that will be helpful to for implementation.

BTW, what do the logs say for the 503 for `item/redirect - CloudFront responds with a 503`. As 503s are generic and can mean anything.

**Comment by jvarho** [comment]
If someone does implement this, it would probably be best to also take into account notFoundRoutes from the prerender manifest. Those are routes which were determined to return 404 during build. I.e. they should not be rendered at all in fallback cases.

(The redirect option from the OP is not something next.js supports for SSG either. The notFound one is what should work.)

**Comment by olivergrimes** [comment]
Thanks for the quick response!  I've put an example into a repo [here](https://github.com/olivergrimes/serverless-nextjs-not-found-ex).

The `notFound` option is perfect for our scenario, using `redirect` was an attempted workaround.  I'll dig out the CF logs in any case so the info is there.

**Comment by olivergrimes** [comment]
For reference, for the the 503/redirect:

CF logged a `LambdaExecutionError`

The Lambda@Edge logs record:

```json
2021-06-24T07:59:58.735Z  ERROR  Invoke Error 	
{
    "errorType": "NotImplemented",
    "errorMessage": "A header you provided implies functionality that is not implemented",
    "Code": "NotImplemented",
    "Header": "Transfer-Encoding",
    "name": "NotImplemented",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 501,
        "httpHeaders": {
            "content-type": "application/xml",
            "transfer-encoding": "chunked",
            "date": "Thu, 24 Jun 2021 07:59:58 GMT",
            "server": "AmazonS3",
            "connection": "close"
        },
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "NotImplemented: A header you provided implies functionality that is not implemented",
        "    at deserializeAws_restXmlPutObjectCommandError (/var/task/index-4d1c10fe.js:3789:41)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```
