### ISSUE TITLE
Calculate Lambda handler sizes after build and post in PR

### ISSUE THREAD

**Issue by dphang** [serverless-nextjs/serverless-next.js#1314]
**Describe the solution you'd like**
To ensure no regressions in Lambda handler sizes due to incorrect imports, etc, it will be nice to calculate the sizes of the standard/minified handlers such as `dist/default-handler`. Ideally there could be a diff as well to show the size increase/decrease compared to previous revision (we could use S3 to store the size per commit)

**Comment by tyler-ground** [comment]
This would also be great to keep an eye on how far off the max lambda code payload limit wall is.

**Comment by dphang** [comment]
The sizes are calculated and uploaded to S3 on every master branch build.

For doing the size diff, we can make the sizes readonly via CF + S3 origin so they can be accessed by any PR. Then just calculate current size and then calculate diff against it.

To post the comment, for non-fork PRs we can simply invoke an action to post a comment. For fork PRs we might need some other way like through a proxy Lambda or using the `pull_request_target`
