### ISSUE TITLE
Rewrites issue resurfacing

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#1328]
Hi @dphang after upgrading versions, an old issue (#733) has resurfaced. I was previously on `@sls-next/serverless-component@1.19.0-alpha.45` (no issue), and upgraded to `@sls-next/serverless-component@1.20.0-alpha.28` (issue re-appears).

### Describe the bug
When using a "no-op rewrite" as in the above issue, direct navigation to a content page 404s.

Example:
- we have our SSG page in the folder `pages/[[...content]]/index.js`
- we have the below rewrite config to allow us to access the URLs directly ie `website.com/my-pretty-route`
- when visiting `website.com/my-pretty-route`, this 404s.

Rewrite config:
```
{
	source: '/:path*',
	destination: '/:path*',
},{
	source: '/:path*',
	destination: '/content/:path*',
}
```

### Actual behavior
404 when visiting a route. Client-side navigation to the route works, but navigating directly doesn't.

### Expected behavior
200

### Steps to reproduce
Load a page as in the above

### Versions

- OS/Environment:
- @sls-next/serverless-component version: `@sls-next/serverless-component@1.19.0-alpha.45`
- Next.js version: `^10.2.4-canary.2` (this should be reproducible on a release version -- I need to use this for a bug fix within next)

**Comment by dphang** [comment]
@patricktyndall yes it was removed during refactoring, I forgot why exactly but we probably should add it back...

**Comment by patricktyndall** [comment]
@dphang ok, yes I definitely need this back -- important next compatibility break, and we both went through some trouble to get it fixed.

Do you know of a version number where this was removed? I had to upgrade to support `fallback: blocking`, but it broke my existing pages.

**Comment by dphang** [comment]
I think somewhere in 1.19.1-alpha.6 according to https://github.com/serverless-nextjs/serverless-next.js/commit/dd6576e6276ad85cda0aabe016eb3e3b06460873

**Comment by patricktyndall** [comment]
Ok, thanks for the quick help. For now I'll be using `1.19.1-alpha.5` as it appears to support `fallback: blocking` and also doesn't have the rewrites issue (phew, glad there was a version that works).

Would be grateful if we could fix this in the future!

**Comment by jvarho** [comment]
I did flag that behavioral change in the pull request in question – #1057 – it was incompatible with what Next.js does when given the same configuration. The compatible way to add it back would be to implement #1003

**Comment by dphang** [comment]
Yeah, I think for some versions I remember it was still supported that way, I can add it back since it seems a small change actually from looking at the code. But yes we should implement the new object format as well.
