### ISSUE TITLE
Cloudfront Outage

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#1330]
Is anyone else's site down due to the current cloudfront outage?

**Comment by andrewnick** [comment]
Yea our site is. Going live today as well

**Comment by patricktyndall** [comment]
Lmk if you can find an alternate AWS stack.

Tried EC2 + ALB but I can't create an ALB due to the issues

**Comment by andrewnick** [comment]
Sure thing, will let you know. I would imagine it is a good chance it will be a waiting game until AWS get it sorted

**Comment by dphang** [comment]
Yep, the e2e tests for this component are also failing due to this. Looks like a major outage related to ACM certificates as well. It appears to be getting mitigated but there may be backlogged CF propagations

**Comment by dphang** [comment]
The issue has been resolved per AWS status page: https://status.aws.amazon.com/ so I think this can be closed.
