### ISSUE TITLE
'BUNDLE_AWS_SDK' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mcnamara-charles** [serverless-nextjs/serverless-next.js#1331]
So this is probably a really stupid bug but I get this when I run `npm run dev` and I get a similar one when I do `npm run dev:infra`. I had been working on Linux with this for a while so I know it works but I swapped it over to windows today using GitHub as middleware.  Someone please provide me with a quick solution if possible.

**Comment by dphang** [comment]
Not sure but it looks like you are using the example app here? https://github.com/serverless-nextjs/serverless-next.js/blob/3a11699f92df41ce9086fbc2f368ae21b2ac7252/packages/serverless-components/nextjs-component/examples/dynamodb-crud/package.json

If you are on Windows it's not valid to set env variables this way, instead you can do this: https://github.com/serverless-nextjs/serverless-next.js/blob/1935f67f0a5af5b3bd538a091624edd38716bcb4/packages/e2e-tests/next-app-windows/package.json#L11

**Comment by mcnamara-charles** [comment]
@dphang Sorry lol! Just trying to get past this bug quickly. It's actually a repurposed form of the dynomodbcrud example but same difference in the end. To elaborate, I built this entire web app I'm working on already on Linux. I had it working for over a month but you're probably on the right track. To clarify, the package.json itself has:
```json
"scripts": {
    "dev": "BUNDLE_AWS_SDK=1 AWS_ACCESS_KEY_ID=1 AWS_SECRET_ACCESS_KEY=1 LOCAL_DYNAMO_DB_ENDPOINT=\"http://localhost:8000\" next dev",
    "build": "next build",
    "start": "next start",
    "dev:infra": "LOCAL_DYNAMO_DB_ENDPOINT=\"http://localhost:8000\" npm run infra",
    "infra": "node infrastructure/provisionTable"
  },
```

The top line is the one in question. How should I change it to format for windows? Is there a way within that short script I can have it check if it's windows or linux? And do any other lines need changed?

**Comment by dphang** [comment]
I gave the example code above which is what's running and working for the end-to-end tests for Windows. I mostly use Mac/GitHub Actions to deploy this component so I'm not familiar how to switch between the two. Probably something like this may work: https://github.com/kentcdodds/cross-env, but you'll need to do your own research.

**Comment by mcnamara-charles** [comment]
Okay I've got another blocker @dphang. This one is `UnhandledPromiseRejectionWarning: UnknownEndpoint: Inaccessible host: `'. This service may not be available in the `us-west-2' region` when I use `npm run dev:infra`

**Comment by dphang** [comment]
I haven't used this example app myself, but if you follow what the command does, you can see it seems to be using some local DynamoDB endpoint:

https://github.com/serverless-nextjs/serverless-next.js/blob/3a11699f92df41ce9086fbc2f368ae21b2ac7252/packages/serverless-components/nextjs-component/examples/dynamodb-crud/package.json#L7

It sets the AWS SDK's endpoint to the local DynamoDB endpoint: https://github.com/serverless-nextjs/serverless-next.js/blob/3a11699f92df41ce9086fbc2f368ae21b2ac7252/packages/serverless-components/nextjs-component/examples/dynamodb-crud/infrastructure/provisionTable.js#L5-L8.

So you probably need to run a local DynamoDB first?

**Comment by mcnamara-charles** [comment]
I figured it out @dphang Too many quotes around the endpoint. Closing this issue thanks so much!
