### ISSUE TITLE
Cold Start Prevention

### ISSUE THREAD

**Issue by IshanKBG** [serverless-nextjs/serverless-next.js#1388]
### Is this a bug or a feature request ?
No it's not a feature request or bug.
### What's your problem ?
I opened this issue to ask few questions and take suggestions regarding the cold start.
My website is a SSG nextjs website (a.k.a a static blog) with one or two api routes/ssr.
Since lambda@edge is used to serve the website isn't after sometime it can cold start thus loading speed of my website will decrease?
SEO is my main concern as crawlers won't be able to index it properly if cold start happens.
I read many articles on how to warm it up but it just confuses me and I am not sure how to integrate it with this plugin.
I want to use serverless because it is not much costly but I also want to keep my website fast.
I don't want to use Vercel or Netlify as it is more expensive and has a lot of limitations in terms of serverless functions.
If this issue can be fixed then can I get some tips or suggestions on how to prevent cold start ?

**Comment by jvarho** [comment]
Keeping the handler warm is not very easy in lambda@edge. That is discussed in a previous issue: https://github.com/serverless-nextjs/serverless-next.js/issues/1042
