### ISSUE TITLE
Stop Codacy complaining about issues in tests?

### ISSUE THREAD

**Issue by jvarho** [serverless-nextjs/serverless-next.js#1391]
**Is your feature request related to a problem? Please describe.**
I noticed the Codacy check in #1144 – while it's potentially useful, the real issues are drowned out by noise from tests. It's useful to take shortcuts in tests and efforts to fix issues there take time that IMO could be used better.

**Describe the solution you'd like**
Drop `**/tests/**` or similar from being considered by Codacy.

**Describe alternatives you've considered**
Spending time fixing tests or ignoring Codacy complaints.

**Additional context**
https://app.codacy.com/gh/serverless-nextjs/serverless-next.js/pullRequest?prid=7701201

**Comment by dphang** [comment]
Actually there is a valid error there, it looks to be the trailing slash in JSON which is actually invalid (though I think most modern parsers should handle it properly?). Otherwise I think it just follows the eslint/prettier rules. But we can also disable Codacy for tests.
