### ISSUE TITLE
.well-known folder in public, not carried over to S3

### ISSUE THREAD

**Issue by isener** [serverless-nextjs/serverless-next.js#1400]
### Issue Summary
When you try to deploy universal link requirements form both iOS and Android env you should put some files into /public/.well-known but when you try to deploy via serverless/nextjs, folders in public starts with `.` is not uploaded to S3.

### Actual behavior
It is not uploading .well-known folder inside public

### Expected behavior
Uploading .well-known folder inside public

### Steps to reproduce
Create .well-known folder in /public, then try to run serverless upload.

### Versions

- OS/Environment: OSX Big Sur
- @sls-next/serverless-component version: 3.1.0
- Next.js version: 11.0.1

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Looks like `fast-glob` used to match what to upload in s3-static-assets does not match dot entries by default, we can add a config here: https://github.com/serverless-nextjs/serverless-next.js/blob/6d76a79aadbe3be96f1c97b0e1bfc2acd0accfa1/packages/libs/s3-static-assets/src/lib/readDirectoryFiles.ts#L21-L24

Ref: https://github.com/mrmlnc/fast-glob#dot
