### ISSUE TITLE
Disable deploy logs stream

### ISSUE THREAD

**Issue by maciejkorolik** [serverless-nextjs/serverless-next.js#1410]
Is there any way to disable the default stream of logs when deploying an app? On local terminal it looks ok, but when I deploy using CI, it generates few thousands of log lines and it makes it difficult to find something important in the CI logs:
![image](https://user-images.githubusercontent.com/46086480/125429377-2d99ff60-8181-4665-bd8a-968932f1698b.png)
... and similar for next ~7k lines.

**Comment by JamiesWhiteShirt** [comment]
@maciejkorolik Assuming you closed this issue because you found a solution, do you mind sharing it with others who might be facing the same issue? If not, I guess this issue should be reopened.

**Comment by maciejkorolik** [comment]
It's a general [serverless/components](https://github.com/serverless/components) issue, not directly connected to this plugin.

So this issue is a duplicate of: https://github.com/serverless/components/issues/834
