### ISSUE TITLE
Unable to read assets & render CSS/JavaScript

### ISSUE THREAD

**Issue by AmoDinho** [serverless-nextjs/serverless-next.js#142]
Hi 🚶 

My app is not able to render it's CSS or JS atm.

I've configured a s3 bucket for for my static assets but it responds with a `403`.

Here are the logs from the console:

```
Failed to load resource: the server responded with a status of 403 ()
commons.3275fea9.chunk.css:1 Failed to load resource: the server responded with a status of 403 ()
pmb-plus-web-2-dev-attachmentsbucket-1jeigd7yk56z1/_next/static/8xb0yYHJ3rVARl49sxXs9/pages/index.js:1 

Failed to load resource: the server responded with a status of 403 ()
pmb-plus-web-2-dev-attachmentsbucket-1jeigd7yk56z1/_next/static/runtime/webpack-8ed9452df514b4d17d80.js:1 

Failed to load resource: the server responded with a status of 403 ()
pmb-plus-web-2-dev-attachmentsbucket-1jeigd7yk56z1/_next/static/runtime/main-45a5e2a432a79f23ce33.js:1 

Failed to load resource: the server responded with a status of 403 ()
pmb-plus-web-2-dev-attachmentsbucket-1jeigd7yk56z1/_next/static/chunks/commons.fbb0994a08bc278e03d8.js:1

 Failed to load resource: the server responded with a status of 403 ()
favicon.ico:1 

Failed to load resource: the server responded with a status of 403 ()
commons.3275fea9.chunk.css:1 Failed to load resource: the server responded with a status of 403 ()
```

I'm thinking that somewhere in my setup  something somewhere does not have the right permissions, any clues on where to start looking?

I've also looked at the resources attached to the Lambdas and the relevant s3 bucket for the assets appear to be attached to it.

**Comment by bdharvey** [comment]
I'm getting the same thing.

Posted my `serverless.yml` in the hopes that might help debug.

```
service: frontend

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'} 

# Dont think that this one is working and its getting region from provider.region above
region: ap-southeast-2

custom:
  name: frontend
  customDomain: "custom.domain"
  serverless-nextjs:
    assetsBucketName: "frontendAssets"

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

portalFrontend:
  component: serverless-next.js
  inputs:
    domain: ["www", "custom.domain"]

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
```

**Comment by bdharvey** [comment]
Thanks @danielcondemarin I will try that and see if it fixes the issue

**Comment by AmoDinho** [comment]
@danielcondemarin Do you have any idea how I might overcome my issue?

**Comment by danielcondemarin** [comment]
@AmoDinho Are you using the new next component or the plugin? If you are using the plugin I suggest you migrate over to overcome this issue. Otherwise it might take a while before I can look into this.

**Comment by AmoDinho** [comment]
@danielcondemarin thanks for getting back to me! I'm using the plugin, so I will just revert to the component and see what happens. Thanks!

**Comment by AmoDinho** [comment]
Hi @danielcondemarin , I've tried using the component but it does not output any resource info:

```
Serverless: Safeguards Summary: 7 passed, 1 warnings, 0 errors
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Service Information
service: serverless-nextjs-demo
stage: dev
region: us-east-1
stack: serverless-nextjs-demo-dev
resources: 1
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  None
Serverless: Removing old service artifacts from S3...
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Successfully published your service to the Serverless Dashboard: https://dashboard.serverless.com/tenants/amodinho/applications/serverlessnextjsdemo/services/serverless-nextjs-demo/stage/dev/region/us-east-1
```

Here is the [repo](https://github.com/AmoDinho/serverless-nextjs-demo), any idea what the issue might be?

**Comment by danielcondemarin** [comment]
@AmoDinho serverless-components don't currently work with the serverless v1 format (service:, endpoints: etc). 
You'll need a `serverless.yml` like the below: 
```yml
  serverlessNextjsDemo:
    component: serverless-next.js
```
Without all the `service:` `functions:` stuff. Then simply run `npx serverless`. See any of the examples as a guide: 
https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component/examples

**Comment by AmoDinho** [comment]
@danielcondemarin thanks, I tried this and it finally deployed.

But It is still doing what it did with the plugin 🤕 : 
![screenshot-d2gyhq8yi74bck cloudfront net-2019 09 26-14_01_15](https://user-images.githubusercontent.com/19347140/65686806-740ff680-e066-11e9-8715-3b98e10f1285.png)


Is there any chance that my `next.config.js` might be dodgy and causing an issue? 

```
const withTM = require("next-transpile-modules");
const withCSS = require("@zeit/next-css");

module.exports = withCSS(
    withTM({
        transpileModules: ["umqombothi-component-library"],
        target: "serverless",
        webpack(config, options) {
            config.module.rules.push({
                test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
                use: {
                    loader: 'url-loader',
                    options: {
                        limit: 100000
                    }
                }
            });

            return config;
        }

    }),
);

```
