### ISSUE TITLE
image lambda output includes node_modules folder

### ISSUE THREAD

**Issue by davegariepy** [serverless-nextjs/serverless-next.js#1427]
### Issue Summary
when building, `node_modules`  is included in `image-lambda` folder

### Actual behavior
`node_modules` is present in build output

### Expected behavior
`node_modules` will be excluded in build output

### Steps to reproduce
build app using `@sls-next/lambda-at-edge`

### Versions

- OS/Environment: macOS 10.14
- @sls-next/lambda-at-edge@3.1.0
- also tried @sls-next/lambda-at-edge@3.2.0-alpha.20
- @sls-next/cdk-construct@3.1.0
- Next.js version: 10.2.3

### Additional context
`node_modules` is ~30mb

### Checklist

- [x ] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x ] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
This is expected as the image lambda needs to use sharp (a c++ library for image operations), which embeds node_modules built specifically for the Lambda environment (using docker).

It might be possible to minify and bundle it using rollup but just need to make sure it's still compatible, and we still need the sharp binaries which is the largest part...

We can update the architecture diagram to be clearer. Just have been busy the last couple of weeks.

**Comment by davegariepy** [comment]
@dphang ok, thanks!
