### ISSUE TITLE
404 status code returned for html files in public folder

### ISSUE THREAD

**Issue by foubei** [serverless-nextjs/serverless-next.js#1466]
### Issue Summary

The html files located in public folder returned with a 404 status code.

### Actual behavior

404 status code

### Expected behavior

200 status code

### Steps to reproduce

Try to put an html file in public folder, run your serverless command and try to browse to your html folder and check the http status code

### Screenshots/Code/Configuration/Logs

![Screenshot from 2021-07-29 22-48-27](https://user-images.githubusercontent.com/12202571/127514224-b3ac7f18-0b14-4b92-9a1c-53bfb17a35a8.png)

### Versions

- OS/Environment: Linux
- @sls-next/serverless-component version: 3.1.0
- Next.js version: 11.0.1

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Thanks, I was able to repro it. The content is rendered, but the status code is 404 as mentioned. As public files do go through the Lambda, I'm guessing for HTML files we might look at the extension and think it's not part of the routing manifest and add a 404 status as a result. Will need to add a check for public HTML files.
