### ISSUE TITLE
Redirecting to incorrectly cased locale and losing actual locale for language-region

### ISSUE THREAD

**Issue by darren-charterindex** [serverless-nextjs/serverless-next.js#1478]
**Setup:**

```
"next": "11.0.1",
"next-translate": "1.0.7",
@sls-next/serverless-component@3.2.0-alpha.24
```

```
locales: ['en-US', 'en-GB'],
defaultLocale: 'en-US',
...
```

```
/pages/[[segments]].js
```

**Lambda Actual** - incorrect behaviour

Navigating to `www.example.com` with an `Accept-Language` containing `en-GB` redirects to `www.example.com/en-gb`

The `locale` is `en-US` and `query.segments[0]` is `en-gb`.

_Notice the incorrect case in the url, the incorrect locale prop, and the actual locale, though incorrectly lowercase, has appeared in the first segment of the catch all dynamic route_

**Local Actual** - correct behaviour

Navigating to `localhost` with an `Accept-Language` containing `en-GB` redirects to `localhost/en-GB`

The `locale` is `en-GB` and `query.segments[0]` is `undefined`.

**Expected** - correct behaviour

Navigating to `www.example.com` with an `Accept-Language` containing `en-GB` redirects to `www.example.com/en-GB`

The `locale` is `en-GB` and `query.segments[0]` is `undefined`.

**Comment by dphang** [comment]
Yes I think we do a lowercasing all throughout to ensure case insensitive matching, but we can fix that for the redirect. Though I am not sure what you mean by the locale is passed incorrectly. On the test app `next-app-with-locales`, it seems to work correctly? If you go to the root with accept-language of `fr`, it will redirect it seems to work correctly?

For example: https://d1f9sulga5gpon.cloudfront.net/ redirects to https://d1f9sulga5gpon.cloudfront.net/fr and locale looks right

**Comment by darren-charterindex** [comment]
Thank you Daniel, though unfortunately that has made no difference, with the redirection still to lowercase, and the locale being incorrect.

Locally the redirect is always correctly cased `localhost/en-GB`, and event if I navigate directly to the page in lowercase `domain/en-gb`, the locale is still correct.

The setup is standard, and to further described, the `/pages/[[segments]].js` catch all page looks like:

```
const Page = memo(({ notFound }) => {
  const {
    query: { segments = [] },
    locale,
  } = router
  console.log(locale)
  console.log(segments[0])
  return <div />
}
```

**Comment by dphang** [comment]
Thanks for the example, will use that to try to repro and add some tests with language-Region locales

**Comment by dphang** [comment]
I think it should be fixed here: https://github.com/serverless-nextjs/serverless-next.js/pull/1496. Locale redirect from root now goes to the correct case, but even with any casing it should work (and we will normalize the URL to the right casing on server-side e.g en-GB)

**Comment by darren-charterindex** [comment]
It works perfectly. Thank you Daniel. Much appreciated for fixing this, and for all your efforts 👍🏼
