### ISSUE TITLE
Trying to build docusaurus (next.js derived framework fails)

### ISSUE THREAD

**Issue by weisisheng** [serverless-nextjs/serverless-next.js#1508]
### Issue Summary

Have no problem building/deploying pure next.js sites.  Trying to build docusaurus fails.  Have scoured SO and the net for solutions.   Have tried to add nextStaticDir" "../" directing to various places.  No luck.

### Actual behavior

Error: Command failed with ENOENT: node_modules/.bin/next build
spawn node_modules/.bin/next ENOENT

### Expected behavior

Successful deploy.

### Steps to reproduce

Using serverless.yml file and component: "@sls-next/serverless-component@3.2.0" with a subdomain and  nextStaticDir: "../", attempt deploy with "npx serverless".  Error surfaces.  node_modules are included in .gitignore file per instructions elsewhere.  No .env file with a stage is used.

### Versions

- OS/Environment: Ubuntu 20.10
- @sls-next/serverless-component version: 3.2.0
- Next.js version: 11.0

### Checklist

- [ X] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ X] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [ X] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
I'm not sure what do you mean that Docusaurus is a Next.js derived framework? AFAIK the only similarities is that they are both React frameworks...are you trying to mix the two together? How is it working locally?

Not sure if you are able to do that, but this component would mostly focus on the Next.js part...

**Comment by weisisheng** [comment]
It renders locally and renders if I go through the manual steps of uploading to S3 and then connecting a cloudfront distribution to it. In the .bin folder there is no next symlink but there is a docusaurus one.

**Comment by weisisheng** [comment]
From my searching around, looks like I can't use this component to deploy.
