### ISSUE TITLE
How can I debug errors (404, 500) on AWS?

### ISSUE THREAD

**Issue by OwaisSiddiqui** [serverless-nextjs/serverless-next.js#1511]
I frequently get errors (404, 500) on my production website. Where can I see the logs for these errors on AWS? Right now I am going through CloudFront function logs but there are so many different functions and I am not sure how to find the error.

**Comment by dphang** [comment]
You need to look into the CloudWatch logs in the region you are accessing from to see runtime errors. Hopefully for 5xx errors there usually will be some error message, for 404 errors it may not as clear... to get the function name (if you didn't name it) you can check the `.serverless` folder which will have the deployment state.

**Comment by dphang** [comment]
Closing old issue, feel free to open another in case there are other issues related with the component.
