### ISSUE TITLE
Cannot read property 'config' of undefined (isOriginResponse - ISR)

### ISSUE THREAD

**Issue by WarcraftYax** [serverless-nextjs/serverless-next.js#1523]
### Issue Summary

I have added a simple ISR page to my app to test that everything works. However, the page is not getting regenerated (reduplicate is set to 10), and I see an error in my CloudWatch Logs.

### Actual behavior

This is the error:

```json
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'config' of undefined",
    "stack": [
        "TypeError: Cannot read property 'config' of undefined",
        "    at isOriginResponse (/var/task/index.js:2326:32)",
        "    at Runtime.handler (/var/task/index.js:2085:9)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

And `isOriginResponse` looks like:

```js
const isOriginResponse = (event) => {
    return event.Records[0].cf.config.eventType === "origin-response";
};
```

### Expected behavior

For no error to occur, and for the page to be regenerated as expected.

### Steps to reproduce

ISR page added as:

```js
import React from 'react';
import PropTypes from 'prop-types';

export default function TestIsr({ time }) {
  return <>{time}</>;
}
TestIsr.propTypes = {
  time: PropTypes.string.isRequired,
};

export async function getStaticProps() {
  return {
    props: {
      time: new Date().toISOString(),
    },
    revalidate: 10,
  };
}
```

My `serverless.yml` is the following (a couple arns redacted)

```yaml
RPGLogsCmsFFStagingSylvanas:
  component: "@sls-next/serverless-component@3.2.0"
  inputs:
    bucketName: rpglogs-cms-ff-staging-sylvanas
    name: RPGLogsCmsFFStagingSylvanas
    domain: ["my", "domain.com"]
    certificateArn: arn:aws:acm:us-east-1:<ARN REMOVED>
    publicDirectoryCache: false
    roleArn: arn:aws:iam::<ARN_REMOVED>
    nextStaticDir: ./cms/public
    build:
      cleanupDotNext: false
      cmd: "true" # no-op skips the next.js build
```

There are a couple things in there that are different from default but probably not related (my pages directory is elsewhere so I build my app first before deploying - that all seems to work fine).

### Screenshots/Code/Configuration/Logs

If it helps, I added a console.log to see what the events sent to the Lambda look like:

```json
{
            "messageId": "f825d0ce-87c9-4817-b3d0-df7f80be1d82",
            "receiptHandle": "AQEBRS4unMmMCozMzBQWYT8901PibfzRI7k5Kh44YTclXdHxIAV+9kueKdHQVYZtXVOPIdtFwVdcHA+z1eCr+8iB+k5SddLZlaOtpDT6t942xQcXlOuGmDq70y19EDaAauBpZcBNlgW+y2AMpAgZXaYtXDBOYn6cHa0kLzcKSpcg2MlzbsSVUuLEihIaljGsQw9M/d6H53ia39tWXHrb5XJchtB8Gxk+g3BCHKERhmk61hP21L3MQEBsJ/RI+oGKgttihYv9G8dz8B6Qy7Xlo6tQqAdwvgttk1IAD8xgpu8/cMmT45MBZpnJtIDPBWg0D14Z",
            "body": "{\"region\":\"us-east-1\",\"bucketName\":\"rpglogs-cms-ff-staging-sylvanas\",\"cloudFrontEventRequest\":{\"clientIp\":\"81.131.213.245\",\"headers\":{\"cookie\":[{\"key\":\"Cookie\",\"value\":\"__gads=ID=f93cea3149b1a7d7:T=1621332797:S=ALNI_MY1BR-yp8cxrtUixxzwdlNTiNMSrg; __qca=P0-954912098-1621332779337; _ga=GA1.2.186571192.1621332779; _gid=GA1.2.869619759.1628497409; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6Ijg2RE8zU1BidWVvZjBHbkFWcC9PVEE9PSIsInZhbHVlIjoiUlpHSU5WN0E4dlY3aS9IT3FtZDQ3eTRtajFmRTRwZEVOM0JueEVYS3F3dGNDMG9jVDRXNHcvRWNoZFo3M242eEEvcnpKOWhxYUplODVuZzJtYXp0OVlvV0R6NDlYWDkzUFhpQjMrZUgyME9LU3czQ245b2RNMVJiaGtmUnpsRUtPNjRRMUZoaEFudFVmdElxY0xJam1SeVZOaGNJdTBNZEY4NC9QOTAwVzc0QUxzNGovMjNCSG9hR0lIMTdsTDIyakxGS01TSXBad0t6aHozN2VPMHpiMG5KUE11SWhYWjVlTlgwTW5Bc0FNST0iLCJtYWMiOiIyYThkZmUyYWZmOWY3MmU0YzRiNTRlMGVhODgyMmQ3MWFlMzI3MjgzZTA0NDQ1MjJjYjdmMjBjY2MwNDU4ODMzIn0%3D\"}],\"x-forwarded-for\":[{\"key\":\"X-Forwarded-For\",\"value\":\"81.131.213.245\"}],\"user-agent\":[{\"key\":\"User-Agent\",\"value\":\"Amazon CloudFront\"}],\"via\":[{\"key\":\"Via\",\"value\":\"2.0 716fd417a527ecd4f9d6cef2c9258583.cloudfront.net (CloudFront)\"}],\"accept-encoding\":[{\"key\":\"Accept-Encoding\",\"value\":\"gzip\"}],\"sec-ch-ua\":[{\"key\":\"sec-ch-ua\",\"value\":\"\\\"Chromium\\\";v=\\\"92\\\", \\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Google Chrome\\\";v=\\\"92\\\"\"}],\"sec-ch-ua-mobile\":[{\"key\":\"sec-ch-ua-mobile\",\"value\":\"?0\"}],\"upgrade-insecure-requests\":[{\"key\":\"upgrade-insecure-requests\",\"value\":\"1\"}],\"sec-fetch-site\":[{\"key\":\"sec-fetch-site\",\"value\":\"same-origin\"}],\"sec-fetch-mode\":[{\"key\":\"sec-fetch-mode\",\"value\":\"navigate\"}],\"sec-fetch-user\":[{\"key\":\"sec-fetch-user\",\"value\":\"?1\"}],\"sec-fetch-dest\":[{\"key\":\"sec-fetch-dest\",\"value\":\"document\"}],\"host\":[{\"key\":\"host\",\"value\":\"rpglogs-cms-ff-staging-sylvanas.s3.us-east-1.amazonaws.com\"}],\"cache-control\":[{\"key\":\"Cache-Control\",\"value\":\"max-age=0\"}]},\"method\":\"GET\",\"origin\":{\"s3\":{\"authMethod\":\"origin-access-identity\",\"customHeaders\":{},\"domainName\":\"rpglogs-cms-ff-staging-sylvanas.s3.us-east-1.amazonaws.com\",\"path\":\"/static-pages/D8COYxhbID2kkl4hKHxex\",\"region\":\"us-east-1\"}},\"querystring\":\"\",\"uri\":\"/test-isr\"},\"basePath\":\"\",\"pagePath\":\"pages/test-isr.js\"}",
            "attributes": {
                "ApproximateReceiveCount": "72",
                "SentTimestamp": "1628526237076",
                "SequenceNumber": "18863646790401008384",
                "MessageGroupId": "/test-isr",
                "SenderId": "AROAUPIGFRAAWB336GB5A:us-east-1.RPGLogsCmsFFStagingSylvanas",
                "MessageDeduplicationId": "\"fb669fa9f0b6d1f223827da094d41539\"",
                "ApproximateFirstReceiveTimestamp": "1628526237076"
            },
            "messageAttributes": {},
            "md5OfBody": "92590fb3e1ac221b8470417d082df290",
            "eventSource": "aws:sqs",
            "eventSourceARN": "arn:aws:sqs:us-east-1:307639977985:rpglogs-cms-ff-staging-sylvanas.fifo",
            "awsRegion": "us-east-1"
        }
```

### Versions

- OS/Environment: Deployed to AWS (from WSL Bash on Windows)
- @sls-next/serverless-component version: 3.2.0
- Next.js version: 11.0.1

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

I haven't tried the latest alpha - I can do that first thing tomorrow so see if it helps, but would appreciate any help in the meantime if there is something obviously wrong going on.

EDIT: It doesn't look like the latest alpha has anything significantly different from 3.2.0, which is what I'm using

**Comment by WarcraftYax** [comment]
I think the cause of my issue if this line in my `serverless.yml`:

```yaml
name: RPGLogsCmsFFStagingSylvanas
```

This causes all the Lambdas to have the same name. I had assumed that they would still get unique names, with this value used as a prefix. So I think I can get this working by specifying the names individually. However, is it worth updating documentation or adding some sort of prefix behaviour when this input is set like this?

**Comment by WarcraftYax** [comment]
Okay I can confirm that the above was the cause of my error. So this was definitely user error, however, the documentation for `name` states:

```
When assigned a string, both the default and api lambdas will assigned name of that value. When assigned to an object, values for the default and api lambdas can be separately defined
```

Which implies that setting `name` to a string is valid. I think something should be updated to indicate that this can cause issues and is not recommended for all scenarios?

**Comment by dphang** [comment]
Thanks, fixed in https://github.com/serverless-nextjs/serverless-next.js/pull/1569
