### ISSUE TITLE
v3.2.0 Breaks Preview Mode?

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#1527]
### Issue Summary
I upgraded from `@sls-next/serverless-component@1.19.1-alpha.5` to `@sls-next/serverless-component@v3.2.0` (as in my serverless.yml). Deployed with no other changes, and now preview mode isn't working. 
- @dphang I chose `v3.2.0` to get the no-op rewrites support, also because it was a release version.

### Actual behavior
Preview mode doesn't work

### Expected behavior
Preview mode works

### Steps to reproduce
Use v3.2.0

### Versions

- OS/Environment: Mac OS
- @sls-next/serverless-component version: `v3.2.0`
- Next.js version: `10.2.4-canary.2` (was on this version before upgrading `serverless-next.js` and everything worked fine.)

**Comment by patricktyndall** [comment]
Update -- a weird thing that is happening is that preview mode is working on my homepage only, but not on any of my other SSG pages.

**Comment by patricktyndall** [comment]
Update -- a weird thing that is happening is that preview mode is working on my homepage only, but not on any of my other SSG pages. My homepage is the base of an optional catch-all ([[...all]]). It’s also behind a rewrite.

Could there be something up with preview mode and catch alls?

**Comment by b3nThomas** [comment]
I think the same or very similar issue is being tracked here:
https://github.com/serverless-nextjs/serverless-next.js/issues/1361

**Comment by patricktyndall** [comment]
Created a minimal reproduction repo [here](https://github.com/patricktyndall/sls-next-1527-repro).

I deployed it [here](https://d22gp3kk2medb6.cloudfront.net).

To reproduce the issue:
- If you visit this preview mode link, it works: https://d22gp3kk2medb6.cloudfront.net/api/preview?secret=my-secret&slug=/
- But if you visit this preview mode link, or just go directly to /route-1, it doesn't work: https://d22gp3kk2medb6.cloudfront.net/api/preview?secret=my-secret&slug=/route-1

The above two routes are SSG'd from the same file `pages/[[...all]]` , which is why it's so strange that preview would work for one and not the other.

(you can exit preview https://d22gp3kk2medb6.cloudfront.net/api/exit-preview)

**Comment by J3tto** [comment]
After a little debugging I found the cause. See PR with fix. 

When route was dynamic e.g. ``[[...slug]]` data and page routes would return the SSG content, rather than the SSR.  
Added the same `&& !isPreview` to ensure it matches the same logic used on non dynamic routes.

**Comment by patricktyndall** [comment]
Thanks @J3tto! Just to confirm -- does that explain why it would have been working for the "base" page of the dynamic route?

**Comment by J3tto** [comment]
> Thanks @J3tto! Just to confirm -- does that explain why it would have been working for the "base" page of the dynamic route?

@patricktyndall Correct the base page `/` evaluates to use the non dynamic SSR routes. As this SSG condition already had the `!isPreview` condition it bypass and pass to the SSR render just below it.
https://github.com/stackcrafters/serverless-next.js/blob/bb85a467f93f90e121a166919a605ec1222c535e/packages/libs/core/src/route/page.ts#L43 


However the rest of the paths for `[[...slug]]` would evaluate to a dynamic route.  With no check for preview bypass so it would serve the SSG version rather than the SSR version. 
https://github.com/stackcrafters/serverless-next.js/blob/bb85a467f93f90e121a166919a605ec1222c535e/packages/libs/core/src/route/page.ts#L96

**Comment by patricktyndall** [comment]
Sweet, thanks for the explanation and the PR. I'll be watching the releases to get this out to my team.

**Comment by b3nThomas** [comment]
Just tested this fix running a local install of the project with the two changes applied and can confirm that it's resolved the issue for me! 🎉 
Great work @J3tto and thanks for the detailed explanation 👏
