### ISSUE TITLE
Build failed when require inside next.config.js

### ISSUE THREAD

**Issue by IzioDev** [serverless-nextjs/serverless-next.js#1571]
### Issue Summary
The build is failing when I have a require inside next.config.js.

### Actual behavior
Considering my nextjs configuration :
```js
const withPWA = require("next-pwa");

module.exports = withPWA({
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr"],
  },
  target: "experimental-serverless-trace", // I tried with serverless, same result
  pwa: {
    dest: "public",
  },
});
```
It is not building and result with the error : 
```
Error: Cannot find module 'webpack'
```
Trace :
```
- /builds/izio38/iziowebsite/node_modules/workbox-webpack-plugin/build/generate-sw.js
- /builds/izio38/iziowebsite/node_modules/workbox-webpack-plugin/build/index.js
- /builds/izio38/iziowebsite/node_modules/next-pwa/index.js
- /builds/izio38/iziowebsite/next.config.js
- /root/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.1-alpha.0/node_modules/@sls-next/lambda-at-edge/dist/build.js
- /root/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.1-alpha.0/node_modules/@sls-next/lambda-at-edge/dist/index.js
- /root/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.1-alpha.0/node_modules/@sls-next/serverless-component/dist/component.js
- /root/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.1-alpha.0/node_modules/@sls-next/serverless-component/serverless.js
- /usr/local/share/.config/yarn/global/node_modules/@serverless/core/src/Component.js
- /usr/local/share/.config/yarn/global/node_modules/@serverless/core/src/index.js
- /usr/local/share/.config/yarn/global/node_modules/@serverless/cli/src/index.js
- /usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/builds/izio38/iziowebsite/node_modules/workbox-webpack-plugin/build/generate-sw.js:24:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/builds/izio38/iziowebsite/node_modules/workbox-webpack-plugin/build/generate-sw.js',
    '/builds/izio38/iziowebsite/node_modules/workbox-webpack-plugin/build/index.js',
    '/builds/izio38/iziowebsite/node_modules/next-pwa/index.js',
    '/builds/izio38/iziowebsite/next.config.js',
    '/root/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.1-alpha.0/node_modules/@sls-next/lambda-at-edge/dist/build.js',
    '/root/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.1-alpha.0/node_modules/@sls-next/lambda-at-edge/dist/index.js',
    '/root/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.1-alpha.0/node_modules/@sls-next/serverless-component/dist/component.js',
    '/root/.serverless/components/registry/npm/@sls-next/serverless-component@3.2.1-alpha.0/node_modules/@sls-next/serverless-component/serverless.js',
    '/usr/local/share/.config/yarn/global/node_modules/@serverless/core/src/Component.js',
    '/usr/local/share/.config/yarn/global/node_modules/@serverless/core/src/index.js',
    '/usr/local/share/.config/yarn/global/node_modules/@serverless/cli/src/index.js',
    '/usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless.js'
  ]
```
### Expected behavior
I expect the require to work or to have a documented workaround.

### Steps to reproduce
You just have to required something inside the next config.

### Versions
- OS/Environment: node:latest
- @sls-next/serverless-component version: 3.2.1-alpha.0
- Next.js version: 11.0.1

### Related issue
https://github.com/vercel/next.js/discussions/14422

### PS
Running a `next build` and a `next start` works tho. So it might be something wrong with the serverless plugin, right ?

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by izio38** [comment]
It looks like the part that is failling is this one : 
```ts
  async readNextConfig(): Promise<NextConfig | undefined> {
    const nextConfigPath = path.join(this.nextConfigDir, "next.config.js");

    if (await fse.pathExists(nextConfigPath)) {
      const nextConfig = await require(nextConfigPath);

      let normalisedNextConfig;
      if (typeof nextConfig === "object") {
        normalisedNextConfig = nextConfig;
      } else if (typeof nextConfig === "function") {
        // Execute using phase based on: https://github.com/vercel/next.js/blob/8a489e24bcb6141ad706e1527b77f3ff38940b6d/packages/next/next-server/lib/constants.ts#L1-L4
        normalisedNextConfig = nextConfig("phase-production-server", {});
      }
      return normalisedNextConfig;
    }
  }
```

From : https://github.com/serverless-nextjs/serverless-next.js/blob/7191bf7317a007e80f4e351b8ee9531cac74af3e/packages/libs/lambda-at-edge/src/build.ts#L505-L520

Is there any reason why we are not using the exported `loadConfig` function from https://github.com/vercel/next.js/blob/d143d9879f2bbb43809f59059ab08cbe4b8fabf6/packages/next/server/config.ts#L451 ?

Also, it looks like the `@next` sub-package from `nextjs` has a dependency to `webpack` according to this: https://github.com/vercel/next.js/blob/d143d9879f2bbb43809f59059ab08cbe4b8fabf6/packages/next/package.json#L252

I guess this is why a normal `next build` does resolve `webpack` while requiring `next.config.js`. And this serverless plugin does not, since it does not add a webpack dependency ?

I am not sure of what I'm saying and would be glad to help if you lead me to the right way :)

**Comment by izio38** [comment]
Adding `webpack` to my project did solve the issue... But eh, is this a viable solution ?

**Comment by dphang** [comment]
Ya, I did write that code but at the time I was new to the project as well, perhaps better to try to use Next.js code where possible so we don't reinvent the wheel. I'll add this to a list of things to refactor.

I guess if we include webpack as a dependency, it should solve the issue for now?

**Comment by IzioDev** [comment]
It should 'solve' my current issue, but I'm not sure that would solve all kind of build error.

Maybe the viable solution is to try using the exported function from nextjs (in a long term).

But yes, adding webpack should do the trick to a workaround :)

**Comment by dphang** [comment]
Ya, that is the short term solution for sure, it would be better if we tried to use Next.js functions to prevent these kinds of issue...will definitely take some time to refactor, though.

**Comment by dphang** [comment]
Anyway I've added webpack here: https://github.com/serverless-nextjs/serverless-next.js/commit/3aa0b6d097bbdc5b978c1bff73db671e082c61a8.
