### ISSUE TITLE
RequestTimeTooSkewed: The difference between the request time and the current time is too large.

### ISSUE THREAD

**Issue by kiorq** [serverless-nextjs/serverless-next.js#1582]
I'm not sure where is the best way to report this. I'm trying to deploy using an aws profile

Command: `AWS_PROFILE=development SLS_DEBUG=* serverless --stage dev --debug`

And i'm getting the following error

```
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'RequestTimeTooSkewed',
  region: null,
  time: 2021-08-24T18:40:02.093Z,
  requestId: 'A1MM3N2EMA5YET6S',
  extendedRequestId: 'VPXk2id/VUQbg3zbIoERD5AADpCSIyx22Gg24IJ4KfvsJEaGmI6drGoWrhd1kXOSomwFOt6BifQ=',
  cfId: 'xfQ90_kAAxYddqyfhrwsedq5qso9YBhF_pjM2W6DZYUsZWzGUxUDmQ==',
  statusCode: 403,
  retryable: false,
  retryDelay: 56.23016580042837
}

  913s › BizHubSite › RequestTimeTooSkewed: The difference between the request time and the current time is too large.

FAIL: 1
```

I did some quick research and tried manually changing my clock on my local machine (macOS) to 6 hours into to future to be near the same time as aws, this lead to me getting a forbidden error. Similar to https://github.com/serverless-nextjs/serverless-next.js/issues/289. However, I do not have env vars in my serverless config. See below

```
name: bizhub-site
BizHubSite:
  component: '@sls-next/serverless-component@3.3.0-alpha.2'
  inputs:
    domain: 'thethebee.com'
    memory: 1024
    name: 'bizhub-site-dev'
```

I don't think it could be something wrong with my credentials unless it is not acknowledging the `AWS_PROFILE` env var. I will also like to add I have other repos using the serverless framework but not with this component. And i'm able to deploy with the argument `--aws-profile development`, which doesn't seem to work with this component.

Thank you all in advance.

**Comment by kiorq** [comment]
After further investigation, it seems to be an issue with AWS file upload when file upload take longer than 15 minutes.

**Comment by dphang** [comment]
Hm, unfortunately I didn't see this before myself but as you mentioned it looks to be related to clock sync. I'm also not in us-east-1 zone but deploy to there and haven't had any issues.

If it's really due to > 15 min upload time, unfortunately I don't think there's much we can do (we already try to compress + optimize the bundle size using Rollup.js as much as possible). Feel free to use the minified handlers and/or minify your own server-side code + use the latest Next.js versions (11+) which have better code size optimizations than behavior.
