### ISSUE TITLE
Allow `postbuild` script to run when build.cmd is `["npm", "run build"]`

### ISSUE THREAD

**Issue by jonahallibone** [serverless-nextjs/serverless-next.js#1587]
### Issue Summary
This issue might have a different solution, but the technical problem I am facing I don't seem to be able to run scripts in the `postbuild` section of my package. I also swapped the `build.cmd` from running the next build binary directly, to running the npm command. Specifically, I am trying to generate a `sitemap.xml` using [next-sitemap](https://github.com/iamvishnusankar/next-sitemap). Locally, I have no issues running `npm run build` and then having the sitemap generate immediately afterward. The package section looks like this:

```json
"build": "next build",
"postbuild": "next-sitemap",
```
I could also run this as `npx next-sitemap` as a standalone command, outside the postbuild. I have tried running this in `build.postBuildCommands` and have it copied into the `.serverless_nextjs/assets/public` folder. However, that as well seems to not run.

### Actual behavior
The script doesn't seem to run, or it get's ignored by the component.

### Expected behavior
The `sitemap.xml` should be generated and be available in the `public/` folder before deployment.

### Steps to reproduce

- Add `next-sitemap` to your repo, follow the steps outlined in their repo. 
- Try and deploy with `serverless` (I am also doing serverless --debug and looking for logs. None appear)

### Versions

- OS/Environment: macOS
- @sls-next/serverless-component version: `3.2.0`
- Next.js version: `11.0.1`

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jonahallibone** [comment]
@dphang I'm wondering if generally you might have some advice for how to build a sitemap and serve the result, even though generation would have to happen after the build and before the deploy. I'm not sure if it won't work because it's not in a manifest or something?

**Comment by dphang** [comment]
Hm, I thought postBuildCommands is suitable for this. Not sure why it is not working? Do other commands work? Ideally you can debug it, the code is here: https://github.com/serverless-nextjs/serverless-next.js/blob/c2f2ac0009d4844376b00c8cefcacf72414d42af/packages/serverless-components/nextjs-component/src/component.ts#L271-L271

Or you can add it here as a third party integration (helpers for third party packages like next-i18next: https://github.com/serverless-nextjs/serverless-next.js/blob/c2f2ac0009d4844376b00c8cefcacf72414d42af/packages/libs/lambda-at-edge/src/build.ts#L345-L345 so it can help others as well. Right now it only passes the lambda directories, but you can start passing the asset directory as well and create a file to copy to there

**Comment by jonahallibone** [comment]
@dphang turns out the issue was associated with our CI runtime not supporting nullish coalescing, not the package. Thanks for the response though!
