### ISSUE TITLE
Enabling i18n causes ISR to break

### ISSUE THREAD

**Issue by WarcraftYax** [serverless-nextjs/serverless-next.js#1598]
### Issue Summary

ISR stopped working for me on a recent deploy. One of the new features I added was using next.js's i18n localization. On a bit of a whim, I decided to remove it and redeploy, and now ISR is working again.

Maybe something to do with the Accept Language header being part of the CloudFront cache key when localization is enabled? Or something to do with the localized subpathing (though I only had a single en localization and I was accessing it without a subpath and still had the issue).

I noticed all my x-cache response headers were misses from CloudFront.

### Steps to reproduce

For me, adding the following to my `next.config.js` caused this behaviour:

```
  i18n: {
    locales: ['en'],
    defaultLocale: 'en',
    localeDetection: false,
  },
```

### Screenshots/Code/Configuration/Logs

This happened a few days ago, and I'm going through the CloudWatch Logs but I don't actually see any errors on this day in either the Default or Regeneration lambdas.

### Versions

- OS/Environment: Runs in GitHub Actions on Ubuntu latest
- @sls-next/serverless-component version: 3.2.0
- Next.js version: 11

### Additional context

I would like to spend more time debugging this, but as localization isn't needed for our initial MVP, I can't yet justify the time now that I have a workaround that works. However, I still wanted to post the issue in case someone else is having issues with ISR and realises that maybe this is the cause. I may be able to look more into this in the future when we need to start adding localized content.

On the initial issue I commented on, @dphang had this remark

> hm yes there is not good e2e test coverage for i18n locales yet, it might be that the path is not translated correctly to hit the regeneration lambda (and save the new page)

**Comment by dphang** [comment]
Thanks, I will try to take a look at this this week.

**Comment by dphang** [comment]
I've added the ISR pages to the locales test app but couldn't see any issue. You can try the below, it does regenerate the page after every ~10 seconds

https://d1f9sulga5gpon.cloudfront.net/fr/revalidated-ssg-page
https://d1f9sulga5gpon.cloudfront.net/en-GB/revalidated-ssg-page

**Comment by dphang** [comment]
Hm, actually there is a problem with the pre-rendered ISR page: https://github.com/serverless-nextjs/serverless-next.js/runs/3492625470?check_suite_focus=true. Seems that the regeneration Lambda is not triggered, need to check why.

**Comment by WarcraftYax** [comment]
Thank you for fixing this! Sorry I wasn't able to be of more help.

**Comment by dphang** [comment]
No worries! It was a legitimate bug so the report is still useful :D
