### ISSUE TITLE
Question: build and deploy without console output every second

### ISSUE THREAD

**Issue by kprzybylo** [serverless-nextjs/serverless-next.js#1642]
Is it possible to run serverless command without having "Deploying" info every second? Just final message about success or error would be needed, but this info every second that something is going one is not always wanted (CI/CD get's messy because of it).

**Comment by dphang** [comment]
Ya unfortunately I think that's because of the serverless beta, there are a couple issues about it before. Either we can patch that part if we know what to fix or upgrade though we have so much custom AWS code already I had been putting it off for now...

**Comment by kprzybylo** [comment]
Thanks for response. Would be nice to have it, but I guess it is not so important as everything works fine with it. I will try to solve it somehow by myself. If it will succeed then I will share my code/workaround.

**Comment by dphang** [comment]
Ya, if you come across something it would be helpful. Maybe a patch can be applied via https://github.com/ds300/patch-package and we can add it to this package 👍

**Comment by dphang** [comment]
Trying out patching @serverless/cli here to avoid having to fork @serverless/cli and serverless package: https://github.com/serverless-nextjs/serverless-next.js/pull/1658 (also added another fix for next silent build failure)

**Comment by dphang** [comment]
https://github.com/serverless-nextjs/serverless-next.js/pull/1658 has been published in npm (alpha for now), so you should be able to run command `npx serverless-patched` which contains the fixes. Let me know if there are any issues; I have tested it locally and it seems to work (tested with `npx --package @sls-next/serverless-component serverless-patched` to force fresh version)
