### ISSUE TITLE
Domain based routing not considered in regeneration lambda

### ISSUE THREAD

**Issue by cmaerz** [serverless-nextjs/serverless-next.js#1729]
### Issue Summary

When a regeneration request is sent to the lambda (for example `https://www.top-radio.de/top-stations`) it's always stored in `/static-pages/<Build ID>/top-stations.html` without the consideration of the domain locale. 

The pages are generated in the right locale. So I think only a change in https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/regeneration-handler.ts#L34 is needed.

I'm on the latest Alpha v3.4.0.alpha-9

I tried to fix this, but I somehow can't build the Repos locally.. it always stucks at `copy-sharp-modules`

### Expected behavior

In this example www.top-radio.de has a default locale `de-DE` so the right thing todo would be storing it to `/static-pages/<Build ID>/de-DE/top-stations.`

### Steps to reproduce
1. use domain based locales
2. add a page with a revalidation timeout
3. check what the regeneration lambda is doing

**Comment by cmaerz** [comment]
I created a WIP Pull Request: https://github.com/serverless-nextjs/serverless-next.js/pull/1731

As I still can't build the project cause of: 
![image](https://user-images.githubusercontent.com/1479186/134358950-411bb081-2a7a-40f7-bcfd-31ff45d40159.png)

I can't test it...

**Comment by dphang** [comment]
Merged the change and published
