### ISSUE TITLE
S3 bucket is set to public read

### ISSUE THREAD

**Issue by revblock** [serverless-nextjs/serverless-next.js#1730]
### Issue Summary
The S3 bucket is set to allow public read access but this goes against AWS security best practices. Also, assets from this bucket are served from CloudFront anyway which presents 2 access patterns for the same data. I think this permission should be removed.

### Actual behavior
S3 bucket has public read access and access via CloudFront

### Expected behavior
S3 bucket should only be accessible via CloudFront and public read denied

### Screenshots/Code/Configuration/Logs
Public read setting is here https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/serverless-components/nextjs-cdk-construct/src/index.ts#L81

### Versions
Latest

### Additional context
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-2

**Comment by dphang** [comment]
Should be fixed in https://github.com/serverless-nextjs/serverless-next.js/pull/1758
