### ISSUE TITLE
Adding a bang symbol (!) to next.config.js values can break production builds

### ISSUE THREAD

**Issue by azoff** [serverless-nextjs/serverless-next.js#1738]
### Issue Summary

I was trying to build a simple NextJS app, with `target: serverless`, but ran into an error like this:

```sh
 ModuleNotFoundError: Module not found: Error: Can't resolve '%22%2C%22option%22%3A%22MLxi%3BRuwVNv%3EsgnLGKfN6%22%2C%22...' in '/codebuild/output/src009805444/src/my-app'
```

After inspecting the generated webpack config file, it became clear that the issue had to do with the inclusion of an exclamation mark (`!`) in the config file as a value. The result of this inclusion was to break the syntax of the webpack loader:

```js
...
entry: {
  'pages/index': 'next-serverless-loader?page=%2F%5B%5B...foo=bar!%22%2C%22option%22%3A%22MLxi%3BRuwVNv%3EsgnLGKfN6%22%2C%22....!'
}
...
```

The result was webpack assuming the contents following the bang symbol were a module, which of course broke the build.

### Actual behavior

The build broke.

### Expected behavior

The build would not break, and that all characters would be properly encoded for the loader params.

### Steps to reproduce

In theory, add an exclamation mark to a value in your nextjs config file.

### Versions

- node@14.17.6
- npm@6.14.15
- OS/Environment: Mac
- @sls-next/serverless-component version: 3.3.0
- Next.js version: 11

### Additional context

Hope this helps, and sorry for not including more thorough repro- hopefully this is easy enough to fix. Also maybe another project is better to post this in?

I also didn't use an Alpha version since this error occurs in Amplify, which I assume uses a stable version.

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Hm, not quite sure if this a problem in this component? I believe we only read `next.config.js` for a few config values like redirects, trailing slash etc. Is there any trace you can provide where it's failing in this component or the lambda@edge build code?

Otherwise I can check this out later.

**Comment by azoff** [comment]
hmm, this might be wrong project then. The project I need to file this report in, is the one that ultimately generates the webpack config for the nextjs production build when `target: serverless` is added to the `next.config.js` file. Would that be the actual nextjs project itself?

**Comment by dphang** [comment]
Yes since we don't actually do the Next.js build (and don't use webpack otherwise), might be good to raise the issue to the Vercel team? Basically try to see if the issue occurs just doing `next build` itself. Hopefully there is nothing in this component that is causing problems.

**Comment by azoff** [comment]
Got it, I'll close this and report it directly to the vercel team.
