### ISSUE TITLE
Query is not included in next.js redirect

### ISSUE THREAD

**Issue by shunkakinoki** [serverless-nextjs/serverless-next.js#1742]
Query string is omitted from the next.js redirect string.

### Versions

- OS/Environment:
- @sls-next/serverless-component version:
- Next.js version:

### Checklist

- [ ] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Please fill out the template completely and add a repro if possible.

Which version are you using? We do test query strings redirect case and they should be passed correctly. See https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/e2e-tests/next-app/cypress/integration/redirects.test.ts

**Comment by shunkakinoki** [comment]
@dphang 

Thank you for the awesome work.

You've done so much for the community. I hope I can give back someday when I make it (hopefully) 

I use ^3.3.0 and the repo is located at https://github.com/shunkakinoki/shunkakinoki.com

**Comment by dphang** [comment]
Hm, just tried your website and it seems to work https://shunkakinoki.com/schedule?a=b redirects with query string. There are a lot of links to try, which one specifically does not work?

**Comment by shunkakinoki** [comment]
Thank you for helping me out on saturday! specifically, https://shunkakinoki.com/zoom does not redirect with query string.

**Comment by dphang** [comment]
Oh, noticed it's an external link, we do test it here with internal links with destination query string here: https://github.com/serverless-nextjs/serverless-next.js/blob/96297b224bce97d6ac187479911a7e97d1c3cdd9/packages/e2e-tests/next-app/cypress/integration/redirects.test.ts#L184. Let me check if there's anything strange with external links.

**Comment by shunkakinoki** [comment]
Thank you so much!!!
