### ISSUE TITLE
Add an option to use lambda functions instead of forcing lambda@edge deployment mode

### ISSUE THREAD

**Issue by electroma** [serverless-nextjs/serverless-next.js#1843]
**Is your feature request related to a problem? Please describe.**

Lamda@edge is an amazing technology, but it has some drawbacks:
* it has some limitation compared to lambdas
* it is harder to debug (due to not transparent multi-region CloudFront deployment model)
* deployment takes 10+ minutes

**Describe the solution you'd like**

Have an option to switch to "normal" lambdas, at least in development mode.

**Comment by dphang** [comment]
Yup, it's definitely on the road map for a while now and there were several issues opened already. Work has already been done to genericize the handlers so it's not coupled to Lambda@Edge. I will just need to wrap them into Lambda handlers (default + image handler) and add the build/deployment logic. https://github.com/serverless-nextjs/serverless-next.js/pull/1144 already did a lot of the legwork, so I hope that an initial release can be done in the next couple of months.
