### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by andreyvital** [serverless-nextjs/serverless-next.js#197]
Hi—sorry for posting this as an issue here. Those questions might have been already answered somewhere but I couldn't locate 😅

1. Is there a way to use this project just to deploy and manage the lambda functions? I want to take care of uploading static to S3 myself through other ways;

2. I'm currently using Terraform to manage CloudFront and several other parts of my infra, is there a way to keep it that way? in short: is there a way to disable CF integration completely?

-- And if I do so, all I need to do is keep the default CF Behaviour sending requests to API Gateway, right?

Thanks!

**Comment by dphang** [comment]
Closing old issue - there have been many changes since this; please take a look at the new component and see if it works for you (if you are still using it).
