### ISSUE TITLE
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. 

### ISSUE THREAD

**Issue by owboateng** [serverless-nextjs/serverless-next.js#2014]
### Issue Summary

Hi,
I am deploying my NextJS app ("next": "^11.0.1") to AWS using @sls-next/serverless-component@3.5.2.
After deployment, I get 503 error on any page that has getServerSideProps.

`503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: k7kgIufjD4o3341WbhMqhzROQuaottYXer8h--dpFs9qvDxSXKmFww==`

In the default lambda@edge associated with the Cloudfront, I see timeouts:
`2021-11-05T11:22:58.499Z 684e1c18-27ec-4dc0-99c3-32423407676c Task timed out after 10.01 seconds
`
Please help fix issue. Thank you
### Versions

- OS/Environment:
- @sls-next/serverless-component version:
- Next.js version:

### Checklist

- [x ] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [ x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by owboateng** [comment]
Issue was caused by wrong configuration of AWS amplify. Issue is resolved.

**Comment by elleryfamilia** [comment]
@owboateng Can you provide specifics on the issue? I'm seen the same error
