### ISSUE TITLE
Getting MethodNotAllowed 405 response from cloudfront 

### ISSUE THREAD

**Issue by anil1712** [serverless-nextjs/serverless-next.js#2021]
### Issue Summary

I am working on one of the 3rd party gateway integration, whereas I am passing the callback url as NextJs API route, which is working fine and after that I am just redirecting it to UI but somehow it is getting redirected with POST request instead of GET, that is why I am getting below error from AWS cloudfront.

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Method>POST</Method><ResourceType>OBJECT</ResourceType><RequestId>5ZSXVRZPCPSPFNZG</RequestId><HostId>MJlSIO2bdGWrGS/36KeQTFOJn7mb9u5RsIe70aXSaBkgXK9CGucKHnOr6o15i9wJHSGQkeWwleo=</HostId></Error>
```

### Actual behavior

Getting redirection with POST request

### Expected behavior

Should get redirect with GET request

### Steps to reproduce

If you deploy any NextJs app using serverless in AWS then just need to add below snippet in NextJs API Layer

```
import { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
    res.redirect(307, '/home'); // It is getting redirected but with POST method.
}
```

### Versions

- OS/Environment: Windows
- @sls-next/serverless-component version: @sls-next/serverless-component@1.19.0-alpha.32
- Next.js version: 9.0.0
![405](https://user-images.githubusercontent.com/4207865/140714383-04e452bd-1e64-454e-abe9-9575f58777c7.png)

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Assuming this also repros with the latest component as 1.19.0-alpha.32 is very old by now.

I think the behavior is as expected? Since 307 redirects instruct the browser not to change the method (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307), if you did a POST to your API then the redirect will also POST to the redirect.  In this case the origin S3 does not allow POST so it will fail. I think you can use 303 status to change to a GET (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303)?

**Comment by anil1712** [comment]
Oh ok @dphang my mistake. 
Yes, I tried with 303 and it worked.

Thanks @dphang for quick reply.

But one thing I did not understand that how it was working on my local machine. I got the error only after the deployment.
