### ISSUE TITLE
Statically importing local images fails in deployed environment

### ISSUE THREAD

**Issue by christian-maigaard** [serverless-nextjs/serverless-next.js#2029]
### Issue Summary
When using the next.js image component with local statically imported images( See Next.js [documentation](https://nextjs.org/docs/basic-features/image-optimization#local-images) we get a network error 403 when the application is deployed to our cloud environment. It works locally. 

### Actual behavior
Using the Next Image component with statically imported images([Next.js doc](https://nextjs.org/docs/basic-features/image-optimization#local-images)) works locally, but gives a 403 network error in the deployed environment. 

### Expected behavior
Using the Next Image component with statically imported images should not give a 403 network error code when deployed to the cloud environment.

### Steps to reproduce
- Clone [minimal repro](https://github.com/christian-maigaard/serverless-next.js)
- yarn
- yarn build
- AWS_PROFILE="<YOUR_AWS_ENVIRONMENT>" yarn serverless 
- image network request should fail with a 403

### Screenshots/Code/Configuration/Logs
We managed to reproduce the issue by modifying the e2e-tests/prev-next-app-with-base-path project. So the issue may be related to the basepath

Minimal repro 
https://github.com/christian-maigaard/serverless-next.js
Cloudfront with deployed minimal repro : https://d14ibtvpgvzxoi.cloudfront.net/basepath

![image](https://user-images.githubusercontent.com/11509319/140897844-300458b5-a798-4ae2-bc1c-2ccaf187d1af.png)

serverless.yml
```
prev-next-app-with-base-path:
  component: "../../serverless-components/nextjs-component"
  inputs:
    removeOldLambdaVersions: true

```

### Versions

- OS/Environment: Mac
- @sls-next/serverless-component version: 3.5.3
- Next.js version: 12.0.3

### Additional context
The image is being added to the S3 Bucket. 

![image](https://user-images.githubusercontent.com/11509319/140909132-02f9cb68-3092-4297-a959-b57614228b7a.png)

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Thanks, it should be fixed by this https://github.com/serverless-nextjs/serverless-next.js/pull/2033. There was an earlier PR to properly normalize the URL for basepaths but the code to build the S3 key checked if path starts with {basepath}/_next/static. Updated it and added a test for it.

**Comment by christian-maigaard** [comment]
Thank you for the quick fix! I will  go ahead and update right away 👍 🥳
