### ISSUE TITLE
ISR pages with spaces (or %20) in the page name, which are defined at build time in getStaticpaths, do not update

### ISSUE THREAD

**Issue by moshfrid** [serverless-nextjs/serverless-next.js#2032]
### Issue Summary
ISR pages do not change as they are cached automatically in cloudfront

### Actual behavior
Locally the ISR pages work but on cloudfront they are cached for a month with the header cache-control: public, max-age=0, s-maxage=2678400, must-revalidate

### Expected behavior
for isr pages to exhibit swr functionality

### Screenshots/Code/Configuration/Logs

my serverless.yml

![Screenshot (18)](https://user-images.githubusercontent.com/20837433/141024452-8db6f48c-2298-46c2-a833-301f72c7e83c.png)

- OS/Environment:
- @sls-next/serverless-component version: 3.5.3
- Next.js version: 12

**Comment by dphang** [comment]
Can you please share a minimal repro including the page code to help debug why it's the case

The cache control should be set based on revalidate: https://github.com/serverless-nextjs/serverless-next.js/blob/ad106665f17f659f79e0830afe673dfe54a3464c/packages/libs/core/src/defaultHandler.ts#L184-L184

This is the example e2e test page that is always tested and working:

https://github.com/serverless-nextjs/serverless-next.js/blob/ad106665f17f659f79e0830afe673dfe54a3464c/packages/e2e-tests/next-app/pages/revalidated-ssg-page.tsx#L1-L1

**Comment by moshfrid** [comment]
I will work on a minimal repo, but i am seeing that the static-pages folder in s3 contains my isr pages as well, and that these are being served with the default cache policy of a month as stated in the docs. is there a reason these may be being treated as static pages?

**Comment by moshfrid** [comment]
I have set up a minimal repo at https://github.com/moshfrid/multi-word-isr-not-updating and hosted at https://d31bmvzou4ke6o.cloudfront.net. It seems that paths with spaces i.e. https://d31bmvzou4ke6o.cloudfront.net/with%20space which are created at build time with getStaticPaths, don't get updated, but those without spaces such as https://d31bmvzou4ke6o.cloudfront.net/hello or https://d31bmvzou4ke6o.cloudfront.net/with_underscore do get updated. All paths that are not defined at build time with getStaticPaths seem to work i.e. https://d31bmvzou4ke6o.cloudfront.net/with%20spaces

**Comment by dphang** [comment]
Thanks, it looks like probably a URL encoding/decoding issue, I'll take a look later this weekend. Probably somewhere there might need to be a decode so it can match against the correct static path for ISR

**Comment by dphang** [comment]
Fixed with https://github.com/serverless-nextjs/serverless-next.js/pull/2038. Ideally you shouldn't use non-URL-safe characters (e.g spaces) in URLs as Next.js doesn't handle them well (for example, I tested on a local Next.js server and it doesn't handle a non-dynamic SSG/SSR page with a space in its name e.g `with a space.tsx`). However, they do seem to handle those generated with `getStaticPaths`, so the fix will put it in parity (it might change in the future though)

**Comment by moshfrid** [comment]
There seems to be another place where the decode is missing, as now the isr works when accessed directly, but the next/data/json file used for spa navigation is still static

**Comment by dphang** [comment]
Just realized that, yeah I will fix and add more tests for it soon
