### ISSUE TITLE
ISR Regeneration fails with cdk

### ISSUE THREAD

**Issue by mathisobadia** [serverless-nextjs/serverless-next.js#2048]
### Issue Summary
When using ISR with static regeneration and the cdk construct, the pages are built the first time correctly, but they are never updated.
The problem seems to be that the regeneration function times out after 30 seconds.

### Actual behavior
Pages are not regenerated and regeneration function fails due to time out. Initial page creation is very quick so the issue should not be that the page takes more than 30 seconds to regenerate.

### Expected behavior
pages should be regenerated

### Steps to reproduce
I have a pretty specific setup and I haven't yet created a repro case. I'm wondering if that might be a known issue, and to not take too much time of the maintainers I would like to try to debug it myself but I don't know how. Is there a way to modify the regeneration function in my setup to add logs to it so I can find out at what step the regeneration function times out? I'm also wondering if there might be a permission issue that is not showing in the logs

### Screenshots/Code/Configuration/Logs
Currently the logs for the regeneration function look like this so it is not very helpfull (that's a snippet but this is repeated over and over again pretty much all the time). 
```
2021-11-17T00:28:54.973+01:00 | START RequestId: 10b72789-d8d6-559f-a3dd-7d87982216b6 Version: $LATEST
  | 2021-11-17T00:29:25.005+01:00 | END RequestId: 10b72789-d8d6-559f-a3dd-7d87982216b6
  | 2021-11-17T00:29:25.005+01:00 | REPORT RequestId: 10b72789-d8d6-559f-a3dd-7d87982216b6 Duration: 30028.59 ms Billed Duration: 30000 ms Memory Size: 128 MB Max Memory Used: 128 MB
  | 2021-11-17T00:29:25.005+01:00 | 2021-11-16T23:29:25.004Z 10b72789-d8d6-559f-a3dd-7d87982216b6 Task timed out after 30.03 seconds
  | 2021-11-17T00:29:25.831+01:00 | START RequestId: 8f927a92-4632-543f-8a90-209c07208843 Version: $LATEST
  | 2021-11-17T00:29:55.867+01:00 | END RequestId: 8f927a92-4632-543f-8a90-209c07208843
  | 2021-11-17T00:29:55.867+01:00 | REPORT RequestId: 8f927a92-4632-543f-8a90-209c07208843 Duration: 30031.70 ms Billed Duration: 30000 ms Memory Size: 128 MB Max Memory Used: 128 MB
  | 2021-11-17T00:29:55.867+01:00 | 2021-11-16T23:29:55.867Z 8f927a92-4632-543f-8a90-209c07208843 Task timed out after 30.03 seconds
```

### Versions

- OS/Environment:
- @sls-next/serverless-component version:
- Next.js version: 12.0.3 (but I tried downgrading to version 11)
@sls-next/cdk-construct: 3.6.0 (but I also tried the latest canary version)

### Additional context
I have added some permissions to both the default lambda and the regeneration lambda throught the use of addToRolePolicy function of the cdk to allow fetching dynamodb content that's used to render the page. This worked on the default lambda but maybe it doesn't work for the regeneration function?

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by mathisobadia** [comment]
The issue was caused by low default memory for this function. I have created a pull request to add the option to change the runtime properties of the function so that it's alligned with the other functions (default, api, image)

**Comment by afenton90** [comment]
Also getting this same issue. The next.js build reports ISR time of 60 seconds so the regeneration lambda will always timeout with the current configuration.
