### ISSUE TITLE
Domain name cannot be resolved after deploy, ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by gustavorps** [serverless-nextjs/serverless-next.js#205]
**Describe the bug**
Domain name cannot be resolved after deploy

**To Reproduce**
1. Use AWS provider '...'
2. Setup `serverless.yml`
```
  webSurvey:
    component: serverless-next.js
```
3. Run `sls` for deploy
4. Get the url from the output and paste

**Expected behavior**
ERR_NAME_NOT_RESOLVED on Chrome 

**Screenshots**
![](https://i.imgur.com/xXsRanE.png)
[https://dlnw78exek9o0.cloudfront.net](https://dlnw78exek9o0.cloudfront.net)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version: 16

**Additional context**
- `"next": "^9.1.1"`
- `"serverless-next.js": "^1.4.1"`

**Comment by danielcondemarin** [comment]
This is due propagation times of the cloudfront dns. The cloudfront component doesn’t wait until it fully propagates. There is an open issue to support this but is still being considered atm https://github.com/serverless-components/aws-cloudfront/pull/9.

**Comment by dphang** [comment]
Closing out old/stale issues. If same issue occurs with the latest version of this component, please reopen a new issue.
