### ISSUE TITLE
Error command execution npx serverless 

### ISSUE THREAD

**Issue by robsonkades** [serverless-nextjs/serverless-next.js#210]
-      Node Version:              10.16.3
-      Framework Version:         1.54.0
-      Plugin Version:            3.1.2
-      SDK Version:               2.1.2
-      Components Core Version:   1.1.1
-      Components CLI Version:    1.4.0

 serverless.yml
myApp:
 component: serverless-next.js

`{ Error: Command failed with exit code 2 (ENOENT): node_modules/.bin/next build
spawn node_modules/.bin/next ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  syscall: 'spawn node_modules/.bin/next',
  path: 'node_modules/.bin/next',
  spawnargs: [ 'build' ],
  originalMessage: 'spawn node_modules/.bin/next ENOENT',
  command: 'node_modules/.bin/next build',
  exitCode: 2,
  exitCodeName: 'ENOENT',
  stdout: '',
  stderr: '',
  all: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined }

  1s › myApp › Error: Command failed with exit code 2 (ENOENT): node_modules/.bin/next build
spawn node_modules/.bin/next ENOENT`

**Comment by danielcondemarin** [comment]
Does running `next build` work on its own?

**Comment by jhlabs** [comment]
I am having the same error thrown when trying to use the `sls` command. I am using a monorepo setup with https://nx.dev/ where only one `node_modules` folder is present in the root directory. I suspect that the error shows because of this. How can I specify the location of my `node_modules`?

**Comment by jghorton14** [comment]
im dumb.. for me I had to `yarn install`

**Comment by dphang** [comment]
Closing stale issue - if still occurring on the latest version, please reopen new issue

**Comment by DanielOrtel** [comment]
I'm having the same issue with a monorepo, does this package run `next build`?

**Comment by DanielOrtel** [comment]
@dphang hey, please reopen this issue. I checked, and the problem is that this package hardcodes the path to the node_modules folder, so in a monorepo environment, where the next binary is hoisted to the root, that command breaks.

Manually symlinking the node_modules in the app folder to the root of the folder fixes this, but this shouldn't be a thing. This should be fixed by the package.

**Comment by alirezavlz** [comment]
Having same issue...None of above solutions worked.
