### ISSUE TITLE
Bundle local files that are referenced in `getStaticProps`

### ISSUE THREAD

**Issue by thiskevinwang** [serverless-nextjs/serverless-next.js#2151]
**Is your feature request related to a problem? Please describe.**

I have an app that builds pages from `.mdx` files in a dedicated `posts` folder and loaded w/ [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote) in `getStaticProps`.

```console
├── next.config.js
├── node_modules
├── package.json
├── posts  <-- a bunch of .mdx files
├── public
├── src    <-- nextjs code: pages, etc.
├── tsconfig.json
└── yarn.lock
```

The app builds fine and deploys with the CDK construct, but the regeneration lambda appears to error when it comes time to ISR.

No comment on the edge lambdas as of yet, since I haven't figure out where their logs actually go...

example from CloudWatch logs
![image](https://user-images.githubusercontent.com/26389321/144163365-4f9a7af2-dbd6-42f1-949b-9ebf9a510d64.png)

**Describe the solution you'd like**

Bundle files that are used by `getStaticProps` and make them available during ISR.

**Describe alternatives you've considered**

An alternative I tried is to fetch the files' string content from the GitHub V4 API in `getStaticProps`, but that isn't totally ideal.

**Additional context**

Using

```json
    "@sls-next/cdk-construct": "3.7.0-alpha.1",
    "@sls-next/lambda-at-edge": "3.7.0-alpha.1",
    "next": "^12.0.1",
    "next-mdx-remote": "3.0.7",
```

**Comment by chrisneal** [comment]
You could use the post build commands to copy those files into the regeneration lambda?

Something along the lines of:

```
postBuildCommands:
- cp -R ./posts .serverless_nextjs/regeneration-lambda/posts
```

**Comment by thiskevinwang** [comment]
@chrisneal Wow, so simple! Thanks, that looks like it did the trick 👍 

I ended up doing something like:
```ts
import { execSync } from "child_process";

// ...

  await builder.build(debug);

    // Fix:
    // ENOENT: no such file or directory, scandir '/var/task/posts'
    execSync("cp -R ../application/posts ./build/regeneration-lambda/posts");
```

**Comment by thiskevinwang** [comment]
Closing this issue for now, though docs on this extra step would be very nice! :D
