### ISSUE TITLE
Cannot deploy without access to region `us-east-1`

### ISSUE THREAD

**Issue by vbackeberg** [serverless-nextjs/serverless-next.js#2198]
### Issue Summary
If the user has no access rights for region `us-east-1` they cannot deploy. It should be possible to restrict the region that are being targeted.

### Actual behavior
If input `region` is defined, the script tries to deploy to all available regions.

### Expected behavior
If input `region` is defined, the app (notably the lambda) should only be deployed to that region.

### Steps to reproduce
1. Set AWS credentials that have no access rights to `us-east-1`.
2. Try deploy typing `serverless`.

### Screenshots/Code/Configuration/Logs

**log**
```
AccessDeniedException: User: arn:aws:sts::[...]:assumed-role/[role]/[user] is not authorized to perform: lambda:GetFunctionConfiguration on resource: arn:aws:lambda:us-east-1:[...]:function:[...] with an explicit deny in an identity-based policy
```

**serverless.yml**
```
example-app:
  component: "@sls-next/serverless-component"
  inputs:
    region: eu-west-1
```

### Versions
- OS/Environment: Windows,
- @sls-next/serverless-component version: serverless 3.6.0
- Next.js version: Next.js 11 latest

### Additional context
My user can only deploy to a single region `eu-west-1`

**Comment by jsw** [comment]
Might be relevant:

https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html

> By default, AWS Security Token Service (AWS STS) is available as a global service, and all AWS STS requests go to a single endpoint at https://sts.amazonaws.com. Global requests map to the US East (N. Virginia) Region.

I think the same applies to CloudFront, a global service, but the control plane is in us-east-1. Someone with more knowledge should confirm/correct me.

**Comment by lytvynenko** [comment]
@jsw is absolutely right. `serverless-next` uses Lambda@Edge compute which is a global service and can be managed only from us-east-1.

**Comment by vbackeberg** [comment]
Thanks for the clarification! :)
