### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by Raffaello** [serverless-nextjs/serverless-next.js#2284]
**Is your feature request related to a problem? Please describe.**
There is no way to set up Cloudfront logs or realtime logs

**Describe the solution you'd like**
i would like a way to set up clodufront logs or disable to update cloudfront logs

**Describe alternatives you've considered**
moving away from serverless framework.

**Additional context**
something like this to tell to do not change the cloudfront log at deployment.

```yml
cloudfront:
      distributionId:  'distributionid'
      logs:
        update: false # true by default
      realtimelogs:
        udpdate: false # true by default  
```

otherwise give a way to set up logs

**Comment by robertsonsamuel** [comment]
Also looking for a way to do this. I use real-time logs and having to redeploy this on each deploy isn't fun.

**Comment by Raffaello** [comment]
it looks like that this lines shouldn't be here: 
https://github.com/serverless-nextjs/serverless-next.js/blob/63639039ba55494b33f92f0e5b6c0117da206c28/packages/serverless-components/aws-cloudfront/src/index.ts#L282-L285

as it is an updated, and the `DefaultCacheBehavior` is already fetched from the already present cloudfront.
instead those line are replacing whatever cloudfront has with, again the default. 

Is this what is wanted?
**Note** that removing those lines it solve the issues with realtime logs.

**Comment by robertsonsamuel** [comment]
Looking deeping into AWS and their CDK library which this utilizes https://github.com/aws/aws-cdk/issues/10202; this seems to be a heavy lift.

So it seems that even the official cloudfront cdk doesn't really have great support for real-time logs as this issue is still open. 

@Raffaello if removing those lines solves the issues with real-time logs then at a minimum it would be great to have options on that to at least turn off the update to logs when provided as you had suggested:

```yml
cloudfront:
      distributionId:  'distributionid'
      logs:
        update: false # true by default
      realtimelogs:
        udpdate: false # true by default  
```

Totally agree in just passing a param here. It's not ideal long term, but a proper configuration can override that and not break anything provided that AWS exposes better API access to logs when available.

@Raffaello have you tried and succeeded in removing those lines, then re-deploying and not having real-time logs / logs altered/removed? I'm skeptical if AWS actually provides the existing real-time logs structure along with the cloudfront params when calling the existing cloudfront configuration, they may but I've not tested it.

**Comment by Raffaello** [comment]
yes removing those line is succesful.

I am trying now this way, it could work:

```yml

distribution:
  component: '@serverless/aws-cloudfront'
  inputs:
    defaults: # optional
      realtimeLogConfigArn: 'relatimelogconfigARN'
      
````

**Comment by Raffaello** [comment]
> yes removing those line is succesful.
> 
> I am trying now this way, it might work:
> 
> ```yaml
> cloudfront:
>       defaults: # optional
>         realtimeLogConfigArn: 'the realtime log config ARN'
> ```

that doesn't work, it is required to patch `getDefaultCacheBehavior` function as it strips out some parameters.
or to patch the yaml parsing and add the extra `defaults.realTimeLogConfigARN` key as it might not be parsed neither.

**Comment by Raffaello** [comment]
> it looks like that this lines shouldn't be here:
> 
> https://github.com/serverless-nextjs/serverless-next.js/blob/63639039ba55494b33f92f0e5b6c0117da206c28/packages/serverless-components/aws-cloudfront/src/index.ts#L282-L285
> 
> as it is an updated, and the `DefaultCacheBehavior` is already fetched from the already present cloudfront. instead those line are replacing whatever cloudfront has with, again the default.
> 
> Is this what is wanted? **Note** that removing those lines it solve the issues with realtime logs.
> 
> is that `input.defaults` that i can't find where is assigned and it might be the solution: passing a parameter to the yaml file already for the realtime log arn

anyway going back to this solution removing the default behavior when updating it makes sense,
especially because the getDefaultBehavior is not merging the current values is just replacing them like creating a new one

https://github.com/serverless-nextjs/serverless-next.js/blob/e5ddcf51bdaa35ea9d7756807b5674e14614bab9/packages/serverless-components/aws-cloudfront/src/getDefaultCacheBehavior.ts#L16

**Comment by robertsonsamuel** [comment]
That's what I figured. https://github.com/aws/aws-cdk/issues/10202#issuecomment-976180059 claims to be able to create the policy but not attach it to a distribution. In that case, setting up an argument to skip updating the cloudfront distribution based on fetched existing params with a flag `update: false present seems like the best solution for now.

**Comment by robertsonsamuel** [comment]
> > it looks like that this lines shouldn't be here:
> > https://github.com/serverless-nextjs/serverless-next.js/blob/63639039ba55494b33f92f0e5b6c0117da206c28/packages/serverless-components/aws-cloudfront/src/index.ts#L282-L285
> > 
> > as it is an updated, and the `DefaultCacheBehavior` is already fetched from the already present cloudfront. instead those line are replacing whatever cloudfront has with, again the default.
> > Is this what is wanted? **Note** that removing those lines it solve the issues with realtime logs.
> > is that `input.defaults` that i can't find where is assigned and it might be the solution: passing a parameter to the yaml file already for the realtime log arn
> 
> anyway going back to this solution removing the default behavior when updating it makes sense, especially because the getDefaultBehavior is not merging the current values is just replacing them like creating a new one
> 
> https://github.com/serverless-nextjs/serverless-next.js/blob/e5ddcf51bdaa35ea9d7756807b5674e14614bab9/packages/serverless-components/aws-cloudfront/src/getDefaultCacheBehavior.ts#L16

To confirm, does this fail to update other parts of the distribution ? If it's just copying and sending updates that would need to be change such as new cache behaviors for endpoints, new origins etc, that's one thing. If it's not updating new params based on changes in the cloudfront input params but just not running the update whatsoever that's not optimal either.

**Comment by chrisneal** [comment]
@Raffaello I just did something similar with setting the ResponseHeadersPolicyId.

Here is the PR:
https://github.com/serverless-nextjs/serverless-next.js/pull/2285

**Comment by Raffaello** [comment]
@chrisneal i have just created this one: https://github.com/serverless-nextjs/serverless-next.js/pull/2301

**Comment by robertsonsamuel** [comment]
> @robertsonsamuel not sure what CDK relates to this missing feature here.
> 
> commenting (not executing) those lines ,it is just doesn't update/restore the default chache beavhor of cloudfront, so after deployment serverless won't change it anymore.
> 
> the ideal solution is to parse the yaml file with a new key `realtimeLogConfigArn` that if it is present it simply attach the ARN to the cloudfront distribution both in create and in update and can be patch in those "commented line too)
> 
> ```yaml
> cloudfront:
>       defaults: # optional
>         realtimeLogConfigArn: 'the realtime log config ARN'
> ```
> 
> or something very close to that as the defaults can be specified but it just ignores new keys.
> 
> I didn't find yet where the yaml schema/parsing is defined.

Ah I didn't understand clearly here what you meant! Seems that just passing in a realtime log config should be enough after I looked through a bit more. That looks like a perfect solution. Thanks for the PR as well. Hopefully we can get that merged in soon. :+1:

**Comment by Raffaello** [comment]
@robertsonsamuel hopefully! 🤞

Any maintainer of the repo to ping as no-one yet come up in the discussion?

**Comment by chrisneal** [comment]
@Raffaello I'm sure @dphang will pick up the PR sometime soon.

**Comment by Raffaello** [comment]
@robertsonsamuel

meanwhile waiting for the merging of the PR and publish of the new version.
I have created a workaround using `patch-package`:

then:
1. install `patch-package` and add the postinstall script ("postinstall": "patch-package")
2. imported the components in the project so it can be used from `./node_modules/` folder, 
```
"@sls-next/aws-cloudfront"
"@sls-next/aws-lambda"
"@sls-next/aws-sqs":
"@sls-next/serverless-component":
````
3. patch the aws-cloudfront with the generated files from TS, so the file in `dist/` (in this case it should be only `getDefaultCacheBehavior.js`)
4. yarn install to run the postinstall script of patch-package
5. Using the latter in `serverless.yml`  as component `component: ./node_modules/@sls-next/component`


the generated patch need to be done from the compiled JS from this PR #2301 

and that it will work.

**Comment by somatorio** [comment]
Just checking, does this also work on another cache behaviours or only on defaults? 'Cause I have tried using realtimeLogConfigArn on another one and it didn't seemed to work
```
cloudfront:
      ...
      defaults:
        realtimeLogConfigArn: ${ssmParameters.realtimeLogConfigArn}
      api/*:
        realtimeLogConfigArn: ${ssmParameters.realtimeLogConfigArn}
        minTTL: 0
        maxTTL: 31530000
        defaultTTL: 0
```
maxTTL was set correctly, but realtimeLogConfigArn apparently did nothing :( (worked just fine on the default cache behaviour though)

**Comment by Raffaello** [comment]
> Just checking, does this also work on another cache behaviours or only on defaults? 'Cause I have tried using realtimeLogConfigArn on another one and it didn't seemed to work
> 
> ```
> cloudfront:
>       ...
>       defaults:
>         realtimeLogConfigArn: ${ssmParameters.realtimeLogConfigArn}
>       api/*:
>         realtimeLogConfigArn: ${ssmParameters.realtimeLogConfigArn}
>         minTTL: 0
>         maxTTL: 31530000
>         defaultTTL: 0
> ```
> 
> maxTTL was set correctly, but realtimeLogConfigArn apparently did nothing :( (worked just fine on the default cache behaviour though)

sorry but this issue has been closed on 27 Jan, apart that i don't remember it neither anymore 😄, It can be the case that the code as further changed, or created a side effects on this topic, or wasn't fully implemented as for your specific case, not sure, the only way is to look at the source code of the version you are using and if you spot something related to `realtimeLogConfigArn` there...
the version are you using also contains the patch listed here? 
as i don't know neither if it has been released as a stable version yet... as v3.7.0 has failed end-to-end tests.

if all your answer are yes, i suggest that you create a PR addressing your case starting with creating a test for it.

or try with the patch mode here:  https://github.com/serverless-nextjs/serverless-next.js/issues/2284#issuecomment-1022228016

or just simply create a new issue.
