### ISSUE TITLE
Deploying ... spinner status destroys useful logs when run in a non-interactive shell - like a CICD system

### ISSUE THREAD

**Issue by mikeputnam** [serverless-nextjs/serverless-next.js#2302]
### Issue Summary

Locally, the Deploying... spinner writes and rewrites the same shell line to give the appearance of a progress bar/status of the deploy. However the same spinner when run in a non-interactive shell (CICD) ends up actually printing every intermediate step of the spinner. This has the effect of pushing all useful build log output many kilobytes into the scrollback.

### Actual behavior

```
  386s › web-ssr › Deploying 
·[NaNA·[G·[J
  386s › web-ssr › Deploying 
·[NaNA·[G·[J
  386s › web-ssr › Deploying 
·[NaNA·[G·[J
  386s › web-ssr › Deploying .
·[NaNA·[G·[J
  386s › web-ssr › Deploying .
·[NaNA·[G·[J
  386s › web-ssr › Deploying ..
·[NaNA·[G·[J
  386s › web-ssr › Deploying ..
·[NaNA·[G·[J
  386s › web-ssr › Deploying ...
·[NaNA·[G·[J
  386s › web-ssr › Deploying ...
·[NaNA·[G·[J
  387s › web-ssr › Deploying 
·[NaNA·[G·[J
  387s › web-ssr › Deploying 
·[NaNA·[G·[J
  387s › web-ssr › Deploying 
·[NaNA·[G·[J
  387s › web-ssr › Deploying .
·[NaNA·[G·[J
  387s › web-ssr › Deploying .
·[NaNA·[G·[J
  387s › web-ssr › Deploying ..
·[NaNA·[G·[J
  387s › web-ssr › Deploying ..
·[NaNA·[G·[J
  387s › web-ssr › Deploying ...
·[NaNA·[G·[J
  387s › web-ssr › Deploying ...
·[NaNA·[G·[J
```

### Expected behavior

It would be great if an argument existed or a default behavior was possible to avoid this non-essential behavior.

### Versions

@sls-next/serverless-component@3.6.0

- OS/Environment: Ubuntu 20.04
- @sls-next/serverless-component version: @sls-next/serverless-component@3.6.0
- Next.js version: ^12.0.7

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by chrisneal** [comment]
@mikeputnam Best way round this is to deploy it using:

`npx @sls-next/serverless-patched --debug`

That gets rid of the annoying "Deploying..." text and some other useless output.

**Comment by kprzybylo** [comment]
@chrisneal I still have "Deploying..." message when using this command. Could you please tell me with what version that works for you?

**Comment by kcjonson** [comment]
Same thing when deploying with Github Actions

![image](https://user-images.githubusercontent.com/1512633/159389521-84e26c85-f875-47c4-ac11-a0319e8f2076.png)

**Comment by chrisneal** [comment]
@kcjonson Can you post your GitHub action file?

**Comment by kcjonson** [comment]
I can do you one better, here's the source in a barebones standalone repo: https://github.com/kcjonson/serverless-nextjs

**Comment by chrisneal** [comment]
@kcjonson Thanks mate. It looks as though you’re still deploying using the ‘serverless’ command. Switch that out for the ‘npx …’ command I said above.

**Comment by mikeputnam** [comment]
This workaround works. Hopefully, this patch or similar makes it into the upstream serverless project. 🤞

**Comment by jamiechong** [comment]
@mikeputnam  perhaps we want to re-open this issue as it hasn't actually been resolved. Only a work-around has been suggested.
