### ISSUE TITLE
Next/image doesn't work with lambda using external urls

### ISSUE THREAD

**Issue by Lea23VC** [serverless-nextjs/serverless-next.js#2331]
Hello, I'm using graphql to get a ton of images from a Wordpress page. I'm using next/image and already added the wordpress domain to my next.config.js. It works perfectly using npm run build on my PC. But serverless, these external images doesn't show, it says "503 error".

![next/image 503 error](https://i.imgur.com/1gLKbF4.png)

This only happens with next/image and externals url, it works with images inside my public folder.

**Comment by b-mendoza** [comment]
Hey @Lea23VC, hello!

I'm currently having the same issue while using [Plaiceholder](https://plaiceholder.co/), and I see that you closed the issue, so I wanted to know if you found a solution for this, or was this moved to another issue?
