### ISSUE TITLE
Redirects not working in getStaticProps

### ISSUE THREAD

**Issue by Talhafayyaz11** [serverless-nextjs/serverless-next.js#2346]
### Issue Summary
Redirects are throwing errors in getStaticProps. I know this is not an issue with the code or anything related to the next js because I have checked the local build and it successfully redirects to the targeted page. 

### Actual behavior
While redirecting it throws an error that the client-side exception occurred.  I am unable to explore more about the error. Actual redirection doesn't occur.
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/49181609/154051113-282f8dcc-3bf3-4bd6-b11f-c68f418732e4.png">

### Expected behavior
getStaticProps should redirect to the destination path.

### Steps to reproduce
- Add redirect to getStaticProps with some external or internal URL. 
- Go to the path that should redirect to the targeted URL
- Client-side exception occurs

### Versions

- OS/Environment: Mac
- @sls-next/serverless-component version: 3.2.0
- Next.js version: ^11.0.1

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by bobrossthepainter** [comment]
Hi @Talhafayyaz11,
I can confirm the issue. Same behavior for me with: 
- @sls-next/serverless-component@3.7.0-alpha.9
- Next.js version: 12.0.10

**Comment by KensukeTakahara** [comment]
@Talhafayyaz11
This issue has been resolved in [v3.7.0-alpha.11](https://github.com/serverless-nextjs/serverless-next.js/releases/tag/v3.7.0-alpha.11).
Please check.

**Comment by Talhafayyaz11** [comment]
> @Talhafayyaz11 This issue has been resolved in [v3.7.0-alpha.11](https://github.com/serverless-nextjs/serverless-next.js/releases/tag/v3.7.0-alpha.11). Please check.

Thanks. Really appreciate quick fix.
