### ISSUE TITLE
ISR pages are regenerated with wrong name when prefetching

### ISSUE THREAD

**Issue by falsyzoo** [serverless-nextjs/serverless-next.js#2349]
### Issue Summary

When Next.js is prefetching an ISR page / when a request is made to `https://example.com/_next/data/.../page.json` and the page is queued for regeneration, the page is stored to `static-pages/.../pageon.html` / `_next/data/.../pageon.json`
(instead of `static-pages/.../page.html` / `_next/data/.../page.json`).

I suspect that `.replace(".js", "")` is the culprit (as `.json` includes `.js`) but I'm not sure if this replacement is actually necessary.
(Are any situations where an ISR page has a `.js` extension?)

https://github.com/serverless-nextjs/serverless-next.js/blob/d009f46df7d67f31b2195912dd599feda22f541a/packages/libs/lambda-at-edge/src/regeneration-handler.ts#L31-L35

#### Next.js prefetch / request to `_next/data/...`
SQS event: 
```
{
  "region": "eu-west-1",
  "bucketName": "example",
  "pageS3Path": "/_next/data/KL5A2qpf1jF1Q63QKlpey/en/event/coursera.json",
  "cloudFrontEventRequest": {
    "method": "GET",
    "origin": {
      "s3": {
        "authMethod": "origin-access-identity",
        "customHeaders": {},
        "domainName": "example.s3.eu-west-1.amazonaws.com",
        "path": "",
        "region": "eu-west-1"
      }
    },
    "querystring": "",
    "uri": "/_next/data/KL5A2qpf1jF1Q63QKlpey/en/event/coursera.json"
  },
  "basePath": "",
  "pagePath": "pages/event/[slug].js"
}
```
Generated objects: 
`static-pages/KL5A2qpf1jF1Q63QKlpey/en/event/courseraon.html`
`_next/data/KL5A2qpf1jF1Q63QKlpey/en/event/courseraon.json`

#### Normal request
SQS event:
```
{
  "region": "eu-west-1",
  "bucketName": "example",
  "pageS3Path": "/en/event/coursera.html",
  "cloudFrontEventRequest": {
    "method": "GET",
    "origin": {
      "s3": {
        "authMethod": "origin-access-identity",
        "customHeaders": {},
        "domainName": "example.s3.eu-west-1.amazonaws.com",
        "path": "/static-pages/KL5A2qpf1jF1Q63QKlpey",
        "region": "eu-west-1"
      }
    },
    "querystring": "",
    "uri": "/en/event/coursera"
  },
  "basePath": "",
  "pagePath": "pages/event/[slug].js"
}
```
Generated objects: 
`static-pages/KL5A2qpf1jF1Q63QKlpey/en/event/coursera.html`
`_next/data/KL5A2qpf1jF1Q63QKlpey/en/event/coursera.json`

### Expected behavior

In both cases the generated objects should be stored to
`static-pages/KL5A2qpf1jF1Q63QKlpey/en/event/coursera.html`
`_next/data/KL5A2qpf1jF1Q63QKlpey/en/event/coursera.json`

### Screenshots/Code/Configuration/Logs

![image](https://user-images.githubusercontent.com/99819375/154307202-6144f50c-0081-4de7-a426-385dcd627924.png)

### Versions

- OS/Environment:
- @sls-next/serverless-component version: 3.6.0
- Next.js version: 12.0.8

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [ ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by cmaerz** [comment]
As the fix seems rather easy. Maybe you just create a PR?
