### ISSUE TITLE
Cloudfront Cache Key includes all cookies - always "Miss From Cloudfront" for static assets

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#2351]
I could not find an issue or documented config for this so apologies if I missed something.

### Issue Summary

When deploying via this component, Cloudfront is configured to include all cookies in the "Cache Key". This means that cloudfront will not "hit" unless all cookies exactly match those of a prior request.

This happens in the Default (*) behavior.

This results in very inefficient use of the cache, as it basically results in every user having their own cache. Any new users to the site always have cache misses. This arguably defeats the purpose of using a CDN for assets.

I also noticed - even if you configure this in the console, this configuration is restored on each deploy. So you can't meaningfully override this as of now.

### Actual behavior

Either
- Allow us to configure this behavior somewhere, or
- Remove this default behavior altogether

### Expected behavior

Provide a way to discard cookies for cloudfront's cache key, which would vastly improve cache hit rate.

### Steps to reproduce

Deploy this component, then use two different clients to access the site and check "X-Cache" response header for response

### Screenshots/Code/Configuration/Logs

<img width="691" alt="image" src="https://user-images.githubusercontent.com/10466863/154379892-5ff6827e-2180-40e7-b993-6e0b9b06ce75.png">

### Versions

- OS/Environment:
- @sls-next/serverless-component version: @sls-next/serverless-component@v3.6.0
- Next.js version: ^10.2.4-canary.2

**Comment by patricktyndall** [comment]
Apologies - I missed that "forward" in the cloudfront config is referring to the above setting. I thought that was a separate thing.

**Comment by LisandroMoura** [comment]
ty for help
