### ISSUE TITLE
The deployment keep creating too many resources through times

### ISSUE THREAD

**Issue by tranphong1991** [serverless-nextjs/serverless-next.js#2397]
### Issue Summary

When I deploy my Next JS page to cloud front using `serverless`. Every time it is creating new resources.

### Actual behavior

Many resources created make my AWS env look messy and we don't use all of them.

### Expected behavior

Should modify or delete the existing resource when new resources are available.

### Steps to reproduce

Run `serverless` to deploy many times. Then look at AWS console

### Screenshots/Code/Configuration/Logs

![Screen Shot 2022-03-10 at 15 08 20](https://user-images.githubusercontent.com/26109589/157616513-c15c4121-3987-4280-92c5-7a66cd51c41e.png)

### Versions

- OS/Environment: MacOS/Linux
- @sls-next/serverless-component version: latest
- Next.js version: 12.1.0

### Checklist

- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by Reiiya** [comment]
Its kinda expected, if deployment script has no place to look at what were old resources that need to be redeployed.

When you run a deployment script, it creates a folder ".serverless", which keeps track of resources. If its not present, it will deploy new ones. 

The way I handle it, is keeping the folder in s3 bucket and update it after deployment. Excerpt from my ci/cd file is something like this - 
```
    - aws s3 sync s3://${APP_NAME}/.serverless .serverless --delete
    - yarn serverless:deploy
    - aws s3 sync .serverless s3://${APP_NAME}/.serverless --delete
```
(That is not something you can keep in git repo as it changes on deployment)

If you are going to hardcode ids of the resources in configuration, that also will prevent creation of new resources.

**Comment by tranphong1991** [comment]
@Reiiya Thank you very much. This is what I am looking for.

**Comment by jeremyrajan** [comment]
@tranphong1991 I have the same issue, it doesn't pickup the existing ones and keeps on creating new ones. I do see `.serverless` folder. Any idea why?
