### ISSUE TITLE
Custom domain does not work

### ISSUE THREAD

**Issue by yankouskia** [serverless-nextjs/serverless-next.js#251]
Create simple configuration for deploying nextjs application:
```yml
app:
  component: serverless-next.js
  inputs:
    domain: www.app.com # tried with app.com as well
    bucketName: my-app-bucket
```

After running:
```sh
serverless --aws-profile profile --debug
```

Always getting: 
```
  Error: Domain www.app.com was not found in your AWS account. Please purchase it from Route53 first then try again.
    at getDomainHostedZoneId (/Users/me/.serverless/components/registry/npm/serverless-next.js@1.6.1/node_modules/@serverless/domain/utils.js:120:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Domain.default (/Users/me/.serverless/components/registry/npm/serverless-next.js@1.6.1/node_modules/@serverless/domain/serverless.js:58:32)
    at async NextjsComponent.deploy (/Users/me/.serverless/components/registry/npm/serverless-next.js@1.6.1/node_modules/serverless-next.js/serverless.js:440:29)
    at async fn (/Users/me/projects/app/node_modules/@serverless/template/utils.js:280:41)
    at async Promise.all (index 0)
    at async executeGraph (/Users/me/projects/app/node_modules/@serverless/template/utils.js:294:3)
    at async Template.default (/Users/me/projects/app/node_modules/@serverless/template/serverless.js:67:38)
    at async Object.runComponents (/Users/me/projects/app/node_modules/@serverless/cli/src/index.js:211:17)

  11s › app › Error: Domain www.app.com was not found in your AWS account. Please purchase it from Route53 first then try again.
```

I have purchased corresponding domain in Route53:
```sh
AWS_PROFILE=profile aws route53domains list-domains

{
    "Domains": [
        {
            "DomainName": "app.com",
            "AutoRenew": true,
            "TransferLock": false,
            "Expiry": 123
        }
    ]
}
```

**Versions:**
 - OS: MacOS Mojave 10.14.6 
 - serverless: 1.58.0
 - serverless-next.js: 1.6.1
 - next: 9.1.4

**Comment by nodabladam** [comment]
I got that same error when I didn't actually have my app.com domain purchased due to using another registrar.  When adding it to Route 53 it then worked.  I believe the format is:
```
    domain:
      - ${subdomain}
      - ${domain}
```

**Comment by yankouskia** [comment]
@nodabladam getting almost the same result...
`Domain www was not found`
Or
`Domain dev was not found`

**Comment by barrysteyn** [comment]
This component uses the `@serverless/aws-cloudfront` component that is assigning the domain name. This component merely forwards the input to that component. If you would to clarify how domains should be used or think there is a bug, that is the place to look.

**Comment by claygorman** [comment]
Few things I ran into was making sure the `[default]` AWS credentials in `~/.aws/credentials` were the account I wanted to deploy with. I don't believe any of the flags like `--aws-profile` work in the new components style yml (correct me if I'm wrong). 

I also just ended up making a public hosted zone and a private hosted zone in route53. I don't think you need both public and private but I ended up just adding both to be sure. After those things I seemed to be ok.

Hope that helps at all.

**Comment by wis** [comment]
thanks for this info @barrysteyn 
technically, according to what I've read online, you can use your domain registrar with S3 (using CNAMEs) but can you use cloudfront (not the component or this component necessarily) without transfering your domain to aws? I'd like to keep my domain and dns with Cloudflare to use Cloudflare  only features (+ DDOS protection).

**Comment by barrysteyn** [comment]
> thanks for this info @barrysteyn
> technically, according to what I've read online, you can use your domain registrar with S3 (using CNAMEs) but can you use cloudfront (not the component or this component necessarily) without transfering your domain to aws? I'd like to keep my domain and dns with Cloudflare to use Cloudflare only features (+ DDOS protection).
> 
> Edit: I figured it out (how to use custom domains that are not registered with and use Route 53 dns), do not use a custom domain with this component (in your serverless.yml), make a SSL certificate for your domain in aws ACM, go the cloudfront web distribution that was created by this component and add
> 
> ```
> yourdomain.whatever
> *.yourdomain.whatever
> ```
> 
> to the **"Alternate Domain Names (CNAMEs)"**, and select the SSL certificate that you created in aws ACM for your domain in the **"SSL Certificate"** field.

Hi, I use Cloudflare as well. There is no need to use AWS for domains. Go into your cloudfront config, and you will see the cloudfront domain. All you then need to do is create a domain/certificate manually within AWS (this is not using Route53 - it's super quick and easy) and associate that domain with the CF domain. Then go to Cloudflare and create a record to points to the CF domain.

**Comment by subhendukundu** [comment]
Hey there,
I am facing the same issue but for a different use case tho. I am trying to add multiple instances of the application, [https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component/examples/multiple-instance-environment](using this link). With the domain added I am getting the same error `Error: Domain www.app.com was not found in your AWS account.`. So to achieve the multiple instances, I tried a hack changing the `env-prod` file to `bucket="prod-appname"` this gets deployed but when I added an `env-stage` file to `bucket="stage-appname"`, this creates a new bucket but deploy it to the same CloudFront url, is there a way to fix any of them so that I can achieve multiple instances?
Thanks in advance

**Comment by dphang** [comment]
Closing as it is possibly a stale issue. Please open a new issue if the README is still unclear or latest alpha version of @sls-next/serverless-component still has issues.

**Comment by felixs8696** [comment]
I am receiving the same issue with the exact same problem. @yankouskia were you able to solve it?

**Comment by yankouskia** [comment]
@felixs8696 I refused using sls components, and implemented it using cloudformation. Components seem to be still pretty raw
