### ISSUE TITLE
Buckets are being deleted unintentionally when deploying multiple apps from one code base

### ISSUE THREAD

**Issue by brimac1634** [serverless-nextjs/serverless-next.js#2513]
### Issue Summary
I am deploying numerous apps that are based off of one code base, each with their own serverless yml settings. When deploying them consecutively, serverless-next deletes each previously deployed bucket. This happens because serverless-next is checking if the config name saved in state still matches the new config name, and if not, then it deletes the bucket with the name saved in state. This functionality is [here](https://github.com/serverless-nextjs/serverless-next.js/blob/aec0f05f5b9f274d9a848b76d4964015ebf4c2f6/packages/serverless-components/aws-s3/src/component.ts) on line 69.

Ideally, it would be nice to avoid this behavior in the configurations, or remove this functionality all together. (There is actually a comment in the code stating it should be removed)

### Actual behavior
- Successfully deploys one app
- Upon starting the deployment of the next app with a new yml file, the previously deployed app's bucket is deleted
- Repeat 

### Expected behavior
There should be a way to avoid deleting the previous deployment, either by setting this in the configuration yml, or removing this functionality all together. 

### Steps to reproduce
- Using one repo, deploy using serverless-next
- Deploy again from the same repo with different serverless yml configuration (including different naming)

### Versions
- OS/Environment: Mac and Ubuntu
- @sls-next/serverless-component version: 3.7.0
- Next.js version: 12.2.3

### Checklist

- [ x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible. As there is only one maintainer (who maintains this in his free time) and thus very limited resources, if you have time, please try to debug the issue a bit yourself if possible.
- [x ] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by brimac1634** [comment]
I have created a [pull request](https://github.com/serverless-nextjs/serverless-next.js/pull/2514) to resolve the issue.

**Comment by djmin43** [comment]
beautiful

**Comment by brimac1634** [comment]
Closing this as I have found a solution. thank you

**Comment by Allin-Moondao** [comment]
> Closing this as I have found a solution. thank you

Hey! How did you resolve the issue?

**Comment by brimac1634** [comment]
@Allin-Moondao there a state of the project stored in the auto-generated .serverless directories. If the name of the bucket changes between deployments, this serverless package deletes the one stored in state. 

So all you have to do is delete those generated directories between deployments. I was deploying each project using bash scripts so I just added in a “rm” command between each project deployment. 😊
