### ISSUE TITLE
Manage SSL Certificates

### ISSUE THREAD

**Issue by cmanzur** [serverless-nextjs/serverless-next.js#253]
**Proposal**
In `serverless.yml` would be good to add the `SSL Certificate ARN` we need. (from ACM)

**Problem**
My _serverles..yml_
```
nextApp:
  component: "serverless-next.js"
  inputs:
    domain: ["service.stage", "example.com"]
```

I have 2 certificates in ACM:
- example.com (Additional Names: *.example.com)
- stage.example.com (Additional Names: *.stage.example.com)

When I run serverless, the CloudFront Distribution automatically choose `example.com` instead of `stage.example.com`. That causes a: 
**Error code: SSL_ERROR_BAD_CERT_DOMAIN**

Then, If I change the domain in serverless.yml:
` domain: ["service", "stage.example.com"] `

I get:
**nextApp › Error: Domain stage.example.com was not found in your AWS account. Please purchase it from Route53 first then try again.**

If I change the Certificate manually in CloudFront it works, but in the next deploy serverless override the Certificate.

**Comment by yankouskia** [comment]
Trying to resolve similar issues, @cmanzur just curious, what's the order of your actions?

1. creating/buying custom domain
2. creating hosted zone
3. creating certificate in acm
4. run sls-next component

Is that correct or you are doing smth in different way?

**Comment by nodabladam** [comment]
It is unfortunate that `*.example.com` wildcard certificates wont cover subdomains like `service.stage.example.com`.  I now do all my domains only one level deep to avoid the issue like `service-stage.example.com` but it is a hack.

**Comment by cmanzur** [comment]
@yankouskia Yes, my steps are exactly those. 
On step 3 I created 2 certificates in ACM in _us-east-1_ to be visible to CloudFront.

My AWS infrastructure is correct, because if I deploy manually (without serverless framework) it works perfectly.

The problem is that serverless _automatically_ choose a wrong certificate from the available array in CloudFront.

Note: I also have 2 more steps to download/upload the current _.serverless_ directory to a private S3 bucket to maintain the state.

**Comment by yeuem1vannam** [comment]
I'm facing the same problem.

I'm having two ACM certs:
  - `example.com` (including `*.example.com`) in `ap-northeast-1` region
  - `next-app.example.com` (including `*.next-app.example.com`) in `us-east-1` region

When deployed with the `serverless.yml` file as below
```yaml
nextApp:
  component: serverless-next.js
  inputs:
    bucketName: nextApp
    domain:
      - dev.next-app
      - example.com
```
<details>
<summary><b>I got the error</b>:</summary>

```bash
$ sls --debug

  DEBUG ─ Resolving the template's static variables.
  DEBUG ─ Collecting components from the template.
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
  DEBUG ─ Deploying bucket nextApp in region us-east-1.
  DEBUG ─ Checking if bucket nextApp exists.
  DEBUG ─ Setting acceleration to "true" for bucket nextApp.
  DEBUG ─ Bucket nextApp was successfully deployed to the us-east-1 region.
  DEBUG ─ Starting upload to bucket nextApp in region us-east-1
  DEBUG ─ Starting upload to bucket nextApp in region us-east-1
  DEBUG ─ Uploading directory /workspace/next_app/.next/static to bucket nextApp
  DEBUG ─ Uploading directory /workspace/next_app/public to bucket nextApp
  DEBUG ─ Starting deployment of lambda xxxxxx-yyyyyy to the us-east-1 region.
  DEBUG ─ Syncing role xxxxxx-yyyyyy in region us-east-1.
  DEBUG ─ Saved state for role xxxxxx-yyyyyy.
  DEBUG ─ Role xxxxxx-yyyyyy was successfully deployed to region us-east-1.
  DEBUG ─ Deployed role arn is arn:aws:iam::123456789000:role/xxxxxx-yyyyyy.
  DEBUG ─ Packaging lambda code from /workspace/next_app/.serverless_nextjs/default-lambda.
  DEBUG ─ Uploading xxxxxx-yyyyyy lambda code.
  DEBUG ─ Updating xxxxxx-yyyyyy lambda config.
  DEBUG ─ Successfully deployed lambda xxxxxx-yyyyyy in the us-east-1 region.
  DEBUG ─ Starting deployment of CloudFront distribution to the us-east-1 region.
  DEBUG ─ Updating CloudFront distribution of ID AAAAAAAAAAAA.
  DEBUG ─ CloudFront deployed successfully with URL: https://xxx-next-app.cloudfront.net.
  DEBUG ─ Starting Domain component deployment.
  DEBUG ─ Validating inputs.
  DEBUG ─ Formatting domains and identifying cloud services being used.
  DEBUG ─ Getting the Hosted Zone ID for the domain example.com.
  DEBUG ─ Searching for an AWS ACM Certificate based on the domain: example.com.
  DEBUG ─ Checking the status of AWS ACM Certificate.
  DEBUG ─ Adding dev.next-app.example.com domain to CloudFront distribution with URL "https://xxx-next-app.cloudfront.net"

  error:
  InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.
    at Request.extractError (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/root/.serverless/components/registry/npm/serverless-next.js@1.7.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: "The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.",
  code: 'InvalidViewerCertificate',
  time: 2019-12-14T09:32:57.455Z,
  requestId: 'b5fa0925-1e54-11ea-a5b7-6f88ad1c4429',
  statusCode: 400,
  retryable: false,
  retryDelay: 44.519610463000234
}

  102s › nextApp › InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.
```

</details>

**Comment by danielcondemarin** [comment]
This sounds like something that could potentially be fixed in https://github.com/serverless-components/domain? cc. @eahefnawy
Note this is what manages the domains behind the scenes and not the next component itself.

**Comment by pbrandone** [comment]
@cmanzur were you able to fix this?

**Comment by cmanzur** [comment]
Yes, I solved it but it's a workaround until someone fix the real problem. :)

What I did is deploy with serverless and then run a script that modifies the CF distribution.

**ONE-TIME PROCESS:**  This process is manual but it's just one time to create you desired CF Distribution Configuration.
1- Deploy NextJS with serverless: `serverless`
2- Go to AWS Web Console -> CloudFront and **manually** modify your domain + CNAME.
3- Save. Test if this work as you expect.

**DEPLOYMENT PROCESS:** This could be run multiple times.
1- Run this script to update the current CF Distribution with the proper configuration
```
serverless
CLOUDFRONT_ID=$(jq .id -r .serverless/Template.nextApp.CloudFront.json)
aws cloudfront get-distribution-config --id $CLOUDFRONT_ID | jq .DistributionConfig > cloudfront.json
sed -i "s/$WrongACMCertificateArn/$RightACMCertificateArn/" cloudfront.json
CLOUDFRONT_ETAG=$(aws cloudfront get-distribution-config --id "$CLOUDFRONT_ID" | jq .ETag -r)
aws cloudfront update-distribution --id "$CLOUDFRONT_ID" --distribution-config file://cloudfront.json --if-match "$CLOUDFRONT_ETAG"
```
(You should install jq first -> `apt install jq`)

Example for the `sed` step:
Suppose your wrong certificate is:
**arn:aws:acm:us-east-1:44444444444:certificate/aaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa**
`$WrongACMCertificateArn=aaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa`
And the right certificate is:
**arn:aws:acm:us-east-1:44444444444:certificate/bbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb**
`$RightACMCertificateArn=bbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb`

This command should replace the **ACMCertificateArn** and **Certificate** in the JSON file

_In my case, I use that script with more `sed` commands because I need to modify more stuff in 
CF and serverless doesn't allow me that._

**Comment by pbrandone** [comment]
@cmanzur thanks for the reply :)

I was actually able to fix this by creating a new hosted zone in Route 53 for the subdomain (should've done this a long time ago! it's much cleaner now)

1. Create a new hosted zone (e.g.: app.domain.com)
2. Copy NS from this new hosted zone
3. Go over to your original hosted zone (e.g.: domain.com)
4. Create a new NS record for app.domain.com and paste the value

serverless.yml:
```yml
nextApp:
  component: "serverless-next.js"
  inputs:
    domain: ["stage", "app.domain.com"]
```

**Comment by dphang** [comment]
In latest alpha there is support to specify `aliases` and `certificateArn`. I think it should give more flexibility and resolve this. Please do open new issue in case this doesn't work.
