### ISSUE TITLE
Custom domains don't work w/ alternate DNS provider (ie. Cloudflare)

### ISSUE THREAD

**Issue by wilsonpage** [serverless-nextjs/serverless-next.js#271]
**Describe the bug**

I'm attempting to use my own domain which is managed by Cloudflare. I'm able to set this up manually by:

1. Deploying the app without a `domain` in the config
2. Creating a CNAME record (in Cloudflare) pointing to the app's `xxx.cloudfront.net` endpoint
3. Creating and validating a certificate in ACM for `batch.songwhip.com`
4. Changing the Cloudfront's domain/CNAME to accept request from my custom domain (batch.songwhip.com)

<img width="911" alt="Screenshot 2019-12-30 at 10 56 55" src="https://user-images.githubusercontent.com/1020551/71579160-4322e000-2af3-11ea-818d-ecc69630c33e.png">

But using the `domain` config in `serverless.yml` always fails with:

`Error: Domain songwhip.com was not found in your AWS account. Please purchase it from Route53 first then try again.`

## Questions

1. Does this plugin only support domains registered/managed by Route53?
2. If so are there any workarounds you can think of?

**Comment by barrysteyn** [comment]
I am using cloudflare to manage my domains, and I pretty much do what you are doing. However, if you want the domain to be automatically setup in cloudfront upon deploy, you will need to use Route53. This requirement does not come from this component, rather, it comes from the fact that this component is using another component that sets things up which insists upon this.

**Comment by Enalmada** [comment]
Note that you don't actually have to change your nameservers to Route53...you just have to create a host entry there so the deploy process wont fail.

**Comment by wilsonpage** [comment]
@Enalmada interesting! Would you be able to offer a little more detail here?

**Comment by wilsonpage** [comment]
@barrysteyn thanks, glad I'm not the only one in this boat! It seems once the domains are manually wired up preferences stick, so it's probably just a one time config job for new projects. Either way, it's nice to have 'config as code' wherever possible.

**Comment by Enalmada** [comment]
@wilsonpage If you try and setup a serverless-next without any domain set, you will get a response like this:
```
  myApp: 
    appUrl:     https://dabcdefghijk.cloudfront.com
    bucketName: my-bucket
```
Add the appUrl as a cname in your CloudFlare.  Then create a hosted zone in route53 for your domain.  You don't actually need to purchase a domain in route53 to created a hosted zone.  After that, you should be able to get serverless-next working.

**Comment by danielcondemarin** [comment]
@barrysteyn is right. @wilsonpage Please raise a feature request in https://github.com/serverless-components/domain as this is what actually manages the domain and cloudfront association behind the scenes. 
I'll keep this issue open anyway as there may be some work to do after the domain component adds support for this.

**Comment by panbanda** [comment]
Hey there.  I do like the workaround of having the route53 entry and still using cloudflare.  However I have a staging site and a production site and the staging site is a subdomain that will then need to generate an SSL cert with ACM.  The production site has already been created for some other services and with terraform.  I really don't want it to generate the certificate for a subdomain, and really only want to specify the CNAME in the cloudfront distribution configuration.  Just trying to avoid having two frameworks (serverless && terraform) competing over SSL certs, route53 configurations, etc. when it can be solved by adding a cname attribute?

I think the serverless domain component is awesome but its specific to having a domain on route53.  I don't think it would be a stretch to have a cname as an attribute on the cloudfront dist just because its technically a different feature?

**Comment by dphang** [comment]
I think there were a couple changes added recently that let you manually add CNAMES/Aliases or ACM certs:

https://github.com/serverless-nextjs/serverless-next.js/commit/ea180e67515ee5dceed1c3e19731291615a7cbbb
https://github.com/serverless-nextjs/serverless-next.js/commit/6bb144385c6621c4c5c00443259df538a185f4f2

It may give more flexibility, please try it out in latest alpha and let us know if there are bugs (I didn't make the change myself, so haven't personally tried it out).

**Comment by panbanda** [comment]
Golden. That did it-- this actually closes it I believe.

```yaml
cloudfront: 
  aliases: [domain.com]
```

**Comment by benjipott** [comment]
Gréât , thks

**Comment by dphang** [comment]
Closing out old/stale issues. If same issue occurs with the latest version of this component, please reopen a new issue.
