### ISSUE TITLE
Navigating to /_document returns a 503 error

### ISSUE THREAD

**Issue by austinwalter** [serverless-nextjs/serverless-next.js#281]
**Describe the bug**
So once my app is deployed, if I navigate to `example.com/_document` AWS returns a "503 request could not be satisfied" error instead of my app. I had expected it to return my 404 page. Not sure if I mis-configured something or if this is happening for other people.

**To Reproduce**
1. Go to example.com/_document
2. Returns an AWS default 503 message, not my app

**Expected behavior**
Expected behavior was to return my 404 message. The correct 404 page is returned for /_app and /_error pages.

**Additional context**
Going to any sub-directory of /_document returns the correct behavior (e.g. /_document/blah)

**Comment by dphang** [comment]
I am helping look at old issues, I think these should be resolved in latest component versions, as I couldn't reproduce, closing for now. Please let us know if there is still an issue.
