### ISSUE TITLE
How to integrate sentry

### ISSUE THREAD

**Issue by diegopamio** [serverless-nextjs/serverless-next.js#284]
**Is your feature request related to a problem? Please describe.**
After revamping the plugin, all the `customHandler` documentation went away, how would be the process now to implement a sentry integration?

**Describe the solution you'd like**
Probably an entry on the next.config.js?

**Describe alternatives you've considered**
None so far.

**Additional context**
I'm not so pro on developing next nor serverless plugins.

**Comment by dphang** [comment]
I guess this is pretty late but I think it works following here: https://github.com/serverless-nextjs/serverless-next.js/issues/1038. Closing this issue otherwise, feel free to open a new one against the latest component versions.
