### ISSUE TITLE
How do I use dev and prod instances without using the `domain` attribute?

### ISSUE THREAD

**Issue by epicfaace** [serverless-nextjs/serverless-next.js#304]
I can't use the `domain` attribute as in [your example](https://github.com/danielcondemarin/serverless-next.js/tree/3abd959387e47ab6f0e04b13b4ee644c50d51694/packages/serverless-nextjs-component/examples/multiple-instance-environment) because my domain name is not managed by Route 53.

However, I would like to still deploy a dev and a prod version of the cloudfront distribution, s3 bucket, etc. I also need to run this on a CI pipeline. Is there a built-in way to do this?

**Comment by barrysteyn** [comment]
Hi @epicfaace - I made that example for @danielcondemarin. I don't understand your question: The example uses domains to illustrate how to set variables that correspond to a stage. You don't need use domain, you can use whatever you want. Please look at the code and dive into the example to see what I am doing.

**Comment by epicfaace** [comment]
Right. Let me explain more -- hope this clarifies:

Your example shows setting environment variables to a stage and then using them to configure `inputs.domain` to change the custom domain.

However, I would like to use environment variables to configure both the bucket name and cloudfront distribution that the app is deployed to. I see that I can configure the bucket name using `inputs.bucketName`, but how do I configure the cloudfront distribution through `inputs`?

**Comment by epicfaace** [comment]
@barrysteyn any thoughts on this?

**Comment by Yalian** [comment]
bump

**Comment by dphang** [comment]
Now you can set CloudFront distributionId in the inputs, so hopefully this solves the issue? You can refer more about managing multiple environments here as well: https://github.com/serverless-nextjs/serverless-next.js#features
