### ISSUE TITLE
static folder doesn't work when used inside public folder

### ISSUE THREAD

**Issue by SarKurd** [serverless-nextjs/serverless-next.js#313]
**Describe the bug**
static folder doesn't work when used inside public folder

**To Reproduce**
1- Make a public folder and make a static folder inside it
2- Put an image inside the static folder

**Expected behavior**
expect static folder to work when used inside public folder

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, CI]
 - Version [e.g. Unknown]

**Comment by dphang** [comment]
It doesn't work because it will conflict with `static/*` cache behavior that is meant for serving files from `static` folder in root of Next app. This intentionally would not have a handler attached to it.

Could you move those assets to `static` folder at root of your Next app instead?
