### ISSUE TITLE
Question: Experimental rewrite feature of Next.js

### ISSUE THREAD

**Issue by oriolcastro** [serverless-nextjs/serverless-next.js#319]
We are working on an application that uses the experimental rewrite function of Next.js to handle internationalization.

example:
`
{ source: '/', destination: '/${defaultLanguage}' },
{ source: '/:path*', destination: '/${defaultLanguage}/:path*' },
`

We have been looking into the routes-manifest generated by Next.js and how to use that information during the build step from the NextjsComponent without any progress so far.

example:
`
 { "source": "/", "destination": "/en", "regex": "^\\/$" },
{
      "source": "/:path*",
      "destination": "/en/:path*",
      "regex": "^(?:\\/((?:[^\\/]+?)(?:\\/(?:[^\\/]+?))*))?$"
    }
`

How could this feature be implemented in the serverless-nextjs-component with the default-lambda architecture?

Thanks for the awesome work put into it!

**Comment by afzalsayed96** [comment]
Hi @oriolcastro, Did you get any success with this yet?

**Comment by dphang** [comment]
Just looking at old issues - rewrites are now supported in the latest alpha: https://github.com/serverless-nextjs/serverless-next.js#features. I think that should work for you? Do let us know with a new issue if there is trouble on this.
