### ISSUE TITLE
Nested dynamic route URL not working when directly accessed

### ISSUE THREAD

**Issue by codeinaire** [serverless-nextjs/serverless-next.js#322]
**Describe the bug**
In deployment when I go to a dynamic route through a link the page loads fine, but when I copy that link and paste it into another window or a completely different browser I get the 404 error page`

This works as expected (the resource of the copied link loads) in local development when I'm using `npm run dev`  but not when deployed through serverless-next.js

**To Reproduce**
1. Go to `https://d2hir6fuy7vez1.cloudfront.net/recipes`
2. Click on any recipe
3. Copy URL from recipe page
4. Paste into another tab, window, or completely different browser
5. Watch the 404 error page load

**Expected behavior**
Expect the same recipe page to load that was loaded when clicked on the link to get to that recipe.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSx
 - Version 10.15.3

**Additional context**
My folder structure for pages:
```
pages/
   recipe/[title-id]
      index.tsx
   _app.tsx
   ...
``` 

This is the `Link` component
```
<Link
    href={{
              pathname: '/recipe/[title-id]',
              query: { difficulty: recipe.difficulty, recipeId: recipe.id }
            }}
            as={`/recipe/${recipe.title}-${recipe.id}`}
          >
```

The only logs I've gotten from CloudWatch for this Lambda are the start, end, and report ones. There's no other information.

I'm using `v1.9.3` of  `serverless-next.js`.

**Comment by tyler-ground** [comment]
@danielcondemarin Would you be able to comment on this?  

I'm seeing this as well and I see elsewhere you mentioned it only works with getInitialProps?  However, I am using getInitialProps in the offending page so I don't understand.

It appears that dynamic routes are broken on a fresh page load?

**Comment by tyler-ground** [comment]
I ended up figuring this out on my end.  I had a route that is in the new style that this lib does not support yet.  Make sure you're exporting the component as default.

**Comment by danielcondemarin** [comment]
> I ended up figuring this out on my end. I had a route that is in the new style that this lib does not support yet. Make sure you're exporting the component as default.

Could you share a code example of what's not working? @tyler-ground Also what you did to work around it.

**Comment by tyler-ground** [comment]
I had multiple exports that some recent tutorial was using.  Changing the format to the following and deploying that with the latest nextjs and voila even hard refreshes of these routes work :)

``
const Page = () => <JSX />

Page.getInitialProps = async () => {}

export default Page
``

**Comment by danielcondemarin** [comment]
> I had multiple exports that some recent tutorial was using. Changing the format to the following and deploying that with the latest nextjs and voila even hard refreshes of these routes work :)
> 
> ```
> const Page = () => <JSX />
> 
> Page.getInitialProps = async () => {}
> 
> export default Page
> ```

Thanks @tyler-ground . Could you share as well what the multiple exports look like? If is supported by next.js then is something that would need fixing here.

**Comment by tyler-ground** [comment]
Unfortunately, I edited the git tree to clean out a bunch of deployment commits and whatnot so I don't have the original anymore.  I had several export const statements from a tutorial I had been following.  This tutorial must have been new because it used getServerSideProps but I had converted it to work without the older functions such as getInitialProps.

**Comment by dphang** [comment]
Several fixes went in for dynamic routing conflicts etc. in the latest alpha. Please try out and open a new issue if it still persists. I'll close this one since it may be stale. Thanks!
