### ISSUE TITLE
AccessDenied: Access denied -- Disable transfer acceleration.

### ISSUE THREAD

**Issue by ytwguru** [serverless-nextjs/serverless-next.js#323]
**Describe the bug**
After running `serverless --debug` the deployment is interrupted with the message: 
```
DEBUG -- Setting acceleration to "true" for bucket mybucketname

error:
{ AccessDenied: Access Denied`
...
}
```

Can you add the option to disable acceleration for users without the permission to enable accelerated transfers?

**To Reproduce**
1. Open terminal
2. Navigate to running directory
3. Type serverless --debug

**Desktop (please complete the following information):**
 - OS: debian
 - Version 10

**Comment by paulolramos** [comment]
I'm getting this same issue. Many have suggested to run `serverless --no-aws-s3-accelerate` but that still doesn't work.

**Comment by tapjay** [comment]
I'm also encountering this, @paulolramos were you able to make progress?

**Comment by tapjay** [comment]
In case anyone is encountering this issue, https://github.com/serverless-nextjs/serverless-next.js/pull/443 is currently in review which will hopefully provide a temporary workaround.

**Comment by revvi** [comment]
I am having the same issues. Using the code in #443, I can pass the accelerate issue. However it presents new issue on access denied on creating CloudFront distribution. I am submitting the case to AWS Support to lift up the limit first.

**Comment by ungarida** [comment]
@revvi could you share more in details what code did you use? Because I could not manage to overcome accelerated issues yet.

**Comment by ungarida** [comment]
I confirm, you can manage with AWS support to get it done.

**Comment by ShibelordHODL** [comment]
try this in serverless.yml

```
myNextApplication:
  component: "@sls-next/serverless-component@1.19.0-alpha.35"
  inputs:
    enableS3Acceleration: false
```

**Comment by dphang** [comment]
As mentioned above we had added function to manually disable or enable it, hopefully it should work
