### ISSUE TITLE
Customizing cloudfront - WAF, custom SSL cert, other settings

### ISSUE THREAD

**Issue by uclaeamsavino** [serverless-nextjs/serverless-next.js#330]
Is there a way to customize cloudfront beyond domain name? We have a custom WAF, a custom SSL cert, custom price class.

Sorry if I'm missing it, I searched for WAF and couldn't find anything.

Edit: well after some experimenting, it looks like I can add a custom WAF after generating the cloudfront instance, then redeploy my serverless-next app over it w/o losing my WAF setting. That feels like it could be dangerous though?

**Comment by dphang** [comment]
Going through some older issues - let's track WAF support in here: https://github.com/serverless-nextjs/serverless-next.js/issues/521. The other two (PriceClass, ACM cert) are now CloudFront inputs which you can now specify. Hopefully this helps.
