### ISSUE TITLE
Support for custom source directory

### ISSUE THREAD

**Issue by mekwall** [serverless-nextjs/serverless-next.js#34]
I am using TypeScript and want to put all pages and components in a `./src` directory. This works fine with Next.js by simply adding `src` as the last argument to any `next` cli command (such as `next build src`) but I can't figure out how to get it to work with this plugin.

**Comment by JuHwon** [comment]
this is also a required feature for my project.

**Comment by danielcondemarin** [comment]
> this is also a required feature for my project. do you allow PRs? im quite busy right now but maybe i can find some time to give it a look.

PRs are most definitely welcome. Feel free to look into this and let me know if you have any questions / need any help

**Comment by Vadorequest** [comment]
@danielcondemarin Any guidelines regarding how should this be implemented? I'm also considering TypeScript and wonder if I can use it right away now that the Component is more mature, or if it still needs some more love :)
