### ISSUE TITLE
Set headers from SSR pages

### ISSUE THREAD

**Issue by thomaschaaf** [serverless-nextjs/serverless-next.js#353]
Maybe I have not found it but is there a way to set the cache control oder expires header for SSR? I would like to utilize the cloudfront cache by returning a header. Is this possible?

**Comment by dphang** [comment]
A bit late, but if you still need this I think you can set the header by updating `ctx.res` in the getInitialProps/getServerSideProps like so:

```ts
ctx.res.setHeader(
  "Cache-Control",
  "public, max-age=0, s-maxage=31536000, must-revalidate"
);
```

**Comment by dphang** [comment]
And now you can also set headers using custom headers feature, if you prefer to do so there: https://github.com/serverless-nextjs/serverless-next.js#features.
