### ISSUE TITLE
Only build the package command (without deploying and resources creating)

### ISSUE THREAD

**Issue by peniakoff** [serverless-nextjs/serverless-next.js#419]
**Is your feature request related to a problem? Please describe.**
I would like to use Serverless Next.js component only for building Lambda@Edges and all resources (.serverless_next directory and more) without deploying stuff (like a domains, buckets, etc.). It will be the best solution if all cloudformation templates (I mean templates for AWS) were prepared already before.

**Describe the solution you'd like**
It would be nice to have a choice to prepare only packages for manually deploying. It coul dbe done eg. with command like below:
`serverless package`

**Describe alternatives you've considered**
I've tried to make this with a Serverless pure solution but without success.

**Comment by Trandel** [comment]
:+1:

**Comment by dphang** [comment]
I've added a new input `deploy` which can be set to false to just build assets and skip deployment (now includes s3 assets as well). Available in @sls-next/serverless-component@1.18.0-alpha.12 now.
