### ISSUE TITLE
Dynamic routing(Client side routing) always run Lambda function

### ISSUE THREAD

**Issue by drizzef** [serverless-nextjs/serverless-next.js#428]
**Describe the bug**
Hi,
I'm using serverless-next.js version 1.9.10.

I don't know if it is a bug nor a feature.

We are using dynamic routing with Link tag as explained in their docs: https://nextjs.org/docs/routing/introduction#linking-between-pages

In the development environment, the first request is creating an SSR request and afterward, every click on the components that we wrapped in the Link tag is making client-side routing. 
We observe that in Chrome's development tools on the Network tab that when we click on the Link tag it request the following route: https://www.example.com/_next/data/z2O_EKzh0NwVl6Fz90ZDR/event/5ea2fd3a9c775d001df4fbcd.json
and get a 404 error.

And in the serverless-next.js architecture, it says that all the requests to the _next folder go to S3.
How can we make it dynamic and use the API instead creating another expensive lambda request?

**To Reproduce**
1. create next.js app that fetches requests from an API.
2. add dynamic routing to some dynamic page like product/[id]
3. deploy to AWS with serverless-next.js plugin.
4. click on product link and you get another SSR request.

**Expected behavior**
You tell me :)

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by lone-cloud** [comment]
Can you verify that you're <Linking> to your dynamic pages using `as` and not simply relying on `href`?

**Comment by drizzef** [comment]
Hi, 
I saw that @danielcondemarin push a code of version 1.13.0 that fixes the issue with getServerProps.
It seems that I won't using getServerProps because I already have an API and this makes another hop for me. 

You can close this issue. Thanks!
