### ISSUE TITLE
feature: redirect to the supported domain type when using the input domainType  = www/apex

### ISSUE THREAD

**Issue by lone-cloud** [serverless-nextjs/serverless-next.js#470]
This is meant to cover the case when deploying to a www/apex domain and using the input "domainType"  = "www" or "apex". Currently there is no redirect to the unsupported domain.
The domainType input was added with https://github.com/danielcondemarin/serverless-next.js/pull/466

The 301 redirect will live in the lambda code and will 301 to the supported www/apex domain when a request comes in for the unsupported domain. 
 
Implementation reference: https://engineering.close.com/posts/redirects-using-cloudfront-lambda-edge#setting-up-the-lambdaedge-function

**Comment by dphang** [comment]
I've supported this with `domainRedirects` input, using a 308 redirect, same as Vercel/Next.js does: https://github.com/serverless-nextjs/serverless-next.js#i-was-expecting-for-automatic-subdomain-redirection-when-using-the-domaintype-wwwapex-input

So this can be closed.
