### ISSUE TITLE
Using useServerlessTraceTarget with nextConfigDir causes a 503 in Cloudfront

### ISSUE THREAD

**Issue by lukemarshdv** [serverless-nextjs/serverless-next.js#473]
serverless-next.js `v14.0`
next.js `v.9.3.1` 

I have `useServerlessTraceTarget: true`
My next.config.js is in a different directory to the serverless.yml file so I'm using `nextConfigDir: ../../../`

I'm getting a 503 error on cloudfront when i deploy:

```
{
    "errorType": "Error",
    "errorMessage": "Cannot find module 'next/dist/next-server/server/render'\nRequire stack:\n- /var/task/pages/[static].js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/pages/[static].js",
        "/var/task/index.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module 'next/dist/next-server/server/render'",
        "Require stack:",
        "- /var/task/pages/[static].js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:840:27)",
        "    at Module.require (internal/modules/cjs/loader.js:1019:19)",
        "    at require (internal/modules/cjs/helpers.js:77:18)",
        "    at Object.KK5V (/var/task/pages/[static].js:947:18)",
        "    at __webpack_require__ (/var/task/pages/[static].js:31:31)",
        "    at Module.Nfsr (/var/task/pages/[static].js:1035:28)",
        "    at __webpack_require__ (/var/task/pages/[static].js:31:31)",
        "    at /var/task/pages/[static].js:126:18",
        "    at Object.<anonymous> (/var/task/pages/[static].js:129:10)"
    ]
}
```

**Comment by lukemarshdv** [comment]
I have removed useServerlessTraceTarget and everything is working but I think there might be an issue with it

**Comment by lone-cloud** [comment]
I would try testing it again with the latest version of Next.js. If that still doesn't work, I suspect that there might be a bug related to "nextConfigDir: ../../../". Ideally you want to have useServerlessTraceTarget set to true and this component will default to this value being true in the future.

**Comment by danielcondemarin** [comment]
@lukemarshdv Can you share your directory structure please? And from which directory you run `serverless`?

The `cwd` from which the `serverless` command is run is set as the [base path for node-file-trace](https://github.com/vercel/node-file-trace#base). That means dependencies seating "above" that directory aren't resolved. For example:

```
dir1/
  dir2/
     package.json # "deploy": "npx serverless"
     ...
```

Only node_modules from `dir2` will be resolved. I realise this isn't ideal and I'm trying to find the best way to handle this atm but it may come down just to better documentation. Look forward to your reply 👍

**Comment by lukemarshdv** [comment]
@danielcondemarin Sorry it's taken me a while to get back to you! I was busy releasing our code into production. Your plugin has made this possible - thank you!

Here is my directory structure:

```
- config
    - app
        - staging
            - serverless.yml
            - .serverless (not in gitignore)
        - production
            - serverless.yml
            - .serverless (not in gitignore)
- src
    - pages
- next.config.js
```

I've set my `nextConfigDir` to `../../../`

The reason we have a setup like this is that we have multiple applications (each requiring different cloudfront settings)

**Comment by lone-cloud** [comment]
The fix is pretty simple based on what Daniel wrote, you just need to correct the path to nodeFileTrace in two places in this file: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/lambda-at-edge/src/build.ts#L153

Instead of doing that I recommend flattening out your config directory to keep .serverless in S3 and to populate a single serverless.yml using env vars during CD. To me, that config directory structure is an anti-pattern.

**Comment by lukemarshdv** [comment]
I agree the pattern I’m using isn’t ideal but we have many origins and behaviours which differ for each application. We used to use terraform to populate these in Cloudfront but this plugin means I can’t use terraform anymore. if I could use this and continue to use terraform it would simplify the serverless files

**Comment by thomasdissert** [comment]
> The fix is pretty simple based on what Daniel wrote, you just need to correct the path to nodeFileTrace in two places in this file: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/lambda-at-edge/src/build.ts#L153
> 
> Instead of doing that I recommend flattening out your config directory to keep .serverless in S3 and to populate a single serverless.yml using env vars during CD. To me, that config directory structure is an anti-pattern.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/171566590/bcfb2180-dc06-11e9-84fb-9028e13935a6"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[serverless-nextjs/serverless-next.js](https://github.com/serverless-nextjs/serverless-next.js)**⚡ Deploy your next apps using the serverless framework - serverless-nextjs/serverless-next.js

I'd actually like to try this, but I'm having Issues that the serverless environment variables aren't resolved. Can you help me with that?

My serverless.yml:
```
user-portal-${env.TESTING}:
  component: '@sls-next/serverless-component@1.15.1'
  stage: ${env.TESTING}
  inputs:
    bucketName: user-portal-${env.TESTING}
    name: user-portal-${env.TESTING}
    useServerlessTraceTarget: true
```

This only results in the serverless command trying to create a `user-portal-${env.NODE_ENV}` deployment without resolving the env-variable which then breaks with an Error: `Forbidden: Invalid credentials or this AWS S3 bucket name may already be taken`

**Comment by thomasdissert** [comment]
Nevermind, I found out that it's not possible to concatenate strings with environment variables.

**Comment by ezalorsara** [comment]
Good Day, I'm also having this problem 503 Error  https://d2wgduol86q4m5.cloudfront.net/

my serverless.yml
```javascript
myapp:
  component: '@sls-next/serverless-component@1.17.0-alpha.6'
  inputs:
    useServerlessTraceTarget: true
    domainType: 'apex'
    cloudfront:
      priceClass: 'PriceClass_100'
```

my file structure

![image](https://user-images.githubusercontent.com/6506275/90711792-38ac9500-e2d4-11ea-8c6e-1b887eafa1a4.png)


This is will work if I remove the useServerlessTraceTarget. but i want it to be true so that the file build is smaller

Thanks

**Comment by darren-charterindex** [comment]
I am also getting the 503. Aside having the next.config.js and serverless.yml in the same directory, I also use the following:

serverless.js
```
const { Component } = require('@serverless/core')
const dotenv = require('dotenv')

class Deploy extends Component {
  async default(inputs = {}) {
    const { env } = inputs
    if (env === 'dev' || env === 'prod') {
      dotenv.config({ path: `${__dirname}/.env/${env}` })
      const template = await this.load('@serverless/template', env)
      const output = await template({ template: 'serverless.yml' })
      return output
    }
    return false
  }
}

module.exports = Deploy
```

serverless.yml
```
myApp:
  component: '@sls-next/serverless-component@1.19.0-alpha.32'
  inputs:
    memory: 256
    domain: ${env.DOMAIN_NAME}
    domainType: www
    bucketRegion: ${env.AWS_REGION}
    cloudfront:
      certificate:
        acmCertificateArn: ${env.CERTIFICATE_ARN}
    minifyHandlers: true
```

**Comment by tom-pavemint** [comment]
My team had the same problem and we figured out an elegant solution!
The way we encountered the problem was this combination:
 - using yarn workspaces
 - using userServerlessTraceTarget
 - CI in Github actions
 - Problem: deploy command was running from 1 dir lower than where the app resources were built
 
 The solution we found was very simple. We changed out the workspaces build command to this:

```
 name: deploy serverless
        working-directory: ./app
        run: yarn run deploy
```
and 'yarn run deploy' == 'serverless' inside /app/package.json

 Hope this solution helps someone.

**Comment by dphang** [comment]
Sorry I did not have the resources to look into this. I think in latest versions useServerlessTrace has been deprecated (they have a smarter code chunking now), so I think this can be closed as no longer relevant + there are the workaround mentioned above?
