### ISSUE TITLE
next-aws-cloudfront is referenced via requires in various places after package rename to @sls-next/next-aws-cloudfront

### ISSUE THREAD

**Issue by bitfrost** [serverless-nextjs/serverless-next.js#475]

**Comment by bitfrost** [comment]
Example: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/lambda-at-edge/src/build.ts#L174

**Comment by danielcondemarin** [comment]
@bitfrost Just pushed a fix for this and deployed. Could you try using this config and close if it works?

```
yourApp:
  component: "@sls-next/serverless-component@1.15.0-alpha.4"
```

**Comment by bitfrost** [comment]
I do not have a full serverless app setup  (I  am using the cdk and a set of these packages directly).   The issue is fixed for me though.  Thank you!

**Comment by danielcondemarin** [comment]
> I do not have a full serverless app setup (I am using the cdk and a set of these packages directly). The issue is fixed for me though. Thank you!

Oh I'm curious now, I'd love  to add CDK support! Let me know if you'd like to contribute on that :)

**Comment by bitfrost** [comment]
Once I get it fully working / and generic enough I would love to. Once I have something worth sharing I will ping you.
