### ISSUE TITLE
Previously deployable,  Cannot find module '@sls-next/next-aws-cloudfront'

### ISSUE THREAD

**Issue by msimonc** [serverless-nextjs/serverless-next.js#483]
Local dev is working,

1.15.0-alpha.0 - 1.15.0-alpha.2

w/ or w/o "next build"

sls:
(After 10+ seconds)

{
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mark/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/build.js',
    '/Users/mark/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/@sls-next/lambda-at-edge/dist/index.js',
    '/Users/mark/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/serverless-next.js/serverless.js',
    '/usr/local/lib/node_modules/serverless/node_modules/@serverless/core/src/Component.js',
    '/usr/local/lib/node_modules/serverless/node_modules/@serverless/core/src/index.js',
    '/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js',
    '/usr/local/lib/node_modules/serverless/lib/components-v1.js',
    '/usr/local/lib/node_modules/serverless/bin/serverless.js'
  ]
}

yaml:
app: seeker
component: website
name: seeker-fe

seeker-fe:
  component: "serverless-next.js"

inputs:
  name: ${name}
  domain: web-data-dev.com
  region: ap-southeast-2

**Comment by lone-cloud** [comment]
Its been renamed, bring in the new component by name like: 
`component: "@sls-next/serverless-component@1.15.0-alpha.4`
