### ISSUE TITLE
Use existing S3 bucket

### ISSUE THREAD

**Issue by lukemarshdv** [serverless-nextjs/serverless-next.js#486]
Firstly, let me say thank you for this plugin. It has saved me a lot of time!

I would like the ability to use an existing bucket as our cdn already contains a bunch of other assets.

Is this something that would be possible?

**Comment by lone-cloud** [comment]
Have you tried using the "bucketName" input? https://github.com/serverless-nextjs/serverless-next.js#inputs

**Comment by lukemarshdv** [comment]
@lone-cloud yes that’s what I’m using but i get an error that the bucket could not be deleted when deploying

**Comment by lone-cloud** [comment]
Have you also tried setting the "bucketRegion" input to match the region of your bucket?

**Comment by lukemarshdv** [comment]
@lone-cloud I added createAssetBucket to inputs and it worked perfectly. I added a debug but it didn't show me anything useful!
