### ISSUE TITLE
S3 307 errors on initial deploy for buckets outside us-east-1

### ISSUE THREAD

**Issue by danielcondemarin** [serverless-nextjs/serverless-next.js#493]
**Is your feature request related to a problem? Please describe.**

When doing the first deployment of my app using any bucket region other than `us-east-1` it takes a while for my app to be available. For example:

```yml
component: @sls-next/serverless-component@1.2.3
inputs:
  bucketRegion: eu-west-1
```

On initial deploy 307 errors are received from the CloudFront distribution. This is because buckets provisioned outside us-east-1 take time for their DNS to propagate. See an in-depth explanation here: https://aws.amazon.com/premiumsupport/knowledge-center/s3-http-307-response/

**Describe the solution you'd like**

I'd like CloudFront to use the regional S3 endpoint to avoid waiting the time it takes for the bucket DNS to propagate fully.

**Describe alternatives you've considered**
N/A

**Additional context**

The only changes required should be [here](https://github.com/serverless-components/aws-cloudfront/blob/master/lib/getOriginConfig.js#L21). Basically use a regional endpoint `<bucket-name>.s3.<aws-region>.amazonaws.com` when the bucket region !== "us-east-1"

**Comment by andrewgadziksonos** [comment]
https://github.com/serverless-nextjs/serverless-next.js/pull/495

**Comment by danielcondemarin** [comment]
Fixed by https://github.com/serverless-nextjs/serverless-next.js/pull/495
