### ISSUE TITLE
Example folder?

### ISSUE THREAD

**Issue by jsphkhan** [serverless-nextjs/serverless-next.js#499]
Sorry to open this as an issue, but I was looking for examples as you had mentioned in the ReadMe.

`See examples/dynamodb-crud for an example Todo application that interacts with DynamoDB.`

Kindly help me with the examples. 

@danielcondemarin Thank you for this amazing component. I have started to move my infrastructure from traditional Docker, EC2 hosted containers to Lambda's. So this component is a life savior for me. As a matter of positive feedback, I would like to know if you are planning to improve the docs, I can help out there and eager to do so. May be some kind of Docusaurus docs.

**Comment by danielcondemarin** [comment]
> Sorry to open this as an issue, but I was looking for examples as you had mentioned in the ReadMe.
> 
> `See examples/dynamodb-crud for an example Todo application that interacts with DynamoDB.`
> 
> Kindly help me with the examples.
> 


@jsphkhan You can find the examples/ [here](https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/serverless-component/examples). Should probably link to them in the README 🙂

> @danielcondemarin Thank you for this amazing component. I have started to move my infrastructure from traditional Docker, EC2 hosted containers to Lambda's. So this component is a life savior for me. As a matter of positive feedback, I would like to know if you are planning to improve the docs, I can help out there and eager to do so. May be some kind of Docusaurus docs.

Improving the docs would be great. I like the sound of something like Docusaurus. I've not set this up before but happy for you to start a PR to get things started and  I'll help wherever I can 👍

**Comment by jsphkhan** [comment]
@danielcondemarin Thanks. I shall set it up in some time and create a PR. Thank you for responding back. 
Meanwhile, I will create a PR for updating the ReadMe with examples link.

**Comment by danielcondemarin** [comment]
Merged in https://github.com/serverless-nextjs/serverless-next.js/pull/500
