### ISSUE TITLE
Question: Is it possible to set a custom Role name?

### ISSUE THREAD

**Issue by bradders** [serverless-nextjs/serverless-next.js#502]
Is it possible to set a role name (similar to naming the lambda function and bucketName). I've run a bunch of test deployments and I now have a tonne of roles that are named after resource IDs. The same happened for buckets and lambda functions, but this was solved by adding `runtime.defaultLambda` and `bucketName`. I'm not that well versed in IAM/AWS so not even sure if this is doable/possible.

**Comment by bradders** [comment]
For context, I'm looking at hooking up the serverless deploy into a bitbucket pipeline so it deploys on every commit to a certain branch, but if I do that I'll have a bunch of randomly named roles and cloudfront instances that aren't needed/used anymore.

**Comment by danielcondemarin** [comment]
> For context, I'm looking at hooking up the serverless deploy into a bitbucket pipeline so it deploys on every commit to a certain branch, but if I do that I'll have a bunch of randomly named roles and cloudfront instances that aren't needed/used anymore.

Sounds like this https://github.com/serverless-nextjs/serverless-next.js#cicd-a-new-cloudfront-distribution-is-created-on-every-ci-build-i-wasnt-expecting-that would help?

**Comment by danielcondemarin** [comment]
I'm going to be closing this. You can't set a custom role name as of today although this may be introduced in future. 

In terms of having multiple distributions and roles being created look at https://github.com/serverless-nextjs/serverless-next.js#cicd-a-new-cloudfront-distribution-is-created-on-every-ci-build-i-wasnt-expecting-that for possible solutions.
