### ISSUE TITLE
"Code storage limit exceeded" error occurs after multiple builds.

### ISSUE THREAD

**Issue by ytwguru** [serverless-nextjs/serverless-next.js#503]
**Describe the bug**
Each build adds a new version.  Lambda has a limit of 75GB for Function and layer storage.  Once you run out of space on AWS you get the "Code storage limit exceeded" error.

**To Reproduce**
Run multiple builds.

**Expected behavior**
You run out of space

**Desktop**
- OS: Debian
- Version: Buster

**Suggestion**

Implement `versionFunctions: false` option for component.

**Comment by danielcondemarin** [comment]
AWS Lambda@Edge only supports a numbered version, not for $LATEST or aliases as [documented by AWS](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html).

You can probably use https://github.com/lumigo/SAR-Lambda-Janitor to clean up older published versions. I'll close this issue as the `versionFunctions: false` proposal is not possible, but feel free to open a new one for a lambda@edge cleanup sort of feature. I think that's needed in this project.
