### ISSUE TITLE
@sls-next/serverless-component has an invalid "main" property on package.json

### ISSUE THREAD

**Issue by lucas-varela** [serverless-nextjs/serverless-next.js#505]
When trying to deploy, I'm facing this issue:

>Error: Cannot find module '/home/lucas/Projects/starlight/trailblazer/node_modules/@sls-next/serverless-component/dist/src/component.js'. Please verify that the package.json has a valid "main" entry.

![screenshot](https://i.imgur.com/JMZMGvs.png)

The "main" entry point on `@sls-next/serverless-component@1.15.1` is set to `dist/src/component.js`, but the `src` directory doesn't exist there:

![screenshot](https://i.imgur.com/4XoZf0Q.png)

The setup I use is a bit different from the usual, though, because I created a package that wraps the nextjs serverless component and introduces a template component (which make the `--stage development` part of my command work).

This is [how it loads the nextjs component](https://github.com/starlightcms/trailblazer/blob/master/serverless.js#L9):
```js
const template = await this.load('@sls-next/serverless-component', stage)
```

My wrapper component used to work fine with the old serverless-next.js component. However, after updating to the new @sls-next/serverless-component, this error started happening. 

Trying to deploy using @sls-next/serverless-component directly, that is, without my wrapper, works fine too. However, my company's projects have various environments, and thus they all need this wrapper to work properly.

Any idea why the new component breaks my wrapper?

**Comment by danielcondemarin** [comment]
Could you try using `@sls-next/serverless-component@1.15.2-alpha.0`. 
I've pushed [a fix](https://github.com/serverless-nextjs/serverless-next.js/commit/96d510d3e21f6fe84c02425f2c8c6f311b90665f) for the `main` property that was broken when we moved over to Typescript.

**Comment by lucas-varela** [comment]
Updating to `@sls-next/serverless-component@1.15.2-alpha.0` did work, but another problem occurred:

![screenshot](https://i.imgur.com/dcbWwgR.png)

After some debugging, I found that the problem is caused by @serverless/core itself, which doesn't support CommonJS modules. Manually rewriting `dist/component.js` to use Node's `module.exports` works, but I believe that changing this is out of question, since CommonJS is the right way to go.

I'll probably create a fork of @serverless/core that fixes this. If I do, I'll post the repo link here to anyone who faces the same issue in the future.

Thanks for the fast response, by the way :grin:

**Comment by lucas-varela** [comment]
Updating to `@sls-next/serverless-component@1.15.2-alpha.0` did work, but another problem occurred:

![screenshot](https://i.imgur.com/KsRbLgr.png)

After some debugging, I found that the problem is caused by @serverless/core itself, which doesn't support CommonJS modules. Manually rewriting `dist/component.js` to use Node's `module.exports` works, but I believe that changing this is out of question, since CommonJS is the right way to go.

I'll probably create a fork of @serverless/core that fixes this. If I do, I'll post the repo link here to anyone who faces the same issue in the future.

Thanks for the fast response, by the way :grin:
