### ISSUE TITLE
Loading the @sls-next/serverless-component component programmatically throws error

### ISSUE THREAD

**Issue by maddygoround** [serverless-nextjs/serverless-next.js#516]
**Describe the bug**
When we are trying to load the component in one of our serverless-components, we see an error occurred

**To Reproduce**

   ```const slsDeploy = await this.load("@sls-next/serverless-component");```
   ```return await slsDeploy(inputs);```

**Additional context**

>   Error: Cannot find module '/Users/next-js/src/node_modules/@sls-next/serverless-component/dist/src/component.js'. Please verify that the package.json has a valid "main" entry

**Comment by danielcondemarin** [comment]
Hey 👋🏼 Could you try using the latest alpha?

**Comment by maddygoround** [comment]
@danielcondemarin changing to alpha did improve but started getting a new error.

`TypeError: childComponent is not a constructor`

We are also a new error which is as below

`ENOENT: no such file or directory, open /Users/Documents/learning/example-frontend-next-js/src/node_modules/acorn-numeric-separator/dist/acorn-numeric-separator.js.map`

Tried the code with specifying the component alias separately as it is not able to find `childComponent.name` under `childComponent` class but it didn't help. 

`const slsDeploy = await this.load("@sls-next/serverless-component","NextjsComponent");`

**Comment by maddygoround** [comment]
Got it working.


The package.json "main" entry location needs to be change from `dist/compoenent.js` to `./serverless.js` 

Changing` "main": "dist/component.js"` to` "main": "./serverless.js"` in package.json got it working.

**Comment by danielcondemarin** [comment]
Great stuff, you mind PRing the fix? I'll get it published tonight.

**Comment by maddygoround** [comment]
@danielcondemarin Sure.
