### ISSUE TITLE
Preparing and deploying apis on lambda-edge with other react frameworks.

### ISSUE THREAD

**Issue by maddygoround** [serverless-nextjs/serverless-next.js#520]
Using the capability for building the serverless API, one can include the same API structure in other react frameworks like create-react-app and can build and prepare the APIs for lambda-edge deployment with there choice of react framework.

I would go ahead and ask if we can support other react framework deployment all together with the way we do nextJS but seeing that the work here is entirely focused on nextJS, at least we could provision change where users can build and deploy APIs separately.

Any thoughts?

**Comment by danielcondemarin** [comment]
@maddygoround This goes outside the scope of the project that has been only focused on Next.js so far. Could you elaborate more on how the create-react-app example would work?

**Comment by dphang** [comment]
As mentioned this project has specific optimizations for Next.js project so this would be quite outside the scope of the project. You can probably look into something like FAB.dev which is about creating portable application bundles and supports general React frameworks.
