### ISSUE TITLE
503 Error - Cannot find module 'cookies' - when using 'next-redux-cookie-wrapper'

### ISSUE THREAD

**Issue by frontend-twentysixdigital** [serverless-nextjs/serverless-next.js#529]
**Describe the bug**
Getting a 503 error when deploying to AWS cloudfront using [next-redux-cookie-wrapper](https://github.com/bjoluc/next-redux-cookie-wrapper). 

Related CloudWatch log:

```json
{
    "errorType": "Error",
    "errorMessage": "Cannot find module 'cookies'\nRequire stack:\n- /var/task/pages/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/pages/index.js",
        "/var/task/index.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module 'cookies'",
        "Require stack:",
        "- /var/task/pages/index.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:840:27)",
        "    at Module.require (internal/modules/cjs/loader.js:1019:19)",
        "    at require (internal/modules/cjs/helpers.js:77:18)",
        "    at eval (eval at 75CO (/var/task/pages/index.js:12002:55), <anonymous>:1:1)",
        "    at Object.75CO (/var/task/pages/index.js:12002:55)",
        "    at __webpack_require__ (/var/task/pages/index.js:31:31)",
        "    at Module.1TCz (/var/task/pages/index.js:5902:17)",
        "    at __webpack_require__ (/var/task/pages/index.js:31:31)",
        "    at Module.qR6r (/var/task/pages/index.js:67662:17)"
    ]
}
```

I have tried installing `cookies` as a dependency and also including it in my app (without actually using it) without success.

_The app runs fine if I swap out `next-redux-cookie-wrapper` for `next-redux-wrapper`_

**To Reproduce**

1. `@sls-next/serverless-component@1.16.0`
2. `next-redux-cookie-wrapper@1.1.3`
3. Using `getInitialProps` within `_app.js`
4. `import { withReduxCookiePersist } from 'next-redux-cookie-wrapper';`
5. `export default withReduxCookiePersist(makeStore)(App);`

**Expected behavior**
cookies module should be loaded server side

**Desktop (please complete the following information):**

- OS: Windows (WSL2)
- Version: 10

**Comment by dphang** [comment]
Seems strange, maybe check your `.next/serverless/pages/index.js` if `cookies` dependency actually got bundled into it (looks like it's a dependency of `next-redux-cookie-wrapper`). I think you can also try importing `cookies` into your app and call a method on it (like its constructor), I believe this will prevent webpack (used by Next.js) from tree-shaking it

**Comment by dphang** [comment]
Closing old issue, if this is still relevant or unsolved please feel free to open against the newer Next.js / component versions
