### ISSUE TITLE
Per API Route Caching TTL

### ISSUE THREAD

**Issue by tyler-ground** [serverless-nextjs/serverless-next.js#532]
**Is your feature request related to a problem? Please describe.**
Currently we can cache specific non-api routes but an attempt to set a ttl for a specific API route results in the error "Error: Setting custom cache behaviour for api/ route "/api/blah/*" is not supported"

**Describe the solution you'd like**
Allow TTL and other Cache Customizations per API.  A couple of my APIs would work well with a short term cache (and save me $$$)

**Describe alternatives you've considered**
Not using serverless-next.js for this route.  This does solve the problem but it's not as nice.

**Comment by dphang** [comment]
I think you can do this a couple of ways:

1. Set Cache-Control header in the response of the Next.js API route.
2. Use the CloudFront custom inputs to define your own cache behavior for routes (I think this is in the readme and was added somewhat recently?)

However, there is still an issue with TTL time for API routes being all 0 (min, max, default). So I think (1) would not work right now as TTL is fixed to always be 0. See PR: https://github.com/serverless-nextjs/serverless-next.js/pull/593

**Comment by dphang** [comment]
PR is merged so API routes have TTL of default = 0, min = 0, max = 1 year, and the latest alpha was published, so you should be able to do this using Cache-Control headers.

For #2, sorry missed the point about the custom cache behavior - not sure why we don't allow custom cache behavior for API routes?

**Comment by dphang** [comment]
This should be available in 1.17.0 now, please open new issue if you find any bugs. Thanks!

**Comment by tyler-ground** [comment]
Wicked, I have an image processing task that will considerably benefit from this.  Will take it for a spin!
