### ISSUE TITLE
Lerna project 404 on page reload

### ISSUE THREAD

**Issue by msimonc** [serverless-nextjs/serverless-next.js#539]
Refactored my project using Lerna.
page reloads to all subroutes work.   (http://.../about)
`<Link href="/"> works.`
local dev works.
but page reloads without subroutes get the NextJS 404 page.   (http://...)

yarn recognizes that it is in a Lerna project so
In the client src folder, overwriting yarn.lock with the known working version, then "yarn" then deploy reproduces.

Deploying exact project outside Lerna works fine.

component: "@sls-next/serverless-component@1.16.0"

**Comment by mdw2000** [comment]
I had the same situation - based on #522 I pinned the versions as below and it solved it for me

```
"@sls-next/serverless-component": "1.16.0",
"next": "9.4.4",
```

**Comment by dphang** [comment]
@msimonc is this still an issue with the latest alpha? I think I helped fixed various routing issues so this might be fixed as well.

**Comment by msimonc** [comment]
thanks @dphang I'll check ASA get 1 min,

**Comment by msimonc** [comment]
Fixed and working

@mdw2000 above currently the working setup, thanks
