### ISSUE TITLE
Custom routes rewrites not working

### ISSUE THREAD

**Issue by pavinthan** [serverless-nextjs/serverless-next.js#543]
Custom routes rewrites not working in Serverless Next.js At The AWS Edge

**To Reproduce**

1. Add some rewrites in next.config.js
```
// next.config.js
module.exports = {
  async rewrites() {
    return [
      {
        source: '/api/login',
        destination: `${process.env.API_URL}/login`,
      },
     {
        source: '/api/:route*',
        destination: `${process.env.API_URL}/:route*`,
      },
    ];
  }
};
```

2. Deploy the Next.js app with 
```
# .env
API_URL=https://laravel-backend.com
```

3. POST to `/api/login` response is `403 ERROR The request could not be satisfied.`
5. GET `/api/user` response is next.js success response code with `404 This page could not be found.`

**Expected behavior**
1. POST to `/api/login` should throw invalid credentials error / success response
2. GET `/api/user` should throw 401 error / logged in user's information

**Additional context**
It's working fine in dev env and also I have verified `.env` values replaced correctly in `routes-manifest.json`

**Comment by devcshort** [comment]
@pavinthan According to the [feature list](https://github.com/serverless-nextjs/serverless-next.js#features)

Rewrites are currently not supported

**Comment by dphang** [comment]
I think it makes sense to add next, we will track this in: https://github.com/serverless-nextjs/serverless-next.js/issues/587 instead.
