### ISSUE TITLE
Cannot deploy even a basic package without breaking AWS (Error: package.json does not exist at /package.json)

### ISSUE THREAD

**Issue by nathanjosiah** [serverless-nextjs/serverless-next.js#548]
# :information_source:  These steps are very verbose but incredibly simple and essentially nothing custom.

**Describe the bug**
Cannot deploy even a basic package without AWS breaking.

**To Reproduce**

Preconditions:
1. Have a fresh AWS account free from existing things that may interfere with reproducing this issue
2. Run `mkdir bugtest && cd bugtest`
3. Per [NextJS installation](https://nextjs.org/docs#manual-setup) install required next packages `yarn add next react react-dom` and also for typescript `yarn add --dev typescript @types/react @types/node`
4. As instructed, add the scripts to `package.json`:
```
{
  "dependencies": {
    "next": "^9.5.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "devDependencies": {
    "@types/node": "^14.0.27",
    "@types/react": "^16.9.46",
    "typescript": "^3.9.7"
  }
}
```
5. Run `mkdir pages && mkdir pages/api`
6. Add `pages/index.jsx`:
```
export default () => {
    return <div>Welcome to the test!</div>;
}
```
7. Add `pages/api/test.ts`:
```
export default async function(req, res) {
    res.json({test:true});
};
```
8. Add `serverless.yml`:
```
foobar:
  component: "@sls-next/serverless-component@1.17.0-alpha.1"
```
9. Install serverless globally `npm install -g serverless` 
10. Run `serverless`
11. Wait for deploy to finish and visit `<ENDPOINT>/api/test`. You should see `{"test":true}`. Awesome, :+1: great so far.
12. Now, run `yarn add argon2 aws-sdk` (`aws-sdk` is required or all future deployments will fail for some reason. Separate bug I think?)
13. Update `pages/api/test.ts`:
```
import {hash} from "argon2";

export default async function(req, res) {
    const hashed = await hash("abc");
    res.json({hashed});
};
```
14. Run `serverless`
15. Wait for deployment to finish.
16. :-1: Visit `<ENDPOINT>/api/test` again. Now you will see a giant error from CloudFront saying it can't render the route. Looking at the CloudWatch Lambda logs the error will be with no real other context:
```
Error: package.json does not exist at /package.json
```

**Expected behavior**
The page loads fine with a payload like 
```
{"hashed":"$argon2i$v=19$m=4096,t=3,p=1$vfQO4EpmsJaAbBr/qIFidA$BDnpT+FAxWCJiyKLLToJdUUa1SItuRHzSnpZrycIAbc"}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/665104/90314327-75dde500-ded8-11ea-987b-e3114c2fbd1b.png)

**Desktop (please complete the following information):**

* OS: Ubuntu 18.04.4
* Node v12.10.0
* Yarn 1.22.4
* npx 6.14.4

`serverless --version`:
* Framework Core: 1.78.1
* Plugin: 3.7.0
* SDK: 2.3.1
* Components: 2.34.3

`aws --version`: 
```
aws-cli/1.16.258 Python/2.7.17 Linux/4.15.0-112-generic botocore/1.12.248
```

**Additional context**

Final `package.json`
```
{
  "dependencies": {
    "argon2": "^0.27.0",
    "aws-sdk": "^2.734.0",
    "next": "^9.5.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "devDependencies": {
    "@types/node": "^14.0.27",
    "@types/react": "^16.9.46",
    "typescript": "^3.9.7"
  }
}
```

**Comment by danielcondemarin** [comment]
@nathanjosiah This issue is not specific to `serverless-next.js`. If you run a production build of next you'll see the same issue,

```
next build
next start
```

![image](https://user-images.githubusercontent.com/1122442/90315117-b78a8200-df10-11ea-8a1d-6dd4bccacd1d.png)

The underlying problem is because [this line](https://github.com/ranisalt/node-argon2/blob/fee5a25e25b4cda7c0236da83f0402e1e4683d99/argon2.js#L8) assumes the `package.json` for `argon2`will be there. However this doesn't play nicely with Next.js compiler and bundling. I suggest you raise the issue on Next's repo, https://github.com/vercel/next.js/issues

**Comment by cadejscroggins** [comment]
@nathanjosiah, did you figure out how to handle this? I have the exact same issue with argon2.

**Comment by nathanjosiah** [comment]
@cadejscroggins Yes, argon2 cannot be used with NextJS and I stopped using it and I switched to a plain ServerrlessJS AWS Lambda project instead. This tech is just not ready for many types of use cases. It isn't just argon2 but anything that needs expressions in exports like argon2 does.

**Comment by cadejscroggins** [comment]
@nathanjosiah thanks for the response/heads up. I ended up switching to bcryptjs and it is working well. hopefully I don't run into it again.
