### ISSUE TITLE
SLS will create a new cloudfront distribution even if one already exists for your lambda and error when associating it with a domain

### ISSUE THREAD

**Issue by danjiro** [serverless-nextjs/serverless-next.js#554]
**Describe the bug**
You will get a `CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.` when you are doing a fresh deploy (one without the .serverless folder with existing config info) and the lambda already exists. Serverless docs say you shouldnt commit your .serverless folder but in this case you would have to or else it will create a new cloudfront distribution and try to assign that new one to your domain and you get the error. Normal SLS avoids these issues because it uses cloudformation?

**Comment by dphang** [comment]
I believe this plugin needs to use new version of Serverless Components: https://github.com/serverless-nextjs/serverless-next.js/issues/415#issuecomment-634682161 to sync the state, though it needs to be upgraded as per the issue.

You can commit it each time but that might make it hard to do in a CI/CD pipeline, especially if you have multiple stages. You can use something like the following:

```
# Before running serverless fetch remotely stored folders
aws s3 sync "s3://my-serverless-state-bucket/my-component/${STAGE}/.serverless" .serverless

serverless

# After running serverless sync it's folders back to S3 bucket
aws s3 sync .serverless "s3://my-serverless-state-bucket/my-component/${STAGE}/.serverless"
```

This is adapted from: https://github.com/serverless-nextjs/serverless-next.js/issues/328#issuecomment-604733316. If you have multiple stages it might be useful to create a custom deployment script.

**Comment by ezalorsara** [comment]
I'm also in this situation having multi stages. I'm still thinking what the best approach to this Issue

**Comment by danjiro** [comment]
Syncing the .serverless folder to an s3 bucket looks like the best way to
approach it.
