### ISSUE TITLE
Please add support for redirect and rewrite rules of Next Js

### ISSUE THREAD

**Issue by nitesh3539** [serverless-nextjs/serverless-next.js#564]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dphang** [comment]
So there is `redirects` / `rewrites` list in `routes-manifest.json` after build, which has list of redirects (file with trailing slash -> file, and trailing slash redirect).

The plugin currently supports trailing slash redirect but it isn't using the default list, rather it is just checking for `trailingSlash` prefix or not for better performance.

For custom redirects/rewrites, we could read from `routes-manifest.json` and if there are any besides the defaults (trailingSlash 308 redirect) or defaults have changed (e.g you want a status other than 308), then use those instead.

**Comment by dphang** [comment]
Closing in favor of: https://github.com/serverless-nextjs/serverless-next.js/issues/587. Please follow that thread for updates.
