### ISSUE TITLE
CloudFront showing generic 503 error page when SSR page fails to render (e.g in getInitialProps()) instead of Next.js error page

### ISSUE THREAD

**Issue by dphang** [serverless-nextjs/serverless-next.js#566]
**Describe the bug**
When SSR page fails to render (e.g a server-side API call fails, etc.), then CloudFront error page (503 Bad Gateway) is shown instead of the Next.js error page.

Searched and I don't believe anyone else reported this issue

**To Reproduce**
Steps to reproduce the behavior

1. Create an SSR page that throws an error in `getInitialProps()`
2. Deploy with serverless-next.js (1.16, 1.17)
3. Go to that page
4. You will get 503 error as below.

```
503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: t-JGXBL9ipU4vhfWAEKtcwPreZ5zWn3Ujwf-U2ynduRlP90VdiZ2AQ==
```

In Lambda logs, we get an unhandled promise rejection:

```
2020-08-27T04:15:23.768Z	dc177b96-2a0c-4094-afea-eebd8899fcbe	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: error",
    "reason": {
        "errorType": "Error",
        "errorMessage": "error",
        "stack": [
            "Error: error",
            "    at Function.module.exports.2HMD.AnotherPage.getInitialProps (/var/task/pages/anotherSSR.js:5691:9)",
            "    at loadGetInitialProps (/var/task/pages/anotherSSR.js:32196:27)",
            "    at Function.appGetInitialProps (/var/task/pages/anotherSSR.js:13867:58)",
            "    at loadGetInitialProps (/var/task/pages/anotherSSR.js:32196:27)",
            "    at renderToHTML (/var/task/pages/anotherSSR.js:1738:1221)",
            "    at async renderReqToHTML (/var/task/pages/anotherSSR.js:21856:22)",
            "    at async Module.render (/var/task/pages/anotherSSR.js:21929:22)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: error",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:315:20)",
        "    at process.EventEmitter.emit (domain.js:482:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

A repro app is provided: https://github.com/dphang/nextjs-repros/tree/error-page, which has a page called `anotherSSR` that always errors out in its `getInitialProps()`

**Expected behavior**

As per Next.js local server / Vercel, they have their own error page (`_error.js`) that should be shown instead of the CloudFront error page. This also has the benefit that it can use an app's `_error.js` if it's defined (which likely has its own layout), so it's more user friendly.

**Screenshots**

CloudFront 503 error page:

<img width="1791" alt="Screen Shot 2020-08-26 at 9 22 52 PM" src="https://user-images.githubusercontent.com/3221524/91383977-6026c480-e7e2-11ea-8dc7-c7dd8402f241.png">

Next.js local server or Vercel error page:
<img width="358" alt="Screen Shot 2020-08-26 at 9 22 40 PM" src="https://user-images.githubusercontent.com/3221524/91383979-62891e80-e7e2-11ea-9d95-301bd12a770f.png">

**Desktop (please complete the following information):**

- OS: Any
- Version: Any

**Additional context**

Looked in the code, I think we may need to change the `page.render` call in `default-handler` to handle an SSR page render error and render the error page instead? Also this will fix that `page.render()` is being called without `await` resulting in unhandled promise rejection.

```ts
  try {
    await page.render(req, res);
  }
  catch (error) {
    console.error(error);
    page = require(`./pages/_error.js`);
    await page.render(req, res);
  }
```

so that in case of any SSR page error, it is handled properly and we instead render the error page which should be able to render (if that doesn't, then we get 503 from CloudFront).

Ref: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/default-handler.ts#L235

I'll continue testing on this and hopefully can create a PR.

**Comment by tiagobbraga** [comment]
The same issue.

**Comment by dphang** [comment]
I've created a draft PR for fixing this behavior: https://github.com/serverless-nextjs/serverless-next.js/pull/570. It's now aligned with what Next/Vercel does.
