### ISSUE TITLE
Add e2e tests (e.g app deployed on CloudFront) as part of CI/CD workflow.

### ISSUE THREAD

**Issue by dphang** [serverless-nextjs/serverless-next.js#573]
**Is your feature request related to a problem? Please describe.**
Not directly, but it would help the developer experience and reduce # regressions. This request is to add end-to-end test automation to the CI/CD workflows. Basically, as part of the workflow, actually deploy a test app to CloudFront and run an e2e test suite.

This would help in a few ways (among others):
* Regressions can be caught earlier by testing across a few recent versions of Next.js in the CI/CD workflow. Fewer GH issues would be created as well.
* We could then tag a release as tested with certain versions of Next.js (e.g 9.5.2). This would give more confidence to users, and less time is needed to validate alpha releases?
* Developers who are making PRs can use the test app + e2e test suite to locally verify their changes on their own AWS account.

**Describe the solution you'd like**

Basically, there are two parts:

* Test app: this should be a simple app, ideally without any UI libraries. This would test common scenarios like SSR/SSG pages, client-side navigation, trailing slash redirects, experimental-serverless-trace, error pages, etc. I guess the test app can live in the same monorepo.
* e2e test suite: we could use a browser test framework like [Cypress](https://www.cypress.io/) and API testing frameworks like [Supertest](https://github.com/visionmedia/supertest), or just use libraries like Axios, or node-fetch. (I'm using these myself, apart from Axios).

Bonus:

* Once this automation is in place and has sufficient coverage, on successful tests + e2e tests, we could auto-publish each commit as alpha releases on npm, so users can try out the latest features soon after the commits are merged. Only manual action is needed to publish stable releases.

**Describe alternatives you've considered**
N/A

**Additional context**
I thought of this since I was recently making a few changes. Right now I am manually testing with my own test app + my production app with these changes, but I can't cover all scenarios by myself or may miss some accidentally. I'm happy to help with some of these (e.g e2e test suite, test app) if you are willing to provide the AWS account (not sure if AWS provides free accounts for open source projects? It probably shouldn't cost more than a few cents to run per month).

**Comment by danielcondemarin** [comment]
@dphang This is a great summary of something I have been wanting to do for a while now, but unfortunately because of time haven't been able to. 

I am 100% on-board with the idea. To be honest I don't have much availability in the next month due personal circumstances but more than happy to help out in the little time I have if you want to take a stab at this.

**Comment by dphang** [comment]
Sounds good! I can try to setup a basic Next.js app in the next week or so.

**Comment by dphang** [comment]
@danielcondemarin added the first test Next app as a PR. Next, I'll work on adding Cypress tests and testing the GH Actions workflow. It's pretty basic for now but I'd rather get some very simple tests working in GH Actions before adding more complex pages / tests. Please let me know if you prefer a different structure :)

**Comment by danielcondemarin** [comment]
> Also when you have some time, please apply for the AWS open source credits? Since Lambda@Edge doesn't have free tier it would be helpful (though it's $0.60 per 1 million requests, pretty cheap)
> 

I will do 👍 I was trying to DM you but couldn't find a way. If you [DM me](https://twitter.com/danielcondemarin) I'll send you an invite link to the contributors slack workspace.

**Comment by dphang** [comment]
> > Also when you have some time, please apply for the AWS open source credits? Since Lambda@Edge doesn't have free tier it would be helpful (though it's $0.60 per 1 million requests, pretty cheap)
> 
> I will do 👍 I was trying to DM you but couldn't find a way. If you [DM me](https://twitter.com/danielcondemarin) I'll send you an invite link to the contributors slack workspace.

Ah yeah, I have my profile to private and don't use social media much. I will DM you on Twitter. Thanks!

**Comment by dphang** [comment]
@danielcondemarin I've created the 2nd PR: https://github.com/serverless-nextjs/serverless-next.js/pull/592. Could you please take a look when you get some time?

Remaining part is to create GH Actions workflow and connect it to the AWS account, will wait for you on that. Also would like to add more test coverage for CloudFront caching.

Thank you in advance :)

**Comment by dphang** [comment]
Thanks @danielcondemarin for helping review this, please let me know once AWS account is ready.

Meanwhile I will start to work on the GH Actions workflow. Since it takes some time for new CloudFront distributions to be active, I'm thinking we should try to reuse distributions when possible instead of deleting them, so CI/CD doesn't take forever to run. Probably just delete the S3 bucket contents using `aws-cli` and maintain a list of distributions that are freed up after testing.
