### ISSUE TITLE
Please add support for custom headers rules of Next Js 9.5

### ISSUE THREAD

**Issue by marcin-piela-sf** [serverless-nextjs/serverless-next.js#579]
**Is your feature request related to a problem? Please describe.**
I want to add custom header to one of a public file

```
async headers() {
      return [
        {
          source: '/sw.js',
          headers: [
            {
              key: 'service-worker-allowed',
              value: process.env.NEXT_PUBLIC_BASE_PATH,
            },
          ],
        },
      ];
    },
```

**Describe the solution you'd like**
Configured headers should be added to response

**Additional context**

I see that configured headers are stored in routes-manifest.json after build:
```
"headers": [
    {
      "source": "/sw.js",
      "headers": [
        {
          "key": "service-worker-allowed",
          "value": "/"
        }
      ],
      "regex": "^/sw\\.js$"
    }
  ],
```

but those values are not read anywhere

**Comment by dphang** [comment]
Thanks, I think this makes sense as next feature to add since it's a major feature of Next.js 9.5. Tracking it in: https://github.com/serverless-nextjs/serverless-next.js/issues/587 since there is some common code that is shared with rewrites/redirects as well.
