### ISSUE TITLE
Best practice for hitting API route from getInitialProps

### ISSUE THREAD

**Issue by MGough** [serverless-nextjs/serverless-next.js#582]
Apologies if I've missed this somewhere. I need to hit my API from within `getInitialProps` (or `getServerSideProps`):
```js
MyPage.getInitialProps = async (ctx) => {
  return fetch(`${HOST}/api/someAPIRoute`).then({ do: something })
})
```
but the hostname of the lambda that was called to return the page itself is obviously different to that of the API. 

Is the best approach here to hit the Cloudfront URL so that the request can be routed to the relevant API lambda in the correct region? It seems a little odd to be accessing it from the 'outside', although it also seems like the best way of handling being '@edge'.
 
If so then is there a nice way to get the Cloudfront URL in the SSR Pages Lambda?

**Comment by dphang** [comment]
Yea, I think you have to do it this way as I believe there is no way to trigger an edge Lambda directly, if you use CloudFront URL then it will route it to the right edge Lambda. Anyway, the DNS resolution time should be super fast, so I don't think this is an issue.

Also, I don't use API routes now (I am using a separate backend), but CloudFront URL would only be known after deploying. I imagine you can just set the correct CloudFront URL as an environment variable after deploying (using `.env` file or next config)

**Comment by MGough** [comment]
> Yea, I think you have to do it this way as I believe there is no way to trigger an edge Lambda directly, if you use CloudFront URL then it will route it to the right edge Lambda. Anyway, the CloudFront/DNS resolution time should be super fast, so I don't think this is an issue, performance wise.

Thanks for the response. Yeah it seemed like a viable solution (and did work), it just felt a little like I might've been missing something obvious especially as I couldn't see it mentioned anywhere. I wasn't too worried about performance, but coming from a world of microservices talking directly to other microservices within a private network it feels a little weird, but that's just part of having NextJS with public API routes I guess!

> Also, I don't use API routes now (I am using a separate backend), but CloudFront URL would only be known after deploying. I imagine you can just set the correct CloudFront URL as an environment variable after deploying (using `.env` file or next config)

That's exactly what I've done, although it'll likely be simpler once I have custom domains set up for cloudfront and don't need to deploy twice when deploying from scratch.

Thanks again for helping to sanity check this!
