### ISSUE TITLE
Apex domain is not loading when using wildcard subdomain

### ISSUE THREAD

**Issue by tapjay** [serverless-nextjs/serverless-next.js#604]
**Describe the bug**
When I configure my custom subdomain like this:

```
inputs:
    domain: ['*', 'mydomain.com']
```
Loading on the site on any subdomain works (e.g `www.mydomain.com`, `testing.subdomain.com` etc) but I encounter a 403 error when loading `mydomain.com`. I would like the site to load on the apex domain and all subdomains.

I have made this work by manually adding an A record pointing to the cloudfront distribution in Route53 (`mydomain.com -> foobar.cloudfront.net.`) and adding `mydomain.com` to the "alternative domain names" field in the cloudfront distribution via the web console, however this is less then ideal as the latter entry is overwritten on subsequent deploys. 

Apologies in advance if this is because I have misunderstood how to configure this properly.

**To Reproduce**
1. Set up a custom domain with a wildcard subdomain like so: `domain: ['*', 'mydomain.com']`
2. Attempt to access your apex domain, in this case `mydomain.com`
3. Receive an error

**Expected behavior**
The app should load on the apex domain as it does on the subdomains

**Desktop (please complete the following information):**

- OS: OSX
- Version 10.14.1

**Comment by dphang** [comment]
I think it is similar to here: https://github.com/serverless-nextjs/serverless-next.js/issues/620. Basically, I think it does not support multiple domain records at the moment, it would need a PR to update this to support multiple domain inputs.

**Comment by tapjay** [comment]
Hmm I see, thanks for posting that @dphang . Unfortunately in this instance I need something other than www so I'll work around it.
