### ISSUE TITLE
next build fails silently 

### ISSUE THREAD

**Issue by michaelwindell26** [serverless-nextjs/serverless-next.js#605]
**Describe the bug**
When running `npx serverless --debug` if the `next build` process fails with an error it is not displayed in the output and the deployment hangs forever.

**To Reproduce**

1. Create a reproducible error in `pages/index.js` (in my case an `import` statement was incorrect)
2. Run `npx serverless --debug`
3. Output displays "appName Deploying" without the error message from `next build` displayed
4. Run `next build`
5. Output displays error message

**Expected behavior**
Output from `next build` should be forwarded to output from `npx serverless --debug`

**Desktop (please complete the following information):**

- OS: [e.g. WSL2 on Windows 10]

**Comment by michaelwindell26** [comment]
For now I will setup our CI / CD pipeline to manually run `next build` so we can at least see an error if it occurs...

**Comment by dphang** [comment]
Couldn't reproduce on Mac OS Catalina and latest alpha (1.17 alpha-13):

```bash
/usr/local/bin/node /usr/local/Cellar/yarn/1.22.4/libexec/bin/yarn.js run serverless
yarn run v1.22.4
$ serverless

  error:
  Error: Command failed with exit code 1: node_modules/.bin/next build
Failed to compile.

./pages/ssr-page.tsx:2:33
Type error: Cannot find module 'next2' or its corresponding type declarations.

  1 | import React from "react";
> 2 | import { NextPageContext } from "next2";
    |                                 ^
  3 | 
  4 | type SSRPageProps = {
  5 |   name: string;
info  - Creating an optimized production build...
    at makeError (/Users/danielphang/IdeaProjects/serverless-next.js/packages/libs/lambda-at-edge/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/danielphang/IdeaProjects/serverless-next.js/packages/libs/lambda-at-edge/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
  command: 'node_modules/.bin/next build',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'info  - Creating an optimized production build...',
  stderr: 'Failed to compile.\n' +
    '\n' +
    './pages/ssr-page.tsx:2:33\n' +
    "Type error: Cannot find module 'next2' or its corresponding type declarations.\n" +
    '\n' +
    '\u001b[0m \u001b[90m 1 | \u001b[39m\u001b[36mimport\u001b[39m \u001b[33mReact\u001b[39m from \u001b[32m"react"\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n' +
    '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 2 | \u001b[39m\u001b[36mimport\u001b[39m { \u001b[33mNextPageContext\u001b[39m } from \u001b[32m"next2"\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m   | \u001b[39m                                \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 3 | \u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 4 | \u001b[39mtype \u001b[33mSSRPageProps\u001b[39m \u001b[33m=\u001b[39m {\u001b[0m\n' +
    '\u001b[0m \u001b[90m 5 | \u001b[39m  name\u001b[33m:\u001b[39m string\u001b[33m;\u001b[39m\u001b[0m',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

  5s › next-app › Error: Command failed with exit code 1: node_modules/.bin/next build
Failed to compile.

./pages/ssr-page.tsx:2:33
Type error: Cannot find module 'next2' or its corresponding type declarations.

  1 | import React from "react";
> 2 | import { NextPageContext } from "next2";
    |                                 ^
  3 | 
  4 | type SSRPageProps = {
  5 |   name: string;
info  - Creating an optimized production build...

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

I believe this is the code that does the Next build: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/build.ts#L446-L460, perhaps it is buggy on Windows? Does the same problem happen for you if you build it in Linux (e.g Ubuntu runner in GitHub Actions). Unfortunately, I don't have a Windows machine to test on, so you or someone else could help make a PR :)

**Comment by michaelwindell26** [comment]
Yes, it was actually a Ubuntu runner on Github Actions that pointed me to this issue.

**Comment by fargito** [comment]
I think the issue is actually on `@serverless/cli`. I've made a PR on this repo to fix the issue

**Comment by raffij** [comment]
Had this issue for a while and investigated today and found this. Looks like they are reluctant to merge as it's no longer maintained.

Possible to fork it as part of this org? Feels like it's quite important as we are stuck on this version?

**Comment by raffij** [comment]
@dphang  this feels like an important bug which you might be able to help with. How do you feel about serverless-nextjs org forking that pr? as it looks like the cli won't be upgraded in the future.

**Comment by dphang** [comment]
@raffij Yeah I am fine if you want to fork it and fix it for now.

**Comment by raffij** [comment]
@dphang the pr that makes the change is here https://github.com/serverless/cli/pull/17

**Comment by dphang** [comment]
@raffij published a forked package with the above change from @fargito under @sls-next/serverless-cli - haven't tried out yet as I just published as is but hopefully it can be used now?

**Comment by raffij** [comment]
That's great. As it's integral to the build process much more confidence in using your fork than someone else.

**Comment by dphang** [comment]
actually just realized `@serverless/cli` is a dependency to https://github.com/serverless/serverless/blob/master/package.json, so not sure how we can replace that without having to also fork `serverless` package?

**Comment by raffij** [comment]
You could add it as a peer dependency, but that's only a prompt to users or add it to the docs as an important step in the build.

**Comment by dphang** [comment]
Since we are still on the deprecated components (which uses deprecated @serverless/cli package), I'm testing out whether we could use a patched serverless binary here (I called it serverless-patched): https://github.com/serverless-nextjs/serverless-next.js/pull/1658

This should avoid having to fork both @serverless/cli and serverless packages.

Let's see if it hopefully works.

**Comment by dphang** [comment]
#1658 has been published in npm (alpha for now), so you should be able to run command npx serverless-patched which contains the fixes. Let me know if there are any issues; I have tested it locally and it seems to work (tested with npx --package @sls-next/serverless-component serverless-patched to force fresh version)

**Comment by raffij** [comment]
That's a much better approach. Thanks for your continued support.

**Comment by jonahallibone** [comment]
@dphang trying to run this, I get a 
```sh
Note: running patched serverless binary.
/bin/sh: /Users/csandvik/code/privco/marketing-site-next/node_modules/@sls-next/serverless-component/dist/bin/../../node_modules/.bin/serverless: No such file or directory
node:child_process:903
    throw err;
    ^

Error: Command failed: /Users/csandvik/code/privco/marketing-site-next/node_modules/@sls-next/serverless-component/dist/bin/../../node_modules/.bin/serverless 
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.<anonymous> (/Users/csandvik/code/privco/marketing-site-next/node_modules/@sls-next/serverless-component/dist/bin/serverless-patched.js:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 21205,
  stdout: null,
  stderr: null
}
```
