### ISSUE TITLE
EEXIST: file already exists

### ISSUE THREAD

**Issue by anupam-newgen** [serverless-nextjs/serverless-next.js#618]
**Describe the bug**
I'm trying to deploy "next": "9.5.2" app on AWS using CodeBuild (triggered through Code Pipeline). I'm using @sls-next/serverless-component@1.17.0-alpha.16
However when I'm running the serverless --debug command, i'm getting the below error:

.......
Page                                                                         Size     First Load JS
┌ λ /                                                                        6.33 kB         575 kB
├   /_app                                                                    0 B             488 kB
├ ● /404                                                                     3.8 kB          538 kB
├   └ css/bdc9da0cbc792461f0e1.css                                           2.69 kB
├ λ /api/manifest.webmanifest                                                0 B             488 kB
├ λ /basket                                                                  7.47 kB         544 kB
├   └ css/469d7ce2febe12416374.css                                           4.58 kB
├ λ /categories/[category]                                                   4.9 kB          558 kB
├ λ /checkout                                                                59.5 kB         638 kB
├   └ css/b79082bb27190fe8b860.css                                           6.84 kB
├ λ /create-store                                                            3.65 kB         553 kB
├   └ css/fde68de6306df56c664c.css                                           1.97 kB
├ λ /favourites                                                              9.87 kB         560 kB
├   ├ css/9e4f8046f3b1d568178a.css                                           4.02 kB
├   └ css/c78f92ef5701365628eb.css                                           4.02 kB
├ λ /login                                                                   10.5 kB         578 kB
├   └ css/b49f3f3050f7449c7816.css                                           4.84 kB
├ λ /lots/[lot]                                                              2.48 kB         589 kB
├ λ /orders                                                                  6.63 kB         540 kB
├   └ css/336d7638898c8a5511a0.css                                           3.07 kB
├ λ /orders/[order]                                                          5.65 kB         540 kB
├   └ css/38812b02ababb3ddf22b.css                                           3.19 kB
├ λ /previous-bids                                                           6.63 kB         546 kB
├   └ css/de29e3934626f3573435.css                                           3.33 kB
├ λ /products/[product]                                                      5.93 kB         587 kB
├ λ /register                                                                1.35 kB         577 kB
├   └ css/6ccc19a03fbdab0cc5db.css                                           527 B
├ λ /search                                                                  760 B           554 kB
├ ● /stores/[store]                                                          886 B           564 kB
├ ● /stores/[store]/categories/[category]                                    3.74 kB         557 kB
├   ├ /stores/test13/categories/a60ee00d-787f-4396-a683-2f1xx5bf6fa8
├   ├ /stores/test11/categories/a60ee00d-787f-4396-a683-2f1xx5bf6fa8
├   ├ /stores/test10/categories/a60ee00d-787f-4396-a683-2f1xx5bf6fa8
├   └ [+105 more paths]
└ ● /stores/[store]/products/[product]                                       4.84 kB         581 kB
    ├ /stores/cteststore1/products/0178712e-1bf7-4e98-a1e1-bb2cf5b8a19d
    ├ /stores/jteststore1/products/fd01a03d-9b5d-4ee1-ba36-e76868e76c54
    ├ /stores/jteststore1/products/953b8cca-77de-4152-8f1a-e723c1657bed
    └ [+2 more paths]
+ First Load JS shared by all                                                488 kB
  ├ chunks/0eceb729.90377c.js                                                1.99 kB
  ├ chunks/c662b23d.3f74cf.js                                                4.91 kB
  ├ chunks/commons.7ec134.js                                                 393 kB
  ├ chunks/framework.8a2450.js                                               45.6 kB
  ├ chunks/main.c2054e.js                                                    6.49 kB
  ├ chunks/pages/_app.48151c.js                                              32.6 kB
  ├ chunks/webpack.408a6a.js                                                 2.57 kB
  ├ css/67fa9f182ba93163802e.css                                             1.1 kB
  └ css/89915d84bebf5309ce70.css                                             2.43 kB

λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

Redirects

┌ source: /:path+/
├ destination: /:path+
└ permanent: true
.......
error:
--
974 | [Error: EEXIST: file already exists, mkdir '/codebuild/output/src600370309/src/.serverless_nextjs/default-lambda/pages'] {
975 | errno: -17,
976 | code: 'EEXIST',
977 | syscall: 'mkdir',
978 | path: '/codebuild/output/src600370309/src/.serverless_nextjs/default-lambda/pages'
979 | }
980 | ·[G·[?25h·[G·[J
981 | 216s › rockinui › Error: EEXIST: file already exists, mkdir '/codebuild/output/src600370309/src/.serverless_nextjs/default-lambda/pages'
982 |  
983 | ·[G·[?25h
984 | [Container] 2020/09/23 09:31:54 Command did not exit successfully npx serverless --debug exit status 1
985 | [Container] 2020/09/23 09:31:54 Phase complete: BUILD State: FAILED
986 | [Container] 2020/09/23 09:31:54 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npx serverless --debug. Reason: exit status 1

**Expected behavior**
Deployment should be successful.

- OS: aws/codebuild/standard:4.0 image
- nodejs: 12
- "next": "9.5.2" 
- @sls-next/serverless-component@1.17.0-alpha.16

**Comment by dphang** [comment]
Hm, I'm not too familiar with how AWS CodeBuild works, but this line should empty that `default-lambda` directory during the build: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/build.ts#L437. 

Not quite sure why it wouldn't work in this case. If you try removing that `.serverless_nextjs` before `serverless`, does it work?

**Comment by anupam-newgen** [comment]
Thanks for the reply, the problem was because of renaming of a certain file and its usage in the code.

pages/api/webmanifest.manifest.js file was renamed to pages/api/manifest.webmanifest.js
Usage: 
From 
import { manifest } from '../../pages/api/webmanifest'; 
to 
import { manifest } from '../../pages/api/manifest.webmanifest';

Once we reverted the change back it worked.
