### ISSUE TITLE
Error on first load getInitialProps

### ISSUE THREAD

**Issue by juancjara** [serverless-nextjs/serverless-next.js#625]
**Describe the bug**
The initial request to the API on page load shows an error, but navigating back to the page (using nextjs Link) makes the request work again, only the first-page load API request fails

**To Reproduce**
See the video attached: https://www.youtube.com/watch?v=63FDXwlIuEA
1. Refresh the browser or open URL directly (https://d3ejqmemi47nwv.cloudfront.net/)
2. Error appears on the screen

**Additional context**
Minimal repository to reproduce the error https://github.com/juancjara/servlerss-next-error
serverless.yml
```
testApp:
  component: "@sls-next/serverless-component@1.15.1"
```

**Error on first load**
```
{
    "message": "Request failed with status code 403",
    "name": "Error",
    "stack": "Error: Request failed with status code 403\n    at createError (/var/task/pages/index.js:3471:15)\n    at settle (/var/task/pages/index.js:4435:12)\n    at IncomingMessage.handleStreamEnd (/var/task/pages/index.js:9971:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
    "config": {
      "url": "https://v8ohknm-d01mhf.s3.amazonaws.com/api/hello",
      "method": "get",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "User-Agent": "axios/0.20.0"
      },
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1
    }
  }
```

**Comment by dphang** [comment]
I see you are using an older version 1.15.1, does the error repro on the latest version 1.17?

**Comment by juancjara** [comment]
Hi @dphang thanks for the quick response, I just updated on the same repo to version 1.17 (the repro repository now have the 1.17 version), this is the new URL for the deployment https://d1nwpaqhfn9se5.cloudfront.net , sadly the same issue keeps happening

**Comment by dphang** [comment]
Thanks, I'll have a look later this weekend.

**Comment by dphang** [comment]
So from above I still see it's trying to hit `https://v8ohknm-d01mhf.s3.amazonaws.com/api/hello` from within the SSR which is an S3 URL but it should be hitting the CloudFront distribution instead.

The relevant code: https://github.com/juancjara/servlerss-next-error/blob/master/pages/index.js#L29

So AWS by default doesn't forward Host header and it's set to the S3 origin host name instead. See here https://stackoverflow.com/questions/23197839/how-does-one-find-real-host-when-using-cloudfront.

You will need to forward the host header by specifying in the CloudFront custom configuration: https://github.com/serverless-nextjs/serverless-next.js#custom-cloudfront-configuration, then Host will point to the CF distribution (or your domain)

**Comment by juancjara** [comment]
@dphang thanks for the response, will try to add the custom CloudFront configuration, just curious if there a better way to make the API request without using 'next-absolute-url' package ? (https://github.com/juancjara/servlerss-next-error/blob/master/pages/index.js#L29) or the custom cloudfront config will be always required anyways?

**Comment by dphang** [comment]
Not familiar with `next-absolute-url` but it looks like it accesses `req.headers.host` so you could access that directly. Or you can just use an environment variable to store that or the CloudFront distribution URL.

I guess accessing the Host might be useful if you need to detect the specific domain name for some reason e.g for localization and want to separate traffic that way.

**Comment by juancjara** [comment]
@dphang thanks so much for your help, and for this awesome library, your suggestion worked 🍾 

will leave my serverless config here, if someone finds it useful

```
appCloudfront:
  component: "@sls-next/serverless-component@1.17.0"
  inputs:
    cloudfront:
      defaults:
        forward:
          headers:
            [
              CloudFront-Is-Desktop-Viewer,
              CloudFront-Is-Mobile-Viewer,
              CloudFront-Is-Tablet-Viewer,
              Host
            ]
```
