### ISSUE TITLE
RRSet with DNS name foo.vercel.com. is not permitted in zone next.com.

### ISSUE THREAD

**Issue by SarKurd** [serverless-nextjs/serverless-next.js#632]
### Describe the bug

Not sure if it's a bug

I have trouble adding domain from another AWS account, i have been setting it manually all this time, i get this error `RRSet with DNS name foo.vercel.com. is not permitted in zone next.com.`

Vercel and Next are just example

AWS Account 1: vercel.com
AWS Account 2: next.com (the account that i host the nextjs app)

Created ACM certificate from Account 2 with these details and approved
domain name: vercel.com
additional name: foo.vercel.com

serverless.yml
```yaml
   inputs:
        domain:
            - foo
            - vercel.com
```

when i'm deploying i get the above error, not sure what i can do.

Currently i set the CNAME and Certificate manually in AWS Console

If it's not a bug, is it possible to allow passing CNAME and Viewer certificate to cloudfront inputs?

### Versions

- OS/Environment: MacOS
- @sls-next/serverless-component version: 1.17

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Consider using the latest [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue.

**Comment by SarKurd** [comment]
I think i found out the issue, the domain is hosted on another account which means we can't create a DNS record for it, the DNS record should be manually created on that account

Serverless-nextjs's domain package doesn't check if the hosted zone is found and tries to create the DNS record which throws
the issue i believe is this line https://github.com/serverless-nextjs/serverless-next.js/blob/a011ad9646af6331b558fb3ce7063504f54877cd/packages/serverless-components/domain/serverless.js#L132 

Ee need to check if the hosted zone is not found then ask the user to manually create it as it's not possible to create it on this account

I double checked with Serverless components GA too and they are doing same check here: https://github.com/serverless-components/website/blob/bc3285cc584f7c0946848d03f1cd3e027613dce8/src/serverless.js#L129

I'm going to create a PR for it

**Comment by dphang** [comment]
Thanks! Yeah I was about to post that domain records in another account aren't detected correctly I am doing similar so I use Terraform to manage the domain records (e.g the app is deployed in account A and domain records are in account B, and I use Terraform to manage account B infrastructure).

If you create a PR to check this, I can help to review it.

**Comment by SarKurd** [comment]
That's exactly what we do too :D

Will try to create it now.

Thanks for replying
