### ISSUE TITLE
Add `handler` as an input option

### ISSUE THREAD

**Issue by emhagman** [serverless-nextjs/serverless-next.js#648]
Is it possible to add / does there already exist a way to set a custom handler via the Serverless component?

We are trying to setup https://docs.datadoghq.com/serverless/installation/nodejs/?tab=custom for our metrics and not being able to set a handler is preventing us from tracing our functions.

Essentially we'd like to use set the handler to `node_modules/datadog-lambda-js/dist/handler.handler` and then set the `default-handler` to the environment variable `DD_LAMBDA_HANDLER` like in the documentation in order to hook into the function.

Another example would be setting up Sentry: https://docs.sentry.io/platforms/node/guides/aws-lambda/ It seems like it would be impossible to use any 3rd party tools without something like this.

EDIT: Having looked at the code now, I am just curious if we could override https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/serverless-components/nextjs-component/src/component.ts#L373 via `inputs` ?

**Comment by luismanuel001** [comment]
@emhagman I'm currently in the middle of this same scenario, trying o integrate DD with this, could you by any chance share a sample of your setup?

**Comment by laerte-sousaneto** [comment]
@emhagman Also trying to integrate with DD and having no luck. Could you share an example?
