### ISSUE TITLE
Index.js (homepage) is blank without any errors

### ISSUE THREAD

**Issue by owboateng** [serverless-nextjs/serverless-next.js#650]
### Describe the bug
I am using "serverless-next.js": "^1.14.0" and I am wondering if anybody is facing this issue.
When I deploy my website, every page loads except the homepage (index.js). 
I get a complete blank page without any errors.
If I rename the index.js to another another name, then the path loads correctly.
I do not have any error logs to show since I get no error, only a blank page. Please help

### Versions

- OS/Environment: MacOs Mojave 10.14.6
- @sls-next/serverless-component version: serverless-next.js": "^1.14.0" 

### Additional context
Installing the latest version of serverless-next.js does not resolve the issue.

### Checklist

- [X] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ X] Consider using the latest [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue.

**Comment by dphang** [comment]
Looks like a new bug. A few questions:

1. Do you have any repro you can share? Without any logs I am not quite sure which part of the handler is failing...
2. If it's showing a blank page, what does the HTML response look like? Is index.js using `getServerSideProps`, `getInitialProps` or `getStaticProps`

**Comment by owboateng** [comment]
Thanks for the response.
With regards to your questions:
1. The repo is private so sorry I cannot share but the issue is if I replace the contents of the index.js with the sample NexjJS code:
`function HomePage() {
  return <div>Welcome to Next.js!</div>
}
export default HomePage`
I still get a blank page.

2. My code though is still using only `getInitialProps` because I have some dependencies that use it and therefore cannot mix with `getServerSideProps`. I have a custom `_app.js` which is like this:
`class MyApp extends App {

    render() {
        const { Component, pageProps } = this.props;

        return (
            <div>
                <Head>
                    <title>Title</title>
                </Head>
                <ReactNotification />
                <Component {...pageProps} />
            </div>
        );
    }
}

export default MyApp;`

One more comment: everything works fine in development mode (`yarn dev` and `yarn start`) all work good, except when I deploy and only the index page return completely blank. From the browser's dev console (Elements):
`<html>
    <head></head>
    <body></body>
 </html>`

Thank you very much

**Comment by dphang** [comment]
Thanks, I understand about the private code, just wanted to see if you can share as much code/repro if possible. I will try to repro the issue and take a look this week.

**Comment by owboateng** [comment]
Thank you. Looking forward to fix.

**Comment by owboateng** [comment]
@dphang Hi, do you have any pointers so far? Thank you.

**Comment by dphang** [comment]
I can't seem to reproduce the issue. Added this code for `index.tsx` and your `_app` and it loads fine for me.

```
function HomePage() {
  return <div>Welcome to Next.js!</div>;
}

HomePage.getInitialProps = (ctx: any) => {
  return { name: "serverless-next.js" };
};

export default HomePage;
```

So I'm not sure why it's only happening for `index` page. If you can, maybe you can try to build a custom handler and add logging statements around here: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/default-handler.ts#L363 to figure out if it's requiring the right file (`index.js`). It should have been requiring & rendering the right file, otherwise you would have gotten a 503 or 500.

You could even do it locally by requiring `index.js` generated file and calling `render(req, res)` on it so see if the same thing is happening locally vs. on the Lambda.

**Comment by owboateng** [comment]
@dphang Thanks for the response. So I followed the steps and I was able deploy and see the index.js page on my UAT (which has no custom domain). I tried the same approach with the production environment which has a custom domain and I got this error:
```
InconsistentQuantities: The specified quantity of Aliases (1) does not match the actual quantity supplied (2)
```
My serverless.yml looks like this:
```
prod_env:
  component: serverless-next.js
  inputs:
    bucketName: bucket-name
    domain: "example.com"
    domainType: "apex"
    memory: 1792
```
I however found out that I had updated my Nextjs version to the latest (9.5.2) which was causing the problem.
I have downgraded to Next version (9.4.4) and the problem is gone.

Is it stated somewhere in the documentation which versions of NextJS a particular serverless-nextjs version is compatible with. That will help a lot.
Thank you

**Comment by dphang** [comment]
Ah, I didn't realize actually you are using a pretty old version 1.14, we had issues with blank pages or 404s on index page, can you try 1.17. It should be compatible with Next.js 9.5.x. I had tested on the latest version and it worked (1.17.0)

Not sure about that error you are getting though, I would say to check the aliases on the CloudFront distribution and make sure they match with serverless.yml. I think sometimes if they were manually edited you will get validation errors like the above.

**Comment by dphang** [comment]
Also didn't notice it, you should use @sls-next/serverless-component, not serverless-next.js as that is deprecated...

**Comment by dphang** [comment]
Please try the latest @sls-next/serverless-component and open an issue if you are still facing problems. Thanks!
