### ISSUE TITLE
serverless-nextjs-component VS serverless-nextjs-plugin

### ISSUE THREAD

**Issue by rohanbam** [serverless-nextjs/serverless-next.js#664]
Hi, I would like to understand the differences in features between the old serverless-nextjs-plugin and the new serverless-nextjs-component. Specifically,

1. Can the new component based version be used with serverless plugins? I would like to use a few plugins from the plugins registry but I'm not sure whether it is possible with the new version.

2. Is the old plugin version compatible with nextjs v9?

3. I read that the old version uses cloudformation for provisioning aws resources and therefore suffers from certain limits. Is that still the case or has it been addressed in the old version?

**Comment by dphang** [comment]
1. This component is based on Serverless Components, not Serverless Framework (with various plugins), so I think it does not work well with those plugins. Also this component has custom logic to deploy to CloudFront/Lambda@Edge so I don't think it anyway work with plugins that expect a regular Lambda.
2. It officially just supports Next.js 8. I think I did get it to work with Next.js 9 but it was pretty buggy and most likely does not support many of Next 9's features.
3. Not sure. I don't think so as I think this was one of the reasons to create this component (and old plugin is no longer maintained), but @danielcondemarin may know more.

**Comment by GraemeAllanBryce** [comment]
I agree there is some confusion here as there are several elements being maintained and released in combination.

My understanding in that we should all be using 

`component: "@sls-next/serverless-component@{versionHere}`

but I have also had the same result when using

`component: serverless-next.js@{differentVersionHere}`

importantly the versions of the component and fo the more simple serverless-next.js are not in sync but both appear to be maintained via the same codebase and I wonder if they are just different references to the same code?

I do understand that the plugin - which is neither of the above - is indeed something different and does not share the same capabilities.

One other note on the subject is a suggestion to firstly for @danielcondemarin to perhaps explain the above in the readme and also to add t the readme that the component should be yarn or npm installed as a DEVELOPMENT dependancy which may not be clear to all.

People also need to heed the note already in the docs about reading the version of the doc that corresponds to the version you have installed!  This is most easily achieved by clicking the brach button in GitHub, switching to the TAGS tab and browsing to the appropriate version.  Now you are reading the appropriate readme.

Once you master it - "it just works" but like everything, it's only obvious AFTER you know how :-)

**Comment by rohanbam** [comment]
Thanks for the clarification.

**Comment by dphang** [comment]
@GraemeAllanBryce so that `serverless-next.js` has not been published to in over 3 months, I wasn't involved in that but I might have been the old version of the current serverless component (not plugin), I believe @danielcondemarin had reorganized the code and split into packages and moved them under a new org `@sls-next`
