### ISSUE TITLE
Redirects stopped working (now returning 404)

### ISSUE THREAD

**Issue by tyler-ground** [serverless-nextjs/serverless-next.js#668]
Follow-up to a problem in #587   .  I reduced the redirects on a test deployment to just a single case and attached the routes-manifest.json and the api-lambda index.js (not sure it matters which is attached?).

### Describe the bug
Redirects are returning 404s

### Actual behavior
Navigate to redirect source and get a 404

### Expected behavior
The redirect occurs to the destination

### Steps to reproduce
1.  Create a redirect in next.config.js
2.  Deploy
3.  Navigate to redirect

### Versions
1.  "next": "9.5.3"
2.  "@sls-next/serverless-component": "1.18.0-alpha.4"
3.  "requires": {
        "@serverless/aws-s3": "^4.2.0",
        "@serverless/core": "^1.1.2",
        "@sls-next/aws-cloudfront": "1.3.0-alpha.1",
        "@sls-next/aws-lambda": "1.0.3-alpha.0",
        "@sls-next/cloudfront": "1.0.4-alpha.0",
        "@sls-next/domain": "1.1.0-alpha.2",
        "@sls-next/lambda-at-edge": "1.7.0-alpha.6",
        "@sls-next/next-aws-cloudfront": "1.5.1-alpha.0",
        "@sls-next/s3-static-assets": "1.3.1-alpha.0",
        "aws-sdk": "^2.702.0",
        "fs-extra": "^9.0.1"
      },

### Additional context
Per @dphang 's request

Attached:
[routes-manifest.json.zip](https://github.com/serverless-nextjs/serverless-next.js/files/5366871/routes-manifest.json.zip)
[index.js.zip](https://github.com/serverless-nextjs/serverless-next.js/files/5366879/index.js.zip)

**Comment by dphang** [comment]
Probably need the default handler as well since your routes-manifest has redirects from page routes

But anyway, I also checked the API-handler you provided and it doesn't have the redirect logic that should be in 1.18.0-alpha.4:

https://github.com/serverless-nextjs/serverless-next.js/blob/%40sls-next/serverless-component%401.18.0-alpha.4/packages/libs/lambda-at-edge/src/api-handler.ts#L66-L74

Is this a problem only in your CI/CD setup or can you repro locally as well? Is it possible to clear the cache or anything? As mentioned before, when I use 1.18.0-alpha.4, I can see the handlers have redirect code. Unsure why you're getting an old version.

**Comment by tyler-ground** [comment]
It's deploying through github actions; I removed all the caching steps last week when trying to debug it.  It starts from an empty container.  I'll pull it down when I am at my desk later today and do a local deployment to compare the output.

Interestingly, I generally hop on features as soon as they're available and this would be the first time there was a bad npm install (if that's the case).

However, if this sounds like a bad environment we could close the ticket and I'll re-open if I can confirm the repro locally.

**Comment by dphang** [comment]
Ok, I will check if I can repro in GitHub Actions. I'm also using the same for my apps but I don't think I had issues. Maybe GitHub Actions is doing something strange or there are some gotchas (it's pretty new in terms of CI/CD so I wouldn't be surprised).

**Comment by tyler-ground** [comment]
I'd hold off until I get a local repro just so it doesn't waste your time.

**Comment by tyler-ground** [comment]
@dphang I got around to a local deploy and the locally generated index.js is identical to the one generated by github actions.

So... somehow an old index.js is ending up in .serverless_next/?  How are these generated?

**Comment by tyler-ground** [comment]
Got an idea!  Does the serverless.yml ignore the package.json?  Checking

**Comment by tyler-ground** [comment]
omg that's the issue.  The package.json is ignored and the component line in the yml file is used for deployments.

**Comment by dphang** [comment]
Yes, it uses the version specified in serverless.yml. You need to pin it there. I am guessing it stopped working because I moved `latest` tag to the latest stable version rather than the alpha versions.

**Comment by tyler-ground** [comment]
yeah that was it!  I am generating different files now.

**Comment by tyler-ground** [comment]
wouldn't be surprised if this was @justingshreve's problem too.

**Comment by tyler-ground** [comment]
I would initially say that multiple sources of truth is a design error, but I can see serverless viewing these as completely independent systems.

**Comment by dphang** [comment]
Yeah, I thought this was clarified before somewhere but apparently the README is not as clear as it should be. I updated it in bold just in case: https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md#getting-started

**Comment by tyler-ground** [comment]
It likely was clarified sometime after I started using this lib. (I've been using it for a while :) ).  When this came out I went looking and there was very little documentation on how serverless components work, they quickly replaced it with a new version so it may be they were not happy with it.
