### ISSUE TITLE
Rewrites with conflicting paths

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#696]
This is continued from the discussion in https://github.com/serverless-nextjs/serverless-next.js/issues/646

Reproduction here: https://github.com/patricktyndall/sls-next-bug-reproduction

### Describe the bug
When rewrite paths conflict with /public or static routes in /pages, things start breaking.

### Actual behavior
/dynamic-1, /login, and /my-test-asset.txt break

### Expected behavior
/dynamic-1, /login, and /my-test-asset.txt don't break

### Steps to reproduce
Deploy using `serverless`

### Versions
- OS/Environment: MacOs
- @sls-next/serverless-component version: `@sls-next/serverless-component@1.18.0-alpha.13`
- Next.js version: `9.5.5`

### Additional context
This is important because it prevents existing next.js apps from using this component, as it breaks compatibility.

I added comments in next.config.js on what happens when you change the rewrites.

**Comment by dphang** [comment]
Thanks for the repro, I'll take a look.

Basically we should follow Next.js:

> Rewrites are not able to override public files or routes in the pages directory as these have higher priority than rewrites. For example, if you have pages/index.js you are not able to rewrite / to another location unless you rename the pages/index.js file.

Right now I didn't check also didn't check for the no-op rewrite:

```js
module.exports = {
  async rewrites() {
    return [
      // we need to define a no-op rewrite to trigger checking
      // all pages/static files before we attempt proxying
      {
        source: '/:path*',
        destination: '/:path*',
      },
      {
        source: '/:path*',
        destination: `https://custom-routes-proxying-endpoint.vercel.app/:path*`,
      },
    ]
  },
}
```

Though external rewrites are more involved to implement, we can implement the no-op rewrite too.

**Comment by patricktyndall** [comment]
Definitely agree on keeping compat with Next.

I view this bug as violating your quoted snippet -- rewrites should not be able to affect other higher "priority" routes (as is observed using `next start`).

> Though external rewrites are more involved to implement, we can implement the no-op rewrite too.

I want to clarify that this issue is not specific to external rewrites. It's also not specific to the no-op rewrite. If you view my example's `next.config.js`, I observe buggy behaviors even when not using the no-op rewrite.

**Comment by dphang** [comment]
Yep, I do note that - just was trying to clarify how it's implemented right now - it just takes the first matching rewrite and tries to rewrite it (it doesn't know about no-ops, doesn't know about existing non-dynamic pages or static/public files). 

I did test the repro with the dev server and confirm your findings. Even with or without the no-op rewrite, it looks like next also doesn't rewrite non-dynamic routes such as `/login` (so `/:path*` to `/content/:path` is not going to rewrite `/login`, as `/login` has priority).

However, for dynamic routes like `/content/dynamic-1`, the no-op rewrite prevents those from being rewritten.

I think this has helped cleared things out. So looks like there are two things to fix:

1. Public/static files and non-dynamic pages should always prioritized over rewrites, i.e they will never be rewritten.
2. No-op rewrite should be respected to try to match to any existing route (including non-dynamic and dynamic routes)

**Comment by patricktyndall** [comment]
Great. I don't personally think no-op rewrite is a huge priority. I don't think my use case should require it, provided the other behaviors are correct. It was only added as that's how I'm working around the other issues with `serverless-next.js`.

**Comment by dphang** [comment]
Fixed (1) above and released in:  @sls-next/serverless-component@1.18.0-alpha.14. Let me know if this works for your use case.

For (2) I think let's track it separately. I'll update docs and/or open new issue for that.

**Comment by patricktyndall** [comment]
Hey @dphang did you consider api route paths in this handling? Everything else is fixed, but I'm now getting 404 from /api/preview.

Thanks for work so far.

**Comment by dphang** [comment]
Sure, I'll fix that tonight, I just updated default handler for now

**Comment by dphang** [comment]
Fixed here: https://github.com/serverless-nextjs/serverless-next.js/pull/698 and published in latest alpha

**Comment by patricktyndall** [comment]
I'm now getting 503s when accessing routes on preview mode (works fine in non-preview). I have updated the reproduction repo for this. You need to visit the api route to enable preview mode ie `/api/preview?secret=96ffe7d4-2ad2-4699-b64a-a5f74750962e&slug=/dynamic-1`

My logs:
![image](https://user-images.githubusercontent.com/10466863/96687693-3e633d00-134e-11eb-83a9-a8708ecfe64e.png)

**Comment by dphang** [comment]
Thanks, perhaps you can create a new issue since this is not related to rewrites.

Your logs aren't showing any error, but it should for a 503 (usually it's because Lambda threw an exception). I was able to find a log when accessing index and login pges on the repro, it seems to be trying to require `pages/404.html`.

```
{
    "errorType": "Error",
    "errorMessage": "Cannot find module './pages/404.html'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/index.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module './pages/404.html'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:841:27)",
        "    at Module.require (internal/modules/cjs/loader.js:1025:19)",
        "    at require (internal/modules/cjs/helpers.js:72:18)",
        "    at handleOriginRequest (/var/task/index.js:6101:16)",
        "    at Runtime.handler$1 [as handler] (/var/task/index.js:5957:26)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

I don't use preview mode so it will take some time to debug. but @thchia added this, maybe he knows why it is failing? On a cursory look, it seems like it's because `login` and `index` route in your repro does not have `getStaticPaths` so the router is not matching it in nonDynamic SSR, there is no JS to render for preview mode, and hence returns the 404 page. Here's the build manifest.

```json
{
  "buildId": "d7SqWJ6ooP3eWCEq8l1FP",
  "logLambdaExecutionTimes": false,
  "pages": {
    "ssr": {
      "dynamic": {
        "/content/:all*": {
          "file": "pages/content/[...all].js",
          "regex": "^\\/content(?:\\/((?:[^\\/#\\?]+?)(?:\\/(?:[^\\/#\\?]+?))*))?[\\/#\\?]?$"
        }
      },
      "nonDynamic": {
        "/_error": "pages/_error.js"
      }
    },
    "html": {
      "dynamic": {},
      "nonDynamic": {
        "/": "pages/index.html",
        "/login": "pages/login.html",
        "/404": "pages/404.html"
      }
    }
  },
  "publicFiles": {
    "/my-test-asset.txt": "my-test-asset.txt"
  },
  "trailingSlash": false,
  "domainRedirects": {}
}
```

Router: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/default-handler.ts#L165

A workaround is to add `getStaticProps` for those routes (`login` and `index`) so that the Lambda bundle includes the JS files needed to render at. But we should still fix it so those HTML pages without any props get rendered without 503.

**Comment by dphang** [comment]
Anyway I tested and it should be fixed in https://github.com/serverless-nextjs/serverless-next.js/pull/701. Please try to open a a new issue for separate bugs so it can be better tracked :)

**Comment by dphang** [comment]
Fixed and released in latest alpha.
