### ISSUE TITLE
Aliases are overwritten when not declared in `serverless.yml`

### ISSUE THREAD

**Issue by LuisFros** [serverless-nextjs/serverless-next.js#703]
Current version: `'@sls-next/serverless-component@1.18.0-alpha.13`
**Is your feature request related to a problem? Please describe.**
When updating a distribution, the `aliases` or CNAMEs get overwritten. This is a problem in the latest version starting from this PR: https://github.com/serverless-nextjs/serverless-next.js/pull/654

**Describe the solution you'd like**
I would like the aliases field to not be overwritten when existing cloudfront distribution already has values that are not empty and `aliases` field is not declared in `serverless.yml`

**Describe alternatives you've considered**
Storing aliases as env variable during CI/CD

**Additional context**
Here could be checked `params.DistributionConfig.Aliases !== null`
https://github.com/serverless-nextjs/serverless-next.js/blob/ef2d596d5a39af2009f48b39742c2aa269f103c0/packages/serverless-components/aws-cloudfront/lib/index.js#L121

**Comment by dphang** [comment]
Thanks for pointing out. Looks like aliases when undefined will get overridden to default value of [] which will be destructive to existing aliases. We should keep inputs non-destructive (similar to terraform) as much as possible, i.e if not specified it should not try to update that configuration. Will fix it tonight.
