### ISSUE TITLE
CI friendly logging

### ISSUE THREAD

**Issue by vicary** [serverless-nextjs/serverless-next.js#706]
**Is your feature request related to a problem? Please describe.**
The deploy timer is nice when working with normal shells, but CI logs, or outputs piped to a file in general does not play nice with the `/r` line replacement.

**Describe the solution you'd like**
I would like the deployment script to either expose a CLI option (e.g. `--ci`), or read a commonly used environment variable `CI=true`.

**Describe alternatives you've considered**
None exists, we have to manually scroll through 10k lines if it ends up with errors.

**Additional context**
![image](https://user-images.githubusercontent.com/85772/96835425-24bd1500-1476-11eb-838d-1bec3c442140.png)

**Comment by dphang** [comment]
Yes I've seen this too, but assumed this was an issue from the Serverless Framework, not this component, not sure we can do anything about it unless we change how we deploy or use new Serverless component version. @danielcondemarin any ideas?

**Comment by danielcondemarin** [comment]
> Yes I've seen this too, but assumed this was an issue from the Serverless Framework, not this component, not sure we can do anything about it unless we change how we deploy or use new Serverless component version. @danielcondemarin any ideas?

Right now I don't think there is anything we can do. My best guess is when we update to serverless components GA then this shouldn't be an issue, and if it is, then we'd close this anyway and raise it on the [components core repo](https://github.com/serverless/components). Let's keep it open here for now 👍

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I am also having the same problem, I created an issue in https://github.com/serverless/components repo.

https://github.com/serverless/components/issues/834

**Comment by dphang** [comment]
Fixed by this: https://github.com/serverless-nextjs/serverless-next.js/pull/1658. The above issue has a PR out for the GA components, but we are still using deprecated `@serverless/cli` so that one needed to be patched in a similar manner. You should be able to run the patched version by deploying using `npx serverless-patched`. Let me know if there are any issues.

**Comment by herrlegno** [comment]
Will running the patched version the final solution? as [serverless/components#834](https://github.com/serverless/components/issues/834) and [PR](https://github.com/serverless/components/pull/995) are now closed?

Thank you.
