### ISSUE TITLE
Monitoring Lambda funtion.

### ISSUE THREAD

**Issue by alan345** [serverless-nextjs/serverless-next.js#712]
I have a traffic of ~500 users per day.
The website take sometimes 6 seconds or 4 seconds or 2 seconds to show.  (I suspect it is because of the cold start)
I am trying to get some monitoring data in AWS to dive more.
In AWS, there are no data in the tab `monitoring`

![image](https://user-images.githubusercontent.com/15246526/97072724-ca8c9300-15e0-11eb-8a8a-df326fa7fabe.png)

Any idea why?

**Comment by dphang** [comment]
Lambda@Edge is globally replicated so logs/metrics will not be in the usual Lambda console for the function (created in us-east-1). You need to check CloudFront monitoring: https://console.aws.amazon.com/cloudfront/v2/home#/monitoring and find your Lambda@Edge function. It will show the Lambda@Edge invocation metrics there.

It will show something like this, broken up into CloudFront regions:

![Screen Shot 2020-10-24 at 9 28 30 AM](https://user-images.githubusercontent.com/3221524/97086944-4c79bd80-15db-11eb-8954-1ebd03a4f0ad.png)

Lambda@Edge logs are also in CloudWatch region closest to the CloudFront viewer. Ex: If I'm accessing the web app from Seattle, they will be in Oregon (us-west-2).

**Comment by alan345** [comment]
Thanks @dphang !
Found it!
