### ISSUE TITLE
503 Cloudfront errors on first load after deployment 

### ISSUE THREAD

**Issue by dmsolutionz** [serverless-nextjs/serverless-next.js#713]
### Describe the bug
After each successful deployment we experience a 503 error when trying to access the cloudfront domain / or configured domain. The error disappears after you reload once or twice, this leads me to think its a caching issue or something that is misconfigured. 

### Actual behaviour
When loading up the app after deployment you see a 503 page.

### Expected behaviour
When loading up the app after deployment you should see the site (200).

### Steps to reproduce
1. Create a large nextjs application, minimum 25 pages under /pages/, include a few heavy libraries like material-ui etc...
2. Build the site using the following config 
```cuckoo:
  component: '@sls-next/serverless-component@1.18.0-alpha.19'
  memory: 1024
  inputs:
    useServerlessTraceTarget: true
    minifyHandlers: true
    defaultLambda: 20
plugins:
  - serverless-dotenv-plugin
```

### Screenshots/Code/Logs
Hard to determine where these would live, please advise.

### Versions
@sls-next/serverless-component@1.18.0-alpha.19
NextJS
- OS/Environment:
- @sls-next/serverless-component version:
- Next.js version: 9.4.2

**Comment by dphang** [comment]
I think I would need more information for debug it - if you are getting a 503 with a message like: "The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions" Please check the Lambda logs in the CloudWatch region closest to where you accessed it from - it should have an error stacktrace.

**Comment by arelaxend** [comment]
Hi, I encounter this several times. I remove the stack `serverless remove`. Also remove `.next`, `.serverless` and `.serverless_nextjs` folder. Then I `npx serverless` and it works.

Looking in the console we can see that it generates new ids. When you upgrade your `serverless.yml` without deleting those folders, the ids have the same values..

**Comment by marcfielding1** [comment]
We get this when we do lots of quick deployments - we're prerendering 20,000 pages currently, and if we have successive quick merges into develop it seems to take a very long time for everything to start working properly, for instance, we were getting 503's on the .json associated with the pages for about a day then suddenly it popped back.

I have noticed that if you create 5 invalidations in CloudFront they take a huge amount of time to go through, I dunno what's going on behind the scenes, 1 is always done pretty quick, concurrent ones seem to go a bit nuts.

I'm not sure why it takes that long, we avoid it now by not running deployments on merge, we test on merge and then deploy every three hours.

**Comment by dphang** [comment]
Yes I think Lambda@Edge is taking some time to propagate, maybe there is mismatch between S3 assets (although now the assets of the last 2 versions of pages/data files/etc are always versioned properly), cache invalidation, and Lambda@Edge versions. And you are accessing the app while these are in-flight.

It might be able to be solved if deploy this way:

* Deploy the application, which updates S3 and Lambda@Edge. Disable the automatic cache invalidation
* Wait for CloudFront to go from In Progress -> Ready. It might take a few minutes but you are certain the Lambda@Edge is now on the latest version at all CloudFront POPs
* Invalidate caches as needed

Then there won't be any old versions of pages that may have been cached BEFORE Lambda@Edge is fully deployed, etc. which may lead to errors.

Hopefully this and/or any recent updates should fix the issue. Please open a new issue if you still find any related issue. Thanks!
