### ISSUE TITLE
Decouple lambda-at-edge deploy logic from nextjs-component

### ISSUE THREAD

**Issue by dphang** [serverless-nextjs/serverless-next.js#715]
Currently, the Lambda@Edge deploy logic is actually coupled into `nextjs-component`.

As a first step to making this package more generic and extensible for supporting other serverless platforms (e.g Lambda, Cloudflare), all Lambda@Edge logic should live in the `lambda-at-edge` package. It would be a plugin and implement two features:

* Build (**already done**): builds artifacts for deploying to Lambda@Edge. Ex: default-handler, api-handler, assets (building of assets for S3 was recently decoupled from component to lambda-at-edge).
* Deploy: we need to move all deployment logic currently from `nextjs-component` into `lambda-at-edge`. Currently, it's doing all the CloudFront, S3 and Lambda deployment work, but this should really live in `lambda-at-edge`. Of course, if there's shared logic (e.g S3 upload logic may be same for Lambda vs. Lambda@Edge), then we'll put those in the respective internal packages.

As part of this, we can define a standard interface that all plugins should implement.

Afterwards, `nextjs-component` itself will be very lightweight and simply call the plugin to use based on inputs (e.g lambda-at-edge for now, and others later).

I also suggest to rename `lambda-at-edge` to `lambda-at-edge-plugin` to be clearer later on.

**Comment by danielcondemarin** [comment]
Thanks for kicking this off 🙌  

When bringing over the deployment logic, could be worth thinking of how this would work if we supported CDK or plain CloudFormation in future. in other words, how would we use the lambda-at-edge-plugin with CloudFormation instead of aws-sdk API calls. 
Good point around shared logic and reuse. The build step is deliberately kept as cloud agnostic as possible for this reason with the exception of the handlers which are Lambda@Edge specific. 

Do you have an interface in mind already for the plugins?

**Comment by dphang** [comment]
@danielcondemarin thanks for the thoughts.

Yes, build should be cloud agnostic as possible, though the build itself should be optimized for each platform. I think mostly the shared core logic (serverless Next.js routing/rendering) should cloud/platform-agnostic. For example, it doesn't know to use AWS S3 for retrieving static pages. For that, it would just call a storage accessor interface (which can later be replaced e.g by Rollup.js by the actual implementation when bundling).

Then each plugin should implement platform-specific logic to make it work with that. Then it can use Rollup.js to build (bundle the core logic + platform's compatibility layer + additional optimizations) and deploy (call AWS CDK/SDK, etc.). Here are some examples of how it'd look like for Lambda@Edge vs. Cloudflare workers, for example:

Lambda@Edge: it requires translating to/from CloudFront events and storage backend is S3 (though theoretically anything else can be used).

* Build will use Rollup.js to bundle core logic + Lambda@Edge/CloudFront translation/compatibility layer + S3 storage accessor (the concrete implementation for the storage accessor interface - there are plugins like Rollup.js replace plugin that can be used: https://github.com/rollup/plugins) into a handler.
* Build copies all JS pages along with above handler into `default-lambda` and `api-lambda` directory.
* Apply any optimizations if needed, e.g minifying handler code, removing dead code (e.g if redirects are not used, that we can use the Rollup.js replace plugin to get rid of that block).
* Build copies assets into assets directory suitable to upload to S3 (or possibly other storage backends).

Finally, deploy phase of the plugin will then call Lambda, CloudFront, S3, etc. to deploy the above build artifacts.

Cloudflare workers: it requires a single JS script, can't use eval statements, etc.

* Build will use Rollup.js to bundle core logic + Cloudflare workers compatibility layer + storage accessor (Cloudflare Workers KV, AWS S3, etc.) into the initial entry point.
* Apply any needed Cloudflare optimizations, using Rollup.js. (A) bundle all pages JS + entry point above into a single JS file. (B) Replace `eval` statements (as Cloudflare doesn't allow it), (C) minify the bundle to avoid going past Cloudflare workers 1 MB compressed limit.
* Build copies assets into assets directory suitable to upload to S3/Cloudflare Workers KV

**Comment by dphang** [comment]
For the interface, I think each plugin should accept a set of `inputs` specific to that plugin (e.g lambda@edge would accept the current set of inputs as they are all for it) in the constructor for that plugin and could implement two methods in a common plugin interface:

* Build: uses the inputs given to build all build artifacts into the `.serverless_nextjs` directory for a given platform. This step can also apply any optimizations (e.g minification, etc.), run additional custom user build functions, build from scratch (e.g custom user handlers) etc. to make it more flexible.
* Deploy: uses the inputs given to deploy all build artifacts from the `.serverless_nextjs` directory to a given platform. It uploads all assets, serverless function code, and configures other services to make it work.

To support a new platform, one would:

1.  Create a new package called `@sls-next/[platform-name]-plugin` and implement the above interface. All logic to build and deploy is then contained in that plugin, along with tests.
2. Add this to list of platforms supported by the top-level NextJS component (can be manual or we can just auto-detect all platform plugins).
3. Ideally, add e2e tests for the new platform. Right now the e2e tests are mostly platform-agnostic (save for some checks for CloudFront cache header, and the deployment-ready script that is CloudFront specific) so with a few minor additions and the GitHub strategy matrix, it could be quite straightforward.

**Comment by dphang** [comment]
RE: CloudFormation/CDK/etc. I think it is quite relevant, though more a **Deploy** implementation detail. But yes, I agree we should try to standardize on it so it's more maintainable. Probably when writing a new plugin, the **Build** would be completely custom code (as it doesn't use any IaC tools, it just packages all assets/functions).

However, if we use something like CDK, we could enforce all **Deploy** implementations use the CDK to make it more maintainable overall. As an aside: CDK is from by AWS so they would be well-supported for AWS platforms, but maybe others may not be as well supported.

I would prefer something more neutral like Terraform. Perhaps [CDK for Terraform](https://www.hashicorp.com/blog/cdk-for-terraform-enabling-python-and-typescript-support) might also work, though I need to do more research.

**Comment by danielcondemarin** [comment]
Thanks for the thought out reply, overall sounds very sensible to me 🙂   

> For example, it doesn't know to use AWS S3 for retrieving static pages. For that, it would just call a storage accessor interface (which can later be replaced e.g by Rollup.js by the actual implementation when bundling).

This would be quite nice 💯

The proposal to introduce a new platform sounds really good as well. Possibly an easy first candidate would be Lambda + API Gateway. 

> As an aside: since CDK is from AWS, it would be well-supported for AWS platforms, but maybe others may not be as well supported.
I used CDK as an example. I was trying to convey it would be nice if we supported other deployment / IaC frameworks such as CDK or Terraform.

> However, if we use something like CDK, we could enforce all Deploy implementations use the CDK to make it more maintainable overall.

There is an interesting trade-off to consider here. Whilst it makes it easier for us to maintain, it means enforcing a particular way of deploying to users. For example, some people will use CDK, others Terraform etc. Ideally `serverless-next.js` would provide different *entry points* for each. That way it integrates nicely with existing tools folks already use for their IaC projects. 

CDK for Terraform sounds quite interesting and potentially a really good fit for this project. 👍

**Comment by dphang** [comment]
> Thanks for the thought out reply, overall sounds very sensible to me 🙂
> 
> > For example, it doesn't know to use AWS S3 for retrieving static pages. For that, it would just call a storage accessor interface (which can later be replaced e.g by Rollup.js by the actual implementation when bundling).
> 
> This would be quite nice 💯
> 
> The proposal to introduce a new platform sounds really good as well. Possibly an easy first candidate would be Lambda + API Gateway.
> 
> > As an aside: since CDK is from AWS, it would be well-supported for AWS platforms, but maybe others may not be as well supported.
> 
> I used CDK as an example. I was trying to convey it would be nice if we supported other deployment / IaC frameworks such as CDK or Terraform.
> 
> > However, if we use something like CDK, we could enforce all Deploy implementations use the CDK to make it more maintainable overall.
> 
> There is an interesting trade-off to consider here. Whilst it makes it easier for us to maintain, it means enforcing a particular way of deploying to users. For example, some people will use CDK, others Terraform etc. Ideally `serverless-next.js` would provide different _entry points_ for each. That way it integrates nicely with existing tools folks already use for their IaC projects.
> 
> CDK for Terraform sounds quite interesting and potentially a really good fit for this project. 👍

Yeah, good point about not enforcing a particular way of deploying. I was mostly referring to enforcing it for first party implementations (i.e the built-in deployment in `serverless-next.js`) to have consistency and maintainability.

Of course users can deploy themselves (e.g right now there is a `deploy` input they can set to false) or with this way, we could potentially allow user to bring their own implementation of `deploy` which uses their own IaC tools.

If we go with CDK for Terraform, do we need to remain on Serverless in that case? I think CDK/Terraform provides way more flexibility in infrastructure management, and already a lot of the packages we've imported into the project or have our own logic to deploy. I think I only saw that we are using the `@serverless/aws-s3` module from Serverless itself.

**Comment by danielcondemarin** [comment]
> If we go with CDK for Terraform, do we need to remain on Serverless in that case? 

We could possibly remove the need for Serverless whilst still supporting serverless components via https://github.com/serverless-components/aws-cloudformation 🤩 Tempting.

**Comment by dphang** [comment]
Closing this as we are reworking deployment logic - not sure if we will continue to use serverless components for deploy due to its fragility
