### ISSUE TITLE
Add Renovate to update dependencies + pin dependencies

### ISSUE THREAD

**Issue by dphang** [serverless-nextjs/serverless-next.js#716]
**Describe the solution you'd like**
Right now dependencies of this project are not being updated automatically (perhaps it has in the past?). I suggest to use Renovate to keep dependencies updated.

This will ensure we keep dependencies more secure, we get performance improvements, etc. Since we have good unit and end-to-end tests coverage now, I believe they can be updated and even be merged automatically, safely, and silently using Renovate's branch automerge strategy.

Additionally, this would allow us to pin all dependencies instead of using a caret range (which could lead to bugs/inconsistent behavior for users in case a dependency has a patch version that breaks it.) - and they'll be automatically updated.

**Describe alternatives you've considered**
We could use Dependabot which is built into GitHub, but AFAIK it actually isn't as configurable as Renovate (in particular, the branch automerge - so you'd get a bunch of PR noise for dependency updates). And from anecdotal evidence I found while researching, apparently it doesn't work as well as Renovate for monorepos.

**Comment by danielcondemarin** [comment]
> perhaps it has in the past?

I can confirm it didn't in the past. It has been manual so far 🙂 Definitely up for automating.

**Comment by dphang** [comment]
Sure, I can add Renovate and see how it goes - probably a weekly cadence will be good for now.
