### ISSUE TITLE
"CNAMEAlreadyExists: One of more of the CNAMEs you provided are already associated with a different resource." Error 

### ISSUE THREAD

**Issue by grantmontgomery** [serverless-nextjs/serverless-next.js#729]
I'm trying to attach a custom domain which is registered on Route 53 to the serverless.yml file. Right now the .yml file looks like this.

`myNextApplication:

component: "@sls-next/serverless-component@1.17.0"

inputs:

domain: "mycustomdomain.com"
`

When I run npx serverless though I get this error. "CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource." The only Cloudfront distribution I have is the one automatically created by Serverless and this domain is associated with no other services. The last Template.myNextApplication.Domain.json file also points to the correct distributionID and url of the Cloudfront distribution. The only records I have for the domain are NS and SOA records going to the hostmaster and awsdns. I also read in your documentation that attaching this domain name to .yml file automatically creates an SSL certificate and records which point to this distribution, but there are no new records or certificates created on AWS. What can I do to troubleshoot this.

**Comment by dphang** [comment]
Usually this happens as the same CNAME cannot be attached to multiple resources in AWS. Please see here: https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

I think you should try to check if there are any other distributions/resources that may be already using that domain, it may be in another AWS account as well. Also, API gateway inherently creates a CloudFront distribution, but it may not be as easy to see (see: https://github.com/serverless-nextjs/serverless-next.js/issues/693). Hope it helps.

**Comment by grantmontgomery** [comment]
Found out that the domain was being used in an old AWS account with an Amplify project. Deleted that app and now deploying serverless works for creating the domain. Thanks for the help.
