### ISSUE TITLE
Error adding a custom ACM certificate for cloudfront distribution

### ISSUE THREAD

**Issue by lemoncrafter** [serverless-nextjs/serverless-next.js#730]
Hi, I don't know if this is really a bug, and I apologize if this is not the correct place to ask this question.

I am trying to add an ACM certificate to the cloudfront config in the serverless.yml file and I am getting an error: Error: CloudFront input failed validation. Could not find next.js pages for "certificateArn"
I'm using version 1.18.0-alpha.22

I have a certificate with a wildcard I would like to use and also I would like to add aliases to the distribution.
I've already gone through the docs (https://www.serverless.com/plugins/serverless-nextjs-plugin) and found that it shoud be possible.
I've seen this (https://github.com/serverless-nextjs/serverless-next.js/issues/491) issue here and it says that it is already fixed.

But I couldn't figure out the correct setup. I've tried everything stated in the aforementioned issue.

My current setup:

inputs:
  cloudfront:
    aliases: ["${subDomain}.${domain}"]
    certificateArn: ${certificate}

If I remove certificateArn I get a cloudfront error because of the missing certificate but it stops complaining about the yml template:
InvalidViewerCertificate: To add an alternate domain name (CNAME) to a CloudFront distribution, you must attach a trusted certificate that validates your authorization to use the domain name. For more details, see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-requirements

What is the correct way of doing this? I wasn't able to find an example

Thanks a lot for this plugin and for any help anyone can provide

**Comment by dphang** [comment]
Yeah, so I don't use `domain` input, but `aliases` should go in `cloudfront`, and `certificateArn` is a top-level input (not in `cloudfront`, just under `inputs`). That should be why you are are getting the error:

```
CloudFront input failed validation. Could not find next.js pages for "certificateArn"
```

because any other input in CloudFront is treated as a cache behavior for a page. Probably I should update that message to be a little more helpful.

Also, do note that the `certificateArn` is actually tied with the `domain` subcomponent.

I am also adding another `cloudfront` input `certificate` to properly specify a certificate independent of the `domain` component, as technically you do not need to use `domain` component (it can be managed externally).

**Comment by lemoncrafter** [comment]
Thanks for the answer!

I have tried adding the domain, but I belive it is ignoring the certificate setting. I am running in debug mode and I can see that is trying to select one.

> DEBUG ─ Searching for an AWS ACM Certificate based on the domain: ......

As I have many subdomains it is not picking the right one (the one I am trying to set) and then failing with the message: "The certificate that is attached to your distribution doesn't cover the alternate domain name (CNAME) that you're trying to add. For more details..."

My current setup:

`inputs:
    useServerlessTraceTarget: true
    cloudfront:
      defaults:
        ttl: 120
    priceClass: "PriceClass_100"
    certificateArn: ${certificate}
    aliases: ["ww3.${domain}"]
    domain: ["${subDomain}", "${domain}"]
    bucketName: "${stage}-assets"`

Is that template well stated? Sorry if it is not.
I have added the ww3 alias to ensure that it will pick the certificate with the wildcard.

**Comment by dphang** [comment]
You can use markdown to display the YML nicely. Use the ```yml and ``` to open and close code blocks

I believe the input should look like this:

```yml
inputs:
  cloudfront:
    aliases: ["www.example.com"]
  certificateArn: ${certificate}
  domain: ["${subDomain}", "${domain}"]
```

Note that `certificateArn` is at top level under `inputs` but `aliases` is under `inputs.cloudfront`. Also as mentioned the `aliases` are already set via use of `domain`, so I think you don't need it.

Though the domain component itself I think is fairly simple and can only manage a single subdomain + domain. If you are using manually added certificate, even if wildcard, I think you need to manually set the alternative domain name to the same one as you are using for `domain: ["${subDomain}", "${domain}"]`

**Comment by lemoncrafter** [comment]
Success!!
That last one did the trick with the last component update: sls-next/serverless-component@1.18.0
Thanks for your time and patience.
I will stay alert for next improves.

**Comment by krikork** [comment]
Hi @dphang, I am on 1.19.0-alpha.21 and having a similar issue. Following your recommendation I got the build to complete, however. I have the following issues:
1. A new certificate is always created even though I have the following configured:

```
  inputs:
    cloudfront:
      certificate:
        cloudFrontDefaultCertificate: false
        acmCertificateArn: "arn...."
```

2. CloudFront gets the correct SSL certificate configured, however, the domain is the default domain from CF e.g. abcd.cloudfront.net. If I specify the domain in serverless.yml my buid fails, most commonly with the following message: "Error: Your newly validated AWS ACM Certificate is taking a while to register as valid.  Please try running this component again in a few minutes."

**Comment by dphang** [comment]
@krikork yes I think the domain component does a lot of internal magic with certificates and it might conflict with certificate input since they may both be trying to set a certificate. The certificate cloudfront input doesn't actually create any certificate, it just uses an existing one.

Would you be able to manage your certificates and domain Route53 records outside of the component?

**Comment by krikork** [comment]
Thanks for the response @dphang. Yes, I can manage certs and domains in Route53 and it seems to work for as long as I do not have any mention of "domain" in the serverless.yml. Wanted to point out that cloudfront.certificate and cloudfront.domain seem incompatible (as of 1.19.0-alpha.21) in case others stumble on the issue or in case you see a way for this to be improved in future versions.

**Comment by dphang** [comment]
Cool, thanks @krikork. I thought I had mentioned in docs but will update to clarify they would be incompatible.
