### ISSUE TITLE
Dynamic rewrites 404ing

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#733]
@dphang this is a continuation of the use case / repro from #705. I'm actually surprised to be just finding this now. In all of the discussion this specific setup must have been missed, but it's really the central issue for my use case.

### Describe the bug
With a page defined at `pages/content/[...all ]` and the following rewrite, visiting `/dynamic-1` gives a 404.
```
{
	source: '/:path*',
	destination: '/:path*',
},{
	source: '/:path*',
	destination: '/content/:path*',
}
```
### Actual behavior
I get a 404 visiting `/dynamic-1`, where next server gives a 200.

### Expected behavior
200

### Steps to reproduce
- Clone and deploy reproduction repo: https://github.com/patricktyndall/sls-next-bug-reproduction
- Visit `/dynamic-1`

### Versions
- OS/Environment: Mac
- @sls-next/serverless-component version: `1.18.0-alpha.27`
- Next.js version: `9.5.5`

**Comment by dphang** [comment]
Yes, I think it should be because of the no-op rewrite not being implemented, I had thought you did not need it anymore based on your latest comments, so I didn't prioritize it. I'll work on it this upcoming week.
