### ISSUE TITLE
200 should be a valid errorPage `responseCode`

### ISSUE THREAD

**Issue by danielberndt** [serverless-nextjs/serverless-next.js#763]
if you take a look at the AWS console, you'll find that `200` is a valid HTTP Response Code:

![image](https://user-images.githubusercontent.com/856386/98133153-8ab98b80-1ebd-11eb-87d3-0b5ccd98cf9a.png)

In your module you're just looking for the `ResponseCode` to be a valid `ErrorCode`. This should probably accept 200 as well.

https://github.com/serverless-nextjs/serverless-next.js/blob/7f38b4f1ca528fe59f8676cc1a406cc2d0947303/packages/serverless-components/aws-cloudfront/lib/getCustomErrorResponses.js#L22

**Comment by danielcondemarin** [comment]
@danielberndt Looks like https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages.html is outdated,

![image](https://user-images.githubusercontent.com/1122442/98154267-7204a200-1ecc-11eb-8106-37d972eacf07.png)

Is the 200 working fine if you set it via the console?

**Comment by danielberndt** [comment]
yes, and it's also working fine when using `patch-package` to patch it into `@sls-next/aws-cloudfront`.

In case you're wondering why I'm interested in it:
turning any `403` into a `200` for `index.html` is essential to allow to run s3-hosted pages with client side routing only.As I'm migrating a cra based app to next-js it's quite useful to keep the old behaviour for the old routes.

**Comment by danielberndt** [comment]
Ah and I just found that this seems to be the docs for the response codes:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages-response-code.html

**Comment by dphang** [comment]
Thanks, patch is here: https://github.com/serverless-nextjs/serverless-next.js/pull/774/files. Will merge it after the tests pass.
