### ISSUE TITLE
Use a local version of serverless that uses local serverless-components

### ISSUE THREAD

**Issue by potench** [serverless-nextjs/serverless-next.js#770]
## The Problem 
I would like to install `serverless` locally and to have `serverless` install and leverage components local to my project as well.  The [serverless documents say](https://github.com/serverless-nextjs/serverless-next.js#getting-started)

> Do not add @sls-next/serverless-component to your package.json file, it is not used and only the version in serverless.yml file is used.

I want `serverless` to install components in my local `./node_modules` directory, but instead it installs components in the home directory `~/.serverless/components/registry/npm/`. This wasn't ideal for working in a docker container where the `.npmrc` couldn't be found to authenticate jfrog/atrifactory permissions to pull from a private npm cache yielding the following error. 
```
0s › Template › Error: Command failed: npm install serverless-next.js@1.15.0-alpha.2 --prefix /home/node/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2
23:38:55 npm ERR! code E401
23:38:55 npm ERR! Unable to authenticate, need: Basic realm="Artifactory Realm"
```

## The Solution 

You _can_ use `serverless` and `serverless-components` locally, so perhaps the solution is to simply remove or update the above warning in your documentation and instead add the following documentation: 

1. install serverless locally 
```sh
npm install serverless --save-dev 
```
2. install serverless component locally, ignoring the documentation warning
```sh
npm install @sls-next/serverless-component --save-dev
```
3. Update serverless.yml to use local version of component 
```yaml
# serverless.yml
MyApplication:
 component: "./node_modules/@sls-next/serverless-component"
```

**Comment by dphang** [comment]
Thanks! Yeah, we can update the docs to clarify that you can use it either way - it can point to a local installation instead of pulling from `npm` directly. I added the warning because it seemed to be a common mistake of installing it in `package.json` and then specifying `component: @sls-next/serverless-component` in the `serverless.yml`, which doesn't use the version as expected in `package.json`
