### ISSUE TITLE
New Roles created every time we run deploy

### ISSUE THREAD

**Issue by thuyvu45** [serverless-nextjs/serverless-next.js#792]
### Describe the bug
Every time we run deploy, the frameworks create two new roles (for Default and API lambdas).  As a result, we hit the limits of number of roles on our AWS account.

I've tried to set the "roleName" (from aws-lambda component) but it doesn't work. Below is the sample of my serverless.yml file:

myApplication:
  component: "@sls-next/serverless-component" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    policy: "my ARN policy."
    domain: [ "${env.subdomain}", "paintzen.com" ]
    runtime: "nodejs12.x"
    cloudfront:
      distributionId: ${env.distributionId}
    bucketName: ${env.bucketName}
    bucketRegion: ${env.region}
    name:
      defaultLambda: ${env.defaultLambdaName}
      apiLambda: ${env.apiLambdaName}
    description: Core-Worlds Lambda
    roleName:
      defaultLambda: my-role-name
      apiLambda: my-role-name

### Versions

- OS/Environment:
- @sls-next/serverless-component version:
- Next.js version:

### Checklist

- [ ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ ] Please first try using the latest `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by Shadrack1701** [comment]
This is currently a known issue/missing feature of serverlessNextJs.  The way to get around it is either keep the .serverless dir in your source code or use S3 to persist it.  

[Here ](https://gist.github.com/hadynz/b4e190e0ce10e5811cb462920a9c678f)is an example of using s3.  The role will still be randomly generated the first time, but it will always use the same role defined in the .serverless files in future runs.

**Comment by thuyvu45** [comment]
Thanks @Shadrack1701.

**Comment by dphang** [comment]
Yes, you can also follow examples here: https://github.com/serverless-nextjs/serverless-next.js#cicd-multi-stage-deployments--a-new-cloudfront-distribution-is-created-on-every-ci-build-i-wasnt-expecting-that for how to manage multiple stages / persist the infrastructure state. Sorry it is not properly built-in for now.

We are looking to improve this by using proper infrastructure-as-configuration tools like CDK/CDK for Terraform to do this for us.
