### ISSUE TITLE
Components GA

### ISSUE THREAD

**Issue by antherkiv** [serverless-nextjs/serverless-next.js#794]
Hello there. I only want to ask about the plugin for components GA support. Best regards.

**Comment by manid** [comment]
TL;DR: for v2 release, we are planning to modularize and decouple the component from Lambda@Edge, make it more platform-agnostic and support more platform deployments, and improve pain points related to infrastructure management. In addition, we will plan to upgrade to Serverless Components GA. We would love feedback or comments to help us improve.


https://github.com/serverless-nextjs/serverless-next.js/issues/777

**Comment by dphang** [comment]
Yes, it's on our roadmap but we are trying to simplify/refactor the component to be more platform-agnostic first. But we would still like to upgrade to Serverless Components GA. I think Q1 2021 could be a good timeline.
