### ISSUE TITLE
SSG not storing to s3 for dynamic pages with fallback: true

### ISSUE THREAD

**Issue by arelaxend** [serverless-nextjs/serverless-next.js#798]
Hi people,

### Describe the bug
Say, we have dynamic pages `/test/[id].js` with some `getStaticPaths(...fallback: true)` and `getStaticProps(...)`. When we request a new id, it renders the html correctly after a loading but it does not store anything on s3. 

So, SSG is not working here!

We suspect that it does not deal multi-regions correctly, but we actually don't know. Please read what follows.

### Actual behavior
Nothing is stored in s3 when `fallback:true` for pages `/test/xxx` not statistically generated at build time. But it does work in `localhost`.

### Expected behavior
After a hit, subsequent requests just follow the RFC that is get from s3, hit, render.

### Additional information

We tested this with the following in `/test/[id].tsx`
```
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useRef } from "react";

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    fallback: true,
    paths: [{ params: { id: "e2efdd70-177f-4bf8-907d-a953c702a304" } }],
  };
};

export const getStaticProps: GetStaticProps = async ({}: any) => {
  return {
    props: {
      id: "e2efdd70-177f-4bf8-907d-a953c702a304",
      upload: {
        title: "UNICEF Children, food and nutrition.",
      },
    },
  };
};

export default function Publication({ upload }: any) {
  const router = useRouter();

  if (router.isFallback) {
    return (
      <div>
        <h1>Loading&hellip;</h1>
      </div>
    );
  }

  const title = useRef((upload && upload.title) || "docduo");

  return (
    <Head>
      <title>{title.current}</title>
    </Head>
  );
}
```

The content of `/static-pages/test/[id].html` is the following:

```

```

<img width="626" alt="Capture d’écran 2020-11-14 à 22 03 50" src="https://user-images.githubusercontent.com/8854658/99156911-4ef4a200-26c5-11eb-8e2a-4ab0f7eed157.png">

The content of `_next/static/QTXnzCYbWqOui3ql6FK75/_buildManifest.js:`

```

```

The content of `_next/static/QTXnzCYbWqOui3ql6FK75/_ssgManifest.js` is: 

```

```

When I test the results of this with the following url: https://e.docduo.fr/test/59407fcb-a848-4ab5-95f0-019f613ea0c1
I expect to have something store in s3 after the first hit.. but in the s3 folder there is just:
![Sans titre-1](https://user-images.githubusercontent.com/8854658/99157079-684a1e00-26c6-11eb-8987-2ed71936a5f7.jpg)

The lambda function (we only see one lambda, Default @ Lambda/Edge, no API) has the following permissions (we also test with administrator permissions, does not work).
<img width="1517" alt="Capture d’écran 2020-11-14 à 22 41 44" src="https://user-images.githubusercontent.com/8854658/99157604-9f223300-26ca-11eb-888f-a814d8e731f9.png">

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Resource": "*",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ]
        },
        {
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::1k4854-p0yvzbh/*",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ]
        }
    ]
}
```

Strangely, there is no lambda invocation (on us-east-1, where the plugin creates the lambda)

<img width="1474" alt="Capture d’écran 2020-11-14 à 22 24 21" src="https://user-images.githubusercontent.com/8854658/99157344-35a12500-26c8-11eb-9a6d-0ab0d6ff4532.png">

The serverless includes a domain where we issue a certificate in `us-east-1`

```
# serverless.yml
nextamplified:
  component: "@sls-next/serverless-component@1.19.0-alpha.7"
  inputs: 
    domain: ["e", "docduo.fr"]
```

Also maybe this is relevant, the cloudwatch logs are in `ue-west-1`:
<img width="1353" alt="Capture d’écran 2020-11-14 à 22 29 20" src="https://user-images.githubusercontent.com/8854658/99157415-e3143880-26c8-11eb-8313-845bee7dc65c.png">

But the plugin setups one lambda in `us-east-1`.

In cloudfront, under `_next/data*` we have this setup (automatically by the plugin, it looks nice)
<img width="965" alt="Capture d’écran 2020-11-14 à 22 51 21" src="https://user-images.githubusercontent.com/8854658/99157735-f8d72d00-26cb-11eb-9402-cdf3f5c0c259.png">

Under s3, there is the following perms:

```
{
    "Version": "2012-10-17",
    "Id": "PolicyForCloudFrontPrivateContent",
    "Statement": [
        {
            "Sid": " Grant a CloudFront Origin Identity access to support private content",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E376221HJ5Y29H"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::1k4854-p0yvzbh/*"
        }
    ]
}
```

### Versions

- OS/Environment: mac os, chrome
- @sls-next/serverless-component version: 1.19.0-alpha.7
- Next.js version: 10

### Checklist
- https://github.com/serverless-nextjs/serverless-next.js/issues/355
- https://github.com/serverless-nextjs/serverless-next.js/issues/713
- https://github.com/serverless-nextjs/serverless-next.js/issues/777

A.

**Comment by dphang** [comment]
Thanks, looks like the problem is in here: https://github.com/serverless-nextjs/serverless-next.js/blob/84a3f40345c4e7a2e6dd72832ee148372bdcc813/packages/libs/lambda-at-edge/src/default-handler.ts#L361-L369. Instead of breaking to do SSR render of the data request in origin request handler, we should try to fetch it from S3 (which will fail the first time, but the origin response handler will then fetch and store it in s3).

Not sure why it wasn't caught in unit tests, I'll fix it and update both the unit/e2e tests to catch this.

**Comment by arelaxend** [comment]
@dphang Well now it stores on s3 🥇 

Still, if you check https://d3hi38y6ftlvgj.cloudfront.net/test/abcde, one may see that the "loading" shows at every render.

Also, when one checks in the network debug tab of a browser, one sees: `x-cache: Miss from cloudfront` is this expected ?
![Capture d’écran 2020-11-15 à 16 23 52](https://user-images.githubusercontent.com/8854658/99188939-f70a7980-275e-11eb-835d-8175a61236f3.png)

**Comment by dphang** [comment]
Thanks for testing. I actually didn't publish the latest yet.

I did find that issue too, it is because fallback page gets cached after 1st hit. But if you bust the cache after hitting a non-prerendered route (add a random query parameter), with the new change it would pick up the page that was just stored in s3.

To fix it, we need to make the fallback page never cached. But we also need to version the pages properly as I realized we are not clearing them properly (we only have one set of pages under static-pages, so subsequent deploys may pick up an old version).

**Comment by arelaxend** [comment]
> Thanks for testing. I actually didn't publish the latest yet.

@dphang I tested with the PR 👍 

> To fix it, we need to make the fallback page never cached, so the lambda can return the newly generated page (and cache it) the next time the same route is hit. But we also need to version the pages properly as I realized we are not clearing them properly (we only have one set of pages under static-pages, so subsequent deploys may pick up an old version).

Absolutely!

**Comment by rahul3103** [comment]
@arelaxend Can you tell me how you are uploading your static generated files to s3.

Right now, what I am doing is after build I upload all the static files and folder on S3 and do `yarn start` after updating the asset prefix. But, I am stuck with this incremental static page generation and also with next-images which generate so many images. But, I am not able to upload these on S3. Can you guide me how you are uploading your build time and incremental static files on S3

**Comment by arelaxend** [comment]
@rahul3103 can you create a request / issue following the instructions and check that your question has no precedence. Thank you

**Comment by danigrandem** [comment]
Im having the same problem. 
How can i solve this?

Thanks
