### ISSUE TITLE
Files served from public folder where names contain spaces are not found

### ISSUE THREAD

**Issue by confix** [serverless-nextjs/serverless-next.js#822]
### Describe the bug
Files having names containing spaces inside public folder result in 404

### Actual behavior
When a file with a name containing spaces is requested, the request path is encoded like so: `/files/my%20special%20file.txt`.
The `manifest.json`  looks something like this
```json
{
   "publicFiles": {
    "/files/my special file.txt": "/files/my special file.txt"
  }
}
```

Hence the following lookup yields `undefined`
https://github.com/serverless-nextjs/serverless-next.js/blob/2427517e093a7f938d22600771b86a6a36c40666/packages/libs/lambda-at-edge/src/default-handler.ts#L259

and we end up with a 404 at some later point.

### Expected behavior
The file should be served.

### Steps to reproduce
1. put a file with a filename containing spaces inside the public directory
2. deploy
3. request the file

### Versions

- OS/Environment: Debian buster
- @sls-next/serverless-component version: current master

### Checklist

- [ x ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [ x ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by confix** [comment]
I guess decoding the path should do the trick. Would that break any other things? 

Additionally the file is stored in S3 like `<bucket>/public/files/my+special+file.txt`. I have not tested whether we would need to replace the spaces here as well. Gave it a quick try by replacing the spaces contain within keys by `%20` and within values by `+` in the `manifest.json`. Now the file is served as expected.

**Comment by dphang** [comment]
Makes sense, though we would also need to consider other special characters in S3: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html. Since the URI from CloudFront is %-encoded, though from the docs "%" should be avoided, so I don't think we should not store S3 keys as URI-encoded.

**Comment by confix** [comment]
Wouldn't it be sufficient to simply wrap 
https://github.com/serverless-nextjs/serverless-next.js/blob/2427517e093a7f938d22600771b86a6a36c40666/packages/libs/lambda-at-edge/src/default-handler.ts#L257
with `decodeURI`? We do not have to modify the request path (it's encoded and S3 should be fine with it). We just have to make the lookup succeed. AFAIK the lookup result is not used anyway, but rather treated like a boolean value indicating whether the file exists.

Anyhow, would you be interested in a PR?

**Comment by dphang** [comment]
Ya that should work, just wanted to consider special characters. S3 key should be the decoded key. Feel free to make a PR and I can review it. Thanks!
