### ISSUE TITLE
Redirect loop occurs when requesting any page (but index) from lambda directly

### ISSUE THREAD

**Issue by henrypiassek** [serverless-nextjs/serverless-next.js#824]
### Describe the bug
HTTP requests to (friendly) page URLs result in a redirect loop instead of being rewritten and served correctly.

### Actual behavior
When requesting a page URL directly from server (e. g. by entering a URL in the browser address bar or coming from an external source), browser gets a 308 HTTP Redirect response. The location provided in the response equals the location currently visited by browser (which results in a redirect loop).

### Expected behavior
The page should be served (as it is done when navigating to it client-side).

### Steps to reproduce
1. Clone the repository below
2. Deploy to AWS
3. Open `https://<cloudfront-host>/pretty-url/` in your browser

### Screenshots/Code/Logs
I created a reproduction repo here: https://github.com/henrypiassek/nextjs-redirect-loop-example

### Versions
- Build Environment: Windows 10, Visual Studio Code 2019
- @sls-next/serverless-component version: 1.19.0-alpha.12 (also tested on 1.18.0)
- Next.js version: 10.0.3

### Additional context
I checked the lambda handler code and found that a custom redirect rule is matched (there seem to be two "default" rules added by serverless-nextjs). I guess `getRedirectPath` is supposed to return `null` at that point. Instead it's testing the input path against these two redirect rules/patterns in `routes-manifest.json` (and matches the second rule). The final RegEx pattern built by the handler looks like this:
`^(?:\/((?!\.well-known(?:\/.*)?)(?:[^/]+\/)*[^/\.]+))[\/#\?]?$`

It is possible to temporarily work around this issue by returning `null` if `compiledDestination` equals input `path` in `getRedirectPath`.

EDIT: Updated steps to reproduce

**Comment by dphang** [comment]
Thanks, let me take a look at it this week.

**Comment by rrooding** [comment]
Experiencing the same issue here with Next 10.0.4 & serverless-component 1.18.0 and 1.19.0-alpha.22

**Comment by dphang** [comment]
Sorry, just got back to this. Yes, it looks like they changed the trailing slash redirect data, we were doing our own redirect (for performance reason so we don't need regex unless needed by custom redirect) and removing these from `routes-manifest` as it can cause redirect loop. But with the new format, we weren't removing it. Fixing it now.
