### ISSUE TITLE
some pages/api/routes return 502s when upgrading @sls-next/serverless-component@1.15.1 to a newer version

### ISSUE THREAD

**Issue by dustingraves** [serverless-nextjs/serverless-next.js#828]
### Describe the bug

When upgrading `@sls-next/serverless-component@1.15.1` to a higher version (`1.18.0` or `1.19.0-alpha3`) the API routes break and I get `502`s from the lambda.

### Actual behavior

I cannot change my serverless yml to a later version or my app no longer works.

### Expected behavior

My app should still work

### Steps to reproduce

If I change my `@sls-next/serverless-component@1.15.1` to a later version it breaks.

### Screenshots/Code/Logs

```
ERROR: The Lambda function returned invalid JSON: The JSON output is not parsable. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```

```yaml
# serverless.yml

sr-web:
  component: "@sls-next/serverless-component@1.18"
  inputs:
    bucketName: <BUCKET>
    memory: 512
    timeout: 30
    runtime: "nodejs12.x"
    useServerlessTraceTarget: true
    domain: ["<SUB>", "<DOMAIN>.com"] # [ sub-domain, domain ]
```

### Versions

- OS/Environment: Linux or OS X
- @sls-next/serverless-component version: > 1.15.1
- Next.js version: 9.4.4

### Additional context

I grabbed some diffs from the good and bad deployments

GREEN is what changed in the BAD (1.18.0) files 

.serverless/Template.sr-web.apiEdgeLambda.AwsIamRole.json :
```diff 
"policy": {
-    "arn": "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
+    "Version": "2012-10-17",
+    "Statement": [
+     {
+       "Effect": "Allow",
+        "Resource": "*",
+        "Action": [
+          "logs:CreateLogGroup",
+          "logs:CreateLogStream",
+          "logs:PutLogEvents"
+        ]
+      },
+      {
+        "Effect": "Allow",
+        "Resource": "arn:aws:s3:::<BUCKET>/*",
+       "Action": [
+          "s3:GetObject",
+          "s3:PutObject"
+        ]
+      }
+    ]
},
```

.serverless/Template.sr-web.CloudFront.json
```diff
"origins": [
    {
-      "url": "http://<URL>.s3.amazonaws.com",
+     "url": "http://<URL>.s3.us-east-1.amazonaws.com",
      "private": true,
      "pathPatterns": {
        "_next/static/*": {
-        "ttl": 86400,
+          "minTTL": 0,
+          "defaultTTL": 86400,
+          "maxTTL": 31536000,
          "forward": {
            "headers": "none",
            "cookies": "none",
            "queryString": false
          }
        },
        "static/*": {
-          "ttl": 86400,
+          "minTTL": 0,
+          "defaultTTL": 86400,
+          "maxTTL": 31536000,
          "forward": {
            "headers": "none",
            "cookies": "none",
            "queryString": false
          }
        },
        "api/*": {
-          "ttl": 0,
+          "minTTL": 0,
+          "defaultTTL": 0,
+          "maxTTL": 31536000,
          "allowedHttpMethods": [
            "HEAD",
            "DELETE",
            "POST",
            "GET",
            "OPTIONS",
            "PUT",
            "PATCH"
          ],
          "lambda@edge": {
            "origin-request": "arn:aws:lambda:us-east-1:<ACCOUNT>:function:pmiy07f-o5pv6hk:354"
          }
        },
        "_next/data/*": {
          "minTTL": 0,
          "defaultTTL": 0,
          "maxTTL": 31536000,
          "allowedHttpMethods": [
            "HEAD",
            "GET"
          ],
          "lambda@edge": {
-            "origin-request": "arn:aws:lambda:us-east-1:<ACCOUNT>:function:pmiy07f-d0ymx8m:346"
+            "origin-response": "arn:aws:lambda:us-east-1:<ACCOUNT>:function:pmiy07f-d0ymx8m:354",
+            "origin-request": "arn:aws:lambda:us-east-1:<ACCOUNT>:function:pmiy07f-d0ymx8m:354"
          }
        }
      }
    }
  ],
-  "errorPages": [],
  "defaults": {
-    "ttl": 0,
+    "minTTL": 0,
+    "defaultTTL": 0,
+    "maxTTL": 31536000,
    "forward": {
      "cookies": "all",
      "queryString": true
    },
    "allowedHttpMethods": [
      "HEAD",
+      "DELETE",
+      "POST",
      "GET",
+      "OPTIONS",
+      "PUT",
+      "PATCH"
    ],
    "lambda@edge": {
-    "origin-request": "arn:aws:lambda:us-east-1:<ACCOUNT>:function:pmiy07f-d0ymx8m:346"
+      "origin-request": "arn:aws:lambda:us-east-1:<ACCOUNT>:function:pmiy07f-d0ymx8m:354",
+     "origin-response": "arn:aws:lambda:us-east-1:<ACCOUNT>:function:pmiy07f-d0ymx8m:354"
    },
```
### Checklist

- [ x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Is there anything in CloudWatch logs besides the 502 error and is it possible for you to provide a reproduction to further debug? Without a repro, it is pretty difficult to tell what is going wrong.

I did find a related issue: https://github.com/serverless-nextjs/serverless-next.js/issues/525 - it seems it can happen if there is some error in React rendering the API/page, then somehow the response data gets corrupted.

**Comment by dustingraves** [comment]
So this started because I wanted to run the build/deploy from GitHub actions and am getting an s3 object error only when running GitHub actions. When I upgrade that error goes away but then I can't deploy with the error with a few of the api/routes. The output above is the diffs I found from gathering the deployment artifacts from each method from an ec2 instance. I can enable further logging in the lambda, this is a project I inherited.

**Comment by dphang** [comment]
Closing old issue, if this is still relevant or unsolved please feel free to open once you've tried the newer Next.js / component versions.

Also 502s can happen I think if the response size is too large, then Lambda truncates it (and results in JSON error)
