### ISSUE TITLE
Allow default lambda and API lambda to have different arn roles

### ISSUE THREAD

**Issue by Arditc** [serverless-nextjs/serverless-next.js#836]
**Is your feature request related to a problem? Please describe.**

Currently both lambdas can only have the same arn role (if set). However it would be better to follow the same approach that there is for the name field

```
  roleArn:
      defaultLambda: arn
      apiLambda: arn
```

The reason I say this is because I wouldn't want to give the `defaultLambda` access to the database.

**A clear and concise description of what the problem is.**
 I wouldn't want to give the `defaultLambda` access to the database

**Describe the solution you'd like**
I can set arn for both defaultLambda & apiLambda 

```
  roleArn:
      defaultLambda: arn
      apiLambda: arn
```

**Comment by dphang** [comment]
Should be fixed in https://github.com/serverless-nextjs/serverless-next.js/issues/1101 already
