### ISSUE TITLE
503 when using image optimization

### ISSUE THREAD

**Issue by arelaxend** [serverless-nextjs/serverless-next.js#840]
Hi there,

**Is your feature request related to a problem? Please describe.**
Still, we check `@sls-next/serverless-component@1.19.0-alpha.16` and for now we get 503 on images when we provide an url for an image for a specific listed domain. We get the same result for images located under `/public`

We setup `next.config.js` with the following:
```
images: {
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    domains: ["stream.domain.com"],
    path: '/_next/image',
    loader: 'default',
  }
```

For: 
```
<Image
            src={`https://stream.domain.com/public/image.jpg`}
            width={300}
            height={300}
            alt="my image"
            layout={`responsive`}
            priority={true}
            loading="eager"
 />
```

On s3 we see yet no file under `_next/images`

**Describe the solution you'd like**
That is create the optimized images in s3 under `_next/images`

**Additional**
- node version: v14.7.0
- @sls-next/serverless-component@1.19.0-alpha.16
- https://github.com/serverless-nextjs/serverless-next.js/pull/829
- https://github.com/serverless-nextjs/serverless-next.js/issues/725

We also found this in cloudwatch logs.

![Capture d’écran 2020-12-08 à 14 05 09](https://user-images.githubusercontent.com/8854658/101487446-78b88600-395e-11eb-9a86-ad398cb5e578.png)

A.

**Comment by dphang** [comment]
If you check the image lambda output, just checking, are the node_modules and sharp correctly copied there? I had prebuilt modules for Lambda so it should just copy those. Also make sure the function is running Node 12.x as that is what is mentioned in the Sharp installation page.

**Comment by jonahallibone** [comment]
@dphang +1 for this issue as well

**Comment by dphang** [comment]
Yea, this is strange, for some reason the `libvips` binaries are now not being copied over to the Lambda when I deploy (`node_modules/sharp/vendor/`). Trying to investigate why that's the case.

**Comment by dphang** [comment]
I think when running it locally, it copies the vendor libs correctly, but when doing an npm publish, it seems to exclude certain files. I think if we update the `files` property to explicitly whitelist everything in `sharp_node_modules` it, it should work.

**Comment by dphang** [comment]
I think it is because the `package.json` in `sharp` module doesn't include it (for good reason, since there are many binaries and it adds to the package). However, since we do need it and we only have Lambda Node.js 12.x platform, I think it is fine to include it. Added PR here: https://github.com/serverless-nextjs/serverless-next.js/issues/840, hoping it works this time.

**Comment by dphang** [comment]
It should be fixed now in`@sls-next/serverless-component@1.19.0-alpha.19`. Will try to optimize/bundle this better in the future, but it should be workable for now. Let me know if there are other issues.

**Comment by jonahallibone** [comment]
@dphang I am deploying with the new alpha as we speak, will report back

**Comment by snowjang24** [comment]
I have same issue, but only works on svg files, my png file has 503 error and cant load all

**Comment by dphang** [comment]
@snowjang24 thanks for reporting. Could you please provide more details like Next.js version, Serverless-next.js version.
 
What kind of URL are you optimizing. Is it absolute URL or relative URL (in public folder?) What do CloudWatch logs say about the errors?

**Comment by snowjang24** [comment]
@dphang 

My dependencies is  
* Next - 10.0.3
* serverless-next - 1.19.0-alpha.16

svg files and png files in the same directory, like `public/example.png`
in this case still svg works, png doesn't works

I tried to optimize the relative URL. 

---

I saw your comment and upgrade to alpha.19 and now it works well for all png and svg ....😭

Thanks for your kind comment

**Comment by arelaxend** [comment]
> It should be fixed now in`@sls-next/serverless-component@1.19.0-alpha.19` after also include [7256ab9](https://github.com/serverless-nextjs/serverless-next.js/commit/7256ab9bbd090dc1503dfebf5c93fb0b3cb452bd). Will try to optimize/bundle this better in the future, but it should be workable for now. Let me know if there are other issues.

Well, 👍

**Comment by jonahallibone** [comment]
Unsure if this is a specific to this lib or to Next.js in general, but it seems sometimes the conversions fail and then the server returns a 503 for the image every time after that point.

**Comment by dphang** [comment]
@jonahallibone not sure what's going on there, please post more details such as CloudWatch logs.

**Comment by kylekirkby** [comment]
Thanks, @dphang! Working now. Any suggestions on how we can stop images from being resized on every deployment of our apps? Looks like the `/*` rule is being used for clearing the CF cache. AFAIK this means that the images will be re-optimized on a subsequent deployment?

**Comment by dphang** [comment]
@kylekirkby yes, the entire cache is invalidated by default, which does include the images path. Please take a look at CloudFront paths section: https://github.com/serverless-nextjs/serverless-next.js#custom-cloudfront-configuration if you would like to specify exact paths.

**Comment by dphang** [comment]
Closing since there were no additional reported issues.

**Comment by jahlherapath** [comment]
Hey I'm getting a 401 on my images on production:

Next - 10.2.3
serverless-next - @sls-next/serverless-component@3.3.0

Any idea?
