### ISSUE TITLE
503 Error when first deploy

### ISSUE THREAD

**Issue by levu304** [serverless-nextjs/serverless-next.js#849]
### Describe the bug
Hi i'm new with serverless-next.js. Today I tried to first deploy using serverless
When i created new create-next-app and deployed, it worked well
Then i tried deploy in my company Next application, it throws 503 error page

### Steps to reproduce
1- Config serverless.yml
2- Set .env AWS key
3- Try npx serverless
3- Deploy success
4- Click on cloudfront URL response 503 error page

### Screenshots/Code/Logs
![yml](https://user-images.githubusercontent.com/9843111/102574625-ce8dea80-4123-11eb-8dc1-eb1880877f55.JPG)
![env](https://user-images.githubusercontent.com/9843111/102574638-d77ebc00-4123-11eb-86c6-cf92d9d182ac.JPG)
![next_config](https://user-images.githubusercontent.com/9843111/102575630-23326500-4126-11eb-930e-9930b601696e.JPG)
![packagejson](https://user-images.githubusercontent.com/9843111/102575674-478e4180-4126-11eb-929a-54f588147e25.JPG)
![503](https://user-images.githubusercontent.com/9843111/102575679-4bba5f00-4126-11eb-8f0f-8e57f10491eb.JPG)

- OS/Environment: Windows 10 - Nodejs 12
- @sls-next/serverless-component version: 1.18.0
- Next.js version: 10.0.0

**Comment by dphang** [comment]
Please look in CloudWatch logs and post the details of the error - The CloudFront 503 error page is very generic and won't tell why it is failing. I suspect it may be related to next-i18next package not able to find files. Please see here for more details: https://github.com/serverless/serverless/issues/8503#issuecomment-727259008

**Comment by dphang** [comment]
Closing stale issue, please let us know in case there are further issues. Thanks!
