### ISSUE TITLE
Is this project backed?

### ISSUE THREAD

**Issue by lcswillems** [serverless-nextjs/serverless-next.js#850]
Hi,

This is a great project! And I am considering using it for deploy my code.

However, I am wondering about the stability of this project. Is it backed by Serverless.com? Or is it a project maintened by mainteners on their free time?

**Comment by dphang** [comment]
Yes, it was backed in the sense that Serverless Framework did give some money to integrate it with Serverless Components (and will give more when we update to use Serverless GA). But they are not actively maintaining the codebase (not quite sure if they had in the past - they may have helped update features in Serverless Components to help with integration) - that's mostly @danielcondemarin, me and a handful of community contributors.

**Comment by lcswillems** [comment]
Thank you for your answer! And thank you for the time you dedicate to this project!!

Another question: when you update to use Serverless GA, will we have to pay to use this library? If I am not wrong, it is currently using the beta version?

**Comment by danielcondemarin** [comment]
> Thank you for your answer! And thank you for the time you dedicate to this project!!
> 
> Another question: when you update to use Serverless GA, will we have to pay to use this library? If I am not wrong, it is currently using the beta version?

Serverless GA provides a free [tier](https://www.serverless.com/pricing/) you will be able to use. I believe it limits number of users and concurrent buillds. 
Also note that we are planning to introduce support for AWS CDK in future. See for more details https://github.com/serverless-nextjs/serverless-next.js/issues/777
