### ISSUE TITLE
New lambda for Next.js Images are created every single deploy

### ISSUE THREAD

**Issue by jonahallibone** [serverless-nextjs/serverless-next.js#853]
### Describe the bug
New lambda for Next.js Images are duplicated every single deploy.

### Actual behavior

Every time I deploy, a new lambda is created for the image optimization. My other lambdas, apiLambda and defaultLambda (named as such and described in the docs) do not seem to be duplicated.

### Expected behavior

I would expect to be able to either name these to prevent duplication, or for them to not be duplicated at all.

### Screenshots/Code/Logs
<img width="728" alt="Screen Shot 2020-12-23 at 6 52 33 PM" src="https://user-images.githubusercontent.com/8886318/103044800-06e05f00-4550-11eb-8687-7545c7b88de3.png">
<img width="1395" alt="Screen Shot 2020-12-23 at 6 52 55 PM" src="https://user-images.githubusercontent.com/8886318/103044815-13fd4e00-4550-11eb-8968-56bc63358d74.png">

### Versions

- OS/Environment: Linux distro in codebuild
- @sls-next/serverless-component version: `"@sls-next/serverless-component@1.19.0-alpha.21"
`
- Next.js version: 10.0.4

### Additional context

I have my Cloudfront and S3 configured in my serverless.yml to prevent those from being recreated in my CI environment. 

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Ah, are you not preserving the `.serverless` directory (which would have the Lambda state) every time you deploy? If you aren't and you didn't specify the `imageLambda` name, that would explain why it is recreating it.

I realized I forgot to update the docs, mentioning you can also set memory/name/timeout for image lambda (using `imageLambda` key). Will update it to be clearer!

**Comment by jonahallibone** [comment]
@dphang Thank you so much! Yea, I am deploying via Codebuild so I have my values hard coded in lieu of caching the .serverless directory. Thanks for the note on imageLambda name, I will add to my config.

**Comment by dphang** [comment]
Sure, no worries. Assuming the issue can be closed now, feel free to open another if there are still further issues.

**Comment by SrihariharaanS** [comment]
Hi Iam facing the same issue. Can i get the code sample?
