### ISSUE TITLE
CredentialsError

### ISSUE THREAD

**Issue by gr-qft** [serverless-nextjs/serverless-next.js#855]
I'm following along this tutorial: 

https://github.com/dabit3/next.js-amplify-workshop

and I've reached the step where I create `serverless.yml` with the following content: 

```
amplifynext:
  component: "@sls-next/serverless-component@1.18.0"
```

However, I'm seeing the following error: 

```
 19s › amplifynext › CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

npm ERR! code 1
npm ERR! path /Users/tn/amplify-next
npm ERR! command failed
npm ERR! command sh -c serverless

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tn/.npm/_logs/2020-12-26T20_22_06_628Z-debug.log
```

Could you help with explaining what's going and how to fix it? 

Thanks!

**Comment by dphang** [comment]
That error looks like AWS credentials are not set. Have you set it up the credentials file (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) or env variables such as `AWS_ACCESS_KEY_ID` or `AWS_SECRET_ACCESS_KEY`?

FYI, I am not familiar with that tutorial, so if there are other issues specific to that, you will have to ask the author of that tutorial.

**Comment by gr-qft** [comment]
@dphang Thanks for the info. Somebody pointed me to the following link 

https://www.serverless.com/framework/docs/providers/aws/guide/credentials/

and after I followed the instructions (installing and using aws) it worked.

**Comment by dphang** [comment]
Cool, thanks for the update, will close this issue now.
