### ISSUE TITLE
S3 bucket creation fails

### ISSUE THREAD

**Issue by richardwillars** [serverless-nextjs/serverless-next.js#86]
Hello. When trying to deploy for the first time I get the following error: 
"The assets bucket "foobar-qa" does not exist. Create it manually or delete the stack and recreate it."

That S3 bucket doesn't exist, and I have already deleted the cloudformation stack. 

serverless.yml:
`assetsBucketName: "foobar-${self:custom.name}"`

next.config.js
`assetPrefix: "https://foobar.blabla.com"`
(The S3 bucket has it's own subdomain pointing at it).

Any ideas?

**Comment by richardwillars** [comment]
FYI for anyone else hitting this issue.. to get it working I rolled back to v1.8.1 and then commented out the line "after:aws:deploy:deploy:uploadArtifacts": this.uploadStaticAssets," in index.js, then for subsequent deployments I upgraded to the latest plugin.

**Comment by mattdell** [comment]
This is what I'm trying to do, but automated.

So you've created a cloudfront to sit in front of your S3 bucket, yeah?

**Comment by danielcondemarin** [comment]
@richardwillars Can you post your `create` and `update` CF templates under the `.serverless` directory (when the error happens) ?

**Comment by Elyx0** [comment]
Also note that `static` and `public` have to contain at least a file or it crashed too

**Comment by mattdell** [comment]
> Also note that `static` and `public` have to contain at least a file or it crashed too

That was actually raised after we published it here: https://github.com/danielcondemarin/serverless-nextjs-plugin/pull/92#issuecomment-504954593

@danielcondemarin were you able to update the package?

**Comment by danielcondemarin** [comment]
> > Also note that `static` and `public` have to contain at least a file or it crashed too
> 
> That was actually raised after we published it here: [#92 (comment)](https://github.com/danielcondemarin/serverless-nextjs-plugin/pull/92#issuecomment-504954593)
> 
> @danielcondemarin were you able to update the package?

I did last night actually, https://github.com/danielcondemarin/serverless-nextjs-plugin/releases/tag/v2.0.8-alpha.0

**Comment by danielcondemarin** [comment]
@richardwillars You mind trying again using v2.1.0-alpha.0? This version might have fixed this.
