### ISSUE TITLE
Rewrite for /api routes not succesful on post requests

### ISSUE THREAD

**Issue by benjaminkay93** [serverless-nextjs/serverless-next.js#863]
### Describe the bug

Off the back of #832 being merged I went to deploy my next app using the latest alpha version `1.19.0-alpha-22`.

As part of my config I rewrite `/api/graphql` to be `https://api.example.com/v1/graphql`, but all requests to this url fail

### Actual behavior

I get a 404 from `/api/graphql`

### Expected behavior

My POST request to resolve

### Versions

- OS/Environment: Deployed in AWS, no errors in build and deploy
- @sls-next/serverless-component version: 1.19.0-alpha-22
- Next.js version: 10.0.2

### Additional context

I found this same problem on the old rewritten site aswell as our new next site that is proxied through. We see the same 404 on POST requests to our PHP API on `/api/auth/login`, I suspect POST is just broken on the rewrite functionality?

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Do other external rewrites work? What about something like making a GET request from `/api/external-rewrite` -> `https://api.github.com`?

I think it might be that it probably needs to pass the method from CloudFront event into the fetch call here: https://github.com/serverless-nextjs/serverless-next.js/blob/bfe030172712beb65cd002b7ae9a20818af338e0/packages/libs/lambda-at-edge/src/routing/rewriter.ts#L92-L93

**Comment by benjaminkay93** [comment]
Yeah it looks to work fine for GET requests, so i presume thats it

See: https://pl-website-next-dev.playerslounge.co/api/github

Yeah that line looks to require options for the body and what not

**Comment by dphang** [comment]
I just published a latest alpha that should fix this. Could you try and see if it works?

**Comment by benjaminkay93** [comment]
So i have deployed using 1.19.0-alpha.23 and found that the same problems still exist for POST requests, my mechanism for testing is outlined below:

1. Spin up `yarn dev` and login to our old PHP site thats rewritten (POST request to `/api/auth/login`), send some messages to our chat (POST request to `/matches/chat`). **All works well as expected.**
1. Deployed to vercel and logined to our old PHP site thats rewritten (POST request to `/api/auth/login`), send some messages to our chat (POST request to `/matches/chat`). **All works well as expected.**
1. Deployed to with 1.19.0-alpha.23 and logined to our old PHP site thats rewritten (POST request to `/api/auth/login`), send some messages to our chat (POST request to `/matches/chat`). **Neither POST request was successful**, the one to `/api/auth/login` returned a 404, and the one to `/matches/chat` return a 503.

Of perticular note the 503 to `/matches/chat` had a response cahe header of `x-cache: LambdaExecutionError from cloudfront`

with the body
``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>503 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: REbUodx5pO5z_P1DRGCJCuErAuJkO1zMhkJlXUy-rKuiVhuxCBBBhw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by dphang** [comment]
I see, what does it say in CloudWatch logs? The 503 error message is generic and would not help much with debugging, unfortunately.

**Comment by benjaminkay93** [comment]
i have also seen a 502 on the apollo requests too,

they all look like theyire cloudfront errors as none of the lambdas are producing any logs for those requests

**Comment by dphang** [comment]
Just wanted to confirm, are you checking in the region from which you are accessing CloudFront? It may not be in us-east-1 where the base Lambda is deployed. I believe it should be related to the Lambda function based on the message (at least what I've seen). Unfortunately, without logs it is hard to tell what went wrong.

Or if you have a repro you can provide, I can try to deploy and debug it myself.

**Comment by dustinsgoodman** [comment]
@dphang Hey, it looks like maybe the post request body is implemented incorrectly here: 

https://github.com/serverless-nextjs/serverless-next.js/blob/e04b4b458e3cf737fae2331bdd4c01c400218372/packages/libs/lambda-at-edge/src/routing/rewriter.ts#L107-L111

Per the [node-fetch lib's spec](https://github.com/node-fetch/node-fetch#post-with-json) and TCP spec, body should be sent as a string and not JSON. You have the `JSON.parse` on L110 above which would cause the data to be sent improperly which I think is causing the issues @benjaminkay93 is seeing.

**Comment by dphang** [comment]
Ah, you are right, I thought I tested it and it worked but let me fix that, thanks!

**Comment by dphang** [comment]
Fixed it in 1.19.0-alpha.24, let me know if it works for you now.

**Comment by benjaminkay93** [comment]
Hey, just deployed it now and all looks good, thanks for this, utterly amazing <3

**Comment by mrtcntn** [comment]
Hi there, I have the same configuration which I have a rewrite for /api, pointing to an AWS Elastic Beanstalk app. I send POST and PUT requests with `'Content-Type' = 'multipart/form-data'` header with proper boundary and payload to handle some file uploads to an S3 bucket. It works correctly and I can access uploaded files in my local development environment, however files get corrupted when I deploy my Next.js project using serverless component. I have tested my EB app seperately via Postman and it works correctly. I am suspicious that somehow the request body is not passed to the Lambda correctly from CouldFront.

### Versions

- OS/Environment: Deployed in AWS, no errors in build and deploy
- @sls-next/serverless-component version: 3.2.0-alpha.21
- Next.js version: 11.0.1
