### ISSUE TITLE
Showing error while deployment

### ISSUE THREAD

**Issue by dhsolver** [serverless-nextjs/serverless-next.js#87]
While deploy by executing 'serverless deploy', showing error like image below.
![Screen Shot 2019-06-10 at 4 18 03 PM](https://user-images.githubusercontent.com/43324939/59303340-3ae87d80-8c53-11e9-8823-4f5e1917f50c.png)

**Comment by danielcondemarin** [comment]
That looks like a problem with your next build. Can you run `next build` and check whether it works?

**Comment by dan1114ho** [comment]
it is building correctly and if I do 'serverless deploy' again after build, still showing same error.

**Comment by danielcondemarin** [comment]
Can you provide your next.config.js including your webpack configuration?

**Comment by dan1114ho** [comment]
module.exports = require('@zeit/next-less')(
    require('@zeit/next-css')(
        require('next-fonts')(
            require('next-images')(
                require('next-offline')({
                    webpack(config) {
                        config.node = {fs: 'empty'};
                        return config;
                    },
                    env: {},
                    workboxOpts: {
                        runtimeCaching: [
                            {
                                urlPattern: /^https?.*/,
                                handler: 'networkFirst',
                                options: {
                                    cacheName: 'https-calls',
                                    networkTimeoutSeconds: 15,
                                    expiration: {maxEntries: 150, maxAgeSeconds: 30 * 24 * 60 * 60},
                                    cacheableResponse: {statuses: [0, 200]},
                                },
                            },
                        ],
                    },
                })
            )
        )
    )
);

**Comment by danielcondemarin** [comment]
@dan1114ho Would be great if you could provide a simple repro repository example. That way I can look into this quicker.

**Comment by dphang** [comment]
Closing out old/stale issues. If same issue occurs with the latest version of this component, please reopen a new issue.
