### ISSUE TITLE
Removed pages still accessible

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#873]
Hey, when I un-publish a blog post and build+deploy, the old URLs still are accessible. I assume the files still exist in Cloudfront. @dphang is this something you are aware of / is this supported by this framework?

### Describe the bug
- Un-published URLs are still accessible

### Actual behavior
- Can visit the page

### Expected behavior
- Page gives a 404

### Steps to reproduce
- Deploy a page and visit the URL
- Un-publish the page
- Redeploy
- Refresh the URL and it will still be available

### Versions
- OS/Environment: Deployed from Alpine linux, dev machine is MacOS Big Sur
- @sls-next/serverless-component version: `1.19.0-alpha.3`
- Next.js version: `9.5.5`

### Additional context
- This is a SSG page (getStaticPaths + getStaticProps)

**Comment by woodwardwebdev** [comment]
Can confirm that I am also facing this issue with static pages.

Currently using a CI/CD pipeline to trigger deployment when a headless CMS is updated. All pages still remain in the S3 bucket related to the deployment, which allows for access.

There are serverless modules that allow for emptying of the bucket before deployment. Is this an option when using serverless-next.js?

**Comment by dphang** [comment]
Yes, this was already fixed in this commit: https://github.com/serverless-nextjs/serverless-next.js/commit/015065d02c1d06659dc1d1a7258b89f9415c3721 which is available since 1.19.0-alpha.8.

It's versioning pages correctly using NEXT_BUILD_ID and keeping only the current + previous deployments' pages/data files in S3, so that new deployments will not have access to old pages and also saves space in S3 by removing old build files.

Ideally, to also guarantee clients get the most updated version of your app, you should also wait until Lambda@Edge is fully propagated (CloudFront is not in progress) before invalidating the cache. I know this component does it right after Lambda@Edge is updated but it's possible a user accesses a page after cache is invalidated but before Lambda@Edge is fully propagated.

Please try and let me know if it works.

**Comment by woodwardwebdev** [comment]
I waited to see if OP would comment here first before replying.

I've updated and pinned 1.19.0-alpha.27 now and am seeing much more reliable behaviour in regards to static pages in S3 buckets.

Thanks for the swift response to this.

**Comment by patricktyndall** [comment]
Hey @dphang I upgraded as suggested, but that turned my 404 pages into 503s, that's why I didn't confirm this fix. I have created a new issue for that here: #894

**Comment by kentobento** [comment]
> Ideally, to also guarantee clients get the most updated version of your app, you should also wait until Lambda@Edge is fully propagated (CloudFront is not in progress) before invalidating the cache.

@dphang 
Just out of curiosity, is there any chance this component will take this approach in the near-future?  I'm encountering the `causing an old page to be cached until the next time you invalidate the caches` scenario, and was wondering whether I should implement something outside of this component to prevent it.

**Comment by dphang** [comment]
Yes, I think for Lambda@Edge should do it, even though it takes 1-2 minutes longer to deploy (possibly) it will avoid any issues with old cached pages. I'll add it to the roadmap. You can just set invalidation paths to empty and invalidate yourself using AWS SDK. Here is example how you can poll for the distribution to be ready:

```ts
async function checkCloudFrontDistributionReady(
  distributionId: string,
  waitDuration: number,
  pollInterval: number
): Promise<boolean> {
  const startDate = new Date();
  const startTime = startDate.getTime();
  const waitDurationMillis = waitDuration * 1000;

  const cloudfront = new AWS.CloudFront();

  while (new Date().getTime() - startTime < waitDurationMillis) {
    const result = await cloudfront
      .getDistribution({ Id: distributionId })
      .promise();

    if (result.Distribution?.Status === "Deployed") {
      return true;
    }

    console.info(
      `Distribution ${distributionId} is not yet ready. Retrying in ${pollInterval} seconds.`
    );
    await new Promise((r) => setTimeout(r, pollInterval * 1000));
  }

  return false;
}
```

**Comment by kentobento** [comment]
@dphang 
Great, thanks!
