### ISSUE TITLE
503 on SSG routes that should 404 when App uses getInitialProps

### ISSUE THREAD

**Issue by patricktyndall** [serverless-nextjs/serverless-next.js#894]
Me again! I'm getting a Cloudfront 503 response from routes that match SSG pages (fallback: false) where I expect to get 404s, _only when I have a custom \_app that has getInitialProps_. I have created a reproduction here: https://github.com/patricktyndall/sls-next-bug-repro

### More info
- I started seeing this issue after upgrading, as instructed by @dphang in #873. (I was able to access old pages, then I upgraded, then those became 503s, as did all other routes that should have 404'd).
- The repro has several "custom"-ish behaviors. These generally work fine and are supported, but could be related to the issue. These include:
-- a rewrite that maps _all_ paths into a `pages` subdirectory (`/content/`)
-- a "no-op" rewrite
- This actually is a big SEO hazard because if you don't have a robots.txt, it will 503, which google considers a "server error".

### Describe the bug
503 where I expect 404s

### Screenshots/Code/Logs
Here's what I see in Cloudfront. Does this mean anything to anyone?
```
ERROR	Invoke Error
{
    "errorType": "AccessDenied",
    "errorMessage": "Access Denied",
    "Code": "AccessDenied",
    "RequestId": "4384B55F0F8A5769",
    "HostId": "NMXCRIP/83sFgCtzWTAeov1m05xK919JJbPkOeF2J20XAVwG3lYDHLdrF3SRrv1MIBY0EZ7RlYs=",
    "name": "AccessDenied",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 403,
        "httpHeaders": {
            "x-amz-request-id": "4384B55F0F8A5769",
            "x-amz-id-2": "NMXCRIP/83sFgCtzWTAeov1m05xK919JJbPkOeF2J20XAVwG3lYDHLdrF3SRrv1MIBY0EZ7RlYs=",
            "content-type": "application/xml",
            "transfer-encoding": "chunked",
            "date": "Mon, 01 Feb 2021 20:30:05 GMT",
            "server": "AmazonS3"
        },
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "AccessDenied: Access Denied",
        "    at deserializeAws_restXmlGetObjectCommandError (/var/task/index.js:19234:41)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

### Versions
- OS/Environment: Amazon Linux
- @sls-next/serverless-component version: `@sls-next/serverless-component@1.19.0-alpha.30`
- Next.js version: `^10.0.6`

**Comment by Lunnatica** [comment]
I'm getting the same error (even when using fallback: true). Did you manage to make it work in the end @patricktyndall ?

**Comment by patricktyndall** [comment]
Nope. My workaround: Every time I deploy I have to create a Cloudfront custom error response that replaces the 503 with a 404, so google indexes my site.

Are you using rewrites?

**Comment by Lunnatica** [comment]
Thanks for the workaround! I'll have it in mind if I cannot find another solution. 

No, I am not using rewrites.

**Comment by patricktyndall** [comment]
@Lunnatica have you figured out other solutions or how to reproduce this?

@dphang do you have any thoughts on this? It's become a problem for my team, and I'd rather not script the custom error response solution.

**Comment by Lunnatica** [comment]
@patricktyndall I didn't manage to fix it so I ended up reverting to using SSR instead, which is not ideal.

**Comment by dphang** [comment]
Sorry I remember looking a bit at this but couldn't remember/figure out the issue at the time. Since it's been some time I can try to take a look again, or if you have any ideas from looking/debugging the code, please let me know.

**Comment by alexedwardjones** [comment]
I'm getting the same issue.

@patricktyndall Should the issue be saying 403 instead of 503? I can see it says `"httpStatusCode": 403` in the log.

**Comment by patricktyndall** [comment]
I'm getting 503, but that doesn't mean your issue isn't related

**Comment by dphang** [comment]
Sorry just got back to this now, it was a bit hard to debug at first but I finally found it's because the 404.html page is not generated by Next.js when adding the `_app.js`, the origin response handler is thus failing to find the s3 page (for fallback: false). I think you need to add a `pages/404.js` so it returns the proper 404 instead.

I'll work on improving the logic so that we check whether a 404 page was actually generated by Next.js and we can just return an empty 404 page instead of trying to access a non-existent s3 key.

**Comment by patricktyndall** [comment]
Too clutch!

What 404 page should we expect to see? I'm now getting an empty html page (was expecting next's default 404). It is returning HTTP 404 though, which is the important part.

**Comment by dphang** [comment]
@patricktyndall yeah in the `.next` folder I don't see any 404.html page generated when you just add an `_app.js` hence we are returning a blank 404 page for now. Not sure how the dev server is doing it? It might be generating it using SSRusing `_error.js` or something. We can try to look into that to improve it
