### ISSUE TITLE
502 LambdaValidationError when used in conjunction with `http-proxy` module, only when deployed

### ISSUE THREAD

**Issue by aomv** [serverless-nextjs/serverless-next.js#898]
### Describe the bug

Serverless-deployed Lambda function appears to introduce a blacklisted header (headerName: `connection`) when using `http-proxy` module via Next API Routes, though not observed during local development. This leads to an immediate 502 LambdaValidationError from cloudfront.

### Actual behavior

We began testing with `http-proxy` sitting between our Next front-end and standalone API back-end. It was working as expected, until we pushed to the cloud. Once in the cloud, our API responses failed with 502 LambdaValidationErrors. Observing our Lambda@Edge logs, we notice the following sequence: 
`(Y4zZWfCBPPxT3TbghhqOoBEkrdXn2yrNO6uW0G1PtblxvvEU9XZp7w==) INFO Invoking LambdaFunctionARN: arn:aws:lambda:us-east-2:630759777581:function:us-east-1.5x0wpwh-kowxcfm:18 Region: us-east-2`
`(Y4zZWfCBPPxT3TbghhqOoBEkrdXn2yrNO6uW0G1PtblxvvEU9XZp7w==) INFO Response received from Lambda: RequestId: 68dfb7a2-6d43-431e-bb45-d33cdc2177c3`
`(Y4zZWfCBPPxT3TbghhqOoBEkrdXn2yrNO6uW0G1PtblxvvEU9XZp7w==) ERROR Validation error: Lambda function result failed validation, the function tried to add a blacklisted header in headers, headerName : connection.`

### Expected behavior

We expect to no blacklisted headers to be set during lambda execution.

### Steps to reproduce

1. Clone our example repo: `https://github.com/aomv/next-sls-proxy-app`
2. `nvm use lts/erbium`
3. Run locally with: `npm run dev`
4. Then deploy: `sls`

### Screenshots/Code/Logs

(See logs and repo `https://github.com/aomv/next-sls-proxy-app` above)

### Versions

- OS/Environment: macOS 10.15.7
- @sls-next/serverless-component version: 1.18.0
- Next.js version: 10.0.6

### Additional context

The latest `@sls-next/serverless-component@1.19.0-alpha.30` exhibits the same behavior.

Any insight would be greatly appreciated, really enjoy using Serverless products.

### Checklist

- [X] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [X] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by larrifax** [comment]
Just ran into this today. Seems like Lambda@Edge [blacklists certain headers](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-blacklisted-headers), amongst them the `connection` header, which the `http-proxy` just passes through from the target response.

I've been able to circumvent this issue by applying the following patch to `http-proxy`:
```
diff --git a/lib/http-proxy/passes/web-outgoing.js b/lib/http-proxy/passes/web-outgoing.js
index 46352f6e377affc701773328d528bd7e4352f242..7574a5a81dc2a02a7c5a455a147352ac87283bf8 100644
--- a/lib/http-proxy/passes/web-outgoing.js
+++ b/lib/http-proxy/passes/web-outgoing.js
@@ -40,11 +40,7 @@ module.exports = { // <--
    * @api private
    */
   setConnection: function setConnection(req, res, proxyRes) {
-    if (req.httpVersion === '1.0') {
-      proxyRes.headers.connection = req.headers.connection || 'close';
-    } else if (req.httpVersion !== '2.0' && !proxyRes.headers.connection) {
-      proxyRes.headers.connection = req.headers.connection || 'keep-alive';
-    }
+    delete proxyRes.headers.connection;
   },
 
   setRedirectHostRewrite: function setRedirectHostRewrite(req, res, proxyRes, options) {

```

**Comment by dphang** [comment]
Yes since there are blacklisted headers, we need to remove them from the response before returning it. We are doing it for external rewrites but not for SSR/API responses. Will refactor to remove these blacklisted headers

**Comment by aomv** [comment]
The example application from my original post works as expected now (using `@sls-next/serverless-component@1.19.0-alpha.35`). Thank you!
