### ISSUE TITLE
URL paths are case sensitive

### ISSUE THREAD

**Issue by thaiphan** [serverless-nextjs/serverless-next.js#902]
### Describe the bug
The URL paths of my deployed Next.js application is case sensitive.

### Actual behavior
When I navigate to https://www.myamazingsite.com/test, I am able to navigate the page that I want.
When I navigate to https://www.myamazingsite.com/Test (notice the uppercase T), I get server the 500 Internal Server Error page.

### Expected behavior
When I navigate to https://www.myamazingsite.com/Test (notice the uppercase T), I am served the same contents as on https://www.myamazingsite.com/test

### Steps to reproduce
- Create a new Next.js page `/pages/test.tsx`
- Deploy to CloudFront
- Try and access https://www.myamazingsite.com/Test

### Screenshots/Code/Logs
<img width="1789" alt="Screen Shot 2021-02-10 at 12 23 01 am" src="https://user-images.githubusercontent.com/644172/107369663-29e1c500-6b36-11eb-876a-7fb0511f5c11.png">

### Versions

- OS/Environment: macOS Big Sur 11.2
- @sls-next/serverless-component version: 1.18.0
- Next.js version: 10.0.6

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by DevNM21** [comment]
This line      
`const { origin, pathname } = new URL(destination);`  [link](https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/routing/matcher.ts#L33)
I think if the `destination` is changed to `destinationLowerCase` (variable from line 27, same file) would fix it.

**Comment by dphang** [comment]
From what I tested, URL paths also seem case sensitive on the local Next.js server. Is it the same case when deploying to Vercel?
