### ISSUE TITLE
Access Denied web page on new deployment

### ISSUE THREAD

**Issue by KamnaNarang** [serverless-nextjs/serverless-next.js#906]
### Describe the bug
Access denied web page renders instead of default page while using version 1.19.0-alpha.32 (latest at the time of reporting) for first/new deployment. It works well if upgraded the version for already deployed application with existing version (previous to 1.19.0-alpha.30).

### Actual behavior
Error page is being rendered as in screenshot below.

### Expected behavior
Default page should be rendered for first/new deployment as it works with the previous @sls-next/serverless-component@1.19.0-alpha.30/31

### Steps to reproduce
Used a sample nextjs project with the following steps.
1. npx create-next-app
2. npx serverless create --template aws-nodejs
3. npx serverless

### Screenshots/Code/Logs
![image](https://user-images.githubusercontent.com/79380257/108608362-c4f45d80-73c6-11eb-875f-69bb03d26167.png)

serverless.yml
testproj:
    component: "@sls-next/serverless-component@1.19.0-alpha.32"

### Versions
"@sls-next/serverless-component@1.19.0-alpha.32"

### OS/Environment:
- "@sls-next/serverless-component@1.19.0-alpha.32"
- "Next.js version: "10.0.6"

### Checklist
- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by IamManchanda** [comment]
This is how I do it and works:

1. npx create-next-app
1. Create `serverless.yml` file as suggested below
1. Add the below code as mentioned below in `.gitignore` besides already added code in there
1. Create `.vercelignore` and add the below code as mentioned below in `.vercelignore` (optional, but you should use it if deploying to vercel also separately)
1. npx serverless

`serverless.yml`

```
nextamplified:
  component: "@sls-next/serverless-component@1.19.0-alpha.32"
```

`.gitignore`

```
# Serverless directories
.serverless
.serverless_nextjs
```

`.vercelignore`

```
serverless.yml
```

**Comment by KamnaNarang** [comment]
> This is how I do it and works:
> 
> 1. npx create-next-app
> 2. Create `serverless.yml` file as suggested below
> 3. Add the below code as mentioned below in `.gitignore` besides already added code in there (don't remove already added code in there, just "add" additional code as mentioned below)
> 4. Create `.vercelignore` and add the below code as mentioned below for `.vercelignore` (optional, but you should use it if you are deploying to vercel also separately)
> 5. npx serverless
> 
> `serverless.yml`
> 
> ```
> nextamplified:
>   component: "@sls-next/serverless-component@1.19.0-alpha.32"
> ```
> 
> `.gitignore`
> 
> ```
> # Serverless directories
> .serverless
> .serverless_nextjs
> ```
> 
> `.vercelignore`
> 
> ```
> serverless.yml
> ```

Thanks Harry. I tried the steps you have mentioned and I still get the same Access Denied issue. Can you please try the steps I mentioned in the issue.

**Comment by raffij** [comment]
I agree there's an issue with the default setup on alpha.32. The lambda's don't get created.

Not sure what the issue is yet.

**Comment by kristype** [comment]
I'm having the same issue with alpha.32. I don't have any locale specific content. 
Will try deploying with an older version.

**Comment by raffij** [comment]
Have to drop to the version before the locale based file changes were. Either 28 or 29 will work.

**Comment by raffij** [comment]
You should both try the latest version 33. It fixed our issues.

**Comment by kostenickj** [comment]
this is happening to me on 1.19.0-alpha.42

I dont have any locale content

The auto generated s3 bucket also is completely empty aside from a "Build ID" file despite having several static pages in my app.

Not really sure what im doing wrong.

![image](https://user-images.githubusercontent.com/17304343/114216419-be408c00-991b-11eb-931f-3a42a8776941.png)

**Comment by dphang** [comment]
@kostenickj I have fixed the Windows fast-glob issue above: https://github.com/serverless-nextjs/serverless-next.js/issues/932. However I am not able to easily test it for real since I don't have a personal windows machine. Please try and see if the latest alpha version works. Hopefully it can solve others issues too if they are using Windows.

**Comment by dphang** [comment]
FYI, in alpha 32 that's not working, the change was adding CDK construct which modified s3 directory read to use `fast-glob`. This broke Windows deployments due to `fast-glob` only working with posix-style paths. Unfortunately it's not caught since our tests only run on Ubuntu 

(I did have a draft PR to run tests on Windows, however it looks like there are other issues that need to be fixed to make it work - if anyone is using Windows and would like to help with this PR, I would appreciate it, since I don't have a usable Windows machine atm!)

**Comment by kostenickj** [comment]
@dphang, upgrading to alpha 43 from alpha 42 fixed my issue!

thanks

**Comment by dphang** [comment]
Thanks for confirming, we should be able to close out this issue now.
