### ISSUE TITLE
Access denied after deploy using versions since locale data copying

### ISSUE THREAD

**Issue by raffij** [serverless-nextjs/serverless-next.js#907]
### Actual behavior
We updated from beta.9 to beta.32 to take advantage of locale based urls, but it's causing us issues as it appears non of the localised files are being copied to the s3 bucket.

### Expected behavior
Being able to access the website

### Steps to reproduce
Build a nextjs project with locale based routes and try to deploy.

### Screenshots/Code/Logs

```js
// next.config.js
module.exports = {
  i18n: {
    localeDetection: false,
    locales: ['none', 'en-GB', 'en-US'],
    defaultLocale: 'none',
  },
});
```

Think all the s3 copying functions are creating incorrect source paths:
https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/build.ts#L964-L968

Such as: 

```
From: /.next/serverless/pages/en-US/en-GB/young-adults.html
To: /.serverless_nextjs/assets/static-pages/jzSOVgLFfMMvDiWCloqWC/en-US/en-GB/young-adults.html
```

### Versions

- OS/Environment:
- @sls-next/serverless-component version: beta.32
- Next.js version: 10.0.7

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by raffij** [comment]
I think the issue is related to https://github.com/vercel/next.js/pull/21404 where the prerender-manifest.json version has been updated as locale based urls are handled differently now.

**Comment by dphang** [comment]
Yes, looks like in newer versions they started generating an entry per locale in prerender manifest like so:

```json
{
  "version": 3,
  "routes": {
    "/en/ssg-page": {
      "initialRevalidateSeconds": false,
      "srcRoute": null,
      "dataRoute": "/_next/data/pAxnSn-EEbDUuH11moQ1L/ssg-page.json"
    },
    "/fr/ssg-page": {
      "initialRevalidateSeconds": false,
      "srcRoute": null,
      "dataRoute": "/_next/data/pAxnSn-EEbDUuH11moQ1L/ssg-page.json"
    },
    "/en": {
      "initialRevalidateSeconds": false,
      "srcRoute": null,
      "dataRoute": "/_next/data/pAxnSn-EEbDUuH11moQ1L/index.json"
    },
    "/fr": {
      "initialRevalidateSeconds": false,
      "srcRoute": null,
      "dataRoute": "/_next/data/pAxnSn-EEbDUuH11moQ1L/index.json"
    },
    "/en/image-component": {
      "initialRevalidateSeconds": false,
      "srcRoute": null,
      "dataRoute": "/_next/data/pAxnSn-EEbDUuH11moQ1L/image-component.json"
    },
    "/fr/image-component": {
      "initialRevalidateSeconds": false,
      "srcRoute": null,
      "dataRoute": "/_next/data/pAxnSn-EEbDUuH11moQ1L/image-component.json"
    }
  },
  "dynamicRoutes": {},
  "notFoundRoutes": [],
  "preview": {
    "previewModeId": "71176bbe3e832b7b22609daebeb4a7c8",
    "previewModeSigningKey": "2b3a1ccf72b1efd9941b7ef18859e75f907f980fb7302e7b9273de8a6e9d701b",
    "previewModeEncryptionKey": "76f4771cc2eef429b1eaa8bfa76279354986d79ed8ddd8314fb36eaccab0edb1"
  }
}
```

Will update the logic to check the prerender manifest version and act accordingly.

**Comment by raffij** [comment]
Confirming 33 is now deploying as expected for us.
