### ISSUE TITLE
JWT Cookie not sent on Page refresh

### ISSUE THREAD

**Issue by johnmikel** [serverless-nextjs/serverless-next.js#928]
Great work! I'm currently running a serverless NextJS deployment and it is blazing fast!

I'm just having a bit of a predicament - it seems that the cookie does not work on page refresh so my user gets redirected to the login screen even I know for a fact that the token is valid for an hour.

Any idea where to start debugging this?

**Comment by dphang** [comment]
Not sure why that would be the case - anything special in your app you are doing? Please add here along with Next.js and this component's versions. Also maybe you can follow this guide: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Cookies.html to make sure cookies are being forwarded correctly to the Lambda.

**Comment by johnmikel** [comment]
Not really doing anything special aside from setting cookies using the nookies library. Oh I had a look at that guide last night and fell asleep trying to solve it lol - the ability to forward cookies per Behavior. 

Also, I've been following the conversation you had about the 12000 timeout as I am getting that too which I wasn't initially when I was doing initial deployments. I thought I might have to bring it up as maybe they are related.

Thanks for the help and sharing your time!

**Comment by johnmikel** [comment]
For some reason, Github Actions does it perfectly. I'd like to think it is an issue with my current ISP. I've deployed via Github Actions and it works perfectly - even faster too!

Although, the cookies still aren't being forwarded XD

**Comment by johnmikel** [comment]
@dphang I can confirm that the cookies are being forwarded to lambda.

Here's what I am doing: I added a HOC that uses getInitialProps to check a cookie if the user's JWT hasn't yet expired. I use it to protect page routes depending if their is a logged in user or depending on their permissions.

Works great after logging in and all that, it means the cookies get forwarded to lambda.
However, if I refresh the page, I get automatically kicked out to the login page, this means that the cookie is no longer valid as that is the functionality of the HOC.

However, if I open the Network tab and try to do the request the HOC does internally, it still works - I get the user that had logged in - stating that the user's token hasn't yet expired.

So I'm kinda lost where the problem is. 

Hope this helps. I'm using the latest serverless-nexjts and Next 9.5.1.
This also works locally so I was a bit surprised it doesn't do as expected when deployed in the serverless platform.

**Comment by johnmikel** [comment]
Closing issue. I've solved it myself. It is due to how I am handling cookies. If you ever encounter this, use next-iron-session.
