### ISSUE TITLE
Fetch redirect mode for rewrites is following 302 that is not setting expected cookies on the client

### ISSUE THREAD

**Issue by ungarida** [serverless-nextjs/serverless-next.js#929]
**Is your feature request related to a problem? Please describe.**
I'm integrating the NextJS app with a legacy WebApp following the https://nextjs.org/blog/incremental-adoption#rewrites approach. The legacy WebApp is returning 302 redirects with cookies on some paths and this is not working correctly because the Default Lambda is using fetch in redirect='follow' mode. This is the code I see in the Lambda handling redirects:

```js
                                // HTTP fetch step 5.5
				switch (request.redirect) {
					case 'error':
						reject(new FetchError(`uri requested responds with a redirect, redirect mode is set to error: ${request.url}`, 'no-redirect'));
						finalize();
						return;
					case 'manual':
						// node-fetch-specific step: make manual redirect a bit easier to use by setting the Location header value to the resolved URL.
						if (locationURL !== null) {
							// handle corrupted header
							try {
								headers.set('Location', locationURL);
							} catch (err) {
								// istanbul ignore next: nodejs server prevent invalid response headers, we can't test this through normal request
								reject(err);
							}
						}
						break;
					case 'follow':
						// HTTP-redirect fetch step 2
						if (locationURL === null) {
							break;
						}

						// HTTP-redirect fetch step 5
						if (request.counter >= request.follow) {
							reject(new FetchError(`maximum redirect reached at: ${request.url}`, 'max-redirect'));
							finalize();
							return;
						}

```
If in the Default Lambda I force it to manual:

```js
		this[INTERNALS$2] = {
			method,
			redirect: init.redirect || input.redirect || 'manual',
			headers,
			parsedURL,
			signal
		};
```

**Describe the solution you'd like**
An option to specify how to handle redirects in rewrites.

**Comment by dphang** [comment]
I think the Next local server actually doesn't seem to follow redirects when doing rewrites. We could update the code to be more in sync with that.

Though the returned redirect location will be a relative path. For example, on my local server if I create a rewrite like so:

```js
      {
        source: "/external-rewrite",
        destination: "https://nextjs.org/blog/next-10/"
      }
```

It will return a 308 redirect with location of `/blog/next-10` which goes to `http://localhost:3000/blog/next-10` which is a 404. Hopefully it's fine for your case where the redirect should point to somewhere valid at the current domain?

**Comment by ungarida** [comment]
You are right, on localhost I did not have the problem I found out when I was setting up the production environment.

I did a similar test to yours just to double check and I can confirm NextJS is not following redirects. I added this configuration to the `rewrites` in `next.config.js`:

```js
      {
        source: "/302",
        destination: "https://httpstat.us/302"
      }
```
This is the resulting network flow when I called `http://localhost:3000/302`:
![20210306-091007_1367x698_screenshot](https://user-images.githubusercontent.com/3428837/110200016-da07cc80-7e5b-11eb-8522-48e6381cccc3.png)

The 302 response is reaching the browser with all the headers ( cookies especially ) and the redirect is performed client side.

I believe this is fundamental for the [incremental adoption of next.js](https://nextjs.org/blog/incremental-adoption#rewrites). Like in my case is pretty common to have a legacy system that you want to replace incrementally with the new app. This is how the architecture would look like ( for future reference ):

![incremental approach](https://user-images.githubusercontent.com/3428837/110200764-ccecdc80-7e5f-11eb-84ad-0bee34876641.png)
