### ISSUE TITLE
CDK Construct "An unexpected error has occurred" on a page that should 404

### ISSUE THREAD

**Issue by iDVB** [serverless-nextjs/serverless-next.js#931]
Deploying the CDK Construct and one of our existing NextJS apps I've been testing ISR and SSR. I'm testing build and runtime pages by increasing and decreasing the todos before and after build using the mockapi endpoint.
- pages at build time work
- pages at runtime return "An unexpected error has occurred" 

## ISR Not working ?
```javascript
import React from 'react'
import axios from 'axios'
import { useRouter } from 'next/router'

const Todo = ({ todo }) => {
  const router = useRouter()

  if (router.isFallback) {
    return <div>Loading....</div>
  }

  return (
    <>
      <p>{todo.id}</p>
      <p>{todo.title}</p>
      <p>{todo.completed}</p>
    </>
  )
}

export async function getStaticProps(_ctx) {
  const todoId = _ctx.params.pid

  let todo
  try {
    todo = await axios
      .get(`https://6005e7693698a80017de1170.mockapi.io/todos/${todoId}`)
      .then((resp) => resp.data)
  } catch (error) {
    return { notFound: true }
  }

  return {
    props: { todo },
    revalidate: 1,
  }
}

export async function getStaticPaths() {
  const todos = await axios
    .get('https://6005e7693698a80017de1170.mockapi.io/todos')
    .then((resp) => resp.data)
  const paths = todos.map((todo) => {
    return {
      params: { pid: todo.id },
    }
  })
  return {
    paths,
    fallback: true,
  }
}

export default Todo
```

**Comment by kirkness** [comment]
Hey @iDVB, serverless-next doesn't currently support ISG. Would be super nice, but I think it's a way off, a [few issues open about it as well](https://github.com/serverless-nextjs/serverless-next.js/issues/804).

I'm not 100% sure whether the issue you are seeing is ISG related, but it is likely.

**Comment by iDVB** [comment]
Thanks @kirkness , ya I am wondering what feature sets are missing.

if SSR still works, is there some way to increase the TTL on the CDN so that things cache a bit more rather than hitting the edge function each request? Is that function on the distro’s origin-request/response ? Just considering how we can turn up the caching if we want.
