### ISSUE TITLE
Locale detection not implemented?

### ISSUE THREAD

**Issue by raffij** [serverless-nextjs/serverless-next.js#933]
### Describe the bug

Next localeDetection is not working.

### Actual behavior

Viewing `/` doesn't redirect the user to `/en-GB`

### Expected behavior

Redirect `/` => `/en-GB` or `/en-US`

### Steps to reproduce

```
// next.config.js

export default {
  i18n: {
    localeDetection: true,
    locales: ['en-GB', 'en-US', 'none'],
    defaultLocale: 'none',
  }
}
```

### Versions

- OS/Environment:
- @sls-next/serverless-component version: 1.19.0-alpha.33
- Next.js version: 10.0.7

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
It should be - make sure you are forwarding `Accept-Language` header to the origin (by default it does, but if you override the forwarded headers you must add it back), otherwise the Lambda function doesn't know what the locale should be.

**Comment by raffij** [comment]
Ill double check tomorrow and see if we are doing anything weird.

**Comment by raffij** [comment]
Not been able to get it working.

I've checked the lambda package and localeDetection is set to true and cloudfront is forwarding headers.

Also checked with a test lambda call which i believe is correct and expect to be redirected to en-GB like i am in dev or running the server directly.

```
{
  "Records": [
    {
      "cf": {
        "config": {
          "distributionId": "EXAMPLE"
        },
        "request": {
          "uri": "/",
          "method": "GET",
          "origin": {
            "s3": {
              "region": "us-east-1",
              "domainName": "lunartunar"
            }
          },
          "headers": {
            "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8"
          }
        }
      }
    }
  ]
}
```

**Comment by raffij** [comment]
@dphang found the problem.

https://github.com/serverless-nextjs/serverless-next.js/blob/98e963b614f4be708156aada08654e115e43dc69/packages/libs/lambda-at-edge/src/routing/redirector.ts#L197

This is transformed to `en-gb`, but within source event.json and next.config.js it's `en-GB`

**Comment by dphang** [comment]
Sorry, was moving last week so didn't get a chance to look into much lately. I think we can do case-insensitive comparison

**Comment by raffij** [comment]
Hope your move went well.

Case insensitive should work, but might also be worth looking at the nextjs implementation as that also allows en fallback. Don't think a simple lowercase comparison would fix that bit.

In my project we actually needed location based locales so I used the cloudfront country code to do a redirect and that's worked well for us.

**Comment by dphang** [comment]
@raffij sounds good, do you know which code does the fallback, not sure I saw it in the link? We are using hapi/accept which I guess just detects locale like `en-gb` but I don't think it handles any fallback by itself

**Comment by raffij** [comment]
@dphang The code here is what I was referring to https://github.com/vercel/next.js/blob/b1a1c80e7cfa3ad8c35ced40fc5c153ee4316935/packages/next/build/webpack/loaders/next-serverless-loader/utils.ts#L342

They pass the following `Accept.language(browserString, localesArray)` so it does the matching for you?

**Comment by dphang** [comment]
Closing as I believe the original issue is solved for now...feel free to add another PR if there are further improvements
