### ISSUE TITLE
Rewrites to /api paths are resulting in 404

### ISSUE THREAD

**Issue by ungarida** [serverless-nextjs/serverless-next.js#939]
### Describe the bug
A configuration of next.config.js as follow:
```
module.exports = {
  target: 'serverless',
  rewrites: async () => [
    {
      source: '/:path*',
      destination: '/:path*',
    },
    {
      source: '/:path*',
      destination: '/api/proxy/:path*',
    },
  ],
}
```
A rewrite to an `/api` path is not gonna work and it is returning 404 page.

### Actual behavior
The current DefaultLambda is not taking in cosideration the manifest of apis, so can not detect if a rewrite is actually leading to a valid API. 

### Expected behavior
This is working in NextJS and it is actually a good workaround for incremental adoption using a proxy to point everything to the existing legacy system.

### Steps to reproduce
Should be enough to create an hello world API under `/pages/api` and a `next.config.js` configuration with a rewrite pointing to the API endpoint path.

### Versions
- OS/Environment: Manjaro Linux
- @sls-next/serverless-component version:@1.19.0-alpha.35
- Next.js version: v10.0.8-canary.5

### Additional context
It is a deal breaker since this was last resort to workaround this issue:
https://github.com/serverless-nextjs/serverless-next.js/issues/929

**Comment by dphang** [comment]
Yes, unfortunately this is limitation of having api lambda and default lambda be separate functions...cross lambda rewrites won't work in this case :(

It would require some refactoring to put all code in a single lambda if there are cross rewrites

I am working on completing locales and some bug fixes, so if you have a chance you could help look into this?

**Comment by ungarida** [comment]
I'll try to look into this in my spare time, right now have to deliver this new project so I will fallback on a classic nodejs server.
I'll keep you posted if I make any progress.

**Comment by nakashkumar** [comment]
is this fixed or will be fixed anytime soon?

**Comment by alexduros** [comment]
Hi, I'm having the same use case on my side. Do you know if there is a way to manage it directly with CloudFront directive on AWS, which could be a workaround to avoid this refacto ?

**Comment by alexduros** [comment]
@ungarida @dphang Figured out a workaround by creating specific behaviour on CF to route the traffic of a redirect to the Lambda@Edge function handling the API. 

For example, I have the following rewrite : 

```
      {
        source: '/sitemap.xml',
        destination: '/api/sitemap',
      },
```

So I created a behaviour making `/sitemap.xml` pointing the Lambda@Edge API function. The lambda is then able to perform the redirect. Not ideal but working solution ☺️.

**Comment by alexduros** [comment]
Hi, @dphang ! I tried to use built-in mechanism to write down those behaviours inside my `serverless.yml` configuration as following : 

```
    cloudfront:
      /sitemap.xml:
        minTTL: 0
        defaultTTL: 86400
        maxTTL: 31536000
        lambda@edge:
          viewer-request: arn:aws:lambda:us-east-1:775843081820:function:myFunc:myVersion
```

However, I ran into this error : 

```
CloudFront input failed validation. Could not find next.js pages for "/sitemap.xml"
```

Would be possible to whitelist also the rewrites/redirects paths ?

**Comment by dphang** [comment]
@alexduros ya I think we just allow behaviors for pages but I think we should just allow all kinds of paths... let me see if that makes sense

**Comment by alexduros** [comment]
@dphang I'm pretty new to serverless and the component architecture so if you can give directions on how to handle it, i would be happy to make a PR to introduce that whitelist.

**Comment by dphang** [comment]
@alexduros I removed the restriction so you should be able to create any cache behavior now. LMK if it works for you

**Comment by alexduros** [comment]
Thanks @dphang , will try it !

**Comment by alexduros** [comment]
After testing it the same way as here : https://github.com/serverless-nextjs/serverless-next.js/issues/939#issuecomment-911703122

I was not deploy it and got a `InvalidLambdaFunctionAssociation: The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 2019012 Max allowed: 1048576`. Actually the function referenced is the Lambda@Edge API function use by the default behaviours `/api*/  so I guess there is a logic to use a compressed version of it ?

**Comment by dphang** [comment]
Not sure but I think if you point to the same version it should work? The lambda should already be uploaded this point, the CF behavior should just be pointing to the function. If you update manually in CF behavior, does it work?

**Comment by alexduros** [comment]
Yes, that was also my understanding and It actually worked through CF but failed when referenced from the yml 🙃

**Comment by dphang** [comment]
Hm, I'm not quite sure why =/ 

Anyway I am working on moving API pages to be handled by the default lambda as well so that it's possible to support cross rewrites. The first PR to consolidate API pages is done here and available in the latest alpha: https://github.com/serverless-nextjs/serverless-next.js/pull/1632 which is experimentally available with `build.separateApiLambda = false`. (See https://github.com/serverless-nextjs/serverless-next.js/blob/5d6ff2edbf53c0a7e109499d54c7a652ac648dfc/packages/e2e-tests/next-app-experimental/serverless.yml#L8-L8 for an example).

And I just need to rework the rewrite logic. Might be worth investing time there since it'd be the ideal solution..hoping to get it out by end of the week

**Comment by alexduros** [comment]
Perfect! Will test it. Thank you.
