### ISSUE TITLE
Error deploying using existing CloudFront OAI Id

### ISSUE THREAD

**Issue by jmateosbb** [serverless-nextjs/serverless-next.js#944]
### Describe the bug

When providing a custom `originAccessIdentityId` for `cloudfront` inside inputs, the deployment fails with the following error: 

```
  error:
  Error: CloudFront input failed validation. Could not find next.js pages for "originAccessIdentityId"
    at NextjsComponent.validatePathPatterns (/Users/xxxxxxx/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/@sls-next/serverless-component/dist/component.js:97:19)
    at NextjsComponent.<anonymous> (/Users/xxxxxxx/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/@sls-next/serverless-component/dist/component.js:346:18)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxxxxxx/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0/node_modules/@sls-next/serverless-component/dist/component.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

  11s › myNextApplication › Error: CloudFront input failed validation. Could not find next.js pages for "originAccessIdentityId"
```

### Actual behavior

Deployment fails

### Expected behavior

Deployment succeeds using the defined `originAccessIdentityId`

### Steps to reproduce

Include arguments for for an existing `CloudFront` distribution that includes a `distributionId` and a `originAccessIdentityId` you've created before.

### Screenshots/Code/Logs

```
myNextApplication:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    name: ${env.AAAAA}
    roleArn: ${env.BBBBB}
    bucketName: ${env.CCCCC}
    bucketRegion: ${env.DDDDD}
    cloudfront:
      distributionId: ${env.EEEEE}
      originAccessIdentityId: ${env.FFFFF}
```

### Versions

- OS/Environment: Darwin Kernel Version 20.3.0
- @sls-next/serverless-component version: 1.18.0
- Next.js version: Next.js v9.0.2

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by raffij** [comment]
I wrote the code that allows this config and it was added with version: 1.19.0-alpha.9

Have you tried the latest version: 1.19.0-alpha.37 ?
