### ISSUE TITLE
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions.

### ISSUE THREAD

**Issue by mcnamara-charles** [serverless-nextjs/serverless-next.js#949]
### Describe the bug

In development my login and logout system works. In production it will always throw the error that is the title. Upon investigation with cloudwatch It revealed this subsequent error:

2021-03-16T12:34:42.147Z 4c0268ab-76ba-46e5-8a94-99a2a19586ce ERROR Invoke Error { "errorType": "TypeError", "errorMessage": "Cannot read property '0' of undefined", "stack": [ "TypeError: Cannot read property '0' of undefined", " at isOriginResponse (/var/task/index.js:6236:25)", " at Runtime.handler$1 [as handler] (/var/task/index.js:5949:9)", " at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)" ] }

My lambdas have been given full permissions and should have no trouble meeting permission requirements

These errors prevent the page from even loading, as the fetch is requested on page load.

### Screenshots/Code/Logs
If applicable, here is my serverless configuration:

myNextApplication:
  service: evote
  component: "@sls-next/serverless-component@1.18.0"
  custom:
   defaultRegion: us-west-2
   defaultEnvironmentGroup: dev
  provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    profile: evote
  inputs:
    domain: "evote.space"
    roleArn: "arn:aws:iam::Theresaproperroleherebutimexcludingitforsecurity"
    bucketName: "evote-serverless"
    build:
      env:
        USER_TABLE_NAME: Users

### Versions

- OS/Environment: Linux Mint
- @sls-next/serverless-component version: @sls-next/serverless-component@1.18.0

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by raffij** [comment]
Are you familiar with the aws console and how to download your lambda function? If so check the line that is erroring and paste it here. If you are deploying locally you can also find the file in the .serverless-nextjs for.

**Comment by mcnamara-charles** [comment]
Essentially I'm an idiot, don't worry about it. 😂

**Comment by tejasadvait** [comment]
Hey,
I am facing a similar issue except for the error message I get is as follows:
{"errorType": "TypeError",
 "errorMessage": "Cannot read property 'style' of undefined",...}
@mcnamara-charles  how were you able to solve it?

**Comment by mcnamara-charles** [comment]
@tejasadvait That's not a similar issue but That's a pretty simple solve. In next.js you can't use style tags on elements. Instead use style jsx elements to hold css, or look into using css stylesheets with next.js

**Comment by mcnamara-charles** [comment]
> Are you familiar with the aws console and how to download your lambda function? If so check the line that is erroring and paste it here. If you are deploying locally you can also find the file in the .serverless-nextjs dir.
> 
> My first thought is you are not forwarding the headers you need from cloudfront.

It actually ended up being that after I deleted my replicated tables I never put them back with caused that error, although there were subsequent errors involving permissions. Actually what I'm curious about now is why my lambda's aren't using the role I provide them.

**Comment by tejasadvait** [comment]
Hey @mcnamara-charles, thank you for your response. This occurs once my Next.js app is deployed and when I try to access one of the pages using the Cloudfront link.

**Comment by mcnamara-charles** [comment]
> Hey @mcnamara-charles, thank you for your response. This occurs once my Next.js app is deployed and when I try to access one of the pages using the Cloudfront link.

Is this an API page or a regular page? And have you configured cloudwatch?

**Comment by tejasadvait** [comment]
It's a regular server-side rendered page and I have configured Cloudwatch to log events from my Cloudfront distribution.

**Comment by tejasadvait** [comment]
What I notice is that getServerSideProps doesn't get triggered. Sometimes it does, and that successfully generates the server-side rendered page. Otherwise, I keep getting a 503 error.

**Comment by mcnamara-charles** [comment]
> What I notice is that getServerSideProps doesn't get triggered. Sometimes it does, and that successfully generates the server-side rendered page. Otherwise, I keep getting a 503 error.

What really helped me figure out my issue was console log statements on the server side. Remember that even though they don't show up in the Chrome console they will show up in your CloudWatch

**Comment by tejasadvait** [comment]
So I have logging statements in getServerSideProps but they do not show up in CloudWatch :(

**Comment by mcnamara-charles** [comment]
What that tells me is that there is an error in your get server side props call. Here are my suggestions, firstly, check your call. You should have a default export and a server side call and you should also not have a client side props call as only one can be present. The way I like to do it is turning my initial return into a variable, then calling server side props, then exporting it all at once. I can show an example if you like. Secondly, check your permissions. Are your lambdas executing with only the default cloudwatch permissions? This makes server side pages, APIS and DataBases impossible to access.

**Comment by tejasadvait** [comment]
Hey @mcnamara-charles ,

Thank you for your detailed response. It would be really helpful to see an example for the proper usage of getServerSideProps. Also, how can I update the default Cloudwatch permissions? Thank you again. I appreciate your help on this matter.

**Comment by mcnamara-charles** [comment]
@tejasadvait So here's what I had to do. So go to your AWS console and create a new IAM role with administrator privileges. Go to your lambda console and perform the following actions to all of your lambdas (there should only be 2-3):
1.  Open your lambda 
2. Go to configuration then permissions
3. The execution role is at the top, click edit
4. Assign it your new role
5. Scroll back to the top of that page and find where it says "Actions"
6. Under Actions click deploy to Lambda@Edge
7. At the options at the top click "Use existing CloudFront trigger on this function"
8. Click deploy then move on to your next one. It may take several minutes for the lambdas to replicate. You'll have to do this each time you redeploy your software.

As for the get ServerSideProps, here's one of my examples. In my code I use it to check session data:
`  
import Container from "../components/container";
import Layout from "../components/layout";
import HomeImage from "../components/home-image";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { withIronSession } from "next-iron-session";

function Features({ user }) {
    return (
      <>
        <Layout user={user}>
          <Head>
            <title>Evote Serverless Features</title>
          </Head>
          <Container>
            <HomeImage />
            <div className="index">
              <h1>evote-serverless<span className="version-tag"> Features</span></h1>
              <div className="index-content">
                <Link href="/assets/docs/evote_user_manual.pdf">
                  <a
                    className="btn noeffect"
                    id="manual"
                  >
                  <i className="fas fa-download"></i>
                  Download User Manual
                  </a>
                </Link>
                <ul className="feature-list">
                  <li>The system is open source and anybody can check the source code. The code is small and written in the Python language. This makes it easy for professionals in the field to check it.</li>
                  <li>The system can run as a service and one installation can run mutiple elections. Anybody can login into the system, create a new election, register voters and managers, and customize the ballot using an easy to use WYSIWYG interface.</li>
                  <li>The system communicates with voters and managers by email.</li>
                  <li>Voters do not need to login into the system to vote. They only need to click on the link in the notification email, fill a web form and submit.</li>
                  <li>Each voter can only vote once per election.</li>
                  <li>Results are computed automatically at closing of the election and published.</li>
                  <li>Voting is completely anonymous. Even a hacker with a complete database dump of the system would not be able to link voters to ballots.</li>
                  <li>Each voter can check at any time that his vote has been properly recorded and not altered.</li>
                  <li>Each voter can independently and at any time perform an election recount.</li>
                  <li>Upon voting, each voter receives an email receipt containing a copy of their filled and anonymized ballot.</li>
                  <li>Managers are notified by email when a new vote is cast and receive a copy of the anonymized ballot.</li>
                  <li>All ballots, anonymized and digitally signed, are published, along with instructions to verify the digital signature.</li>
                </ul>
              </div>
            </div>
          </Container>
        </Layout>
      </>
  );
}

export const getServerSideProps = withIronSession(
  async ({ req, res }) => {
    const user = req.session.get("user");
    console.log(user);

    if (!user) {
      return { props: {} };
    }
    return {
      props: { user }
    };
  },
  {
    cookieName: "LOGIN",
    cookieOptions: {
      secure: process.env.NODE_ENV === "production" ? true : false
    },
    password: process.env.APPLICATION_SECRET
  }
);

export default Features;`

**Comment by tejasadvait** [comment]
Hey @mcnamara-charles,

Thank you again for the detailed response. I tried following your steps and it looks like it is not a permission issue but a Cloudfront caching/Lambda cold-start issue. Your suggestions and example have been quite helpful for my learning. I am going to create a separate issue for my problem. Thank you for all the help.

**Comment by flandycheng** [comment]
@tejasadvait  yes, it is not a permission issue, it happens occasionally in my cases.  It might be a cold-start issue, because after the first success of an execution, the following execution are very likely to be successful.
