### ISSUE TITLE
CDK Construct: CachePolicy names must be unique

### ISSUE THREAD

**Issue by kmcarter** [serverless-nextjs/serverless-next.js#952]
### Describe the bug
I'm experimenting with the NextJSLambdaEdge construct and recently ran into failures to deploy (see console output below).

With a [little research](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/571#issuecomment-707969492) it appears that CachePolicy names must be unique across stacks, and I will be deploying at least two stacks for different environments. This appears to be issue I'm having, as the error code in my CloudTrail event history log is `CachePolicyAlreadyExists`. In reviewing the construct's code, it appears that the 3 CachePolicy names are hardcoded in the construct and cannot be overwritten, which means (I think) that only one stack can be created using this construct.

### Actual behavior
I receive this error upon deploying my stack:

```
35/42 | 11:57:25 AM | CREATE_FAILED        | AWS::CloudFront::CachePolicy                    | dev-NaccPortal/NextLambdaCache (devNaccPortalNextLambdaCacheA470A77A) Internal error reported from downstream service 
during operation 'AWS::CloudFront::CachePolicy'.
        new CachePolicy (C:\Users\Kelly\Source\naccportal\cdk\node_modules\@aws-cdk\aws-cloudfront\lib\cache-policy.js:28:26)
        \_ new NextJSLambdaEdge (C:\Users\Kelly\Source\naccportal\cdk\node_modules\@sls-next\cdk-construct\dist\index.js:150:39)
        \_ new CdkStack (C:\Users\Kelly\Source\naccportal\cdk\lib\cdk-stack.js:14:20)
        \_ C:\Users\Kelly\Source\naccportal\cdk\bin\cdk.js:30:5
 35/42 | 11:57:42 AM | CREATE_FAILED        | AWS::CloudFront::CachePolicy                    | dev-NaccPortal/NextImageCache (devNaccPortalNextImageCache5CA9C7EB) Internal error reported from downstream service during operation 'AWS::CloudFront::CachePolicy'.
        new CachePolicy (C:\Users\Kelly\Source\naccportal\cdk\node_modules\@aws-cdk\aws-cloudfront\lib\cache-policy.js:28:26)
        \_ new NextJSLambdaEdge (C:\Users\Kelly\Source\naccportal\cdk\node_modules\@sls-next\cdk-construct\dist\index.js:139:38)
        \_ new CdkStack (C:\Users\Kelly\Source\naccportal\cdk\lib\cdk-stack.js:14:20)
        \_ C:\Users\Kelly\Source\naccportal\cdk\bin\cdk.js:30:5
 35/42 | 11:57:50 AM | CREATE_FAILED        | AWS::CloudFront::CachePolicy                    | dev-NaccPortal/NextStaticsCache (devNaccPortalNextStaticsCache22B63382) Internal error reported from downstream service during operation 'AWS::CloudFront::CachePolicy'.
        new CachePolicy (C:\Users\Kelly\Source\naccportal\cdk\node_modules\@aws-cdk\aws-cloudfront\lib\cache-policy.js:28:26)
        \_ new NextJSLambdaEdge (C:\Users\Kelly\Source\naccportal\cdk\node_modules\@sls-next\cdk-construct\dist\index.js:128:40)
        \_ new CdkStack (C:\Users\Kelly\Source\naccportal\cdk\lib\cdk-stack.js:14:20)
        \_ C:\Users\Kelly\Source\naccportal\cdk\bin\cdk.js:30:5
```

CloudTrial console result:
![image](https://user-images.githubusercontent.com/4644617/111526965-94c98180-871c-11eb-8c21-4a471f84470f.png)

### Expected behavior
I would have expected the stack to deploy without error, as it did for the previously deployed stack that still exists in my AWS account.

### Steps to reproduce
1. Deploy a stack using the NextJSLambdaEdge construct using `cdk deploy`.
2. Change the name of the stack so that CloudFormation recognizes it as a new stack.
3. Attempt to deploy the stack using `cdk deploy`.

### Screenshots/Code/Logs

A [gist](https://gist.github.com/kmcarter/177ae5c01ed9132878f457d676f9e7ca) of my CDK stack code - note that I use a prefix to identify what environment each stack is for.

### Versions

- OS/Environment: Windows 10, 64bit
- @sls-next/serverless-component version: not in use
- @sls-next/cdk-construct: 1.19.0-alpha.28
- @sls-next/lambda-at-edge: 1.8.0-alpha.15
- Next.js version: 10.0.7

### Additional context
I may take a shot at a PR, so happy to hear recommendations/suggestions as I pursue that. My initial thought is to add configuration similar to how one can configure Lambda names so that a developer can ensure uniqueness. However, there is also #947 and a solution for that issue would likely solve this issue as well.

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by kirkness** [comment]
Cheers for reporting @kmcarter, this has actually already been resolved in [this commit](https://github.com/serverless-nextjs/serverless-next.js/commit/81d9d18f0bd82c36be47c4bda8fa51d1b7e422b0). Currently this is only released under `alpha`.

**Comment by kmcarter** [comment]
@kirkness My apologies, I did not find #912 in my searching, and didn't see an alpha that went up that high. Thanks for the quick response!
