### ISSUE TITLE
How to enable warmup plugin?

### ISSUE THREAD

**Issue by Carel155** [serverless-nextjs/serverless-next.js#956]
Hi,

I am trying to enable serverless-plugin-warmup plugin but i can't figure out how do to it with component.

Also is there a way to send back early response when serverless-plugin-warmup calls the function?

**Comment by antboy2020** [comment]
Were you able to run `serverless info` from your project home?

**Comment by dphang** [comment]
I don't think that plugin will work as intended as it is meant for regular serverless framework which is a single Lambda in a single region. Even if you can get it running and pointing to the Lambda, it will only warm the us-east-1 region's Lambda. With this component, it uses Lambda@Edge which could spin up a Lambda in any of the CloudFront locations (depending on viewer's location) - so you'd need to keep a lot of different locations warm.

You could kind of work around it by creating a regular Lambda that periodically calls a dummy page in your CloudFront distribution, and deploy this in multiple regions. But there aren't enough Lambda regions as there are CloudFront regions, so it may not work too well.

**Comment by Carel155** [comment]
Thanks for the clear explanation
