### ISSUE TITLE
How to access the browser origin url when SSR 

### ISSUE THREAD

**Issue by vkmita** [serverless-nextjs/serverless-next.js#958]
The origin currently is some AWS server and I would like the SSR server to pass the origin to my API server. Is it currently not possible to access the origin?

Thank you!

**Comment by dphang** [comment]
I think you can follow here: https://github.com/serverless-nextjs/serverless-next.js#when-accessing-the-host-header-in-my-ssr-pages-or-apis-i-get-an-s3-domain-instead-of-the-cloudfront-distribution-or-my-domain-name, you need to forward the host header, otherwise it is set to some S3 URL
