### ISSUE TITLE
Error during build time when you import a module in 'next.config.js' 

### ISSUE THREAD

**Issue by jginorio** [serverless-nextjs/serverless-next.js#959]
### Describe the bug
Error during build time when you import a module in 'next.config.js' 

### Actual behavior
My project works locally but When I try to deploy it using 'npx serverless' I get the following error:
```
Unhandled error during request: Error: Cannot find module '/Users/user/Documents/Nextjs/findit-nextjs/next-i18next.config.js'
    at webpackEmptyContext (/Users/user/Documents/Nextjs/findit-nextjs/.next/serverless/pages/index.js:25505:10)
    at /Users/user/Documents/Nextjs/findit-nextjs/.next/serverless/pages/index.js:379:90
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND'
}
```

### next.config.js
```
const { i18n } = require('./next-i18next.config.js');

module.exports = {
	images: {
		domains: [ 'mydomain.com' ]
	},
	i18n
};

```

### next-i18next.config.js
```
module.exports = {
	i18n: {
		localeDetection: false,
		locales: [ 'en', 'es' ],
		defaultLocale: 'es'
	}
};
```

### Versions

- OS/Environment: macOS Catalina v10.15.4
- @sls-next/serverless-component version:
 

  1. **1.19.0-alpha**: 38,37,36
  2. **1.18.0**

- Next.js version: 10.0.9

- ✅  You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- ✅  Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by jginorio** [comment]
### UPDATE FIX ✅
I was successfully able to deploy the project by adding: `useServerlessTraceTarget: true` to my `inputs` in my _serverless.yml_ file

**Comment by Reiiya** [comment]
Hey @jginorio, which next-i18next version did you use? I am using the latest and your fix did not do it for me :/ I am getting the same error as you. I eventually hacked around it by not using next-i18next config at all (used a differently named config file that i put into every function by hand).

**Comment by jginorio** [comment]
Hi, the version of next-i18next I was "8.1.2"

**Comment by izio38** [comment]
> Hey @jginorio, which next-i18next version did you use? I am using the latest and your fix did not do it for me :/ I am getting the same error as you. I eventually hacked around it by not using next-i18next config at all (used a differently named config file that i put into every function by hand).

Same here, did you found a 'not ugly fix' ? @Reiiya 

I am using version "8.6.0".
