### ISSUE TITLE
503 Error: The request could not be satisfied.

### ISSUE THREAD

**Issue by tejasadvait** [serverless-nextjs/serverless-next.js#960]
### Describe the bug

I have a Next.js app deployed on AWS using the serverless-next.js component. I am also using AWS Amplify for SSR authentication. After logging in successfully, the user is taken to an overview page. This overview page exports getServerSideProps to fetch some data by making Axios get requests. This overview page loads successfully. However, there are other similar pages that export getServerSideProps, and Cloudfront shows a 503 error page when these pages are accessed.

The interesting thing is that after refreshing these pages continuously, these pages are rendered successfully. I suspect that this is a Cloudfront caching/Lambda cold start issue. I have noticed that whenever a 503 error is shown, getServerSideProps does not get called by the server. Whenever any of these pages are rendered successfully, getServerSideProps corresponding to that page is called successfully. I have confirmed this by putting logging statements in getServerSideProps and reviewing the Cloudwatch log.

Whenever the 503 error is thrown, the following statements are present in the Cloudwatch log:

WARN	[WARN] 25:45.503 ClientDevice_Browser - No navigator object available to get browser client info.
ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'style' of undefined",
    "stack": [
        "TypeError: Cannot read property 'style' of undefined",
        "    at Object.p4r7 (/var/task/pages/admin/employees.js:203024:52)",
        "    at __webpack_require__ (/var/task/pages/admin/employees.js:23:31)",
        "    at Object.nikJ (/var/task/pages/admin/employees.js:199965:25)",
        "    at __webpack_require__ (/var/task/pages/admin/employees.js:23:31)",
        "    at Object.cuOD (/var/task/pages/admin/employees.js:146604:18)",
        "    at __webpack_require__ (/var/task/pages/admin/employees.js:23:31)",
        "    at Object.RG8o (/var/task/pages/admin/employees.js:112992:81)",
        "    at __webpack_require__ (/var/task/pages/admin/employees.js:23:31)",
        "    at Object.i6E2 (/var/task/pages/admin/employees.js:167338:87)",
        "    at __webpack_require__ (/var/task/pages/admin/employees.js:23:31)"
    ]
}

As stated earlier, this 503 error is an intermittent issue. It comes and goes on its own. Sometimes pages are rendered successfully and sometimes they are not.

### Actual behavior

Behavior is as described above ---  when trying to access certain pages, Cloudfront throws a 503 error and it renders the page successfully after refreshing continuously. getServerSideProps is not being invoked by the server when trying to access server-side rendered pages.

### Expected behavior

Server-side rendered pages are rendered successfully and delivered to the user without 503 error. getServerSideProps is invoked at every request.

### Steps to reproduce

Seems like this problem is specific to my codebase and deployment. I'm not sure how others would be able to reproduce it. I am sharing my serverless.yml and Cloudwatch log below.

### Screenshots/Code/Logs

serverless.yml:

myNextApp:
    org: myApp
    component: "@sls-next/serverless-component@1.19.0-alpha.32"
    inputs:
      memory: 2048
      timeout:
        defaultLambda: 30

        imageLambda: 30
        apiLambda: 30

Cloudwatch Log on Error:
<img width="1014" alt="Screen Shot 2021-03-22 at 5 34 35 PM" src="https://user-images.githubusercontent.com/76187667/112061457-e7e46f80-8b34-11eb-9c46-0aeb45fbb11c.png">

Cloudwatch Log on Success:
<img width="1018" alt="Screen Shot 2021-03-22 at 5 38 22 PM" src="https://user-images.githubusercontent.com/76187667/112061868-7c4ed200-8b35-11eb-9c92-1c8ba8cb694a.png">

### Versions

- OS/Environment: macOS 10.15.7
- @sls-next/serverless-component version: tried with 1.18.0 & 1.19.0-alpha.32
- Next.js version: 10.0.6

### Additional context

I have tried to give some context above. I apologize if it is not sufficient. Please let me know if more information is required.

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

Thank you in advance.

**Comment by dphang** [comment]
I am not sure but it seems 

```
{
"errorType": "TypeError",
"errorMessage": "Cannot read property 'style' of undefined",
"stack": [
"TypeError: Cannot read property 'style' of undefined",
" at Object.p4r7 (/var/task/pages/admin/employees.js:203024:52)",
```

doesn't seem like part of this component's code, as we don't use webpack but rollup.js to bundle the code. It seems to be failing in webpack require, likely why you don't even see `getServerSideProps` being hit. Can you please check the line that is failing in `employees.js`?
