### ISSUE TITLE
Best way to target a current deploy?

### ISSUE THREAD

**Issue by jaredwiener** [serverless-nextjs/serverless-next.js#962]
My team and I are using this component, and it works great! Except...

Every time one of us deploys, we seem to create a whole new instance on the AWS account. Is there a way to target the same instance? Or do I need to just manually set every ARN for every role, Lambda, etc?

**Comment by raffij** [comment]
You need to find a way to share your .serverless dir. If you only have one environment then you can add the directory to git. Otherwise search for "Multi-stage deployments" in the repo for some suggestions.

**Comment by jaredwiener** [comment]
@raffij thank you!
