### ISSUE TITLE
RequestEntityTooLargeException randomly began erroring on deploys

### ISSUE THREAD

**Issue by jonahallibone** [serverless-nextjs/serverless-next.js#979]
### Describe the bug

I randomly started getting
```
RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation
```
I auto-deploy my site to pull in new content every morning, and the past few mornings it has failed. I've seen mentioned in other issues that this could be due to the lambda size generated by the api routes or server side rendering. I have no server rendered pages, everything is statically optimized. I have two (small) api routes for adding to my Mailchimp list, as well as my sending an email via Sendgrid's Node API. If there's something else I could check that would be great. I'm on the most recent alpha now, however it started happening to me after I'd been using alpha.32 for a while so I upgraded to check for a difference. I should also mention I generate 716 pages via `getStaticProps` and `getStaticPaths`

### Actual behavior

By deploys fail because of an error related to the RequestEntity being too large. Full error below:
```
RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation
--
972 | at Object.extractError (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/protocol/json.js:52:27)
973 | at Request.extractError (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
974 | at Request.callListeners (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
975 | at Request.emit (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
976 | at Request.emit (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/request.js:688:14)
977 | at Request.transition (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/request.js:22:10)
978 | at AcceptorStateMachine.runTo (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/state_machine.js:14:12)
979 | at /root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/state_machine.js:26:10
980 | at Request.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/request.js:38:9)
981 | at Request.<anonymous> (/root/.serverless/components/registry/npm/@sls-next/serverless-component@1.19.0-alpha.41/node_modules/aws-sdk/lib/request.js:690:12) {
982 | code: 'RequestEntityTooLargeException',
983 | time: 2021-04-01T20:17:48.596Z,
984 | requestId: '9311f8d0-30db-455b-a6fa-f906ff6b36bf',
985 | statusCode: 413,
986 | retryable: false,
987 | retryDelay: 43.53153814869912
```

### Expected behavior

My site should build all my static deps and depoy properly.

### Steps to reproduce

I attempt to deploy my site.

### Versions

- OS/Environment: macOS / Codebuild Linux
- @sls-next/serverless-component version: ` component: "@sls-next/serverless-component@1.19.0-alpha.41"`
- Next.js version: 10.0.7

### Additional context

Here is the output of my build from Next: 
<img width="806" alt="Screen Shot 2021-04-01 at 5 29 45 PM" src="https://user-images.githubusercontent.com/8886318/113356208-e9215380-930f-11eb-9e9c-eeddac5773cc.png">

**Comment by dphang** [comment]
As you mentioned, this happens when Lambda function is too large, can you check and confirm which Lambda it is failing on? Is it default, API, or image lambda? Maybe there is an issue where some old files are not cleared properly before deploying...?

**Comment by aomv** [comment]
I got this repeatedly just now with alpha-41 on a just-created single page project with one image (though not using next/image). Tried with alpha-40 instead and it worked as expected.

**Comment by dphang** [comment]
I just checked all the handler sizes and it seems that for the image-lambda, the `node_modules` is like 300 MB (!)`lambda-at-edge/dist/sharp_node_modules`, it seems to be growing in size continuously on each publish... it should be like 30 MB at most, which will fit in Lambda once compressed. Let me check and see what is happening with it...

**Comment by dphang** [comment]
Found the problem - the `sharp_node_modules` used for the image lambda gets copied into `dist/sharp_node_modules` directory during the `yarn` build, and then I publish the package to npm. So that when you deploy, it gets copied into the Lambda. However, for some reason this directory kept growing in size every time I published, as it runs `yarn` command and it copies again, even though it's the same files. Not sure why that's the case

Seems the fix is to ensure the `dist/sharp_node_modules` is clean before re-copying, to ensure its size isn't growing indefinitely... I'll probably mark some of the later versions as deprecated due to this...

**Comment by jonahallibone** [comment]
@dphang thanks for getting back so quickly. Is there anything I can do before you push out a fix or should I just wait?

**Comment by dphang** [comment]
@jonahallibone I am just about to publish a fix, the existing package is busted nothing you can do, best thing is to bump the version (don't want to republish over it in case it breaks someone using it)

**Comment by jonahallibone** [comment]
@dphang ok great, thanks so much!
