### ISSUE TITLE
Question: How to create custom routes with locale in path?

### ISSUE THREAD

**Issue by mekwall** [serverless-nextjs/serverless-next.js#98]
It's recommended for SEO to have separate url per locale so I'm trying to create custom routes that is prefixed with `{language}/` but I cannot get this to work. It fails to deploy with the following error:

```
An error occurred: ApiGatewayResourceLanguageVar - A sibling ({proxy+}) of this resource already has a variable path part -- only one is allowed (Service: AmazonApiGa00; Error Code: BadRequestException; Request ID: <redacted>).
```

Any ideas on how to solve this?

**Comment by danielcondemarin** [comment]
Interesting. I believe what's happening here is that the catch all route added by the plugin for rendering the next 404 page, uses the path variable `/{proxy+}` and that is conflicting with your homepage path `/{language}` and potentially other paths like /{language}/blog etc.
For example, a request comes in with `/en` or some nonsense `/xyz`  , api gateway wouldn't know whether to match using `/{proxy+}` or `/{language}`.

I never particularly liked using a catch all route like that just for rendering next error pages but seemed to do the job fine until now 😄 Don't know right now how this can be solved but I'll look into it.

**Comment by mekwall** [comment]
@danielcondemarin What if we could add our own custom router to the catch all handler, and also allow us to define the catch all url structure? That would allow us to create redirectors and other cool things. Well defined urls would still route directly to the lambda handler like it is right now.

**Comment by danielcondemarin** [comment]
@mekwall Did you try using a custom route for the `_error` page? For example:

```
plugins:
  - serverless-nextjs-plugin

custom:
  serverless-nextjs:
    routes:
      - src: _error
        path: {language}/{proxy+}
```

I'm hoping this overrides the default /{proxy+} catch all route, athough I've not actually tried it.

I've got another idea similar to what you proposed but I think is worth trying this first.

**Comment by mekwall** [comment]
@danielcondemarin Will try and report back with my findings. Thanks!

**Comment by dphang** [comment]
Closed since serverless-nextjs-plugin is deprecated - locale support is in the new component (Lambda@Edge for now only)
