### ISSUE TITLE
Returning XML causes 502

### ISSUE THREAD

**Issue by darren-charterindex** [serverless-nextjs/serverless-next.js#981]
Using [next-sitemap](https://github.com/iamvishnusankar/next-sitemap) to render a server-side sitemap as detailed in the [readme](https://github.com/iamvishnusankar/next-sitemap#generating-dynamicserver-side-sitemaps), returns the following from Cloudfront:

```
502 ERROR
The request could not be satisfied.
The Lambda function returned invalid JSON: The JSON output is not parsable. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
```

Using versions:

```
@sls-next/serverless-component@1.19.0-alpha.42
"next-sitemap": "^1.6.18",
"next": "^10.1.2",
```

**Comment by raffij** [comment]
Is this error when deploying or when trying to load sitemap.xml? If the later have you checked your S3 bucket to see if it was generated?

**Comment by darren-charterindex** [comment]
hi @raffij, the sitemap I'm referring to is a Next.js page as per the (readme)[https://github.com/iamvishnusankar/next-sitemap#generating-dynamicserver-side-sitemaps]

**Comment by dphang** [comment]
Might be related to: https://github.com/serverless-nextjs/serverless-next.js/issues/525. It seems like a Lambda@Edge limitation, if returning more than 1 MB of data through CloudFront it might cause 502s. How big is the server-site sitemap?

**Comment by darren-charterindex** [comment]
It is over 1MB. Now breaking it down and will report back.

**Comment by darren-charterindex** [comment]
Reduced to under 1MB and works as expected. Thank you.
