### ISSUE TITLE
503 ERROR The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. 

### ISSUE THREAD

**Issue by techexe-code** [serverless-nextjs/serverless-next.js#984]
I have used aws-sdk for DynamoDB query in api pages. Working fine in localhost but I am getting this error in live 

import aws from 'aws-sdk';
const client = new aws.DynamoDB.DocumentClient({
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    region: 'xx-xxxx-xx',
    params: {
      TableName: 'xxxx'
    }
  });
  const handler = async (req, res) => {
const params = {
    FilterExpression: "contains(#title, :title)", 
    ExpressionAttributeNames: {
        "#title": "title",
    }, 
    ExpressionAttributeValues: { ":title": 'a' },
}
    const data = await client.scan(params).promise();
    res.status(200).json(data);
};
export default handler;

<img width="1439" alt="Screenshot 2021-04-05 at 11 09 16 PM" src="https://user-images.githubusercontent.com/8767521/113605237-0170d580-9664-11eb-8bb3-c88811012958.png">

**Comment by aomv** [comment]
Since interacting with DynamoDB requires permissions outside of the default `AWSLambdaBasicExecutionRole`, you will need to create and specify a custom policy or role (as described here: [https://github.com/serverless-nextjs/serverless-next.js#aws-permissions](https://github.com/serverless-nextjs/serverless-next.js#aws-permissions)).

**Comment by techexe-code** [comment]
I have already attached dynamoDB policy with existing role 

when I test lambda function from the console, I am getting this error 

{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "UnrecognizedClientException: The security token included in the request is invalid.",
  "trace": [
    "Runtime.UnhandledPromiseRejection: UnrecognizedClientException: The security token included in the request is invalid.",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:314:20)",
    "    at process.EventEmitter.emit (domain.js:483:12)",
    "    at processPromiseRejections (internal/process/promises.js:209:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
  ]
}

**Comment by dphang** [comment]
I think it probably is related to permissions.

You should try hitting the CloudFront endpoint in browser and then post the CloudWatch logs, I think that should help more (not sure if testing from console will work since it directly invokes Lambda, not from CloudFront).

**Comment by techexe-code** [comment]
Thanks @dphang 

It's working fine now
