### ISSUE TITLE
503 error on pages that user getServerSideProps, Lambda@edge error Cannot find module '../../chunks/188.5cfa7090ba8f9961a3f8.js'

### ISSUE THREAD

**Issue by 7ruth** [serverless-nextjs/serverless-next.js#985]
### Describe the bug

I get the following on a page that uses getServerSideProps:

```The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.```

### Actual behavior
I have a page that uses getServerSideProps (works locally fine, but not when deployed), when I navigate to that page through a click, it works fine (mostly, sometimes I also get a 503). When I open in new tab by right clicking, I always get a 503.

### Expected behavior
Page loads with server's data.

### Steps to reproduce
Just using getServerSideProps to build the page and then deploying it.

### Screenshots/Code/Logs
serverless.yml:
```awsNextApp:
  component: "@sls-next/serverless-component@1.19.0-alpha.42"
```

My Lambda@edge logs example:
```
2021-04-08T05:23:32.733Z	9cda5568-45bc-45ed-9a98-53f0681872da	ERROR	Error: Cannot find module '../../chunks/188.5cfa7090ba8f9961a3f8.js'
Require stack:
- /var/task/pages/listings/[urlAddress].js
- /var/task/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.__webpack_require__.f.require (/var/task/pages/listings/[urlAddress].js:263109:28)
    at /var/task/pages/listings/[urlAddress].js:263037:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (/var/task/pages/listings/[urlAddress].js:263036:67)
    at __webpack_modules__.11522.Layout.loadableGenerated.webpack (/var/task/pages/listings/[urlAddress].js:225066:96)
    at LoadableSubscription.load [as _loadFn] (/var/task/pages/listings/[urlAddress].js:221459:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/pages/listings/[urlAddress].js',
    '/var/task/index.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
```

### Versions

- OS/Environment: Big Sur
- @sls-next/serverless-component version: 1.19.0-alpha.42
- Next.js version: 10.0.6

### Checklist

- [- ] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [- ] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Looks like it's your SSR code trying to find this file which is split out from webpack `../../chunks/188.5cfa7090ba8f9961a3f8.js`. Can you elaborate what this file does and how it? 

Usually we expect the entire SSR page JS to be bundled in one file, I believe Next.js should bundle it with webpack, but maybe if you are using some special library/dependency it might not be properly bundled into one file. This component is just copying all the pages from `.next` folder into `.serverless_nextjs` to then upload to Lambda, so I'm thinking it might not have all the JS files from `.next` folder (that's why it could still work locally?).

Can you post how the `.serverless_nextjs` as well as `.next` folder looks like so we can see what is missing?

**Comment by insomenia-seongjun** [comment]
Any other changes? I am having the same problem.

**Comment by tim1uphealth** [comment]
@7ruth did you find a solution? I'm having the exact same error.

**Comment by dphang** [comment]
Strange, I did not see these chunks, maybe it is a new thing in later Next.js versions. I had just upgraded the e2e test versions (they were on 10.0.2 mostly) and came across this problem as well.

It looks like we'll need to copy the contents of chunks as well.

**Comment by dphang** [comment]
Should be fixed by https://github.com/serverless-nextjs/serverless-next.js/pull/1095

**Comment by tim1uphealth** [comment]
@dphang thank you, worked on first deploy!
