### ISSUE TITLE
Enable passing deploy and build.enabled flags as environment variables

### ISSUE THREAD

**Issue by giovai** [serverless-nextjs/serverless-next.js#999]
**Is your feature request related to a problem? Please describe.**
I'd like to separate the build, package and deploy stages in my CI/CD pipeline. Currently, there is no packaging command available (but that's a separate issue).
It's not possible to inject the value of `deploy` and `build.enabled` flags as environment variables as they are always passed as strings.  

**Describe the solution you'd like**
I'd like to change the types of  `ServerlessComponentInputs.deploy` and `BuildOptions.enabled` to a union type `boolean | string`. This will enable passing these flags as environment variables and perform additional checks like `inputs.deploy === "false"`.

**Describe alternatives you've considered**
To work around it, I've created two separate serverless.yml files - one with hardcoded `build: false` and one with `deploy: false`, which is far from ideal.

**Comment by dphang** [comment]
Merged the PR and published in latest alpha.
